ALTER TABLE camddmw.account_compliance_dim ADD COLUMN last_update_date timestamp without time zone;
ALTER TABLE camddmw.account_fact ADD COLUMN last_update_date timestamp without time zone;
ALTER TABLE camddmw.account_owner_dim ADD COLUMN last_update_date timestamp without time zone;
ALTER TABLE camddmw.allowance_holding_dim ADD COLUMN last_update_date timestamp without time zone;
ALTER TABLE camddmw.control_year_dim ADD COLUMN last_update_date timestamp without time zone;
ALTER TABLE camddmw.fuel_year_dim ADD COLUMN last_update_date timestamp without time zone;
ALTER TABLE camddmw.owner_display_fact ADD COLUMN last_update_date timestamp without time zone;
ALTER TABLE camddmw.owner_year_dim ADD COLUMN last_update_date timestamp without time zone;
ALTER TABLE camddmw.program_year_dim ADD COLUMN last_update_date timestamp without time zone;
ALTER TABLE camddmw.transaction_block_dim ADD COLUMN last_update_date timestamp without time zone;
ALTER TABLE camddmw.transaction_fact ADD COLUMN last_update_date timestamp without time zone;
ALTER TABLE camddmw.transaction_owner_dim ADD COLUMN last_update_date timestamp without time zone;
ALTER TABLE camddmw.unit_compliance_dim ADD COLUMN last_update_date timestamp without time zone;
ALTER TABLE camddmw.unit_fact ADD COLUMN last_update_date timestamp without time zone;
ALTER TABLE camddmw.unit_type_year_dim ADD COLUMN last_update_date timestamp without time zone;

COMMENT ON COLUMN camddmw.account_compliance_dim.last_update_date IS 'Latest add or update date on source records that are used to populate this record';
COMMENT ON COLUMN camddmw.account_fact.last_update_date IS 'Latest add or update date on source records that are used to populate this record';
COMMENT ON COLUMN camddmw.account_owner_dim.last_update_date IS 'Latest add or update date on source records that are used to populate this record';
COMMENT ON COLUMN camddmw.allowance_holding_dim.last_update_date IS 'Latest add or update date on source records that are used to populate this record';
COMMENT ON COLUMN camddmw.control_year_dim.last_update_date IS 'Latest add or update date on source records that are used to populate this record';
COMMENT ON COLUMN camddmw.fuel_year_dim.last_update_date IS 'Latest add or update date on source records that are used to populate this record';
COMMENT ON COLUMN camddmw.owner_display_fact.last_update_date IS 'Latest add or update date on source records that are used to populate this record';
COMMENT ON COLUMN camddmw.owner_year_dim.last_update_date IS 'Latest add or update date on source records that are used to populate this record';
COMMENT ON COLUMN camddmw.program_year_dim.last_update_date IS 'Latest add or update date on source records that are used to populate this record';
COMMENT ON COLUMN camddmw.transaction_block_dim.last_update_date IS 'Latest add or update date on source records that are used to populate this record';
COMMENT ON COLUMN camddmw.transaction_fact.last_update_date IS 'Latest add or update date on source records that are used to populate this record';
COMMENT ON COLUMN camddmw.transaction_owner_dim.last_update_date IS 'Latest add or update date on source records that are used to populate this record';
COMMENT ON COLUMN camddmw.unit_compliance_dim.last_update_date IS 'Latest add or update date on source records that are used to populate this record';
COMMENT ON COLUMN camddmw.unit_fact.last_update_date IS 'Latest add or update date on source records that are used to populate this record';
COMMENT ON COLUMN camddmw.unit_type_year_dim.last_update_date IS 'Latest add or update date on source records that are used to populate this record';
