-------------------------------------------------------------------------------------------------------------------------------------
/* CAMP RELEASE */
-------------------------------------------------------------------------------------------------------------------------------------
SELECT 'camd' AS schema_name, 'generator' AS table_name, COUNT(*) FROM camd.generator UNION ALL
SELECT 'camd' AS schema_name, 'plant' AS table_name, COUNT(*) FROM camd.plant UNION ALL
SELECT 'camd' AS schema_name, 'unit' AS table_name, COUNT(*) FROM camd.unit UNION ALL
SELECT 'camd' AS schema_name, 'unit_generator' AS table_name, COUNT(*) FROM camd.unit_generator UNION ALL
SELECT 'camdecmps' AS schema_name, 'dm_emissions' AS table_name, COUNT(*) FROM camdecmps.dm_emissions UNION ALL
SELECT 'camdecmpsaux' AS schema_name, 'em_submission_access' AS table_name, COUNT(*) FROM camdecmpsaux.em_submission_access UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'apportionment_type_code' AS table_name, COUNT(*) FROM camdecmpsmd.apportionment_type_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'control_code' AS table_name, COUNT(*) FROM camdecmpsmd.control_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'control_equip_param_code' AS table_name, COUNT(*) FROM camdecmpsmd.control_equip_param_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'dm_emissions_user_code' AS table_name, COUNT(*) FROM camdecmpsmd.dm_emissions_user_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'fuel_group_code' AS table_name, COUNT(*) FROM camdecmpsmd.fuel_group_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'fuel_type_code' AS table_name, COUNT(*) FROM camdecmpsmd.fuel_type_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'parameter_code' AS table_name, COUNT(*) FROM camdecmpsmd.parameter_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'reporting_period' AS table_name, COUNT(*) FROM camdecmpsmd.reporting_period UNION ALL
SELECT 'camdmd' AS schema_name, 'account_type_code' AS table_name, COUNT(*) FROM camdmd.account_type_code UNION ALL
SELECT 'camdmd' AS schema_name, 'county_code' AS table_name, COUNT(*) FROM camdmd.county_code UNION ALL
SELECT 'camdmd' AS schema_name, 'epa_region_code' AS table_name, COUNT(*) FROM camdmd.epa_region_code UNION ALL
SELECT 'camdmd' AS schema_name, 'generator_source_code' AS table_name, COUNT(*) FROM camdmd.generator_source_code UNION ALL
SELECT 'camdmd' AS schema_name, 'naics_code' AS table_name, COUNT(*) FROM camdmd.naics_code UNION ALL
SELECT 'camdmd' AS schema_name, 'nerc_region_code' AS table_name, COUNT(*) FROM camdmd.nerc_region_code UNION ALL
SELECT 'camdmd' AS schema_name, 'prime_mover_type_code' AS table_name, COUNT(*) FROM camdmd.prime_mover_type_code UNION ALL
SELECT 'camdmd' AS schema_name, 'program_code' AS table_name, COUNT(*) FROM camdmd.program_code UNION ALL
SELECT 'camdmd' AS schema_name, 'program_group_code' AS table_name, COUNT(*) FROM camdmd.program_group_code UNION ALL
SELECT 'camdmd' AS schema_name, 'sic_code' AS table_name, COUNT(*) FROM camdmd.sic_code UNION ALL
SELECT 'camdmd' AS schema_name, 'source_category_code' AS table_name, COUNT(*) FROM camdmd.source_category_code UNION ALL
SELECT 'camdmd' AS schema_name, 'state_code' AS table_name, COUNT(*) FROM camdmd.state_code UNION ALL
SELECT 'camdmd' AS schema_name, 'transaction_type_code' AS table_name, COUNT(*) FROM camdmd.transaction_type_code UNION ALL
SELECT 'camdmd' AS schema_name, 'tribal_land_code' AS table_name, COUNT(*) FROM camdmd.tribal_land_code UNION ALL
SELECT 'camdmd' AS schema_name, 'unit_type_code' AS table_name, COUNT(*) FROM camdmd.unit_type_code
order by 1,2
-------------------------------------------------------------------------------------------------------------------------------------
/* MP MODULE */
-------------------------------------------------------------------------------------------------------------------------------------
SELECT 'camd' AS schema_name, 'program' AS table_name, COUNT(*) FROM camd.program UNION ALL
SELECT 'camd' AS schema_name, 'unit_boiler_type' AS table_name, COUNT(*) FROM camd.unit_boiler_type UNION ALL
SELECT 'camd' AS schema_name, 'unit_exemption' AS table_name, COUNT(*) FROM camd.unit_exemption UNION ALL
SELECT 'camd' AS schema_name, 'unit_op_status' AS table_name, COUNT(*) FROM camd.unit_op_status UNION ALL
SELECT 'camd' AS schema_name, 'unit_program' AS table_name, COUNT(*) FROM camd.unit_program UNION ALL
SELECT 'camdecmps' AS schema_name, 'analyzer_range' AS table_name, COUNT(*) FROM camdecmps.analyzer_range UNION ALL
SELECT 'camdecmps' AS schema_name, 'component' AS table_name, COUNT(*) FROM camdecmps.component UNION ALL
SELECT 'camdecmps' AS schema_name, 'flow_to_load_check' AS table_name, COUNT(*) FROM camdecmps.flow_to_load_check UNION ALL
SELECT 'camdecmps' AS schema_name, 'flow_to_load_reference' AS table_name, COUNT(*) FROM camdecmps.flow_to_load_reference UNION ALL
SELECT 'camdecmps' AS schema_name, 'fuel_flowmeter_accuracy' AS table_name, COUNT(*) FROM camdecmps.fuel_flowmeter_accuracy UNION ALL
SELECT 'camdecmps' AS schema_name, 'mats_method_data' AS table_name, COUNT(*) FROM camdecmps.mats_method_data UNION ALL
SELECT 'camdecmps' AS schema_name, 'monitor_default' AS table_name, COUNT(*) FROM camdecmps.monitor_default UNION ALL
SELECT 'camdecmps' AS schema_name, 'monitor_formula' AS table_name, COUNT(*) FROM camdecmps.monitor_formula UNION ALL
SELECT 'camdecmps' AS schema_name, 'monitor_load' AS table_name, COUNT(*) FROM camdecmps.monitor_load UNION ALL
SELECT 'camdecmps' AS schema_name, 'monitor_location' AS table_name, COUNT(*) FROM camdecmps.monitor_location UNION ALL
SELECT 'camdecmps' AS schema_name, 'monitor_location_attribute' AS table_name, COUNT(*) FROM camdecmps.monitor_location_attribute UNION ALL
SELECT 'camdecmps' AS schema_name, 'monitor_method' AS table_name, COUNT(*) FROM camdecmps.monitor_method UNION ALL
SELECT 'camdecmps' AS schema_name, 'monitor_plan' AS table_name, COUNT(*) FROM camdecmps.monitor_plan UNION ALL
SELECT 'camdecmps' AS schema_name, 'monitor_plan_comment' AS table_name, COUNT(*) FROM camdecmps.monitor_plan_comment UNION ALL
SELECT 'camdecmps' AS schema_name, 'monitor_plan_location' AS table_name, COUNT(*) FROM camdecmps.monitor_plan_location UNION ALL
SELECT 'camdecmps' AS schema_name, 'monitor_plan_reporting_freq' AS table_name, COUNT(*) FROM camdecmps.monitor_plan_reporting_freq UNION ALL
SELECT 'camdecmps' AS schema_name, 'monitor_qualification' AS table_name, COUNT(*) FROM camdecmps.monitor_qualification UNION ALL
SELECT 'camdecmps' AS schema_name, 'monitor_qualification_lee' AS table_name, COUNT(*) FROM camdecmps.monitor_qualification_lee UNION ALL
SELECT 'camdecmps' AS schema_name, 'monitor_qualification_lme' AS table_name, COUNT(*) FROM camdecmps.monitor_qualification_lme UNION ALL
SELECT 'camdecmps' AS schema_name, 'monitor_qualification_pct' AS table_name, COUNT(*) FROM camdecmps.monitor_qualification_pct UNION ALL
SELECT 'camdecmps' AS schema_name, 'monitor_span' AS table_name, COUNT(*) FROM camdecmps.monitor_span UNION ALL
SELECT 'camdecmps' AS schema_name, 'monitor_system' AS table_name, COUNT(*) FROM camdecmps.monitor_system UNION ALL
SELECT 'camdecmps' AS schema_name, 'monitor_system_component' AS table_name, COUNT(*) FROM camdecmps.monitor_system_component UNION ALL
SELECT 'camdecmps' AS schema_name, 'qa_supp_data' AS table_name, COUNT(*) FROM camdecmps.qa_supp_data UNION ALL
SELECT 'camdecmps' AS schema_name, 'rect_duct_waf' AS table_name, COUNT(*) FROM camdecmps.rect_duct_waf UNION ALL
SELECT 'camdecmps' AS schema_name, 'stack_pipe' AS table_name, COUNT(*) FROM camdecmps.stack_pipe UNION ALL
SELECT 'camdecmps' AS schema_name, 'system_fuel_flow' AS table_name, COUNT(*) FROM camdecmps.system_fuel_flow UNION ALL
SELECT 'camdecmps' AS schema_name, 'test_summary' AS table_name, COUNT(*) FROM camdecmps.test_summary UNION ALL
SELECT 'camdecmps' AS schema_name, 'unit_capacity' AS table_name, COUNT(*) FROM camdecmps.unit_capacity UNION ALL
SELECT 'camdecmps' AS schema_name, 'unit_control' AS table_name, COUNT(*) FROM camdecmps.unit_control UNION ALL
SELECT 'camdecmps' AS schema_name, 'unit_default_test' AS table_name, COUNT(*) FROM camdecmps.unit_default_test UNION ALL
SELECT 'camdecmps' AS schema_name, 'unit_fuel' AS table_name, COUNT(*) FROM camdecmps.unit_fuel UNION ALL
SELECT 'camdecmps' AS schema_name, 'unit_stack_configuration' AS table_name, COUNT(*) FROM camdecmps.unit_stack_configuration UNION ALL
SELECT 'camdecmps' AS schema_name, 'used_identifier' AS table_name, COUNT(*) FROM camdecmps.used_identifier UNION ALL
SELECT 'camdecmpsaux' AS schema_name, 'apportionment' AS table_name, COUNT(*) FROM camdecmpsaux.apportionment UNION ALL
SELECT 'camdecmpsaux' AS schema_name, 'apportionment_data' AS table_name, COUNT(*) FROM camdecmpsaux.apportionment_data UNION ALL
SELECT 'camdecmpsaux' AS schema_name, 'apportionment_range' AS table_name, COUNT(*) FROM camdecmpsaux.apportionment_range UNION ALL
SELECT 'camdecmpsaux' AS schema_name, 'check_log' AS table_name, COUNT(*) FROM camdecmpsaux.check_log UNION ALL
SELECT 'camdecmpsaux' AS schema_name, 'check_session' AS table_name, COUNT(*) FROM camdecmpsaux.check_session UNION ALL
SELECT 'camdecmpsaux' AS schema_name, 'es_spec' AS table_name, COUNT(*) FROM camdecmpsaux.es_spec UNION ALL
SELECT 'camdecmpsaux' AS schema_name, 'program_parameter' AS table_name, COUNT(*) FROM camdecmpsaux.program_parameter UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'accuracy_test_method_code' AS table_name, COUNT(*) FROM camdecmpsmd.accuracy_test_method_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'acquisition_method_code' AS table_name, COUNT(*) FROM camdecmpsmd.acquisition_method_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'analyzer_range_code' AS table_name, COUNT(*) FROM camdecmpsmd.analyzer_range_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'basis_code' AS table_name, COUNT(*) FROM camdecmpsmd.basis_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'bypass_approach_code' AS table_name, COUNT(*) FROM camdecmpsmd.bypass_approach_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'calibration_source_code' AS table_name, COUNT(*) FROM camdecmpsmd.calibration_source_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'calibration_standard_code' AS table_name, COUNT(*) FROM camdecmpsmd.calibration_standard_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'category_code' AS table_name, COUNT(*) FROM camdecmpsmd.category_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'check_catalog' AS table_name, COUNT(*) FROM camdecmpsmd.check_catalog UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'check_catalog_result' AS table_name, COUNT(*) FROM camdecmpsmd.check_catalog_result UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'check_type_code' AS table_name, COUNT(*) FROM camdecmpsmd.check_type_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'component_type_code' AS table_name, COUNT(*) FROM camdecmpsmd.component_type_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'default_purpose_code' AS table_name, COUNT(*) FROM camdecmpsmd.default_purpose_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'default_source_code' AS table_name, COUNT(*) FROM camdecmpsmd.default_source_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'dem_method_code' AS table_name, COUNT(*) FROM camdecmpsmd.dem_method_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'em_status_code' AS table_name, COUNT(*) FROM camdecmpsmd.em_status_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'em_sub_type_code' AS table_name, COUNT(*) FROM camdecmpsmd.em_sub_type_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'equation_code' AS table_name, COUNT(*) FROM camdecmpsmd.equation_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'es_match_data_type_code' AS table_name, COUNT(*) FROM camdecmpsmd.es_match_data_type_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'es_match_loc_type_code' AS table_name, COUNT(*) FROM camdecmpsmd.es_match_loc_type_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'es_match_time_type_code' AS table_name, COUNT(*) FROM camdecmpsmd.es_match_time_type_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'es_parameter' AS table_name, COUNT(*) FROM camdecmpsmd.es_parameter UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'es_parameter_category' AS table_name, COUNT(*) FROM camdecmpsmd.es_parameter_category UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'es_parameter_group_code' AS table_name, COUNT(*) FROM camdecmpsmd.es_parameter_group_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'es_reason_code' AS table_name, COUNT(*) FROM camdecmpsmd.es_reason_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'file_type_code' AS table_name, COUNT(*) FROM camdecmpsmd.file_type_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'fuel_code' AS table_name, COUNT(*) FROM camdecmpsmd.fuel_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'fuel_indicator_code' AS table_name, COUNT(*) FROM camdecmpsmd.fuel_indicator_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'injection_protocol_code' AS table_name, COUNT(*) FROM camdecmpsmd.injection_protocol_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'material_code' AS table_name, COUNT(*) FROM camdecmpsmd.material_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'mats_method_code' AS table_name, COUNT(*) FROM camdecmpsmd.mats_method_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'mats_method_parameter_code' AS table_name, COUNT(*) FROM camdecmpsmd.mats_method_parameter_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'max_rate_source_code' AS table_name, COUNT(*) FROM camdecmpsmd.max_rate_source_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'method_code' AS table_name, COUNT(*) FROM camdecmpsmd.method_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'modc_code' AS table_name, COUNT(*) FROM camdecmpsmd.modc_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'monitoring_plan_status_code' AS table_name, COUNT(*) FROM camdecmpsmd.monitoring_plan_status_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'op_supp_data_type_code' AS table_name, COUNT(*) FROM camdecmpsmd.op_supp_data_type_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'operating_condition_code' AS table_name, COUNT(*) FROM camdecmpsmd.operating_condition_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'operating_level_code' AS table_name, COUNT(*) FROM camdecmpsmd.operating_level_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'parameter_uom' AS table_name, COUNT(*) FROM camdecmpsmd.parameter_uom UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'process_code' AS table_name, COUNT(*) FROM camdecmpsmd.process_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'qual_data_type_code' AS table_name, COUNT(*) FROM camdecmpsmd.qual_data_type_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'qual_lee_test_type_code' AS table_name, COUNT(*) FROM camdecmpsmd.qual_lee_test_type_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'qual_type_code' AS table_name, COUNT(*) FROM camdecmpsmd.qual_type_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'report_freq_code' AS table_name, COUNT(*) FROM camdecmpsmd.report_freq_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'rule_check' AS table_name, COUNT(*) FROM camdecmpsmd.rule_check UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'severity_code' AS table_name, COUNT(*) FROM camdecmpsmd.severity_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'shape_code' AS table_name, COUNT(*) FROM camdecmpsmd.shape_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'span_method_code' AS table_name, COUNT(*) FROM camdecmpsmd.span_method_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'span_scale_code' AS table_name, COUNT(*) FROM camdecmpsmd.span_scale_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'submission_availability_code' AS table_name, COUNT(*) FROM camdecmpsmd.submission_availability_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'substitute_data_code' AS table_name, COUNT(*) FROM camdecmpsmd.substitute_data_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'system_designation_code' AS table_name, COUNT(*) FROM camdecmpsmd.system_designation_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'system_type_code' AS table_name, COUNT(*) FROM camdecmpsmd.system_type_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'test_basis_code' AS table_name, COUNT(*) FROM camdecmpsmd.test_basis_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'test_reason_code' AS table_name, COUNT(*) FROM camdecmpsmd.test_reason_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'test_result_code' AS table_name, COUNT(*) FROM camdecmpsmd.test_result_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'test_type_code' AS table_name, COUNT(*) FROM camdecmpsmd.test_type_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'units_of_measure_code' AS table_name, COUNT(*) FROM camdecmpsmd.units_of_measure_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'waf_method_code' AS table_name, COUNT(*) FROM camdecmpsmd.waf_method_code UNION ALL
SELECT 'camdmd' AS schema_name, 'applicability_status_code' AS table_name, COUNT(*) FROM camdmd.applicability_status_code UNION ALL
SELECT 'camdmd' AS schema_name, 'class_code' AS table_name, COUNT(*) FROM camdmd.class_code UNION ALL
SELECT 'camdmd' AS schema_name, 'exemption_type_code' AS table_name, COUNT(*) FROM camdmd.exemption_type_code UNION ALL
SELECT 'camdmd' AS schema_name, 'nonstandard_code' AS table_name, COUNT(*) FROM camdmd.nonstandard_code UNION ALL
SELECT 'camdmd' AS schema_name, 'operating_status_code' AS table_name, COUNT(*) FROM camdmd.operating_status_code UNION ALL
SELECT 'camdmd' AS schema_name, 'program_class' AS table_name, COUNT(*) FROM camdmd.program_class UNION ALL
SELECT 'camdmd' AS schema_name, 'program_exemption' AS table_name, COUNT(*) FROM camdmd.program_exemption
order by 1,2
-------------------------------------------------------------------------------------------------------------------------------------
/* QA MODULE */
-------------------------------------------------------------------------------------------------------------------------------------
SELECT 'camdecmps' AS schema_name, 'ae_correlation_test_run' AS table_name, COUNT(*) FROM camdecmps.ae_correlation_test_run UNION ALL
SELECT 'camdecmps' AS schema_name, 'ae_correlation_test_sum' AS table_name, COUNT(*) FROM camdecmps.ae_correlation_test_sum UNION ALL
SELECT 'camdecmps' AS schema_name, 'ae_hi_gas' AS table_name, COUNT(*) FROM camdecmps.ae_hi_gas UNION ALL
SELECT 'camdecmps' AS schema_name, 'ae_hi_oil' AS table_name, COUNT(*) FROM camdecmps.ae_hi_oil UNION ALL
SELECT 'camdecmps' AS schema_name, 'air_emission_testing' AS table_name, COUNT(*) FROM camdecmps.air_emission_testing UNION ALL
SELECT 'camdecmps' AS schema_name, 'calibration_injection' AS table_name, COUNT(*) FROM camdecmps.calibration_injection UNION ALL
SELECT 'camdecmps' AS schema_name, 'cycle_time_injection' AS table_name, COUNT(*) FROM camdecmps.cycle_time_injection UNION ALL
SELECT 'camdecmps' AS schema_name, 'cycle_time_summary' AS table_name, COUNT(*) FROM camdecmps.cycle_time_summary UNION ALL
SELECT 'camdecmps' AS schema_name, 'flow_rata_run' AS table_name, COUNT(*) FROM camdecmps.flow_rata_run UNION ALL
SELECT 'camdecmps' AS schema_name, 'fuel_flow_to_load_baseline' AS table_name, COUNT(*) FROM camdecmps.fuel_flow_to_load_baseline UNION ALL
SELECT 'camdecmps' AS schema_name, 'fuel_flow_to_load_check' AS table_name, COUNT(*) FROM camdecmps.fuel_flow_to_load_check UNION ALL
SELECT 'camdecmps' AS schema_name, 'hg_test_injection' AS table_name, COUNT(*) FROM camdecmps.hg_test_injection UNION ALL
SELECT 'camdecmps' AS schema_name, 'hg_test_summary' AS table_name, COUNT(*) FROM camdecmps.hg_test_summary UNION ALL
SELECT 'camdecmps' AS schema_name, 'linearity_injection' AS table_name, COUNT(*) FROM camdecmps.linearity_injection UNION ALL
SELECT 'camdecmps' AS schema_name, 'linearity_summary' AS table_name, COUNT(*) FROM camdecmps.linearity_summary UNION ALL
SELECT 'camdecmps' AS schema_name, 'on_off_cal' AS table_name, COUNT(*) FROM camdecmps.on_off_cal UNION ALL
SELECT 'camdecmps' AS schema_name, 'protocol_gas' AS table_name, COUNT(*) FROM camdecmps.protocol_gas UNION ALL
SELECT 'camdecmps' AS schema_name, 'protocol_gas_vendor' AS table_name, COUNT(*) FROM camdecmps.protocol_gas_vendor UNION ALL
SELECT 'camdecmps' AS schema_name, 'qa_cert_event' AS table_name, COUNT(*) FROM camdecmps.qa_cert_event UNION ALL
SELECT 'camdecmps' AS schema_name, 'qa_cert_event_supp_data' AS table_name, COUNT(*) FROM camdecmps.qa_cert_event_supp_data UNION ALL
SELECT 'camdecmps' AS schema_name, 'qa_supp_attribute' AS table_name, COUNT(*) FROM camdecmps.qa_supp_attribute UNION ALL
SELECT 'camdecmps' AS schema_name, 'rata' AS table_name, COUNT(*) FROM camdecmps.rata UNION ALL
SELECT 'camdecmps' AS schema_name, 'rata_run' AS table_name, COUNT(*) FROM camdecmps.rata_run UNION ALL
SELECT 'camdecmps' AS schema_name, 'rata_summary' AS table_name, COUNT(*) FROM camdecmps.rata_summary UNION ALL
SELECT 'camdecmps' AS schema_name, 'rata_traverse' AS table_name, COUNT(*) FROM camdecmps.rata_traverse UNION ALL
SELECT 'camdecmps' AS schema_name, 'test_extension_exemption' AS table_name, COUNT(*) FROM camdecmps.test_extension_exemption UNION ALL
SELECT 'camdecmps' AS schema_name, 'test_qualification' AS table_name, COUNT(*) FROM camdecmps.test_qualification UNION ALL
SELECT 'camdecmps' AS schema_name, 'trans_accuracy' AS table_name, COUNT(*) FROM camdecmps.trans_accuracy UNION ALL
SELECT 'camdecmps' AS schema_name, 'unit_default_test_run' AS table_name, COUNT(*) FROM camdecmps.unit_default_test_run UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'accuracy_spec_code' AS table_name, COUNT(*) FROM camdecmpsmd.accuracy_spec_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'aps_code' AS table_name, COUNT(*) FROM camdecmpsmd.aps_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'extension_exemption_code' AS table_name, COUNT(*) FROM camdecmpsmd.extension_exemption_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'gas_level_code' AS table_name, COUNT(*) FROM camdecmpsmd.gas_level_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'gas_type_code' AS table_name, COUNT(*) FROM camdecmpsmd.gas_type_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'pressure_measure_code' AS table_name, COUNT(*) FROM camdecmpsmd.pressure_measure_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'probe_type_code' AS table_name, COUNT(*) FROM camdecmpsmd.probe_type_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'qa_cert_event_code' AS table_name, COUNT(*) FROM camdecmpsmd.qa_cert_event_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'qa_cert_event_supp_data_code' AS table_name, COUNT(*) FROM camdecmpsmd.qa_cert_event_supp_data_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'qa_cert_event_supp_date_code' AS table_name, COUNT(*) FROM camdecmpsmd.qa_cert_event_supp_date_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'rata_frequency_code' AS table_name, COUNT(*) FROM camdecmpsmd.rata_frequency_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'ref_method_code' AS table_name, COUNT(*) FROM camdecmpsmd.ref_method_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'required_test_code' AS table_name, COUNT(*) FROM camdecmpsmd.required_test_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'run_status_code' AS table_name, COUNT(*) FROM camdecmpsmd.run_status_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'test_claim_code' AS table_name, COUNT(*) FROM camdecmpsmd.test_claim_code
order by 1,2
-------------------------------------------------------------------------------------------------------------------------------------
/* EM MODULE */
-------------------------------------------------------------------------------------------------------------------------------------
SELECT 'camd' AS schema_name, 'generator' AS table_name, COUNT(*) FROM camd.generator UNION ALL
SELECT 'camd' AS schema_name, 'plant' AS table_name, COUNT(*) FROM camd.plant UNION ALL
SELECT 'camd' AS schema_name, 'plant_person' AS table_name, COUNT(*) FROM camd.plant_person UNION ALL
SELECT 'camd' AS schema_name, 'program' AS table_name, COUNT(*) FROM camd.program UNION ALL
SELECT 'camd' AS schema_name, 'program_phase' AS table_name, COUNT(*) FROM camd.program_phase UNION ALL
SELECT 'camd' AS schema_name, 'unit' AS table_name, COUNT(*) FROM camd.unit UNION ALL
SELECT 'camd' AS schema_name, 'unit_boiler_type' AS table_name, COUNT(*) FROM camd.unit_boiler_type UNION ALL
SELECT 'camd' AS schema_name, 'unit_exemption' AS table_name, COUNT(*) FROM camd.unit_exemption UNION ALL
SELECT 'camd' AS schema_name, 'unit_generator' AS table_name, COUNT(*) FROM camd.unit_generator UNION ALL
SELECT 'camd' AS schema_name, 'unit_op_status' AS table_name, COUNT(*) FROM camd.unit_op_status UNION ALL
SELECT 'camd' AS schema_name, 'unit_program' AS table_name, COUNT(*) FROM camd.unit_program UNION ALL
SELECT 'camdecmps' AS schema_name, 'ae_correlation_test_run' AS table_name, COUNT(*) FROM camdecmps.ae_correlation_test_run UNION ALL
SELECT 'camdecmps' AS schema_name, 'ae_correlation_test_sum' AS table_name, COUNT(*) FROM camdecmps.ae_correlation_test_sum UNION ALL
SELECT 'camdecmps' AS schema_name, 'ae_hi_gas' AS table_name, COUNT(*) FROM camdecmps.ae_hi_gas UNION ALL
SELECT 'camdecmps' AS schema_name, 'ae_hi_oil' AS table_name, COUNT(*) FROM camdecmps.ae_hi_oil UNION ALL
SELECT 'camdecmps' AS schema_name, 'air_emission_testing' AS table_name, COUNT(*) FROM camdecmps.air_emission_testing UNION ALL
SELECT 'camdecmps' AS schema_name, 'analyzer_range' AS table_name, COUNT(*) FROM camdecmps.analyzer_range UNION ALL
SELECT 'camdecmps' AS schema_name, 'calibration_injection' AS table_name, COUNT(*) FROM camdecmps.calibration_injection UNION ALL
SELECT 'camdecmps' AS schema_name, 'component' AS table_name, COUNT(*) FROM camdecmps.component UNION ALL
SELECT 'camdecmps' AS schema_name, 'component_op_supp_data' AS table_name, COUNT(*) FROM camdecmps.component_op_supp_data UNION ALL
SELECT 'camdecmps' AS schema_name, 'cycle_time_injection' AS table_name, COUNT(*) FROM camdecmps.cycle_time_injection UNION ALL
SELECT 'camdecmps' AS schema_name, 'cycle_time_summary' AS table_name, COUNT(*) FROM camdecmps.cycle_time_summary UNION ALL
SELECT 'camdecmps' AS schema_name, 'daily_calibration' AS table_name, COUNT(*) FROM camdecmps.daily_calibration UNION ALL
SELECT 'camdecmps' AS schema_name, 'daily_emission' AS table_name, COUNT(*) FROM camdecmps.daily_emission UNION ALL
SELECT 'camdecmps' AS schema_name, 'daily_fuel' AS table_name, COUNT(*) FROM camdecmps.daily_fuel UNION ALL
SELECT 'camdecmps' AS schema_name, 'daily_test_summary' AS table_name, COUNT(*) FROM camdecmps.daily_test_summary UNION ALL
SELECT 'camdecmps' AS schema_name, 'daily_test_supp_data' AS table_name, COUNT(*) FROM camdecmps.daily_test_supp_data UNION ALL
SELECT 'camdecmps' AS schema_name, 'daily_test_system_supp_data' AS table_name, COUNT(*) FROM camdecmps.daily_test_system_supp_data UNION ALL
SELECT 'camdecmps' AS schema_name, 'derived_hrly_value' AS table_name, COUNT(*) FROM camdecmps.derived_hrly_value UNION ALL
SELECT 'camdecmps' AS schema_name, 'dm_emissions' AS table_name, COUNT(*) FROM camdecmps.dm_emissions UNION ALL
SELECT 'camdecmps' AS schema_name, 'emission_evaluation' AS table_name, COUNT(*) FROM camdecmps.emission_evaluation UNION ALL
SELECT 'camdecmps' AS schema_name, 'flow_rata_run' AS table_name, COUNT(*) FROM camdecmps.flow_rata_run UNION ALL
SELECT 'camdecmps' AS schema_name, 'flow_to_load_check' AS table_name, COUNT(*) FROM camdecmps.flow_to_load_check UNION ALL
SELECT 'camdecmps' AS schema_name, 'flow_to_load_reference' AS table_name, COUNT(*) FROM camdecmps.flow_to_load_reference UNION ALL
SELECT 'camdecmps' AS schema_name, 'fuel_flow_to_load_baseline' AS table_name, COUNT(*) FROM camdecmps.fuel_flow_to_load_baseline UNION ALL
SELECT 'camdecmps' AS schema_name, 'fuel_flow_to_load_check' AS table_name, COUNT(*) FROM camdecmps.fuel_flow_to_load_check UNION ALL
SELECT 'camdecmps' AS schema_name, 'fuel_flowmeter_accuracy' AS table_name, COUNT(*) FROM camdecmps.fuel_flowmeter_accuracy UNION ALL
SELECT 'camdecmps' AS schema_name, 'hg_test_injection' AS table_name, COUNT(*) FROM camdecmps.hg_test_injection UNION ALL
SELECT 'camdecmps' AS schema_name, 'hg_test_summary' AS table_name, COUNT(*) FROM camdecmps.hg_test_summary UNION ALL
SELECT 'camdecmps' AS schema_name, 'hrly_fuel_flow' AS table_name, COUNT(*) FROM camdecmps.hrly_fuel_flow UNION ALL
SELECT 'camdecmps' AS schema_name, 'hrly_gas_flow_meter' AS table_name, COUNT(*) FROM camdecmps.hrly_gas_flow_meter UNION ALL
SELECT 'camdecmps' AS schema_name, 'hrly_op_data' AS table_name, COUNT(*) FROM camdecmps.hrly_op_data UNION ALL
SELECT 'camdecmps' AS schema_name, 'hrly_param_fuel_flow' AS table_name, COUNT(*) FROM camdecmps.hrly_param_fuel_flow UNION ALL
SELECT 'camdecmps' AS schema_name, 'last_qa_value_supp_data' AS table_name, COUNT(*) FROM camdecmps.last_qa_value_supp_data UNION ALL
SELECT 'camdecmps' AS schema_name, 'linearity_injection' AS table_name, COUNT(*) FROM camdecmps.linearity_injection UNION ALL
SELECT 'camdecmps' AS schema_name, 'linearity_summary' AS table_name, COUNT(*) FROM camdecmps.linearity_summary UNION ALL
SELECT 'camdecmps' AS schema_name, 'long_term_fuel_flow' AS table_name, COUNT(*) FROM camdecmps.long_term_fuel_flow UNION ALL
SELECT 'camdecmps' AS schema_name, 'mats_derived_hrly_value' AS table_name, COUNT(*) FROM camdecmps.mats_derived_hrly_value UNION ALL
SELECT 'camdecmps' AS schema_name, 'mats_method_data' AS table_name, COUNT(*) FROM camdecmps.mats_method_data UNION ALL
SELECT 'camdecmps' AS schema_name, 'mats_monitor_hrly_value' AS table_name, COUNT(*) FROM camdecmps.mats_monitor_hrly_value UNION ALL
SELECT 'camdecmps' AS schema_name, 'monitor_default' AS table_name, COUNT(*) FROM camdecmps.monitor_default UNION ALL
SELECT 'camdecmps' AS schema_name, 'monitor_formula' AS table_name, COUNT(*) FROM camdecmps.monitor_formula UNION ALL
SELECT 'camdecmps' AS schema_name, 'monitor_hrly_value' AS table_name, COUNT(*) FROM camdecmps.monitor_hrly_value UNION ALL
SELECT 'camdecmps' AS schema_name, 'monitor_load' AS table_name, COUNT(*) FROM camdecmps.monitor_load UNION ALL
SELECT 'camdecmps' AS schema_name, 'monitor_location' AS table_name, COUNT(*) FROM camdecmps.monitor_location UNION ALL
SELECT 'camdecmps' AS schema_name, 'monitor_location_attribute' AS table_name, COUNT(*) FROM camdecmps.monitor_location_attribute UNION ALL
SELECT 'camdecmps' AS schema_name, 'monitor_method' AS table_name, COUNT(*) FROM camdecmps.monitor_method UNION ALL
SELECT 'camdecmps' AS schema_name, 'monitor_plan' AS table_name, COUNT(*) FROM camdecmps.monitor_plan UNION ALL
SELECT 'camdecmps' AS schema_name, 'monitor_plan_comment' AS table_name, COUNT(*) FROM camdecmps.monitor_plan_comment UNION ALL
SELECT 'camdecmps' AS schema_name, 'monitor_plan_location' AS table_name, COUNT(*) FROM camdecmps.monitor_plan_location UNION ALL
SELECT 'camdecmps' AS schema_name, 'monitor_plan_reporting_freq' AS table_name, COUNT(*) FROM camdecmps.monitor_plan_reporting_freq UNION ALL
SELECT 'camdecmps' AS schema_name, 'monitor_qualification' AS table_name, COUNT(*) FROM camdecmps.monitor_qualification UNION ALL
SELECT 'camdecmps' AS schema_name, 'monitor_qualification_lee' AS table_name, COUNT(*) FROM camdecmps.monitor_qualification_lee UNION ALL
SELECT 'camdecmps' AS schema_name, 'monitor_qualification_lme' AS table_name, COUNT(*) FROM camdecmps.monitor_qualification_lme UNION ALL
SELECT 'camdecmps' AS schema_name, 'monitor_qualification_pct' AS table_name, COUNT(*) FROM camdecmps.monitor_qualification_pct UNION ALL
SELECT 'camdecmps' AS schema_name, 'monitor_span' AS table_name, COUNT(*) FROM camdecmps.monitor_span UNION ALL
SELECT 'camdecmps' AS schema_name, 'monitor_system' AS table_name, COUNT(*) FROM camdecmps.monitor_system UNION ALL
SELECT 'camdecmps' AS schema_name, 'monitor_system_component' AS table_name, COUNT(*) FROM camdecmps.monitor_system_component UNION ALL
SELECT 'camdecmps' AS schema_name, 'nsps4t_annual' AS table_name, COUNT(*) FROM camdecmps.nsps4t_annual UNION ALL
SELECT 'camdecmps' AS schema_name, 'nsps4t_compliance_period' AS table_name, COUNT(*) FROM camdecmps.nsps4t_compliance_period UNION ALL
SELECT 'camdecmps' AS schema_name, 'nsps4t_summary' AS table_name, COUNT(*) FROM camdecmps.nsps4t_summary UNION ALL
SELECT 'camdecmps' AS schema_name, 'on_off_cal' AS table_name, COUNT(*) FROM camdecmps.on_off_cal UNION ALL
SELECT 'camdecmps' AS schema_name, 'operating_supp_data' AS table_name, COUNT(*) FROM camdecmps.operating_supp_data UNION ALL
SELECT 'camdecmps' AS schema_name, 'protocol_gas' AS table_name, COUNT(*) FROM camdecmps.protocol_gas UNION ALL
SELECT 'camdecmps' AS schema_name, 'protocol_gas_vendor' AS table_name, COUNT(*) FROM camdecmps.protocol_gas_vendor UNION ALL
SELECT 'camdecmps' AS schema_name, 'qa_cert_event' AS table_name, COUNT(*) FROM camdecmps.qa_cert_event UNION ALL
SELECT 'camdecmps' AS schema_name, 'qa_cert_event_supp_data' AS table_name, COUNT(*) FROM camdecmps.qa_cert_event_supp_data UNION ALL
SELECT 'camdecmps' AS schema_name, 'qa_supp_attribute' AS table_name, COUNT(*) FROM camdecmps.qa_supp_attribute UNION ALL
SELECT 'camdecmps' AS schema_name, 'qa_supp_data' AS table_name, COUNT(*) FROM camdecmps.qa_supp_data UNION ALL
SELECT 'camdecmps' AS schema_name, 'rata' AS table_name, COUNT(*) FROM camdecmps.rata UNION ALL
SELECT 'camdecmps' AS schema_name, 'rata_run' AS table_name, COUNT(*) FROM camdecmps.rata_run UNION ALL
SELECT 'camdecmps' AS schema_name, 'rata_summary' AS table_name, COUNT(*) FROM camdecmps.rata_summary UNION ALL
SELECT 'camdecmps' AS schema_name, 'rata_traverse' AS table_name, COUNT(*) FROM camdecmps.rata_traverse UNION ALL
SELECT 'camdecmps' AS schema_name, 'rect_duct_waf' AS table_name, COUNT(*) FROM camdecmps.rect_duct_waf UNION ALL
SELECT 'camdecmps' AS schema_name, 'sampling_train' AS table_name, COUNT(*) FROM camdecmps.sampling_train UNION ALL
SELECT 'camdecmps' AS schema_name, 'sampling_train_supp_data' AS table_name, COUNT(*) FROM camdecmps.sampling_train_supp_data UNION ALL
SELECT 'camdecmps' AS schema_name, 'sorbent_trap' AS table_name, COUNT(*) FROM camdecmps.sorbent_trap UNION ALL
SELECT 'camdecmps' AS schema_name, 'sorbent_trap_supp_data' AS table_name, COUNT(*) FROM camdecmps.sorbent_trap_supp_data UNION ALL
SELECT 'camdecmps' AS schema_name, 'stack_pipe' AS table_name, COUNT(*) FROM camdecmps.stack_pipe UNION ALL
SELECT 'camdecmps' AS schema_name, 'summary_value' AS table_name, COUNT(*) FROM camdecmps.summary_value UNION ALL
SELECT 'camdecmps' AS schema_name, 'system_fuel_flow' AS table_name, COUNT(*) FROM camdecmps.system_fuel_flow UNION ALL
SELECT 'camdecmps' AS schema_name, 'system_op_supp_data' AS table_name, COUNT(*) FROM camdecmps.system_op_supp_data UNION ALL
SELECT 'camdecmps' AS schema_name, 'test_extension_exemption' AS table_name, COUNT(*) FROM camdecmps.test_extension_exemption UNION ALL
SELECT 'camdecmps' AS schema_name, 'test_qualification' AS table_name, COUNT(*) FROM camdecmps.test_qualification UNION ALL
SELECT 'camdecmps' AS schema_name, 'test_summary' AS table_name, COUNT(*) FROM camdecmps.test_summary UNION ALL
SELECT 'camdecmps' AS schema_name, 'trans_accuracy' AS table_name, COUNT(*) FROM camdecmps.trans_accuracy UNION ALL
SELECT 'camdecmps' AS schema_name, 'unit_capacity' AS table_name, COUNT(*) FROM camdecmps.unit_capacity UNION ALL
SELECT 'camdecmps' AS schema_name, 'unit_control' AS table_name, COUNT(*) FROM camdecmps.unit_control UNION ALL
SELECT 'camdecmps' AS schema_name, 'unit_default_test' AS table_name, COUNT(*) FROM camdecmps.unit_default_test UNION ALL
SELECT 'camdecmps' AS schema_name, 'unit_default_test_run' AS table_name, COUNT(*) FROM camdecmps.unit_default_test_run UNION ALL
SELECT 'camdecmps' AS schema_name, 'unit_fuel' AS table_name, COUNT(*) FROM camdecmps.unit_fuel UNION ALL
SELECT 'camdecmps' AS schema_name, 'unit_stack_configuration' AS table_name, COUNT(*) FROM camdecmps.unit_stack_configuration UNION ALL
SELECT 'camdecmps' AS schema_name, 'used_identifier' AS table_name, COUNT(*) FROM camdecmps.used_identifier UNION ALL
SELECT 'camdecmps' AS schema_name, 'weekly_system_integrity' AS table_name, COUNT(*) FROM camdecmps.weekly_system_integrity UNION ALL
SELECT 'camdecmps' AS schema_name, 'weekly_test_summary' AS table_name, COUNT(*) FROM camdecmps.weekly_test_summary UNION ALL
SELECT 'camdecmpsaux' AS schema_name, 'apportionment' AS table_name, COUNT(*) FROM camdecmpsaux.apportionment UNION ALL
SELECT 'camdecmpsaux' AS schema_name, 'apportionment_data' AS table_name, COUNT(*) FROM camdecmpsaux.apportionment_data UNION ALL
SELECT 'camdecmpsaux' AS schema_name, 'apportionment_range' AS table_name, COUNT(*) FROM camdecmpsaux.apportionment_range UNION ALL
SELECT 'camdecmpsaux' AS schema_name, 'check_log' AS table_name, COUNT(*) FROM camdecmpsaux.check_log UNION ALL
SELECT 'camdecmpsaux' AS schema_name, 'check_session' AS table_name, COUNT(*) FROM camdecmpsaux.check_session UNION ALL
SELECT 'camdecmpsaux' AS schema_name, 'em_submission_access' AS table_name, COUNT(*) FROM camdecmpsaux.em_submission_access UNION ALL
SELECT 'camdecmpsaux' AS schema_name, 'es_spec' AS table_name, COUNT(*) FROM camdecmpsaux.es_spec UNION ALL
SELECT 'camdecmpsaux' AS schema_name, 'program_parameter' AS table_name, COUNT(*) FROM camdecmpsaux.program_parameter UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'accuracy_spec_code' AS table_name, COUNT(*) FROM camdecmpsmd.accuracy_spec_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'accuracy_test_method_code' AS table_name, COUNT(*) FROM camdecmpsmd.accuracy_test_method_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'acquisition_method_code' AS table_name, COUNT(*) FROM camdecmpsmd.acquisition_method_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'analyzer_range_code' AS table_name, COUNT(*) FROM camdecmpsmd.analyzer_range_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'apportionment_type_code' AS table_name, COUNT(*) FROM camdecmpsmd.apportionment_type_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'aps_code' AS table_name, COUNT(*) FROM camdecmpsmd.aps_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'basis_code' AS table_name, COUNT(*) FROM camdecmpsmd.basis_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'bypass_approach_code' AS table_name, COUNT(*) FROM camdecmpsmd.bypass_approach_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'calibration_source_code' AS table_name, COUNT(*) FROM camdecmpsmd.calibration_source_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'calibration_standard_code' AS table_name, COUNT(*) FROM camdecmpsmd.calibration_standard_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'category_code' AS table_name, COUNT(*) FROM camdecmpsmd.category_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'check_catalog' AS table_name, COUNT(*) FROM camdecmpsmd.check_catalog UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'check_catalog_result' AS table_name, COUNT(*) FROM camdecmpsmd.check_catalog_result UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'check_type_code' AS table_name, COUNT(*) FROM camdecmpsmd.check_type_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'component_type_code' AS table_name, COUNT(*) FROM camdecmpsmd.component_type_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'control_code' AS table_name, COUNT(*) FROM camdecmpsmd.control_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'control_equip_param_code' AS table_name, COUNT(*) FROM camdecmpsmd.control_equip_param_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'default_purpose_code' AS table_name, COUNT(*) FROM camdecmpsmd.default_purpose_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'default_source_code' AS table_name, COUNT(*) FROM camdecmpsmd.default_source_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'dem_method_code' AS table_name, COUNT(*) FROM camdecmpsmd.dem_method_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'dm_emissions_user_code' AS table_name, COUNT(*) FROM camdecmpsmd.dm_emissions_user_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'em_status_code' AS table_name, COUNT(*) FROM camdecmpsmd.em_status_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'em_sub_type_code' AS table_name, COUNT(*) FROM camdecmpsmd.em_sub_type_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'equation_code' AS table_name, COUNT(*) FROM camdecmpsmd.equation_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'es_match_data_type_code' AS table_name, COUNT(*) FROM camdecmpsmd.es_match_data_type_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'es_match_loc_type_code' AS table_name, COUNT(*) FROM camdecmpsmd.es_match_loc_type_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'es_match_time_type_code' AS table_name, COUNT(*) FROM camdecmpsmd.es_match_time_type_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'es_parameter' AS table_name, COUNT(*) FROM camdecmpsmd.es_parameter UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'es_parameter_category' AS table_name, COUNT(*) FROM camdecmpsmd.es_parameter_category UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'es_parameter_group_code' AS table_name, COUNT(*) FROM camdecmpsmd.es_parameter_group_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'es_reason_code' AS table_name, COUNT(*) FROM camdecmpsmd.es_reason_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'extension_exemption_code' AS table_name, COUNT(*) FROM camdecmpsmd.extension_exemption_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'file_type_code' AS table_name, COUNT(*) FROM camdecmpsmd.file_type_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'fuel_code' AS table_name, COUNT(*) FROM camdecmpsmd.fuel_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'fuel_flow_period_code' AS table_name, COUNT(*) FROM camdecmpsmd.fuel_flow_period_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'fuel_group_code' AS table_name, COUNT(*) FROM camdecmpsmd.fuel_group_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'fuel_indicator_code' AS table_name, COUNT(*) FROM camdecmpsmd.fuel_indicator_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'fuel_type_code' AS table_name, COUNT(*) FROM camdecmpsmd.fuel_type_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'gas_level_code' AS table_name, COUNT(*) FROM camdecmpsmd.gas_level_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'gas_type_code' AS table_name, COUNT(*) FROM camdecmpsmd.gas_type_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'hour_measure_code' AS table_name, COUNT(*) FROM camdecmpsmd.hour_measure_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'hourly_type_code' AS table_name, COUNT(*) FROM camdecmpsmd.hourly_type_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'injection_protocol_code' AS table_name, COUNT(*) FROM camdecmpsmd.injection_protocol_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'material_code' AS table_name, COUNT(*) FROM camdecmpsmd.material_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'mats_method_code' AS table_name, COUNT(*) FROM camdecmpsmd.mats_method_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'mats_method_parameter_code' AS table_name, COUNT(*) FROM camdecmpsmd.mats_method_parameter_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'max_rate_source_code' AS table_name, COUNT(*) FROM camdecmpsmd.max_rate_source_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'method_code' AS table_name, COUNT(*) FROM camdecmpsmd.method_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'modc_code' AS table_name, COUNT(*) FROM camdecmpsmd.modc_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'monitoring_plan_status_code' AS table_name, COUNT(*) FROM camdecmpsmd.monitoring_plan_status_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'nsps4t_electrical_load_code' AS table_name, COUNT(*) FROM camdecmpsmd.nsps4t_electrical_load_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'nsps4t_emission_standard_code' AS table_name, COUNT(*) FROM camdecmpsmd.nsps4t_emission_standard_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'op_supp_data_type_code' AS table_name, COUNT(*) FROM camdecmpsmd.op_supp_data_type_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'operating_condition_code' AS table_name, COUNT(*) FROM camdecmpsmd.operating_condition_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'operating_level_code' AS table_name, COUNT(*) FROM camdecmpsmd.operating_level_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'operating_type_code' AS table_name, COUNT(*) FROM camdecmpsmd.operating_type_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'parameter_code' AS table_name, COUNT(*) FROM camdecmpsmd.parameter_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'parameter_uom' AS table_name, COUNT(*) FROM camdecmpsmd.parameter_uom UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'pressure_measure_code' AS table_name, COUNT(*) FROM camdecmpsmd.pressure_measure_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'probe_type_code' AS table_name, COUNT(*) FROM camdecmpsmd.probe_type_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'process_code' AS table_name, COUNT(*) FROM camdecmpsmd.process_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'qa_cert_event_code' AS table_name, COUNT(*) FROM camdecmpsmd.qa_cert_event_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'qa_cert_event_supp_data_code' AS table_name, COUNT(*) FROM camdecmpsmd.qa_cert_event_supp_data_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'qa_cert_event_supp_date_code' AS table_name, COUNT(*) FROM camdecmpsmd.qa_cert_event_supp_date_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'qual_data_type_code' AS table_name, COUNT(*) FROM camdecmpsmd.qual_data_type_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'qual_lee_test_type_code' AS table_name, COUNT(*) FROM camdecmpsmd.qual_lee_test_type_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'qual_type_code' AS table_name, COUNT(*) FROM camdecmpsmd.qual_type_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'rata_frequency_code' AS table_name, COUNT(*) FROM camdecmpsmd.rata_frequency_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'ref_method_code' AS table_name, COUNT(*) FROM camdecmpsmd.ref_method_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'report_freq_code' AS table_name, COUNT(*) FROM camdecmpsmd.report_freq_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'reporting_period' AS table_name, COUNT(*) FROM camdecmpsmd.reporting_period UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'required_test_code' AS table_name, COUNT(*) FROM camdecmpsmd.required_test_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'rule_check' AS table_name, COUNT(*) FROM camdecmpsmd.rule_check UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'run_status_code' AS table_name, COUNT(*) FROM camdecmpsmd.run_status_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'sample_type_code' AS table_name, COUNT(*) FROM camdecmpsmd.sample_type_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'severity_code' AS table_name, COUNT(*) FROM camdecmpsmd.severity_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'shape_code' AS table_name, COUNT(*) FROM camdecmpsmd.shape_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'sod_mass_code' AS table_name, COUNT(*) FROM camdecmpsmd.sod_mass_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'sod_volumetric_code' AS table_name, COUNT(*) FROM camdecmpsmd.sod_volumetric_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'sorbent_trap_aps_code' AS table_name, COUNT(*) FROM camdecmpsmd.sorbent_trap_aps_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'span_method_code' AS table_name, COUNT(*) FROM camdecmpsmd.span_method_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'span_scale_code' AS table_name, COUNT(*) FROM camdecmpsmd.span_scale_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'submission_availability_code' AS table_name, COUNT(*) FROM camdecmpsmd.submission_availability_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'substitute_data_code' AS table_name, COUNT(*) FROM camdecmpsmd.substitute_data_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'system_designation_code' AS table_name, COUNT(*) FROM camdecmpsmd.system_designation_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'system_type_code' AS table_name, COUNT(*) FROM camdecmpsmd.system_type_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'test_basis_code' AS table_name, COUNT(*) FROM camdecmpsmd.test_basis_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'test_claim_code' AS table_name, COUNT(*) FROM camdecmpsmd.test_claim_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'test_reason_code' AS table_name, COUNT(*) FROM camdecmpsmd.test_reason_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'test_result_code' AS table_name, COUNT(*) FROM camdecmpsmd.test_result_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'test_type_code' AS table_name, COUNT(*) FROM camdecmpsmd.test_type_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'train_qa_status_code' AS table_name, COUNT(*) FROM camdecmpsmd.train_qa_status_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'units_of_measure_code' AS table_name, COUNT(*) FROM camdecmpsmd.units_of_measure_code UNION ALL
SELECT 'camdecmpsmd' AS schema_name, 'waf_method_code' AS table_name, COUNT(*) FROM camdecmpsmd.waf_method_code UNION ALL
SELECT 'camdmd' AS schema_name, 'account_type_code' AS table_name, COUNT(*) FROM camdmd.account_type_code UNION ALL
SELECT 'camdmd' AS schema_name, 'applicability_status_code' AS table_name, COUNT(*) FROM camdmd.applicability_status_code UNION ALL
SELECT 'camdmd' AS schema_name, 'class_code' AS table_name, COUNT(*) FROM camdmd.class_code UNION ALL
SELECT 'camdmd' AS schema_name, 'county_code' AS table_name, COUNT(*) FROM camdmd.county_code UNION ALL
SELECT 'camdmd' AS schema_name, 'epa_region_code' AS table_name, COUNT(*) FROM camdmd.epa_region_code UNION ALL
SELECT 'camdmd' AS schema_name, 'exemption_type_code' AS table_name, COUNT(*) FROM camdmd.exemption_type_code UNION ALL
SELECT 'camdmd' AS schema_name, 'generator_source_code' AS table_name, COUNT(*) FROM camdmd.generator_source_code UNION ALL
SELECT 'camdmd' AS schema_name, 'naics_code' AS table_name, COUNT(*) FROM camdmd.naics_code UNION ALL
SELECT 'camdmd' AS schema_name, 'nerc_region_code' AS table_name, COUNT(*) FROM camdmd.nerc_region_code UNION ALL
SELECT 'camdmd' AS schema_name, 'nonstandard_code' AS table_name, COUNT(*) FROM camdmd.nonstandard_code UNION ALL
SELECT 'camdmd' AS schema_name, 'operating_status_code' AS table_name, COUNT(*) FROM camdmd.operating_status_code UNION ALL
SELECT 'camdmd' AS schema_name, 'prime_mover_type_code' AS table_name, COUNT(*) FROM camdmd.prime_mover_type_code UNION ALL
SELECT 'camdmd' AS schema_name, 'program_class' AS table_name, COUNT(*) FROM camdmd.program_class UNION ALL
SELECT 'camdmd' AS schema_name, 'program_code' AS table_name, COUNT(*) FROM camdmd.program_code UNION ALL
SELECT 'camdmd' AS schema_name, 'program_exemption' AS table_name, COUNT(*) FROM camdmd.program_exemption UNION ALL
SELECT 'camdmd' AS schema_name, 'program_group_code' AS table_name, COUNT(*) FROM camdmd.program_group_code UNION ALL
SELECT 'camdmd' AS schema_name, 'responsibility' AS table_name, COUNT(*) FROM camdmd.responsibility UNION ALL
SELECT 'camdmd' AS schema_name, 'sic_code' AS table_name, COUNT(*) FROM camdmd.sic_code UNION ALL
SELECT 'camdmd' AS schema_name, 'source_category_code' AS table_name, COUNT(*) FROM camdmd.source_category_code UNION ALL
SELECT 'camdmd' AS schema_name, 'state_code' AS table_name, COUNT(*) FROM camdmd.state_code UNION ALL
SELECT 'camdmd' AS schema_name, 'transaction_type_code' AS table_name, COUNT(*) FROM camdmd.transaction_type_code UNION ALL
SELECT 'camdmd' AS schema_name, 'tribal_land_code' AS table_name, COUNT(*) FROM camdmd.tribal_land_code UNION ALL
SELECT 'camdmd' AS schema_name, 'unit_type_code' AS table_name, COUNT(*) FROM camdmd.unit_type_code
order by 1,2
