DO $$
DECLARE
	v_calendar_year NUMERIC := 2025; --change to desired year
	v_quarter NUMERIC := 3; -- change to desired quarter

	V_PERIOD_ID CAMDECMPSMD.REPORTING_PERIOD.RPT_PERIOD_ID%TYPE;
	V_BEGINDATE CAMDECMPSAUX.EM_SUBMISSION_ACCESS.ACCESS_BEGIN_DATE%TYPE;
	V_ENDDATE   CAMDECMPSAUX.EM_SUBMISSION_ACCESS.ACCESS_END_DATE%TYPE;
BEGIN

	IF V_QUARTER = 1 THEN
		V_BEGINDATE := TO_DATE('04/01/' || V_CALENDAR_YEAR, 'mm/dd/yyyy');
	ELSIF V_QUARTER = 2 THEN
		V_BEGINDATE := TO_DATE('07/01/' || V_CALENDAR_YEAR, 'mm/dd/yyyy');
	ELSIF V_QUARTER = 3 THEN
		V_BEGINDATE := TO_DATE('10/01/' || V_CALENDAR_YEAR, 'mm/dd/yyyy');
	ELSIF V_QUARTER = 4 THEN
		V_BEGINDATE := TO_DATE('01/01/' || TO_CHAR(V_CALENDAR_YEAR + 1), 'mm/dd/yyyy');
	END IF;
	
	V_ENDDATE := V_BEGINDATE + 29;
	
	SELECT RPT_PERIOD_ID INTO V_PERIOD_ID
	FROM CAMDECMPSMD.REPORTING_PERIOD I
	WHERE CALENDAR_YEAR = V_CALENDAR_YEAR AND 
		QUARTER = V_QUARTER;
	
	DELETE FROM CAMDECMPSAUX.EM_SUBMISSION_ACCESS
	WHERE RPT_PERIOD_ID = V_PERIOD_ID AND
		EM_SUB_TYPE_CD = 'INITIAL' AND
		EM_STATUS_CD = 'APPRVD';
	
	INSERT INTO CAMDECMPSAUX.EM_SUBMISSION_ACCESS(
		MON_PLAN_ID,
		RPT_PERIOD_ID,
		ACCESS_BEGIN_DATE,
		ACCESS_END_DATE,
		EM_SUB_TYPE_CD,
		USERID,
		ADD_DATE,
		EM_STATUS_CD,
		SUB_AVAILABILITY_CD
	)
	SELECT sjwo.MON_PLAN_ID,
		sjwo.RPT_PERIOD_ID,
		V_BEGINDATE,
		V_ENDDATE,
		'INITIAL',
		'ECMPSOPN',
		CURRENT_TIMESTAMP,
		CASE WHEN sjwo.create_pending = 'T' THEN 'PENDING' ELSE 'APPRVD' END,
		CASE WHEN sjwo.create_pending = 'T' THEN NULL ELSE 'REQUIRE' END
	FROM camdecmpsaux.vw_submission_window_job_open sjwo
		where sjwo.CALENDAR_YEAR = V_CALENDAR_YEAR
		  and sjwo.QUARTER = V_QUARTER; 
	
	EXCEPTION
		WHEN OTHERS THEN
			ROLLBACK;
			RAISE;
end $$;
