TRUNCATE camdaux.job_configuration;

INSERT INTO camdaux.job_configuration (job_type, job_group, job_name, job_description, trigger_name, trigger_description, cron_expression, active, run_once, run_at)
    VALUES ('AllowanceComplianceBulkDataFiles', 'BULK_DATA', 'Allowance Compliance Bulk Data', 'Determine which allowance compliance data needs to be regenerated and schedule BulkDataFile jobs to handle the regen', 'Run yearly and check which allowance compliance files need to be regenerated', 'Runs yearly to determine if files need to be regenerated based on query results', '0 0/10 2-4 15 * ? *', TRUE, FALSE, NULL),
    ('AllowanceHoldingsBulkDataFiles', 'BULK_DATA', 'Allowance Holdings Bulk Data', 'Generate Allowance Holdings and schedule BulkDataFile jobs to handle the regen', 'Run nightly and regen allowance holdings files', 'Runs nightly to generate allowance holdings files', '0 0/10 2-4 ? * * *', TRUE, FALSE, NULL),
    ('AllowanceTransactionsBulkDataFiles', 'BULK_DATA', 'Allowance Transactions Bulk Data', 'Determine which allowance transactions need to be regenerated and schedule BulkDataFile jobs to handle the regen', 'Run nightly and check which allowance transaction attributes files need to be regenerated', 'Runs nightly to determine if files need to be regenerated based on query results', '0 0/10 2-4 15 1 ? *', TRUE, FALSE, NULL),
    ('ApportionedEmissionsBulkData', 'BULK_DATA', 'Apportioned Emissions Bulk Data', 'Determine which emissions need to be regenerated and schedule BulkDataFile jobs to handle the regen', 'Run nightly and check which emissions files need to be regenerated', 'Runs nightly to determine if files need to be regenerated based on query results or end of reporting quarter', '0 0/10 4-6 ? * * *', TRUE, FALSE, NULL),
    ('BulkDataFileMaintenance', 'BULK_DATA', 'Bulk Data File Maintenance', 'Run a check on the bulk data file maintenance queue', 'Run nightly and check which files need to have maintenance performed', 'Run nightly and check which files need to get rerun or cleaned up', '0 0 6 ? * * *', TRUE, FALSE, NULL),
    ('BulkFileJobQueue', 'MAINTAINANCE', 'Bulk File Job Queue', 'Operates on an interval to determine if files in queue can be triggered.', 'Check file queue every minute', 'Operate every minute to determine if there are files in queue which can be triggered', '0 0/1 * 1/1 * ? *', TRUE, FALSE, NULL),
    ('EmailQueue', 'MAINTAINANCE', 'Email Queue', 'Operates on an interval to determine if emails in the send email table can be sent.', 'Check to_send email queue every minute', 'Operate every minute to determine if there are emails in the queue which can be sent', '0 0/1 * 1/1 * ? *', TRUE, FALSE, NULL),
    ('EmissionsComplianceBulkDataFiles', 'BULK_DATA', 'Emissions Compliance Bulk Data', 'Determine which emissions compliance data needs to be regenerated and schedule BulkDataFile jobs to handle the regen', 'Run yearly and check which emissions compliance files need to be regenerated', 'Runs nightly to determine if files need to be regenerated based on query results', '0 0/10 2-4 15 * ? *', TRUE, FALSE, NULL),
    ('EvaluationJobQueue', 'MAINTAINANCE', 'Evaluation Job Queue', 'Operates on an interval to determine if files in evaluation queue can be triggered.', 'Check evaluation queue every 15 seconds', 'Operate every 15 seconds to determine if there are files in evaluation queue which can be triggered', '*/15 * * * * ? *', TRUE, FALSE, NULL),
    ('FacilityAttributesBulkDataFiles', 'BULK_DATA', 'Facility Attributes Bulk Data', 'Determine which facility attributes need to be regenerated and schedule BulkDataFile jobs to handle the regen', 'Run nightly and check which facility attributes files need to be regenerated', 'Runs nightly to determine if files need to be regenerated based on query results', '0 0/10 2-4 ? * * *', TRUE, FALSE, NULL),
    ('InventoryChanges', 'MAINTAINANCE', 'Inventory Changes', 'Operates on an interval to determine if any remote facility/unit inventory changes require changes to existing monitoring plans.', 'Check status log every 5 minutes', 'Operate every 5 minutes to determine if there are any new changes recorded in the inventory status log.', '0 0/5 * * * ?', TRUE, FALSE, NULL),
    ('PdemJobQueue', 'MAINTAINANCE', 'Program Data Emissions Job Queue', 'Operates on an interval to determine if emission reports in PDEM_REPORT table need to be generated.', 'Check PDEM report queue every minute', 'Operate every minute to determine if there are PDEM reports which can be triggered for generation', '0 0/1 * 1/1 * ? *', TRUE, FALSE, NULL),
    ('SubmissionJobQueue', 'MAINTAINANCE', 'Submission Job Queue', 'Operates on an interval to determine if sets in SubmissionSet table can be submitted.', 'Check submission queue every minute', 'Operate every minute to determine if there are files in submission queue which can be triggered', '0 0/1 * 1/1 * ? *', TRUE, FALSE, NULL),
    ('SubmissionReminderProcessQueue', 'MAINTAINANCE', 'Submission Reminder Process Queue', 'Operates on an interval to determine if submissions reminder emails can be processed.', 'Check file queue every minute for submission reminder emails', 'Operate every minute to determine if there are files in the queue which can be processed for Submission Reminders', '0 0/1 * 1/1 * ? *', TRUE, FALSE, NULL),
    ('SubmissionWindowProcessQueue', 'MAINTAINANCE', 'Submission Window Process Queue', 'Operates on an interval to determine if submission window reminder emails can be processed.', 'Check file queue every minute for submission window reminder emails', 'Operate every minute to determine if there are files in the queue which can be processed for Submission Window Reminders', '0 0/1 * 1/1 * ? *', TRUE, FALSE, NULL);

