INSERT INTO camdecmpsmd.component_type_code (component_type_cd, component_type_cd_description, span_indicator, parameter_cd) VALUES ('BGFF', 'Billing Gas Fuel Flowmeter', NULL, NULL);
INSERT INTO camdecmpsmd.component_type_code (component_type_cd, component_type_cd_description, span_indicator, parameter_cd) VALUES ('BOFF', 'Billing Oil Fuel Flowmeter', NULL, NULL);
INSERT INTO camdecmpsmd.component_type_code (component_type_cd, component_type_cd_description, span_indicator, parameter_cd) VALUES ('CALR', 'Calorimeter', NULL, NULL);
INSERT INTO camdecmpsmd.component_type_code (component_type_cd, component_type_cd_description, span_indicator, parameter_cd) VALUES ('CO2', 'CO2 Concentration', 1, 'CO2C');
INSERT INTO camdecmpsmd.component_type_code (component_type_cd, component_type_cd_description, span_indicator, parameter_cd) VALUES ('DAHS', 'Data Acquisition and Handling System', NULL, NULL);
INSERT INTO camdecmpsmd.component_type_code (component_type_cd, component_type_cd_description, span_indicator, parameter_cd) VALUES ('DL', 'Data Logger or Recorder', NULL, NULL);
INSERT INTO camdecmpsmd.component_type_code (component_type_cd, component_type_cd_description, span_indicator, parameter_cd) VALUES ('DP', 'Differential Pressure Transmitter/Transducer', NULL, NULL);
INSERT INTO camdecmpsmd.component_type_code (component_type_cd, component_type_cd_description, span_indicator, parameter_cd) VALUES ('FLC', 'Flow Computer', NULL, NULL);
INSERT INTO camdecmpsmd.component_type_code (component_type_cd, component_type_cd_description, span_indicator, parameter_cd) VALUES ('FLOW', 'Stack Flow Analyzer', 1, 'FLOW');
INSERT INTO camdecmpsmd.component_type_code (component_type_cd, component_type_cd_description, span_indicator, parameter_cd) VALUES ('GCH', 'Gas Chromatograph', NULL, NULL);
INSERT INTO camdecmpsmd.component_type_code (component_type_cd, component_type_cd_description, span_indicator, parameter_cd) VALUES ('GFFM', 'Gas Fuel Flowmeter', NULL, NULL);
INSERT INTO camdecmpsmd.component_type_code (component_type_cd, component_type_cd_description, span_indicator, parameter_cd) VALUES ('H2O', 'Continuous Moisture Sensor', NULL, 'H2O');
INSERT INTO camdecmpsmd.component_type_code (component_type_cd, component_type_cd_description, span_indicator, parameter_cd) VALUES ('HG', 'Mercury Concentration Analyzer (Hg CEMS)', 1, 'HGC');
INSERT INTO camdecmpsmd.component_type_code (component_type_cd, component_type_cd_description, span_indicator, parameter_cd) VALUES ('MS', 'Mass Spectrograph', NULL, NULL);
INSERT INTO camdecmpsmd.component_type_code (component_type_cd, component_type_cd_description, span_indicator, parameter_cd) VALUES ('NOX', 'NOx Concentration', 1, 'NOXC');
INSERT INTO camdecmpsmd.component_type_code (component_type_cd, component_type_cd_description, span_indicator, parameter_cd) VALUES ('O2', 'O2 Concentration', 1, 'O2C');
INSERT INTO camdecmpsmd.component_type_code (component_type_cd, component_type_cd_description, span_indicator, parameter_cd) VALUES ('OFFM', 'Oil Fuel Flowmeter', NULL, NULL);
INSERT INTO camdecmpsmd.component_type_code (component_type_cd, component_type_cd_description, span_indicator, parameter_cd) VALUES ('OP', 'Opacity Monitor', NULL, NULL);
INSERT INTO camdecmpsmd.component_type_code (component_type_cd, component_type_cd_description, span_indicator, parameter_cd) VALUES ('PLC', 'Programmable Logic Controller', NULL, NULL);
INSERT INTO camdecmpsmd.component_type_code (component_type_cd, component_type_cd_description, span_indicator, parameter_cd) VALUES ('PRB', 'Probe', NULL, NULL);
INSERT INTO camdecmpsmd.component_type_code (component_type_cd, component_type_cd_description, span_indicator, parameter_cd) VALUES ('PRES', 'Pressure Transmitter/Transducer', NULL, NULL);
INSERT INTO camdecmpsmd.component_type_code (component_type_cd, component_type_cd_description, span_indicator, parameter_cd) VALUES ('SO2', 'SO2 Concentration', 1, 'SO2C');
INSERT INTO camdecmpsmd.component_type_code (component_type_cd, component_type_cd_description, span_indicator, parameter_cd) VALUES ('TANK', 'Oil Supply Tank', NULL, NULL);
INSERT INTO camdecmpsmd.component_type_code (component_type_cd, component_type_cd_description, span_indicator, parameter_cd) VALUES ('TEMP', 'Temperature Transmitter/Transducer', NULL, NULL);
INSERT INTO camdecmpsmd.component_type_code (component_type_cd, component_type_cd_description, span_indicator, parameter_cd) VALUES ('HCL', 'HCl Concentration Analyzer', 1, 'HCLC');
INSERT INTO camdecmpsmd.component_type_code (component_type_cd, component_type_cd_description, span_indicator, parameter_cd) VALUES ('HF', 'HF Concentration Analyzer', NULL, 'HFC');
INSERT INTO camdecmpsmd.component_type_code (component_type_cd, component_type_cd_description, span_indicator, parameter_cd) VALUES ('STRAIN', 'Sorbent Trap Sampling Train Component, consisting of a sample gas flow meter and the associated sorbent trap', NULL, 'HG');
INSERT INTO camdecmpsmd.component_type_code (component_type_cd, component_type_cd_description, span_indicator, parameter_cd) VALUES ('PM', 'Particulate Matter Analyzer', NULL, 'PMC');

