-----------------
-- Constraints --
-----------------

ALTER TABLE CAMDNATS.TAUTHYR ADD CONSTRAINT TAUTHYR_PK PRIMARY KEY (LIMITTYP_CD, ALLWYEAR_DT, ACCTNUM_ID);
ALTER TABLE CAMDNATS.TAUTHYR ADD CONSTRAINT TAUTHYR_ACC_FK FOREIGN KEY (ACCTNUM_ID) REFERENCES CAMDNATS.TACCOUNT (ACCTNUM_ID);
