---------------------
-- General Indexes --
---------------------

CREATE INDEX TACCT_REP_ACCT_IX ON CAMDNATS.TACCT_REP (ACCTNUM_ID);
CREATE INDEX TACCT_REP_CD_IX ON CAMDNATS.TACCT_REP (REP_CD);
CREATE INDEX TACCT_REP_END_IX ON CAMDNATS.TACCT_REP (END_DATE);
CREATE INDEX TACCT_REP_PPL_IX ON CAMDNATS.TACCT_REP (PPL_ID);
CREATE INDEX TACCT_REP_START_IX ON CAMDNATS.TACCT_REP (START_DATE);


-----------------
-- Constraints --
-----------------

ALTER TABLE CAMDNATS.TACCT_REP ADD CONSTRAINT TACCT_REP_PK PRIMARY KEY (ACCT_REP_ID);
ALTER TABLE CAMDNATS.TACCT_REP ADD CONSTRAINT TACCT_REP_ACC_FK FOREIGN KEY (ACCTNUM_ID) REFERENCES CAMDNATS.TACCOUNT (ACCTNUM_ID);
ALTER TABLE CAMDNATS.TACCT_REP ADD CONSTRAINT TACCT_REP_PPL_FK FOREIGN KEY (PPL_ID) REFERENCES CAMD.PERSON (PPL_ID);
