-----------------
-- Constraints --
-----------------

ALTER TABLE CAMDNATS.TARS_ALLW_DED ADD CONSTRAINT TARS_ALLW_DED_PK PRIMARY KEY (COMPYEAR_DT, ACCTNUM_ID, DEDTYPE_CD);
ALTER TABLE CAMDNATS.TARS_ALLW_DED ADD CONSTRAINT TARS_ALLW_DED_ACC_FK FOREIGN KEY (ACCTNUM_ID) REFERENCES CAMDNATS.TACCOUNT (ACCTNUM_ID);
