-----------------
-- Constraints --
-----------------

ALTER TABLE CAMDNATS.TARS_ALLW_MSID ADD CONSTRAINT TARS_ALLW_MSID_PK PRIMARY KEY (COMPYEAR_DT, ACCTNUM_ID, MSID_ID);
ALTER TABLE CAMDNATS.TARS_ALLW_MSID ADD CONSTRAINT TARS_ALLW_MSID_ACC_FK FOREIGN KEY (ACCTNUM_ID) REFERENCES CAMDNATS.TACCOUNT (ACCTNUM_ID);
