-----------------
-- Constraints --
-----------------

ALTER TABLE CAMDNATS.TAUTHOR ADD CONSTRAINT TAUTHOR_PK PRIMARY KEY (LIMITTYP_CD, ACCTNUM_ID);
ALTER TABLE CAMDNATS.TAUTHOR ADD CONSTRAINT TAUTHOR_ACC_FK FOREIGN KEY (ACCTNUM_ID) REFERENCES CAMDNATS.TACCOUNT (ACCTNUM_ID);
