-----------------
-- Constraints --
-----------------

ALTER TABLE CAMDNATS.TAUTHCHG ADD CONSTRAINT TAUTHCHG_PK PRIMARY KEY (ALLWYEAR_DT, MODDATE_DT, TIME_TM, ACCTNUM_ID);
ALTER TABLE CAMDNATS.TAUTHCHG ADD CONSTRAINT TAUTHCHG_ACC_FK FOREIGN KEY (ACCTNUM_ID) REFERENCES CAMDNATS.TACCOUNT (ACCTNUM_ID);
