-----------------
-- Constraints --
-----------------

ALTER TABLE CAMDNATS.TTOTALLOW ADD CONSTRAINT TTOTALLOW_PK PRIMARY KEY (ACCTNUM_ID, ALLWYEAR_DT);
ALTER TABLE CAMDNATS.TTOTALLOW ADD CONSTRAINT TTOTALLOW_ACC_FK FOREIGN KEY (ACCTNUM_ID) REFERENCES CAMDNATS.TACCOUNT (ACCTNUM_ID);
