---------------------
-- General Indexes --
---------------------

CREATE INDEX TTRANSACT_BUY_IX ON CAMDNATS.TTRANSACT (BUYACCT_ID);
CREATE INDEX TTRANSACT_SEL_IX ON CAMDNATS.TTRANSACT (SELLACCT_ID);


-----------------
-- Constraints --
-----------------

ALTER TABLE CAMDNATS.TTRANSACT ADD CONSTRAINT TTRANSACT_PK PRIMARY KEY (TRANEVNT_CNT);
ALTER TABLE CAMDNATS.TTRANSACT ADD CONSTRAINT TTRANSACT_BUY_FK FOREIGN KEY (BUYACCT_ID) REFERENCES CAMDNATS.TACCOUNT (ACCTNUM_ID);
ALTER TABLE CAMDNATS.TTRANSACT ADD CONSTRAINT TTRANSACT_SEL_FK FOREIGN KEY (SELLACCT_ID) REFERENCES CAMDNATS.TACCOUNT (ACCTNUM_ID);
ALTER TABLE CAMDNATS.TTRANSACT ADD CONSTRAINT TTRANSACT_TYP_FK FOREIGN KEY (TRANTYPE_CD) REFERENCES CAMDNATS.TTRANTYPE (TRANTYPE_CD);

