-----------------
-- Constraints --
-----------------

ALTER TABLE CAMDNATS.TARS_OVDFT_DED ADD CONSTRAINT TARS_OVDFT_DED_PK PRIMARY KEY (TRANEVNT_CNT);
ALTER TABLE CAMDNATS.TARS_OVDFT_DED ADD CONSTRAINT TARS_OVDFT_DED_ACC_FK FOREIGN KEY (ACCTNUM_ID) REFERENCES CAMDNATS.TACCOUNT (ACCTNUM_ID);
ALTER TABLE CAMDNATS.TARS_OVDFT_DED ADD CONSTRAINT TARS_OVDFT_DED_TRN_FK FOREIGN KEY (TRANEVNT_CNT) REFERENCES CAMDNATS.TTRANSACT (TRANEVNT_CNT);
