-----------------
-- Constraints --
-----------------

ALTER TABLE CAMDNATS.TCOMPPROB_TRANSACT ADD CONSTRAINT TCOMPPROB_TRANSACT_PK PRIMARY KEY (TRANEVNT_CNT, ACCTNUM_ID, COMPYEAR_DT, TRANTYPE_CD, ALLWYEAR_DT);
ALTER TABLE CAMDNATS.TCOMPPROB_TRANSACT ADD CONSTRAINT TCOMPPROB_TRANSACT_ACC_FK FOREIGN KEY (ACCTNUM_ID) REFERENCES CAMDNATS.TACCOUNT (ACCTNUM_ID);
ALTER TABLE CAMDNATS.TCOMPPROB_TRANSACT ADD CONSTRAINT TCOMPPROB_TRANSACT_TRN_FK FOREIGN KEY (TRANEVNT_CNT) REFERENCES CAMDNATS.TTRANSACT (TRANEVNT_CNT);
