-----------------
-- Constraints --
-----------------

ALTER TABLE CAMDNATS.TCOMPPROB_TRANSACT ADD CONSTRAINT TCOMPPROB_TRANSACT_PK PRIMARY KEY (TRANEVNT_CNT, ACCTNUM_ID, COMPYEAR_DT, TRANTYPE_CD, ALLWYEAR_DT);
