CREATE OR REPLACE FUNCTION camdecmps.checkmpcombinedmethods
(	
	p_facilityId bigint
)
RETURNS TABLE(
MON_METHOD_ID character varying(45), 
MON_LOC_ID character varying(45), 
PARAMETER_CD character varying(7), 
SUB_DATA_CD character varying(7), 
BYPASS_APPROACH_CD  character varying(7), 
METHOD_CD  character varying(7), 
BEGIN_DATE date, 
BEGIN_HOUR numeric(2,0), 
END_DATE date, 
END_HOUR numeric(2,0), 
STACK_PIPE_ID character varying(45), 
UNIT_ID numeric(38),
STACK_NAME character varying(6),
UNITID character varying(6),
BEGIN_DATEHOUR timestamp,
END_DATEHOUR timestamp,
CROSSCHECK_PARAMETER character varying(7)
)
AS
$$
BEGIN

RETURN QUERY

	SELECT 
			m.MON_METHOD_ID, 
			l.MON_LOC_ID, 
			m.PARAMETER_CD, 
			m.SUB_DATA_CD, 
			m.BYPASS_APPROACH_CD, 
			m.METHOD_CD, 
			m.BEGIN_DATE, 
			m.BEGIN_HOUR, 
			m.END_DATE, 
			m.END_HOUR, 
			l.STACK_PIPE_ID, 
			l.UNIT_ID,
			CASE WHEN l.STACK_PIPE_ID IS NULL THEN NULL ELSE l.LOCATION_IDENTIFIER END AS STACK_NAME,
			CASE WHEN l.UNIT_ID IS NULL THEN NULL ELSE l.LOCATION_IDENTIFIER END AS UNITID,
			m.BEGIN_HOUR * INTERVAL '1 HOUR' + m.BEGIN_DATE BEGIN_DATEHOUR,
			m.END_HOUR * INTERVAL '1 HOUR' + m.END_DATE END_DATEHOUR,
			m.PARAMETER_CD CROSSCHECK_PARAMETER
	FROM ecmps.MONITOR_METHOD m
	INNER JOIN ecmps.VW_MONITOR_LOCATION l ON m.MON_LOC_ID = l.MON_LOC_ID
	INNER JOIN ecmps.MONITOR_PLAN_LOCATION mpl ON mpl.MON_LOC_ID = l.MON_LOC_ID
	WHERE (p_facilityId IS NULL OR FAC_ID=p_facilityId)

	UNION

	SELECT	
		mth.MATS_METHOD_ID, 
		mth.MON_LOC_ID,
		mth.MATS_METHOD_PARAMETER_CD PARAMETER_CD, 
		NULL AS SUB_DATA_CD, 
		NULL AS BYPASS_APPROACH_CD, 
		mth.MATS_METHOD_CD METHOD_CD,
		mth.BEGIN_DATE, 
		mth.BEGIN_HOUR, 
		mth.END_DATE, 
		mth.END_HOUR, 
		l.STACK_PIPE_ID, 
		l.UNIT_ID,
		CASE WHEN l.STACK_PIPE_ID IS NULL THEN NULL ELSE l.LOCATION_IDENTIFIER END AS STACK_NAME,
		CASE WHEN l.UNIT_ID IS NULL THEN NULL ELSE l.LOCATION_IDENTIFIER END AS UNITID,
		mth.BEGIN_HOUR * INTERVAL '1 HOUR' + mth.BEGIN_DATE BEGIN_DATEHOUR,
		mth.END_HOUR * INTERVAL '1 HOUR' + mth.END_DATE END_DATEHOUR,
		'MATSSUP' CROSSCHECK_PARAMETER
	FROM ecmps.MATS_METHOD_DATA mth 
	INNER JOIN	ecmps.MONITOR_PLAN_LOCATION mpl	ON	mth.MON_LOC_ID = mpl.MON_LOC_ID
	INNER JOIN ecmps.VW_MONITOR_LOCATION l ON mpl.MON_LOC_ID = l.MON_LOC_ID
	WHERE (p_facilityId IS NULL OR FAC_ID=p_facilityId);
	
	
end;

$$ LANGUAGE plpgsql;