-- Ticket #7307: convert numeric(38,0) id columns to bigint (camdecmpswks)

ALTER TABLE IF EXISTS camdecmpswks.check_log ALTER COLUMN check_catalog_result_id TYPE bigint, ALTER COLUMN error_suppress_id TYPE bigint, ALTER COLUMN rule_check_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmpswks.check_session ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmpswks.component_op_supp_data ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmpswks.daily_backstop ALTER COLUMN rpt_period_id TYPE bigint, ALTER COLUMN unit_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmpswks.daily_calibration ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmpswks.daily_emission ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmpswks.daily_fuel ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmpswks.daily_test_summary ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmpswks.daily_test_supp_data ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmpswks.daily_test_system_supp_data ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmpswks.derived_hrly_value ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmpswks.emission_evaluation ALTER COLUMN rpt_period_id TYPE bigint, ALTER COLUMN submission_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmpswks.emission_view_dailycal ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmpswks.hrly_fuel_flow ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmpswks.hrly_gas_flow_meter ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmpswks.hrly_op_data ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmpswks.hrly_param_fuel_flow ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmpswks.last_qa_value_supp_data ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmpswks.long_term_fuel_flow ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmpswks.mats_bulk_file ALTER COLUMN fac_id TYPE bigint, ALTER COLUMN submission_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmpswks.mats_derived_hrly_value ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmpswks.mats_monitor_hrly_value ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmpswks.monitor_hrly_value ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmpswks.monitor_location ALTER COLUMN unit_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmpswks.monitor_plan ALTER COLUMN begin_rpt_period_id TYPE bigint, ALTER COLUMN end_rpt_period_id TYPE bigint, ALTER COLUMN fac_id TYPE bigint, ALTER COLUMN submission_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmpswks.monitor_plan_reporting_freq ALTER COLUMN begin_rpt_period_id TYPE bigint, ALTER COLUMN end_rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmpswks.nsps4t_annual ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmpswks.nsps4t_compliance_period ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmpswks.nsps4t_summary ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmpswks.operating_supp_data ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmpswks.qa_cert_event ALTER COLUMN submission_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmpswks.qa_cert_event_supp_data ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmpswks.qa_supp_data ALTER COLUMN rpt_period_id TYPE bigint, ALTER COLUMN submission_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmpswks.sampling_train ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmpswks.sampling_train_supp_data ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmpswks.sorbent_trap ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmpswks.sorbent_trap_supp_data ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmpswks.stack_pipe ALTER COLUMN fac_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmpswks.summary_value ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmpswks.system_op_supp_data ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmpswks.test_extension_exemption ALTER COLUMN rpt_period_id TYPE bigint, ALTER COLUMN submission_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmpswks.test_summary ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmpswks.unit ALTER COLUMN fac_id TYPE bigint, ALTER COLUMN unit_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmpswks.unit_capacity ALTER COLUMN unit_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmpswks.unit_control ALTER COLUMN unit_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmpswks.unit_fuel ALTER COLUMN unit_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmpswks.unit_stack_configuration ALTER COLUMN unit_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmpswks.weekly_system_integrity ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmpswks.weekly_test_summary ALTER COLUMN rpt_period_id TYPE bigint;
