create materialized view camdsnap.PEOPLE_DETAIL_SS
as 
SELECT P.PPL_ID,
       CASE WHEN CU.CDX_USER_ID IS NOT NULL THEN STRING_AGG(DISTINCT CO.CDX_ORG_NAME, '; ' ORDER BY CO.CDX_ORG_NAME) ELSE C.COMPANY_NAME END AS AFFILIATION,
       P.PPL_ID AS REP_ID,
       COALESCE(CU.USERID, P.USERID) AS USERID,
       GREATEST(COALESCE(P.UPDATE_DATE, P.ADD_DATE), COALESCE(CU.UPDATE_DATE, CU.ADD_DATE)) AS UPDATE_DATE,
       P.ADD_DATE,
       GREATEST(COALESCE(P.UPDATE_DATE, P.ADD_DATE), COALESCE(CU.UPDATE_DATE, CU.ADD_DATE)) AS LAST_MODIFIED,
       P.PERSON_TYPE_CD,
       PT.PERSON_TYPE_DESCRIPTION,
       PT.PERSON_TYPE_GROUP_CD,
       (P.PERSON_TYPE_CD || ', ' || PT.PERSON_TYPE_GROUP_CD) AS PERSON_TYPE_AND_GRP,
       C.COMPANY_ID AS COMP_ID
  FROM CAMD.PERSON P
  LEFT OUTER JOIN CAMDMD.PERSON_TYPE_CODE PT ON P.PERSON_TYPE_CD = PT.PERSON_TYPE_CD
  LEFT OUTER JOIN CAMD.CDX_USER CU ON P.PPL_ID = CU.PPL_ID
  LEFT OUTER JOIN CAMD.CDX_USER_ORG CUO ON CU.CDX_USER_ID = CUO.CDX_USER_ID AND CUO.ACTIVE_IND = 1
  LEFT OUTER JOIN CAMD.CDX_ORG CO ON CUO.CDX_ORG_ID = CO.CDX_ORG_ID
  LEFT OUTER JOIN CAMD.COMPANY C ON P.COMPANY_ID = C.COMPANY_ID
 WHERE COALESCE(PT.PERSON_TYPE_GROUP_CD, 'IND') = 'IND'
 GROUP BY P.PPL_ID,
            P.PPL_ID,
            COALESCE(CU.USERID, P.USERID),
            GREATEST(COALESCE(P.UPDATE_DATE, P.ADD_DATE), COALESCE(CU.UPDATE_DATE, CU.ADD_DATE)),
            P.ADD_DATE,
            GREATEST(COALESCE(P.UPDATE_DATE, P.ADD_DATE), COALESCE(CU.UPDATE_DATE, CU.ADD_DATE)),
            P.PERSON_TYPE_CD,
            PT.PERSON_TYPE_DESCRIPTION,
            PT.PERSON_TYPE_GROUP_CD,
            (P.PERSON_TYPE_CD || ', ' || PT.PERSON_TYPE_GROUP_CD),
            C.COMPANY_ID,
            CU.CDX_USER_ID,
            C.COMPANY_NAME
UNION ALL
SELECT P.PPL_ID,
       CASE WHEN CU.CDX_USER_ID IS NOT NULL THEN STRING_AGG(DISTINCT CO.CDX_ORG_NAME, '; ' ORDER BY CO.CDX_ORG_NAME) ELSE A.AGENCY_NAME END AS AFFILIATION,
       NULL AS REP_ID,
       COALESCE(CU.USERID, P.USERID) AS USERID,
       GREATEST(COALESCE(P.UPDATE_DATE, P.ADD_DATE), COALESCE(CU.UPDATE_DATE, CU.ADD_DATE)) AS UPDATE_DATE,
       P.ADD_DATE,
       GREATEST(COALESCE(P.UPDATE_DATE, P.ADD_DATE), COALESCE(CU.UPDATE_DATE, CU.ADD_DATE)) AS LAST_MODIFIED,
       P.PERSON_TYPE_CD,
       PT.PERSON_TYPE_DESCRIPTION,
       PT.PERSON_TYPE_GROUP_CD,
       (P.PERSON_TYPE_CD || ',' || PT.PERSON_TYPE_GROUP_CD) AS PERSON_TYPE_AND_GRP,
       NULL AS COMP_ID
  FROM CAMD.PERSON P
  LEFT OUTER JOIN CAMDMD.PERSON_TYPE_CODE PT ON P.PERSON_TYPE_CD = PT.PERSON_TYPE_CD
  LEFT OUTER JOIN CAMD.CDX_USER CU ON P.PPL_ID = CU.PPL_ID
  LEFT OUTER JOIN CAMD.CDX_USER_ORG CUO ON CU.CDX_USER_ID = CUO.CDX_USER_ID AND CUO.ACTIVE_IND = 1
  LEFT OUTER JOIN CAMD.CDX_ORG CO ON CUO.CDX_ORG_ID = CO.CDX_ORG_ID
  LEFT OUTER JOIN CAMD.AGENCY A ON P.AGENCY_ID = A.AGENCY_ID
 WHERE PT.PERSON_TYPE_GROUP_CD = 'AGY'
 GROUP BY P.PPL_ID,
            COALESCE(CU.USERID, P.USERID),
            GREATEST(COALESCE(P.UPDATE_DATE, P.ADD_DATE), COALESCE(CU.UPDATE_DATE, CU.ADD_DATE)),
            P.ADD_DATE,
            GREATEST(COALESCE(P.UPDATE_DATE, P.ADD_DATE), COALESCE(CU.UPDATE_DATE, CU.ADD_DATE)),
            P.PERSON_TYPE_CD,
            PT.PERSON_TYPE_DESCRIPTION,
            PT.PERSON_TYPE_GROUP_CD,
            (P.PERSON_TYPE_CD || ', ' || PT.PERSON_TYPE_GROUP_CD),
            CU.CDX_USER_ID,
            A.AGENCY_NAME;

comment on materialized view camdsnap.PEOPLE_DETAIL_SS is 'snapshot table for snapshot CAMDSNAP.PEOPLE_DETAIL_SS';
