-----------------
-- Constraints --
-----------------

ALTER TABLE CAMD.UNIT_PROGRAM_90TH_OP_DATE ADD CONSTRAINT UNIT_PROGRAM_90TH_OP_DATE_PK PRIMARY KEY ( UNIT_ID, PRG_CD );
ALTER TABLE CAMD.UNIT_PROGRAM_90TH_OP_DATE ADD CONSTRAINT UNIT_PROGRAM_90TH_OP_DATE_PRG_FK FOREIGN KEY ( PRG_CD ) REFERENCES CAMDMD.PROGRAM_CODE ( PRG_CD );
