CREATE OR REPLACE VIEW vw_inconsistent_MP_MPRF_dates AS
SELECT 
    VMP.ORIS_CODE,
    VMP.FACILITY_NAME,
    VMP.STATE,
    VMP.LOCATIONS,
    BRP.CALENDAR_YEAR || ' Q' || BRP.QUARTER AS BEGIN_PERIOD,
    CASE 
         WHEN RF.END_RPT_PERIOD_ID IS NOT NULL THEN ERP.CALENDAR_YEAR || ' Q' || ERP.QUARTER 
         ELSE '' 
    END AS END_PERIOD,
    RF.REPORT_FREQ_CD AS LOCATIONS2,
    NULL AS BEGIN_PERIOD2,
    NULL AS END_PERIOD2
FROM 
    (
      SELECT DISTINCT 
          MON_PLAN_ID,
          ORIS_CODE,
          FACILITY_NAME,
          STATE,
          LOCATIONS
      FROM camdecmps.VW_MONITOR_PLAN
    ) VMP
JOIN 
    (
      SELECT 
          MON_PLAN_ID,
          MPRF.BEGIN_RPT_PERIOD_ID,
          MPRF.END_RPT_PERIOD_ID,
          MPRF.REPORT_FREQ_CD
      FROM camdecmps.MONITOR_PLAN_REPORTING_FREQ MPRF
      WHERE EXISTS (
          SELECT 1
          FROM camdecmps.MONITOR_PLAN_REPORTING_FREQ
          WHERE MON_PLAN_RF_ID <> MPRF.MON_PLAN_RF_ID
            AND MON_PLAN_ID = MPRF.MON_PLAN_ID
            AND (
                 BEGIN_RPT_PERIOD_ID BETWEEN MPRF.BEGIN_RPT_PERIOD_ID AND COALESCE(MPRF.END_RPT_PERIOD_ID, 999)
                 OR COALESCE(END_RPT_PERIOD_ID, 999) BETWEEN MPRF.BEGIN_RPT_PERIOD_ID AND COALESCE(MPRF.END_RPT_PERIOD_ID, 999)
                )
      )
    ) RF 
      ON VMP.MON_PLAN_ID = RF.MON_PLAN_ID
JOIN camdecmpsmd.REPORTING_PERIOD BRP 
      ON RF.BEGIN_RPT_PERIOD_ID = BRP.RPT_PERIOD_ID
LEFT JOIN camdecmpsmd.REPORTING_PERIOD ERP 
      ON RF.END_RPT_PERIOD_ID = ERP.RPT_PERIOD_ID
ORDER BY 
    VMP.ORIS_CODE,
    VMP.LOCATIONS,
    BRP.CALENDAR_YEAR || ' Q' || BRP.QUARTER;
