CREATE OR REPLACE VIEW vw_MP_EM_date_in_inconsistencies AS
SELECT 
    VMP.ORIS_CODE,
    VMP.FACILITY_NAME,
    VMP.STATE,
    VMP.LOCATIONS,
    BRP.CALENDAR_YEAR || ' Q' || BRP.QUARTER AS BEGIN_PERIOD,
    CASE 
         WHEN X.END_RPT_PERIOD_ID IS NOT NULL 
         THEN ERP.CALENDAR_YEAR || ' Q' || ERP.QUARTER 
         ELSE '' 
    END AS END_PERIOD,
    NULL AS LOCATIONS2,
    RP.CALENDAR_YEAR || ' Q' || RP.QUARTER AS BEGIN_PERIOD2,
    NULL AS END_PERIOD2
FROM (
    SELECT 
         MP.MON_PLAN_ID,
         E.RPT_PERIOD_ID,
         MP.BEGIN_RPT_PERIOD_ID,
         MP.END_RPT_PERIOD_ID
    FROM camdecmps.EMISSION_EVALUATION E
    JOIN camdecmps.MONITOR_PLAN MP 
         ON E.MON_PLAN_ID = MP.MON_PLAN_ID
    WHERE E.RPT_PERIOD_ID < MP.BEGIN_RPT_PERIOD_ID 
       OR E.RPT_PERIOD_ID > COALESCE(MP.END_RPT_PERIOD_ID, 999)
) X
JOIN camdecmps.VW_MONITOR_PLAN VMP 
    ON X.MON_PLAN_ID = VMP.MON_PLAN_ID
JOIN camdecmpsmd.REPORTING_PERIOD BRP 
    ON X.BEGIN_RPT_PERIOD_ID = BRP.RPT_PERIOD_ID
LEFT JOIN camdecmpsmd.REPORTING_PERIOD ERP 
    ON X.END_RPT_PERIOD_ID = ERP.RPT_PERIOD_ID
JOIN camdecmpsmd.REPORTING_PERIOD RP 
    ON X.RPT_PERIOD_ID = RP.RPT_PERIOD_ID
ORDER BY VMP.ORIS_CODE, VMP.LOCATIONS;
