-- Table: camdecmpswks.certification_statement

-- DROP TABLE camdecmpswks.certification_statement;

CREATE TABLE IF NOT EXISTS camdecmpswks.certification_statement
(
    statement_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    statement_text text COLLATE pg_catalog."default" NOT NULL,
    prg_cd character varying(7) COLLATE pg_catalog."default",
    display_order numeric(4,0) NOT NULL DEFAULT 1,
    CONSTRAINT pk_certification_statement PRIMARY KEY (statement_id)
);

INSERT INTO camdecmpswks.certification_statement(statement_text, prg_cd)
VALUES
	('I am authorized to make this submission on behalf of the owners and operators of the source or units for which the submission is made. I certify under penalty of law that I have personally examined, and am familiar with, the statements and information submitted in this document and all its attachments. Based on my inquiry of those individuals with primary responsibility for obtaining the information, I certify that the statements and information are to the best of my knowledge and belief true, accurate, and complete. I am aware that there are significant penalties for submitting false statements and information or omitting required statements and information, including the possibility of fine or imprisonment. If I am an agent authorized to make this electronic submission, I am signing the above certification on behalf of the authorizing designated representative or alternate designated representative, and this action is deemed to be a certification by that designated representative or alternate designated representative. The designated representative or alternate designated representative must sign (i.e., agree to) this certification statement. If you are an agent and you click on "Agree", you are not agreeing to the certification statement, but are submitting the certification statement on behalf of the designated representative or alternate designated representative who is agreeing to the certification statement. An agent is only authorized to make the electronic submission on behalf of the designated representative, not to sign (i.e., agree to) the certification statement.', null),
	('I am authorized to make this submission on behalf of the owners and operators of the source or units for which the submission is made. I certify under penalty of law that I have personally examined, and am familiar with, the statements and information submitted in this document and all its attachments. Based on my inquiry of those individuals with primary responsibility for obtaining the information, I certify that the statements and information are to the best of my knowledge and belief true, accurate, and complete. I am aware that there are significant penalties for submitting false statements and information or omitting required statements and information, including the possibility of fine or imprisonment. Except as provided in the paragraph below, If I am an agent authorized to make this electronic submission, I am signing the above certification on behalf of the authorizing designated representative or alternate designated representative, and this action is deemed to be a certification by that designated representative or alternate designated representative. If the facility for which this submission is being made has a responsible official (RO) that has registered in the CAMD Business System as an RO that attests to the truthfulness, accuracy, and completeness of the MATS-associated data submitted in each electronic quarterly report under section 7.2.5 of Appendix B to Subpart UUUUU of MATS, I certify that I am signing the above certification on behalf of the RO, and this action is deemed to be a certification by that RO covering the MATS-associated data only.', 'MATS');
	