CREATE TABLE IF NOT EXISTS camdecmpswks.emission_view_noxmasscems(
    em_nox_mass_cems_id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    mon_plan_id VARCHAR(45) NOT NULL,
    mon_loc_id VARCHAR(45) NOT NULL,
    rpt_period_id INTEGER NOT NULL,
    datehour varchar(25) NOT NULL,
    op_time NUMERIC(3,2),
    unit_load NUMERIC(6,0),
    load_uom VARCHAR(7),
    unadj_nox NUMERIC(13,3),
    calc_nox_baf NUMERIC(5,3),
    rpt_adj_nox NUMERIC(13,3),
    adj_nox_used NUMERIC(13,3),
    nox_modc VARCHAR(7),
    nox_pma NUMERIC(4,1),
    unadj_flow NUMERIC(13,3),
    calc_flow_baf NUMERIC(5,3),
    rpt_adj_flow NUMERIC(13,3),
    adj_flow_used NUMERIC(13,3),
    flow_modc VARCHAR(7),
    flow_pma NUMERIC(4,1),
    pct_h2o_used NUMERIC(5,1),
    source_h2o_value VARCHAR(7),
    noxmass_formula_code VARCHAR(7),
    rpt_nox_mass NUMERIC(14,4),
    calc_nox_mass NUMERIC(14,4),
    error_codes VARCHAR(1000)
)