CREATE TABLE IF NOT EXISTS camdecmpswks.emission_view_so2appd(
    em_so2_appd_id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    mon_plan_id VARCHAR(45) NOT NULL,
    mon_loc_id VARCHAR(45) NOT NULL,
    rpt_period_id INTEGER NOT NULL,
    datehour varchar(25) NOT NULL,
    op_time NUMERIC(3,2),
    fuel_sys_id VARCHAR(3),
    fuel_type VARCHAR(7) NOT NULL,
    fuel_use_time NUMERIC(3,2),
    unit_load NUMERIC(6,0),
    load_uom VARCHAR(7),
    calc_fuel_flow NUMERIC(10,1),
    fuel_flow_uom VARCHAR(7),
    fuel_flow_sodc VARCHAR(7),
    sulfur_content NUMERIC(13,5),
    sulfur_uom VARCHAR(7),
    sulfur_sampling_type VARCHAR(7),
    default_so2_emission_rate NUMERIC(13,5),
    calc_hi_rate NUMERIC(13,5),
    formula_code VARCHAR(7),
    rpt_so2_mass_rate NUMERIC(13,5),
    calc_so2_mass_rate NUMERIC(13,5),
    summation_formula_cd VARCHAR(7),
    rpt_so2_mass_rate_all_fuels NUMERIC(14,4),
    calc_so2_mass_rate_all_fuels NUMERIC(14,4),
    error_codes VARCHAR(1000)
)