CREATE TABLE IF NOT EXISTS camdecmpswks.emission_view_mats_sorbent(
    em_mats_sorbent_id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    mon_plan_id VARCHAR(45) NOT NULL,
    mon_loc_id VARCHAR(45) NOT NULL,
    rpt_period_id INTEGER NOT NULL,
    system_identifier VARCHAR(3) NOT NULL,
    date_hour varchar(25) NOT NULL,
    end_date_time varchar(25) NOT NULL,
    paired_trap_agreement NUMERIC(5,2),
    absolute_difference_ind INTEGER,
    modc_cd VARCHAR(7),
    hg_concentration VARCHAR(30),
    a_component_id VARCHAR(45),
    a_sorbent_trap_serial_number VARCHAR(45),
    a_main_trap_hg VARCHAR(30),
    a_breakthrough_trap_hg VARCHAR(30),
    a_spike_trap_hg VARCHAR(30),
    a_spike_ref_value VARCHAR(30),
    a_total_sample_volume DOUBLE PRECISION,
    a_ref_flow_to_sampling_ratio NUMERIC(4,1),
    a_hg_concentration VARCHAR(30),
    a_percent_breakthrough NUMERIC(6,1),
    a_percent_spike_recovery NUMERIC(4,1),
    a_sampling_ratio_test_result_cd VARCHAR(7),
    a_post_leak_test_result_cd VARCHAR(7),
    a_train_qa_status_cd VARCHAR(10) NOT NULL,
    a_sample_damage_explanation VARCHAR(1000),
    b_component_id VARCHAR(45),
    b_sorbent_trap_serial_number VARCHAR(45),
    b_main_trap_hg VARCHAR(30),
    b_breakthrough_trap_hg VARCHAR(30),
    b_spike_trap_hg VARCHAR(30),
    b_spike_ref_value VARCHAR(30),
    b_total_sample_volume DOUBLE PRECISION,
    b_ref_flow_to_sampling_ratio NUMERIC(4,1),
    b_hg_concentration VARCHAR(30),
    b_percent_breakthrough NUMERIC(6,1),
    b_percent_spike_recovery NUMERIC(4,1),
    b_sampling_ratio_test_result_cd VARCHAR(7),
    b_post_leak_test_result_cd VARCHAR(7),
    b_train_qa_status_cd VARCHAR(10) NOT NULL,
    b_sample_damage_explanation VARCHAR(1000),
    error_codes VARCHAR(1000),
    sorbent_trap_aps_cd VARCHAR(7),
    rata_ind INTEGER
)