CREATE TABLE IF NOT EXISTS camdecmpswks.emission_view_noxappesinglefuel(
    em_nox_appe_single_fuel_id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    mon_plan_id VARCHAR(45) NOT NULL,
    mon_loc_id VARCHAR(45) NOT NULL,
    rpt_period_id INTEGER NOT NULL,
    date_hour varchar(25) NOT NULL,
    op_time NUMERIC(3,2),
    fuel_sys_id VARCHAR(3),
    fuel_type VARCHAR(45) NOT NULL,
    fuel_use_time NUMERIC(3,2),
    unit_load NUMERIC(6,0),
    load_uom VARCHAR(45),
    calc_hi_rate NUMERIC(13,5),
    operating_condition_cd VARCHAR(45),
    segment_number INTEGER,
    app_e_sys_id VARCHAR(3),
    rpt_nox_emission_rate NUMERIC(13,5),
    calc_nox_emission_rate NUMERIC(13,5),
    summation_formula_cd VARCHAR(45),
    rpt_nox_emission_rate_all_fuels NUMERIC(14,4),
    calc_nox_emission_rate_all_fuels NUMERIC(14,4),
    calc_hi_rate_all_fuels NUMERIC(14,4),
    nox_mass_rate_formula_cd VARCHAR(45),
    rpt_nox_mass_all_fuels NUMERIC(14,4),
    calc_nox_mass_all_fuels NUMERIC(14,4),
    error_codes VARCHAR(1000)
)