CREATE TABLE IF NOT EXISTS camdecmpswks.emission_view_co2cems(
    em_co2_cems_id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    mon_plan_id VARCHAR(45) NOT NULL,
    mon_loc_id VARCHAR(45) NOT NULL,
    rpt_period_id INTEGER NOT NULL,
    date TIMESTAMP NOT NULL,
    hour NUMERIC(2,0 ) NOT NULL,
    op_time NUMERIC(3,2),
    unit_load NUMERIC(6,0),
    load_uom VARCHAR(7),
    component_type VARCHAR(3),
    rpt_pct_co2 NUMERIC(14,4),
    pct_co2_used NUMERIC(5,1),
    co2_modc VARCHAR(7),
    co2_pma NUMERIC(4,1),
    unadj_flow NUMERIC(13,3),
    calc_flow_baf NUMERIC(5,3),
    rpt_adj_flow NUMERIC(13,3),
    adj_flow_used NUMERIC(13,3),
    flow_modc VARCHAR(45),
    flow_pma NUMERIC(4,1),
    pct_h2o_used NUMERIC(5,1),
    source_h2o_value VARCHAR(7),
    co2_formula_code VARCHAR(45),
    rpt_co2_mass_rate NUMERIC(14,4),
    calc_co2_mass_rate NUMERIC(14,4),
    error_codes VARCHAR(1000)
)