CREATE TABLE IF NOT EXISTS camdecmpswks.emission_view_hicems(
    em_hi_cems_id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    mon_plan_id varchar(45) NOT NULL,
    mon_loc_id varchar(45) NOT NULL,
    rpt_period_id integer NOT NULL,
    hour_id varchar(45) NOT NULL,
    datehour varchar(25) NOT NULL,
    op_time NUMERIC(3,2),
    unit_load NUMERIC(6,0),
    load_uom varchar(7),
    load_range INTEGER,
    common_stack_load_range INTEGER,
    hi_formula_code varchar(7),
    hi_modc varchar(7),
    rpt_hi_rate NUMERIC(14,4),
    calc_hi_rate NUMERIC(14,4),
    diluent_param VARCHAR(3),
    rpt_pct_diluent NUMERIC(13,3),
    pct_diluent_used NUMERIC(5,1),
    diluent_modc VARCHAR(7),
    diluent_pma NUMERIC(4,1),
    unadj_flow NUMERIC(13,3),
    calc_flow_baf NUMERIC(5,3),
    rpt_adj_flow NUMERIC(13,3),
    adj_flow_used NUMERIC(13,3),
    flow_modc varchar(7),
    flow_pma NUMERIC(4,1),
    pct_h2o_used NUMERIC(5,1),
    source_h2o_value VARCHAR(7),
    f_factor NUMERIC(8,1),
    error_codes varchar(1000),
    fuel_cd varchar(7)
)