CREATE TABLE IF NOT EXISTS camdecmpswks.emission_view_hiappd(
    em_hi_appd_id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    mon_plan_id VARCHAR(45) NOT NULL,
    mon_loc_id VARCHAR(45) NOT NULL,
    rpt_period_id INTEGER NOT NULL,
    datehour varchar(25) NOT NULL,
    op_time NUMERIC(3,2),
    fuel_sys_id VARCHAR(3),
    fuel_type VARCHAR(7) NOT NULL,
    fuel_use_time NUMERIC(3,2),
    unit_load NUMERIC(6,0),
    load_uom VARCHAR(7),
    rpt_fuel_flow NUMERIC(10,1),
    calc_fuel_flow NUMERIC(10,1),
    fuel_flow_uom VARCHAR(7),
    fuel_flow_sodc VARCHAR(7),
    gross_calorific_value NUMERIC(13,5),
    gcv_uom VARCHAR(7),
    gcv_sampling_type VARCHAR(7),
    formula_code VARCHAR(7),
    rpt_hi_rate NUMERIC(13,5),
    calc_hi_rate NUMERIC(13,5),
    error_codes VARCHAR(1000)
)