CREATE TABLE IF NOT EXISTS camdecmpswks.emission_view_mats_hg(
    em_mats_hg_id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    mon_plan_id VARCHAR(45) NOT NULL,
    mon_loc_id VARCHAR(45) NOT NULL,
    rpt_period_id INTEGER NOT NULL,
    date_hour character varying(25) COLLATE pg_catalog."default" NOT NULL, 
    op_time NUMERIC(3,2),
    mats_load NUMERIC(6,0),
    mats_startup_shutdown VARCHAR(1000),
    hg_conc_value VARCHAR(30),
    hg_conc_system_id VARCHAR(3),
    hg_conc_sys_type VARCHAR(1000),
    hg_conc_modc_cd VARCHAR(7),
    hg_conc_pma NUMERIC(4,1),
    sampling_train_comp_id1 VARCHAR(3),
    gas_flowmeter_reading1 NUMERIC(13,3),
    ratio_stack_gas_flow_rate1 NUMERIC(4,1),
    sampling_train_comp_id2 VARCHAR(3),
    gas_flowmeter_reading2 NUMERIC(13,3),
    ratio_stack_gas_flow_rate2 NUMERIC(4,1),
    flow_rate VARCHAR(30),
    flow_modc VARCHAR(7),
    flow_pma NUMERIC(4,1),
    rpt_pct_diluent VARCHAR(30),
    diluent_parameter VARCHAR(8),
    calc_pct_diluent NUMERIC(5,1),
    diluent_modc VARCHAR(7),
    calc_pct_h2o NUMERIC(5,1),
    h2o_source VARCHAR(7),
    f_factor NUMERIC(8,1),
    hg_formula_cd VARCHAR(7),
    rpt_hg_rate VARCHAR(30),
    hg_uom VARCHAR(10),
    hg_modc_cd VARCHAR(7),
    error_codes VARCHAR(1000),
    calc_hg_rate VARCHAR(30)
);