CREATE TABLE IF NOT EXISTS camdecmpswks.rata_summary
(
    rata_sum_id character varying(45) COLLATE pg_catalog."default" NOT NULL,
    rata_id character varying(45) COLLATE pg_catalog."default" NOT NULL,
    relative_accuracy numeric(5,2),
    calc_relative_accuracy numeric(5,2),
    bias_adj_factor numeric(5,3),
    calc_bias_adj_factor numeric(5,3),
    mean_cem_value numeric(15,5),
    calc_mean_cem_value numeric(15,5),
    mean_rata_ref_value numeric(15,5),
    calc_mean_rata_ref_value numeric(15,5),
    op_level_cd character varying(7) COLLATE pg_catalog."default" NOT NULL,
    mean_diff numeric(15,5),
    calc_mean_diff numeric(15,5),
    default_waf numeric(6,4),
    avg_gross_unit_load numeric(6,0),
    calc_avg_gross_unit_load numeric(6,0),
    aps_ind numeric(38,0),
    calc_aps_ind numeric(38,0),
    stnd_dev_diff numeric(15,5),
    calc_stnd_dev_diff numeric(15,5),
    confidence_coef numeric(15,5),
    calc_confidence_coef numeric(15,5),
    co2_o2_ref_method_cd character varying(7) COLLATE pg_catalog."default",
    ref_method_cd character varying(7) COLLATE pg_catalog."default",
    t_value numeric(6,3),
    calc_t_value numeric(6,3),
    stack_diameter numeric(5,2),
    stack_area numeric(6,1),
    calc_stack_area numeric(6,1),
    calc_waf numeric(6,4),
    calc_calc_waf numeric(6,4),
    num_traverse_point numeric(2,0),
    userid character varying(160) COLLATE pg_catalog."default",
    add_date timestamp without time zone,
    update_date timestamp without time zone,
    aps_cd character varying(7) COLLATE pg_catalog."default"
);