-- PROCEDURE: camdecmps.refresh_emission_view_noxappemixedfuel(character varying, numeric)

DROP PROCEDURE IF EXISTS camdecmps.refresh_emission_view_noxappemixedfuel(character varying, numeric);

CREATE OR REPLACE PROCEDURE camdecmps.refresh_emission_view_noxappemixedfuel(
	vmonplanid character varying,
	vrptperiodid numeric
)
LANGUAGE 'plpgsql'
AS $BODY$
BEGIN
	CALL camdecmps.load_temp_hourly_test_errors(vMonPlanId, vRptPeriodId);

	DELETE FROM camdecmps.EMISSION_VIEW_NOXAPPEMIXEDFUEL 
	WHERE MON_PLAN_ID = vmonplanid AND RPT_PERIOD_ID = vrptperiodid;

	INSERT INTO camdecmps.EMISSION_VIEW_NOXAPPEMIXEDFUEL(
		MON_PLAN_ID,
		MON_LOC_ID,
		RPT_PERIOD_ID,
		DATE_HOUR,
		OP_TIME,
		SYSTEM_ID,
		UNIT_LOAD,
		LOAD_UOM,
		CALC_HI_RATE,
		OPERATING_CONDITION_CD,
		SEGMENT_NUMBER,
		RPT_NOX_EMISSION_RATE,
		CALC_NOX_EMISSION_RATE,
		NOX_MASS_RATE_FORMULA_CD,
		RPT_NOX_MASS_RATE,
		CALC_NOX_MASS_RATE,
		ERROR_CODES
	)
	SELECT DISTINCT
		HOD.MON_PLAN_ID, 
		HOD.MON_LOC_ID, 
		HOD.RPT_PERIOD_ID,
		camdecmps.format_date_hour(hod.BEGIN_DATE, hod.BEGIN_HOUR, null),
		HOD.OP_TIME,
		MS_NOXR.SYSTEM_IDENTIFIER AS SYSTEM_ID,
		HOD.HR_LOAD AS UNIT_LOAD, 
		HOD.LOAD_UOM_CD AS LOAD_UOM, 
		DHV_HI.ADJUSTED_HRLY_VALUE AS CALC_HI_RATE,
		DHV_NOXR.OPERATING_CONDITION_CD,
		DHV_NOXR.SEGMENT_NUM AS SEGMENT_NUMBER,
		DHV_NOXR.ADJUSTED_HRLY_VALUE AS RPT_NOX_EMISSION_RATE,
		DHV_NOXR.CALC_ADJUSTED_HRLY_VALUE AS CALC_NOX_EMISSION_RATE,
		MF_NOX.EQUATION_CD AS NOX_MASS_RATE_FORMULA_CD,
		DHV_NOX.ADJUSTED_HRLY_VALUE AS RPT_NOX_MASS_RATE,
		DHV_NOX.CALC_ADJUSTED_HRLY_VALUE AS CALC_NOX_MASS_RATE,
		HOD.ERROR_CODES
	FROM temp_hourly_test_errors AS HOD 
	INNER JOIN camdecmps.DERIVED_HRLY_VALUE DHV_NOXR 
		ON DHV_NOXR.HOUR_ID = HOD.HOUR_ID AND DHV_NOXR.PARAMETER_CD = 'NOXR' 
		AND DHV_NOXR.OPERATING_CONDITION_CD IS NOT NULL
	INNER JOIN camdecmps.MONITOR_SYSTEM MS_NOXR  
		ON DHV_NOXR.MON_SYS_ID = MS_NOXR.MON_SYS_ID AND MS_NOXR.SYS_TYPE_CD='NOXE'
	LEFT OUTER JOIN camdecmps.DERIVED_HRLY_VALUE DHV_HI   
		ON ((DHV_HI.HOUR_ID = HOD.HOUR_ID) AND (DHV_HI.PARAMETER_CD = 'HI'))
	LEFT OUTER JOIN camdecmps.DERIVED_HRLY_VALUE DHV_NOX  
		ON ((DHV_NOX.HOUR_ID = HOD.HOUR_ID) AND (DHV_NOX.PARAMETER_CD = 'NOX'))
	LEFT OUTER JOIN camdecmps.MONITOR_FORMULA MF_NOX   
		ON DHV_NOX.MON_FORM_ID = MF_NOX.MON_FORM_ID;

  CALL camdecmps.refresh_emission_view_count(vmonplanid, vrptperiodid, 'NOXAPPEMIXEDFUEL');
END
$BODY$;
