DROP PROCEDURE IF EXISTS camdecmps.refresh_emission_view_matshg(character varying, numeric);

CREATE OR REPLACE PROCEDURE camdecmps.refresh_emission_view_matshg(
	vmonplanid character varying,
	vrptperiodid numeric
)
LANGUAGE 'plpgsql'
AS $BODY$
BEGIN
  RAISE NOTICE 'Loading temp_hourly_test_errors...';
	CALL camdecmps.load_temp_hourly_test_errors(vMonPlanId, vRptPeriodId);

  RAISE NOTICE 'Deleting existing records...';
	DELETE FROM camdecmps.EMISSION_VIEW_MATSHG
	WHERE MON_PLAN_ID = vMonPlanId AND RPT_PERIOD_ID = vRptPeriodId;

  RAISE NOTICE 'Refreshing view data...';
	INSERT INTO camdecmps.EMISSION_VIEW_MATSHG(
		MON_PLAN_ID,
		MON_LOC_ID,
		RPT_PERIOD_ID,
		DATE_HOUR,
		OP_TIME,
		MATS_LOAD,
		MATS_STARTUP_SHUTDOWN,
		HG_CONC_VALUE,
		HG_CONC_SYSTEM_ID,
		HG_CONC_SYS_TYPE,
		HG_CONC_MODC_CD,
		HG_CONC_PMA,
		SAMPLING_TRAIN_COMP_ID1,
		GAS_FLOWMETER_READING1,
		RATIO_STACK_GAS_FLOW_RATE1,
		SAMPLING_TRAIN_COMP_ID2,
		GAS_FLOWMETER_READING2,
		RATIO_STACK_GAS_FLOW_RATE2,
		FLOW_RATE,
		FLOW_MODC,
		FLOW_PMA,
		RPT_PCT_DILUENT,
		DILUENT_PARAMETER,
		CALC_PCT_DILUENT,
		DILUENT_MODC,
		CALC_PCT_H2O,
		H2O_SOURCE,
		F_FACTOR,
		HG_FORMULA_CD,
		RPT_HG_RATE,
		CALC_HG_RATE,
		HG_UOM,
		HG_MODC_CD,
		ERROR_CODES
	)
	SELECT
		hod.MON_PLAN_ID, 
		hod.MON_LOC_ID, 
		hod.RPT_PERIOD_ID,
		camdecmps.format_date_hour(hod.BEGIN_DATE, hod.BEGIN_HOUR, null) AS DATE_HOUR,
		hod.OP_TIME,
		hod.MATS_LOAD,
		hod.MATS_STARTUP_SHUTDOWN,
		mhv.UNADJUSTED_HRLY_VALUE AS HG_CONC_VALUE, 
		ms.SYSTEM_IDENTIFIER AS HG_CONC_SYSTEM_ID, 
		stc.SYS_TYPE_DESCRIPTION AS HG_CONC_SYS_TYPE,
		mhv.MODC_CD AS HG_CONC_MODC_CD,
		mhv.PCT_AVAILABLE AS HG_CONC_PMA,
		cmp1.COMPONENT_IDENTIFIER AS SAMPLING_TRAIN_COMP_ID1,
		gfm1.GFM_READING AS GAS_FLOWMETER_READING1,
		gfm1.FLOW_TO_SAMPLING_RATIO AS RATIO_STACK_GAS_FLOW_RATE1,
		cmp2.COMPONENT_IDENTIFIER AS SAMPLING_TRAIN_COMP_ID2,
		gfm2.GFM_READING AS GAS_FLOWMETER_READING2,
		gfm2.FLOW_TO_SAMPLING_RATIO AS RATIO_STACK_GAS_FLOW_RATE2,
		mhv_FLOW.UNADJUSTED_HRLY_VALUE AS FLOW_RATE,
		mhv_FLOW.MODC_CD AS FLOW_MODC,
		mhv_FLOW.PCT_AVAILABLE AS FLOW_PMA,
		CASE
			WHEN (dhv.PARAMETER_CD IN ('HCLRE', 'HFRE', 'HGRE' )) THEN NULL
			WHEN (dhv.PARAMETER_CD IN ('HCLRH', 'HFRH', 'HGRH' )) THEN 
				CASE 
					WHEN mf.EQUATION_CD IN ('19-6', '19-7', '19-8', '19-9') THEN mhv_CO2C.UNADJUSTED_HRLY_VALUE
				  WHEN mf.EQUATION_CD IN ('19-1', '19-4') THEN mhv_DRY.UNADJUSTED_HRLY_VALUE
					WHEN mf.EQUATION_CD IN ('19-2', '19-3', '19-3D', '19-5', '19-5D') THEN mhv_WET.UNADJUSTED_HRLY_VALUE
					ELSE NULL
				END
			ELSE NULL
		END AS RPT_PCT_DILUENT,
		CASE
			WHEN (dhv.PARAMETER_CD IN ('HCLRE', 'HFRE', 'HGRE' )) THEN NULL
			WHEN (dhv.PARAMETER_CD IN ('HCLRH', 'HFRH', 'HGRH' )) THEN 
				CASE
					WHEN mf.EQUATION_CD IN ('19-6', '19-7', '19-8', '19-9') THEN 'CO2'
					WHEN mf.EQUATION_CD IN ('19-1', '19-2', '19-3', '19-3D', '19-4', '19-5', '19-5D') THEN 'O2'
					ELSE NULL
				END
			ELSE NULL
		END AS DILUENT_PARAMETER,
		dhv.CALC_PCT_DILUENT AS CALC_PCT_DILUENT,
		CASE
			WHEN (dhv.PARAMETER_CD IN ('HCLRE', 'HFRE', 'HGRE' )) THEN NULL
			WHEN (dhv.PARAMETER_CD IN ('HCLRH', 'HFRH', 'HGRH' )) THEN 
				CASE
					WHEN mf.EQUATION_CD IN ('19-6', '19-7', '19-8', '19-9') THEN mhv_CO2C.MODC_CD 
					WHEN mf.EQUATION_CD IN ('19-1', '19-4') THEN mhv_DRY.MODC_CD
					WHEN mf.EQUATION_CD IN ('19-2', '19-3', '19-3D', '19-5', '19-5D') THEN mhv_WET.MODC_CD
					ELSE NULL
				END
			ELSE NULL
		END AS DILUENT_MODC,
		dhv.CALC_PCT_MOISTURE AS CALC_PCT_H2O,
		CASE 
			WHEN dhv.CALC_PCT_MOISTURE IS NULL THEN NULL 
			WHEN dhv_H2O.MODC_CD IS NOT NULL THEN dhv_H2O.MODC_CD
			WHEN mhv_H2O.MODC_CD IS NOT NULL THEN mhv_H2O.MODC_CD
			ELSE 'DF'
		END AS H2O_SOURCE,
		CASE
			WHEN (dhv.PARAMETER_CD IN ('HCLRE', 'HFRE', 'HGRE' )) THEN NULL
			WHEN (dhv.PARAMETER_CD IN ('HCLRH', 'HFRH', 'HGRH' )) THEN 
				CASE
					WHEN mf.EQUATION_CD IN ('19-6', '19-7', '19-8', '19-9') THEN hod.FC_FACTOR
					WHEN mf.EQUATION_CD IN ('19-1', '19-3', '19-3D', '19-4', '19-5', '19-5D') THEN hod.FD_FACTOR
					WHEN mf.EQUATION_CD IN ('19-2') THEN hod.FW_FACTOR
					ELSE NULL
				END
			ELSE NULL
		END AS F_FACTOR,
		mf.EQUATION_CD AS HG_FORMULA_CD,
		dhv.UNADJUSTED_HRLY_VALUE AS RPT_HG_RATE,
		dhv.CALC_UNADJUSTED_HRLY_VALUE AS CALC_HG_RATE,
		CASE
			WHEN dhv.PARAMETER_CD = 'HGRE' THEN 'lb/GWh'
			WHEN dhv.PARAMETER_CD = 'HGRH' THEN 'lb/TBtu'
			WHEN dhv.PARAMETER_CD IN ('HCLRE', 'HFRE', 'SO2RE') THEN 'lb/MWh'
			WHEN dhv.PARAMETER_CD IN ('HCLRH', 'HFRH', 'SO2RH') THEN 'lb/mmBtu'
		END AS HG_UOM,
		dhv.MODC_CD AS HG_MODC_CD,
		hod.ERROR_CODES
	FROM temp_hourly_test_errors AS hod
	JOIN camdecmps.MATS_MONITOR_HRLY_VALUE AS mhv 
		ON mhv.HOUR_ID = hod.HOUR_ID
		AND mhv.MON_LOC_ID = hod.MON_LOC_ID
		AND mhv.RPT_PERIOD_ID = hod.RPT_PERIOD_ID
		AND mhv.PARAMETER_CD = 'HGC'
	JOIN camdecmps.MATS_DERIVED_HRLY_VALUE AS dhv
		ON dhv.HOUR_ID = hod.HOUR_ID
		AND dhv.MON_LOC_ID = hod.MON_LOC_ID
		AND dhv.RPT_PERIOD_ID = hod.RPT_PERIOD_ID
		AND dhv.PARAMETER_CD IN ( 'HGRE', 'HGRH' )
	LEFT JOIN (
		SELECT
			HOUR_ID, MON_LOC_ID, RPT_PERIOD_ID, MODC_CD,
			MON_FORM_ID, ADJUSTED_HRLY_VALUE, CALC_ADJUSTED_HRLY_VALUE
		FROM camdecmps.DERIVED_HRLY_VALUE
		WHERE RPT_PERIOD_ID = vrptperiodid AND PARAMETER_CD = 'H2O'
	) AS dhv_H2O
		ON dhv_H2O.HOUR_ID = dhv.HOUR_ID
		AND dhv_H2O.MON_LOC_ID = dhv.MON_LOC_ID
		AND dhv_H2O.RPT_PERIOD_ID = dhv.RPT_PERIOD_ID
	LEFT JOIN camdecmps.MONITOR_FORMULA AS mf
		ON mf.MON_FORM_ID = dhv.MON_FORM_ID
	LEFT JOIN (
		SELECT
			HOUR_ID, MON_LOC_ID, RPT_PERIOD_ID, MODC_CD,
			ADJUSTED_HRLY_VALUE, UNADJUSTED_HRLY_VALUE, CALC_ADJUSTED_HRLY_VALUE
		FROM camdecmps.MONITOR_HRLY_VALUE
		WHERE RPT_PERIOD_ID = vrptperiodid AND PARAMETER_CD = 'CO2C'
	) AS mhv_CO2C
		ON mhv_CO2C.HOUR_ID = dhv.HOUR_ID
		AND mhv_CO2C.MON_LOC_ID = dhv.MON_LOC_ID
		AND mhv_CO2C.RPT_PERIOD_ID = dhv.RPT_PERIOD_ID
	LEFT JOIN (
		SELECT
			HOUR_ID, MON_LOC_ID, RPT_PERIOD_ID, MODC_CD, PCT_AVAILABLE,
			ADJUSTED_HRLY_VALUE, UNADJUSTED_HRLY_VALUE, CALC_ADJUSTED_HRLY_VALUE
		FROM camdecmps.MONITOR_HRLY_VALUE
		WHERE RPT_PERIOD_ID = vrptperiodid AND PARAMETER_CD = 'FLOW'
	) AS mhv_FLOW
		ON mhv_FLOW.HOUR_ID = dhv.HOUR_ID
		AND mhv_FLOW.MON_LOC_ID = dhv.MON_LOC_ID
		AND mhv_FLOW.RPT_PERIOD_ID = dhv.RPT_PERIOD_ID
	LEFT JOIN (
		SELECT
			HOUR_ID, MON_LOC_ID, RPT_PERIOD_ID, MODC_CD,
			ADJUSTED_HRLY_VALUE, UNADJUSTED_HRLY_VALUE, CALC_ADJUSTED_HRLY_VALUE
		FROM camdecmps.MONITOR_HRLY_VALUE
		WHERE RPT_PERIOD_ID = vrptperiodid AND PARAMETER_CD = 'H2O'
	) AS mhv_H2O
		ON mhv_H2O.HOUR_ID = dhv.HOUR_ID
		AND mhv_H2O.MON_LOC_ID = dhv.MON_LOC_ID
		AND mhv_H2O.RPT_PERIOD_ID = dhv.RPT_PERIOD_ID
	LEFT JOIN (
		SELECT
			HOUR_ID, MON_LOC_ID, RPT_PERIOD_ID, MODC_CD,
			ADJUSTED_HRLY_VALUE, UNADJUSTED_HRLY_VALUE, CALC_ADJUSTED_HRLY_VALUE
		FROM camdecmps.MONITOR_HRLY_VALUE
		WHERE RPT_PERIOD_ID = vrptperiodid AND PARAMETER_CD = 'O2' AND MOISTURE_BASIS = 'D'
	) AS mhv_DRY 
		ON mhv_DRY.HOUR_ID = dhv.HOUR_ID
		AND mhv_DRY.MON_LOC_ID = dhv.MON_LOC_ID
		AND mhv_DRY.RPT_PERIOD_ID = dhv.RPT_PERIOD_ID
	LEFT JOIN (
		SELECT
			HOUR_ID, MON_LOC_ID, RPT_PERIOD_ID, MODC_CD,
			ADJUSTED_HRLY_VALUE, UNADJUSTED_HRLY_VALUE, CALC_ADJUSTED_HRLY_VALUE
		FROM camdecmps.MONITOR_HRLY_VALUE
		WHERE RPT_PERIOD_ID = vrptperiodid AND PARAMETER_CD = 'O2' AND MOISTURE_BASIS = 'W'
	) AS mhv_WET 
		ON mhv_WET.HOUR_ID = dhv.HOUR_ID
		AND mhv_WET.MON_LOC_ID = dhv.MON_LOC_ID
		AND mhv_WET.RPT_PERIOD_ID = dhv.RPT_PERIOD_ID
	LEFT JOIN camdecmps.MONITOR_SYSTEM AS ms 
		ON ms.MON_SYS_ID = mhv.MON_SYS_ID
	LEFT JOIN camdecmpsmd.SYSTEM_TYPE_CODE AS stc 
		ON stc.SYS_TYPE_CD = ms.SYS_TYPE_CD
	LEFT JOIN camdecmps.HRLY_GAS_FLOW_METER gfm1 
		ON gfm1.HOUR_ID = hod.HOUR_ID 
		AND gfm1.MON_LOC_ID = hod.MON_LOC_ID
		AND gfm1.RPT_PERIOD_ID = hod.RPT_PERIOD_ID
		AND gfm1.COMPONENT_ID = camdecmps.mats_sampling_train_component( mhv.MON_SYS_ID, hod.BEGIN_DATE, hod.BEGIN_HOUR, 1 )
	LEFT JOIN camdecmps.HRLY_GAS_FLOW_METER gfm2 
		ON gfm2.HOUR_ID = hod.HOUR_ID 
		AND gfm2.MON_LOC_ID = hod.MON_LOC_ID
		AND gfm2.RPT_PERIOD_ID = hod.RPT_PERIOD_ID
		AND gfm2.COMPONENT_ID = camdecmps.mats_sampling_train_component( mhv.MON_SYS_ID, hod.BEGIN_DATE, hod.BEGIN_HOUR, 2 )
	LEFT JOIN camdecmps.COMPONENT cmp1 
		ON cmp1.COMPONENT_ID = gfm1.COMPONENT_ID
	LEFT JOIN camdecmps.COMPONENT cmp2 
		ON cmp2.COMPONENT_ID = gfm2.COMPONENT_ID;

  RAISE NOTICE 'Refreshing view counts...';
  CALL camdecmps.refresh_emission_view_count(vmonplanid, vrptperiodid, 'MATSHG');
END
$BODY$;

/*
----------------------------------------------------------------------------------------
FOR TESTING PURPOSES ONLY
----------------------------------------------------------------------------------------
DROP TABLE temp_hourly_test_errors;
CALL camdecmps.load_temp_hourly_test_errors('TWCORNEL5-C0E3879920A14159BAA98E03F1980A7A', 120);
CALL camdecmps.load_temp_hourly_test_errors('MDC-19939DF8A9FD4C12B3869C394A2C0B1D', 120);
CALL camdecmps.load_temp_hourly_test_errors('MDC-94FE334B615548CDB3F22AED7D333EEF', 120);

select a.mon_plan_id, *
from camdecmps.monitor_plan_location a
JOIN camdecmps.MATS_MONITOR_HRLY_VALUE AS MHV 
	ON a.MON_LOC_ID = mhv.MON_LOC_ID
	AND mhv.RPT_PERIOD_ID = 120	
	AND mhv.PARAMETER_CD = 'HGC'
JOIN camdecmps.MATS_DERIVED_HRLY_VALUE AS DHV 
	ON a.MON_LOC_ID = dhv.MON_LOC_ID
	AND dhv.RPT_PERIOD_ID = 120	
	AND dhv.PARAMETER_CD IN ( 'HGRE', 'HGRH' )
	AND mhv.HOUR_ID = dhv.HOUR_ID
order by a.mon_loc_id
*/
