-- PROCEDURE: camdecmps.refresh_emission_view_dailycal()

DROP PROCEDURE IF EXISTS camdecmps.refresh_emission_view_dailycal();

CREATE OR REPLACE PROCEDURE camdecmps.refresh_emission_view_dailycal()
LANGUAGE 'plpgsql'
AS $BODY$
BEGIN
	TRUNCATE camdecmps.EMISSION_VIEW_DAILYCAL RESTART IDENTITY;

	INSERT INTO camdecmps.EMISSION_VIEW_DAILYCAL(
		MON_PLAN_ID,
		MON_LOC_ID,
        RPT_PERIOD_ID,
        TEST_SUM_ID,
        COMPONENT_IDENTIFIER,
		COMPONENT_TYPE_CD,
        SPAN_SCALE_CD,
		END_DATETIME,
        RPT_TEST_RESULT_CD,
        CALC_TEST_RESULT_CD,
		APPLICABLE_SPAN_VALUE,
        UPSCALE_GAS_LEVEL_CD,
        UPSCALE_INJECTION_DATE,
        UPSCALE_INJECTION_TIME,
        UPSCALE_MEASURED_VALUE,
        UPSCALE_REF_VALUE,
        RPT_UPSCALE_CE_OR_MEAN_DIFF,
        RPT_UPSCALE_APS_IND,
        CALC_UPSCALE_CE_OR_MEAN_DIFF,
        CALC_UPSCALE_APS_IND,
        ZERO_INJECTION_DATE,
        ZERO_INJECTION_TIME,
        ZERO_MEASURED_VALUE,
        ZERO_REF_VALUE,
        RPT_ZERO_CE_OR_MEAN_DIFF,
        RPT_ZERO_APS_IND,
        CALC_ZERO_CE_OR_MEAN_DIFF,
        CALC_ZERO_APS_IND,
        RPT_ONLINE_OFFLINE_IND,
        CALC_ONLINE_OFFLINE_IND,
        UPSCALE_GAS_TYPE_CD,
        VENDOR_ID,
        CYLINDER_ID,
        EXPIRATION_DATE,
        ERROR_CODES
	)
	SELECT DISTINCT
		DTS.MON_PLAN_ID, 
		DTS.MON_LOC_ID, 
		DTS.RPT_PERIOD_ID,
		DTS.DAILY_TEST_SUM_ID,
		DTS.COMPONENT_IDENTIFIER,
		DTS.COMPONENT_TYPE_CD,
		DTS.SPAN_SCALE_CD,
		camdecmps.format_date_hour(DTS.END_DATE, null, null) || ' ' || DTS.END_TIME AS END_DATETIME,
		DTS.TEST_RESULT_CD AS RPT_TEST_RESULT_CD,
		DTS.CALC_TEST_RESULT_CD AS CALC_TEST_RESULT_CD,
		MS.SPAN_VALUE AS APPLICABLE_SPAN_VALUE,
		DC.UPSCALE_GAS_LEVEL_CD,
		DC.UPSCALE_INJECTION_DATE,
		camdecmps.format_time( DC.UPSCALE_INJECTION_HOUR, DC.UPSCALE_INJECTION_MIN ) as UPSCALE_INJECTION_TIME,
		DC.UPSCALE_MEASURED_VALUE,
		DC.UPSCALE_REF_VALUE,
		DC.UPSCALE_CAL_ERROR AS RPT_UPSCALE_CE_OR_MEAN_DIFF,
		DC.UPSCALE_APS_IND AS RPT_UPSCALE_APS_IND,
		DC.CALC_UPSCALE_CAL_ERROR AS CALC_UPSCALE_CE_OR_MEAN_DIFF,
		DC.CALC_UPSCALE_APS_IND,
		DC.ZERO_INJECTION_DATE,
		camdecmps.format_time( DC.ZERO_INJECTION_HOUR, DC.ZERO_INJECTION_MIN ) as ZERO_INJECTION_TIME,
		DC.ZERO_MEASURED_VALUE,
		DC.ZERO_REF_VALUE,
		DC.ZERO_CAL_ERROR AS RPT_ZERO_CE_OR_MEAN_DIFF,
		DC.ZERO_APS_IND AS RPT_ZERO_APS_IND,
		DC.CALC_ZERO_CAL_ERROR AS CALC_ZERO_CE_OR_MEAN_DIFF,
		DC.CALC_ZERO_APS_IND,
		DC.ONLINE_OFFLINE_IND AS RPT_ONLINE_OFFLINE_IND,
		DC.CALC_ONLINE_OFFLINE_IND,
		DC.UPSCALE_GAS_TYPE_CD,
		DC.VENDOR_ID,
		DC.CYLINDER_IDENTIFIER,
		DC.EXPIRATION_DATE,
		DTS.ERROR_CODES
	FROM camdecmps.vw_daily_errors AS DTS
	INNER JOIN camdecmps.DAILY_CALIBRATION AS DC
		ON DTS.DAILY_TEST_SUM_ID = DC.DAILY_TEST_SUM_ID
	LEFT OUTER JOIN camdecmps.MONITOR_SPAN AS MS
		ON DTS.MON_LOC_ID = MS.MON_LOC_ID AND DTS.COMPONENT_TYPE_CD = MS.COMPONENT_TYPE_CD AND
		Coalesce(DTS.SPAN_SCALE_CD,'') = Coalesce(MS.SPAN_SCALE_CD,'') AND
		camdecmps.EMISSIONS_MONITOR_SPAN_ACTIVE(MS.BEGIN_DATE, MS.BEGIN_HOUR, MS.END_DATE, MS.END_HOUR, DTS.END_DATE, CAST(LEFT(DTS.END_TIME, 2) AS numeric)) = 1
	WHERE DTS.TEST_TYPE_CD = 'DAYCAL';
END
$BODY$;
