-- PROCEDURE: camdecmps.refresh_emission_view_hicems(character varying, numeric)

DROP PROCEDURE IF EXISTS camdecmps.refresh_emission_view_hicems(character varying, numeric);

CREATE OR REPLACE PROCEDURE camdecmps.refresh_emission_view_hicems(
	vmonplanid character varying,
	vrptperiodid numeric
)
LANGUAGE 'plpgsql'
AS $BODY$
BEGIN
	CALL camdecmps.load_temp_hourly_test_errors(vMonPlanId, vRptPeriodId);

	DELETE FROM camdecmps.EMISSION_VIEW_HICEMS 
	WHERE MON_PLAN_ID = vmonplanid AND RPT_PERIOD_ID = vrptperiodid;

	INSERT INTO camdecmps.EMISSION_VIEW_HICEMS(
		MON_PLAN_ID,
		MON_LOC_ID,
		RPT_PERIOD_ID,
		HOUR_ID,
		DATE_HOUR,
		OP_TIME,
		UNIT_LOAD,
		LOAD_UOM,
		LOAD_RANGE,
		COMMON_STACK_LOAD_RANGE,
		HI_FORMULA_CD,
		HI_MODC,
		RPT_HI_RATE,
		CALC_HI_RATE,
		DILUENT_PARAM,
		RPT_PCT_DILUENT,
		PCT_DILUENT_USED,
		DILUENT_MODC,
		DILUENT_PMA,
		UNADJ_FLOW,
		CALC_FLOW_BAF,
		RPT_ADJ_FLOW,
		ADJ_FLOW_USED,
		FLOW_MODC,
		FLOW_PMA,
		PCT_H2O_USED,
		SOURCE_H2O_VALUE,
		F_FACTOR,
		ERROR_CODES,
		FUEL_CD
	)
	SELECT
		HOD.MON_PLAN_ID, 
		HOD.MON_LOC_ID, 
		HOD.RPT_PERIOD_ID,
		HOD.HOUR_ID,
		camdecmps.format_date_hour(hod.BEGIN_DATE, hod.BEGIN_HOUR, null) AS DATE_HOUR,
		HOD.OP_TIME, 
		HOD.HR_LOAD AS UNIT_LOAD, 
		HOD.LOAD_UOM_CD AS LOAD_UOM, 
		HOD.LOAD_RANGE, 
		HOD.COMMON_STACK_LOAD_RANGE, 
		MF.EQUATION_CD AS HI_FORMULA_CD, 
		DHV.MODC_CD AS HI_MODC,
		DHV.ADJUSTED_HRLY_VALUE AS RPT_HI_RATE, 
		DHV.CALC_ADJUSTED_HRLY_VALUE AS CALC_HI_RATE, 
		CASE MF.EQUATION_CD 
			WHEN 'F-15' THEN 'CO2' 
			WHEN 'F-16' THEN 'CO2' 
			WHEN 'F-17' THEN 'O2' 
			WHEN 'F-18' THEN 'O2' 
			ELSE NULL 
		END AS DILUENT_PARAM, 
		CASE MF.EQUATION_CD 
			WHEN 'F-15' THEN 
				CASE
					WHEN MHV_CO2C_2.MONITOR_HRLY_VAL_ID IS NOT NULL THEN MHV_CO2C_2.UNADJUSTED_HRLY_VALUE
					ELSE MHV_CO2C.UNADJUSTED_HRLY_VALUE 
				END
			WHEN 'F-16' THEN 
				CASE
					WHEN MHV_CO2C_2.MONITOR_HRLY_VAL_ID IS NOT NULL THEN MHV_CO2C_2.UNADJUSTED_HRLY_VALUE
					ELSE MHV_CO2C.UNADJUSTED_HRLY_VALUE
				END
			WHEN 'F-17' THEN 
				CASE
					WHEN MHV_O2C_WET_2.MONITOR_HRLY_VAL_ID IS NOT NULL THEN MHV_O2C_WET_2.UNADJUSTED_HRLY_VALUE
					ELSE MHV_O2C_WET.UNADJUSTED_HRLY_VALUE
				END
			WHEN 'F-18' THEN 
				CASE 
					WHEN MHV_O2C_DRY_2.MONITOR_HRLY_VAL_ID IS NOT NULL THEN MHV_O2C_DRY_2.UNADJUSTED_HRLY_VALUE
					ELSE MHV_O2C_DRY.UNADJUSTED_HRLY_VALUE
				END
			ELSE NULL 
		END AS RPT_PCT_DILUENT, 
		DHV.CALC_PCT_DILUENT AS PCT_DILUENT_USED,
		CASE MF.EQUATION_CD 
			WHEN 'F-15' THEN 
				CASE
					WHEN MHV_CO2C_2.MONITOR_HRLY_VAL_ID IS NOT NULL THEN MHV_CO2C_2.MODC_CD
					ELSE MHV_CO2C.MODC_CD 
				END
			WHEN 'F-16' THEN 
				CASE
					WHEN MHV_CO2C_2.MONITOR_HRLY_VAL_ID IS NOT NULL THEN MHV_CO2C_2.MODC_CD
					ELSE MHV_CO2C.MODC_CD
				END
			WHEN 'F-17' THEN 
				CASE
					WHEN MHV_O2C_WET_2.MONITOR_HRLY_VAL_ID IS NOT NULL THEN MHV_O2C_WET_2.MODC_CD
					ELSE MHV_O2C_WET.MODC_CD
				END
			WHEN 'F-18' THEN 
				CASE 
					WHEN MHV_O2C_DRY_2.MONITOR_HRLY_VAL_ID IS NOT NULL THEN MHV_O2C_DRY_2.MODC_CD
					ELSE MHV_O2C_DRY.MODC_CD
				END
			ELSE NULL  
		END AS DILUENT_MODC, 
		CASE MF.EQUATION_CD 
			WHEN 'F-15' THEN 
				CASE
					WHEN MHV_CO2C_2.MONITOR_HRLY_VAL_ID IS NOT NULL THEN MHV_CO2C_2.PCT_AVAILABLE
					ELSE MHV_CO2C.PCT_AVAILABLE 
				END
			WHEN 'F-16' THEN 
				CASE
					WHEN MHV_CO2C_2.MONITOR_HRLY_VAL_ID IS NOT NULL THEN MHV_CO2C_2.PCT_AVAILABLE
					ELSE MHV_CO2C.PCT_AVAILABLE
				END
			WHEN 'F-17' THEN 
				CASE
					WHEN MHV_O2C_WET_2.MONITOR_HRLY_VAL_ID IS NOT NULL THEN MHV_O2C_WET_2.PCT_AVAILABLE
					ELSE MHV_O2C_WET.PCT_AVAILABLE
				END
			WHEN 'F-18' THEN 
				CASE 
					WHEN MHV_O2C_DRY_2.MONITOR_HRLY_VAL_ID IS NOT NULL THEN MHV_O2C_DRY_2.PCT_AVAILABLE
					ELSE MHV_O2C_DRY.PCT_AVAILABLE
				END
			ELSE NULL 
		END AS DILUENT_PMA,
		MHV.UNADJUSTED_HRLY_VALUE AS UNADJ_FLOW, 
		MHV.APPLICABLE_BIAS_ADJ_FACTOR AS CALC_FLOW_BAF, 
		MHV.ADJUSTED_HRLY_VALUE AS RPT_ADJ_FLOW, 
		MHV.CALC_ADJUSTED_HRLY_VALUE AS ADJ_FLOW_USED, 
		MHV.MODC_CD AS FLOW_MODC, 
		MHV.PCT_AVAILABLE AS FLOW_PMA,
		DHV.CALC_PCT_MOISTURE AS PCT_H2O_USED, 
		CASE 
			WHEN (DHV.CALC_PCT_MOISTURE IS NOT NULL) THEN 
				CASE 
					WHEN (H2O_DHV.MODC_CD IS NOT NULL) THEN H2O_DHV.MODC_CD 
					WHEN (H2O_MHV.MODC_CD IS NOT NULL) THEN H2O_MHV.MODC_CD 
					ELSE 'DF'
				END 
			ELSE NULL
		END AS SOURCE_H2O_VALUE, 
		CASE MF.EQUATION_CD 
			WHEN 'F-15' THEN HOD.FC_FACTOR 
			WHEN 'F-16' THEN HOD.FC_FACTOR 
			WHEN 'F-17' THEN HOD.FD_FACTOR 
			WHEN 'F-18' THEN HOD.FD_FACTOR 
		END AS F_FACTOR, 
		HOD.ERROR_CODES,
		hod.FUEL_CD
	FROM temp_hourly_test_errors AS HOD 
	JOIN camdecmps.DERIVED_HRLY_VALUE AS DHV 
		ON HOD.HOUR_ID = DHV.HOUR_ID
		AND HOD.MON_LOC_ID = DHV.MON_LOC_ID
		AND HOD.RPT_PERIOD_ID = DHV.RPT_PERIOD_ID
	JOIN camdecmps.MONITOR_HRLY_VALUE AS MHV 
		ON HOD.HOUR_ID = MHV.HOUR_ID
		AND HOD.MON_LOC_ID = MHV.MON_LOC_ID
		AND HOD.RPT_PERIOD_ID = MHV.RPT_PERIOD_ID
	LEFT JOIN camdecmps.MONITOR_FORMULA AS MF 
		ON DHV.MON_FORM_ID = MF.MON_FORM_ID 
	LEFT JOIN camdecmps.MONITOR_HRLY_VALUE AS H2O_MHV
		ON HOD.HOUR_ID = H2O_MHV.HOUR_ID
		AND HOD.MON_LOC_ID = H2O_MHV.MON_LOC_ID
		AND HOD.RPT_PERIOD_ID = H2O_MHV.RPT_PERIOD_ID
		AND H2O_MHV.PARAMETER_CD = 'H2O'
	LEFT JOIN camdecmps.DERIVED_HRLY_VALUE AS H2O_DHV
		ON HOD.HOUR_ID = H2O_DHV.HOUR_ID
		AND HOD.MON_LOC_ID = H2O_DHV.MON_LOC_ID
		AND HOD.RPT_PERIOD_ID = H2O_DHV.RPT_PERIOD_ID
		AND H2O_DHV.PARAMETER_CD = 'H2O' 
	LEFT JOIN camdecmps.MONITOR_DEFAULT AS H2O_MD 
		ON HOD.MON_LOC_ID = H2O_MD.MON_LOC_ID
		AND H2O_MD.DEFAULT_PURPOSE_CD = 'PM'
		AND H2O_MD.PARAMETER_CD = 'H2O'
		AND camdecmps.emissions_monitor_default_active(H2O_MD.BEGIN_DATE, H2O_MD.BEGIN_HOUR, H2O_MD.END_DATE, H2O_MD.END_HOUR, HOD.BEGIN_DATE, HOD.BEGIN_HOUR) = 1
	LEFT JOIN camdecmps.MONITOR_HRLY_VALUE AS MHV_CO2C
		ON HOD.HOUR_ID = MHV_CO2C.HOUR_ID
		AND HOD.MON_LOC_ID = MHV_CO2C.MON_LOC_ID
		AND HOD.RPT_PERIOD_ID = MHV_CO2C.RPT_PERIOD_ID
		AND MHV_CO2C.PARAMETER_CD = 'CO2C'
	LEFT JOIN camdecmps.MONITOR_HRLY_VALUE AS MHV_CO2C_2
		ON HOD.HOUR_ID = MHV_CO2C_2.HOUR_ID
		AND HOD.MON_LOC_ID = MHV_CO2C_2.MON_LOC_ID
		AND HOD.RPT_PERIOD_ID = MHV_CO2C_2.RPT_PERIOD_ID
		AND MHV_CO2C_2.PARAMETER_CD = 'CO2C'
		AND MHV_CO2C_2.MODC_CD IN ('06', '07', '08', '09', '10', '11', '12', '55')
	LEFT JOIN camdecmps.MONITOR_HRLY_VALUE AS MHV_O2C_DRY 
		ON HOD.HOUR_ID = MHV_O2C_DRY.HOUR_ID
		AND HOD.MON_LOC_ID = MHV_O2C_DRY.MON_LOC_ID
		AND HOD.RPT_PERIOD_ID = MHV_O2C_DRY.RPT_PERIOD_ID
		AND MHV_O2C_DRY.PARAMETER_CD = 'O2C'
		AND (
			MHV_O2C_DRY.MOISTURE_BASIS IS NULL OR MHV_O2C_DRY.MOISTURE_BASIS = 'D'
		) 
	LEFT JOIN camdecmps.MONITOR_HRLY_VALUE AS MHV_O2C_DRY_2 
		ON HOD.HOUR_ID = MHV_O2C_DRY_2.HOUR_ID
		AND HOD.MON_LOC_ID = MHV_O2C_DRY_2.MON_LOC_ID
		AND HOD.RPT_PERIOD_ID = MHV_O2C_DRY_2.RPT_PERIOD_ID
		AND MHV_O2C_DRY_2.PARAMETER_CD = 'O2C'
		AND (
			MHV_O2C_DRY_2.MOISTURE_BASIS IS NULL OR MHV_O2C_DRY_2.MOISTURE_BASIS = 'D'
		) AND MHV_O2C_DRY_2.MODC_CD IN ('06', '07', '08', '09', '10', '11', '12', '55')
	LEFT JOIN camdecmps.MONITOR_HRLY_VALUE AS MHV_O2C_WET 
		ON HOD.HOUR_ID = MHV_O2C_WET.HOUR_ID
		AND HOD.MON_LOC_ID = MHV_O2C_WET.MON_LOC_ID
		AND HOD.RPT_PERIOD_ID = MHV_O2C_WET.RPT_PERIOD_ID
		AND MHV_O2C_WET.PARAMETER_CD = 'O2C'
		AND (
			MHV_O2C_WET.MOISTURE_BASIS IS NULL OR MHV_O2C_WET.MOISTURE_BASIS = 'W'
		) 
	LEFT JOIN camdecmps.MONITOR_HRLY_VALUE AS MHV_O2C_WET_2 
		ON HOD.HOUR_ID = MHV_O2C_WET_2.HOUR_ID
		AND HOD.MON_LOC_ID = MHV_O2C_WET_2.MON_LOC_ID
		AND HOD.RPT_PERIOD_ID = MHV_O2C_WET_2.RPT_PERIOD_ID
		AND MHV_O2C_WET_2.PARAMETER_CD = 'O2C'
		AND (
			MHV_O2C_WET_2.MOISTURE_BASIS IS NULL OR MHV_O2C_WET_2.MOISTURE_BASIS = 'W'
		) AND MHV_O2C_WET_2.MODC_CD IN ('06', '07', '08', '09', '10', '11', '12', '55')
  WHERE DHV.PARAMETER_CD = 'HI' AND MHV.PARAMETER_CD = 'FLOW';

  CALL camdecmps.refresh_emission_view_count(vmonplanid, vrptperiodid, 'HICEMS');
END
$BODY$;
