-- PROCEDURE: camdecmps.refresh_emission_view_matsweekly()

DROP PROCEDURE IF EXISTS camdecmps.refresh_emission_view_matsweekly();

CREATE OR REPLACE PROCEDURE camdecmps.refresh_emission_view_matsweekly()
LANGUAGE 'plpgsql'
AS $BODY$
BEGIN
	TRUNCATE camdecmps.EMISSION_VIEW_MATSWEEKLY RESTART IDENTITY;

	INSERT INTO camdecmps.EMISSION_VIEW_MATSWEEKLY(
		MON_PLAN_ID,
		MON_LOC_ID,
		RPT_PERIOD_ID,
		WEEKLY_TEST_SUM_ID,
		SYSTEM_COMPONENT_IDENTIFIER,
		SYSTEM_COMPONENT_TYPE,
		DATE_HOUR,
		TEST_TYPE,
		TEST_RESULT,
		SPAN_SCALE,
		GAS_LEVEL,
		REF_VALUE,
		MEASURED_VALUE,
		SYSTEM_INTEGRITY_ERROR,
		ERROR_CODES
	)
	SELECT DISTINCT
		ts.MON_PLAN_ID,
		ts.MON_LOC_ID,
		ts.RPT_PERIOD_ID,
		wts.WEEKLY_TEST_SUM_ID,
		SYSTEM_COMPONENT_IDENTIFIER,
		SYSTEM_COMPONENT_TYPE,
		ts.TEST_DATE || ' ' || ts.TEST_TIME, 
		wts.TEST_TYPE_CD,
		wts.TEST_RESULT_CD,
		wts.SPAN_SCALE_CD,
		wsi.GAS_LEVEL_CD,
		wsi.REF_VALUE,
		wsi.MEASURED_VALUE,
		wsi.SYSTEM_INTEGRITY_ERROR,
		ts.ERROR_CODES
	FROM camdecmps.vw_weekly_errors AS ts
	LEFT OUTER JOIN	camdecmps.WEEKLY_TEST_SUMMARY wts 
		ON wts.WEEKLY_TEST_SUM_ID = ts.WEEKLY_TEST_SUM_ID
	LEFT OUTER JOIN camdecmps.WEEKLY_SYSTEM_INTEGRITY wsi 
		ON wts.WEEKLY_TEST_SUM_ID=wsi.WEEKLY_TEST_SUM_ID
	LEFT OUTER JOIN camdecmps.MONITOR_SPAN MS  
		ON wts.MON_LOC_ID = MS.MON_LOC_ID 
		AND ts.COMPONENT_TYPE_CD = MS.COMPONENT_TYPE_CD 
		AND Coalesce(wts.SPAN_SCALE_CD,'') = Coalesce(MS.SPAN_SCALE_CD,'')
		AND camdecmps.emissions_monitor_span_active(MS.BEGIN_DATE, MS.BEGIN_HOUR, MS.END_DATE, MS.END_HOUR, TS.TEST_DATE, LEFT(ts.TEST_TIME, 2)) = 1;
END
$BODY$;
