DROP PROCEDURE IF EXISTS camdecmps.refresh_emission_view_noxappemixedfuel(character varying, numeric);

CREATE OR REPLACE PROCEDURE camdecmps.refresh_emission_view_noxappemixedfuel(
	vmonplanid character varying,
	vrptperiodid numeric
)
LANGUAGE 'plpgsql'
AS $BODY$
BEGIN
  RAISE NOTICE 'Loading temp_hourly_test_errors...';
	CALL camdecmps.load_temp_hourly_test_errors(vMonPlanId, vRptPeriodId);

  RAISE NOTICE 'Deleting existing records...';
	DELETE FROM camdecmps.EMISSION_VIEW_NOXAPPEMIXEDFUEL
	WHERE MON_PLAN_ID = vMonPlanId AND RPT_PERIOD_ID = vRptPeriodId;

  RAISE NOTICE 'Refreshing view data...';
	INSERT INTO camdecmps.EMISSION_VIEW_NOXAPPEMIXEDFUEL(
		MON_PLAN_ID,
		MON_LOC_ID,
		RPT_PERIOD_ID,
		DATE_HOUR,
		OP_TIME,
		SYSTEM_ID,
		UNIT_LOAD,
		LOAD_UOM,
		CALC_HI_RATE,
		OPERATING_CONDITION_CD,
		SEGMENT_NUMBER,
		RPT_NOX_EMISSION_RATE,
		CALC_NOX_EMISSION_RATE,
		NOX_MASS_RATE_FORMULA_CD,
		RPT_NOX_MASS_RATE,
		CALC_NOX_MASS_RATE,
		ERROR_CODES
	)
	SELECT
		HOD.MON_PLAN_ID, 
		HOD.MON_LOC_ID, 
		HOD.RPT_PERIOD_ID,
		camdecmps.format_date_hour(hod.BEGIN_DATE, hod.BEGIN_HOUR, null),
		HOD.OP_TIME,
		MS_NOXR.SYSTEM_IDENTIFIER AS SYSTEM_ID,
		HOD.HR_LOAD AS UNIT_LOAD, 
		HOD.LOAD_UOM_CD AS LOAD_UOM, 
		DHV_HI.ADJUSTED_HRLY_VALUE AS CALC_HI_RATE,
		DHV_NOXR.OPERATING_CONDITION_CD,
		DHV_NOXR.SEGMENT_NUM AS SEGMENT_NUMBER,
		DHV_NOXR.ADJUSTED_HRLY_VALUE AS RPT_NOX_EMISSION_RATE,
		DHV_NOXR.CALC_ADJUSTED_HRLY_VALUE AS CALC_NOX_EMISSION_RATE,
		MF_NOX.EQUATION_CD AS NOX_MASS_RATE_FORMULA_CD,
		DHV_NOX.ADJUSTED_HRLY_VALUE AS RPT_NOX_MASS_RATE,
		DHV_NOX.CALC_ADJUSTED_HRLY_VALUE AS CALC_NOX_MASS_RATE,
		HOD.ERROR_CODES
	FROM temp_hourly_test_errors AS HOD 
	JOIN camdecmps.DERIVED_HRLY_VALUE DHV_NOXR 
		ON DHV_NOXR.HOUR_ID = HOD.HOUR_ID
		AND DHV_NOXR.MON_LOC_ID = HOD.MON_LOC_ID
		AND DHV_NOXR.RPT_PERIOD_ID = HOD.RPT_PERIOD_ID
    AND DHV_NOXR.PARAMETER_CD = 'NOXR' 
		AND DHV_NOXR.OPERATING_CONDITION_CD IS NOT NULL
	JOIN camdecmps.MONITOR_SYSTEM MS_NOXR  
		ON DHV_NOXR.MON_SYS_ID = MS_NOXR.MON_SYS_ID AND MS_NOXR.SYS_TYPE_CD='NOXE'
	LEFT JOIN (
		SELECT
			HOUR_ID, MON_LOC_ID, RPT_PERIOD_ID,
			MON_FORM_ID, ADJUSTED_HRLY_VALUE, CALC_ADJUSTED_HRLY_VALUE
		FROM camdecmps.DERIVED_HRLY_VALUE
		WHERE RPT_PERIOD_ID = vrptperiodid AND PARAMETER_CD = 'HI'
	) AS dhv_HI
		ON dhv_HI.HOUR_ID = hod.HOUR_ID
		AND dhv_HI.MON_LOC_ID = hod.MON_LOC_ID
		AND dhv_HI.RPT_PERIOD_ID = hod.RPT_PERIOD_ID
	LEFT JOIN (
		SELECT
			HOUR_ID, MON_LOC_ID, RPT_PERIOD_ID,
			MON_FORM_ID, ADJUSTED_HRLY_VALUE, CALC_ADJUSTED_HRLY_VALUE
		FROM camdecmps.DERIVED_HRLY_VALUE
		WHERE RPT_PERIOD_ID = vrptperiodid AND PARAMETER_CD = 'NOX'
	) AS dhv_NOX
		ON dhv_NOX.HOUR_ID = hod.HOUR_ID
		AND dhv_NOX.MON_LOC_ID = hod.MON_LOC_ID
		AND dhv_NOX.RPT_PERIOD_ID = hod.RPT_PERIOD_ID
	LEFT JOIN camdecmps.MONITOR_FORMULA MF_NOX   
		ON DHV_NOX.MON_FORM_ID = MF_NOX.MON_FORM_ID;

  RAISE NOTICE 'Refreshing view counts...';
  CALL camdecmps.refresh_emission_view_count(vmonplanid, vrptperiodid, 'NOXAPPEMIXEDFUEL');
END
$BODY$;
