CREATE TABLE CAMDNATS.TACCOUNT
(
  ACCTNUM_ID             CHAR(12)          NOT NULL,
  ACCTTYPE_CD            CHAR(2)           NOT NULL,
  ACCTNAME_NME           VARCHAR(50),
  NOBROKER_IND           CHAR(1),
  BRKRTRAN_IND           CHAR(1),
  BRKRHOLD_IND           CHAR(1),
  BRKROTHER_IND          CHAR(1),
  UTILITY_IND            CHAR(1),
  NONUTIL_IND            CHAR(1),
  COAL_IND               CHAR(1),
  OIL_IND                CHAR(1),
  GAS_IND                CHAR(1),
  FUELOTHR_IND           CHAR(1),
  POLLUTN_IND            CHAR(1),
  CONSUMER_IND           CHAR(1),
  ENVIRON_IND            CHAR(1),
  OTHPUBL_IND            CHAR(1),
  OTHER_IND              CHAR(1),
  BOILER_IND             CHAR(1),
  USERID_ID              VARCHAR(160)     NOT NULL,
  DATEADD_DT             CHAR(8)           NOT NULL,
  FORM_RECEIVED_DATE     DATE,
  INDUSTRIAL_BOILER_IND  CHAR(1),
  LAST_UPDATE_DATE       DATE,
  OTHER_DESCRIPTION      VARCHAR(1000)
);


COMMENT ON TABLE CAMDNATS.TACCOUNT IS 'This tables stores information common to all ATS accounts.';

COMMENT ON COLUMN CAMDNATS.TACCOUNT.ACCTNUM_ID IS 'ACCOUNT NUMBER ID';
COMMENT ON COLUMN CAMDNATS.TACCOUNT.ACCTTYPE_CD IS 'ACCOUNT TYPE CODE';
COMMENT ON COLUMN CAMDNATS.TACCOUNT.ACCTNAME_NME IS 'ACCOUNT NAME';
COMMENT ON COLUMN CAMDNATS.TACCOUNT.NOBROKER_IND IS 'NOT EMPLOYED BY BROKERAGE FLAG';
COMMENT ON COLUMN CAMDNATS.TACCOUNT.BRKRTRAN_IND IS 'BROKERAGE TRANSFER ALLOWANCES FLAG';
COMMENT ON COLUMN CAMDNATS.TACCOUNT.BRKRHOLD_IND IS 'BROKERAGE HOLD ALLOWANCES FLAG';
COMMENT ON COLUMN CAMDNATS.TACCOUNT.BRKROTHER_IND IS 'BROKERAGE OTHER PURPOSE FLAG';
COMMENT ON COLUMN CAMDNATS.TACCOUNT.UTILITY_IND IS 'UTILITY GENERATOR FLAG';
COMMENT ON COLUMN CAMDNATS.TACCOUNT.NONUTIL_IND IS 'NON-UTILITY GENERATOR FLAG';
COMMENT ON COLUMN CAMDNATS.TACCOUNT.COAL_IND IS 'COAL SUPPLIER FLAG';
COMMENT ON COLUMN CAMDNATS.TACCOUNT.OIL_IND IS 'OIL SUPPLIER FLAG';
COMMENT ON COLUMN CAMDNATS.TACCOUNT.GAS_IND IS 'GAS SUPPLIER FLAG';
COMMENT ON COLUMN CAMDNATS.TACCOUNT.FUELOTHR_IND IS 'OTHER FUEL SUPPLIER FLAG';
COMMENT ON COLUMN CAMDNATS.TACCOUNT.POLLUTN_IND IS 'POLLUTION CONTROL FLAG';
COMMENT ON COLUMN CAMDNATS.TACCOUNT.CONSUMER_IND IS 'CONSUMER GROUP FLAG';
COMMENT ON COLUMN CAMDNATS.TACCOUNT.ENVIRON_IND IS 'ENVIRONMENTAL GROUP FLAG';
COMMENT ON COLUMN CAMDNATS.TACCOUNT.OTHPUBL_IND IS 'OTHER PUBLIC FLAG';
COMMENT ON COLUMN CAMDNATS.TACCOUNT.OTHER_IND IS 'OTHER BUSINESS FLAG';
COMMENT ON COLUMN CAMDNATS.TACCOUNT.BOILER_IND IS 'BOILER FLAG';
COMMENT ON COLUMN CAMDNATS.TACCOUNT.USERID_ID IS 'USER ID';
COMMENT ON COLUMN CAMDNATS.TACCOUNT.DATEADD_DT IS 'ACCOUNT CREATION DATE';
COMMENT ON COLUMN CAMDNATS.TACCOUNT.FORM_RECEIVED_DATE IS 'Date the account form was received.';
COMMENT ON COLUMN CAMDNATS.TACCOUNT.INDUSTRIAL_BOILER_IND IS 'INDUSTRIAL BOILER FLAG';
COMMENT ON COLUMN CAMDNATS.TACCOUNT.LAST_UPDATE_DATE IS 'This is used by the Data Mart to determine which data to update.  It is populated by triggers on insert and on update.';
COMMENT ON COLUMN CAMDNATS.TACCOUNT.OTHER_DESCRIPTION IS 'OTHER FLAG';
