CREATE TABLE CAMDNATS.TACCT_REP
(
  ACCT_REP_ID  NUMERIC(38)      NOT NULL,
  PPL_ID       NUMERIC(38)      NOT NULL,
  ACCTNUM_ID   CHAR(12)         NOT NULL,
  START_DATE   TIMESTAMP        NOT NULL,
  END_DATE     TIMESTAMP,
  REP_CD       CHAR(3)          NOT NULL,
  USERID       VARCHAR(160)     NOT NULL,
  UPDATE_DATE  TIMESTAMP        NOT NULL
);


COMMENT ON TABLE CAMDNATS.TACCT_REP IS 'This table stores the Representative-Account relationships for Non-Unit Accounts.  Unit Accounts will have this information tracked in SMS.';

COMMENT ON COLUMN CAMDNATS.TACCT_REP.ACCT_REP_ID IS 'ACCOUNT REPRESENTATIVE ID';
COMMENT ON COLUMN CAMDNATS.TACCT_REP.PPL_ID IS 'PEOPLE ID';
COMMENT ON COLUMN CAMDNATS.TACCT_REP.ACCTNUM_ID IS 'ACCOUNT NUMERICID';
COMMENT ON COLUMN CAMDNATS.TACCT_REP.START_DATE IS 'START DATE';
COMMENT ON COLUMN CAMDNATS.TACCT_REP.END_DATE IS 'END DATE';
COMMENT ON COLUMN CAMDNATS.TACCT_REP.REP_CD IS 'RESPONSIBILITY CODE';
COMMENT ON COLUMN CAMDNATS.TACCT_REP.USERID IS 'USER ID';
COMMENT ON COLUMN CAMDNATS.TACCT_REP.UPDATE_DATE IS 'UPDATE DATE';
