CREATE TABLE CAMDNATS.TALLOW
(
  TRANEVNT_CNT  NUMERIC(10) NOT NULL,
  ALLWYEAR_DT   NUMERIC(4)  NOT NULL,
  SERSTART_CNT  NUMERIC(8)  NOT NULL,
  SEREND_CNT    NUMERIC(8)  NOT NULL,
  ALLWTRANS_CD  CHAR(2)
);


COMMENT ON TABLE CAMDNATS.TALLOW IS 'This table stores information about blocks of allowances.';

COMMENT ON COLUMN CAMDNATS.TALLOW.TRANEVNT_CNT IS 'TRANSACTION EVENT NUMERIC';
COMMENT ON COLUMN CAMDNATS.TALLOW.ALLWYEAR_DT IS 'ALLOWANCE YEAR';
COMMENT ON COLUMN CAMDNATS.TALLOW.SERSTART_CNT IS 'SERIAL START NUMERIC';
COMMENT ON COLUMN CAMDNATS.TALLOW.SEREND_CNT IS 'SERIAL END NUMERIC';
COMMENT ON COLUMN CAMDNATS.TALLOW.ALLWTRANS_CD IS 'ALLOWANCE TRANSACTION CODE';
