CREATE TABLE CAMDNATS.TARS_ETS_TONS
(
  COMPYEAR_DT    CHAR(4)        NOT NULL,
  PLANTID_ID     CHAR(6)        NOT NULL,
  UNIT_STACK_ID  CHAR(6)        NOT NULL,
  YEARTONS_CNT   NUMERIC(9)     NOT NULL
);


COMMENT ON TABLE CAMDNATS.TARS_ETS_TONS IS 'This table stores emission tonnage levels for a given unit/stack in a given year.';

COMMENT ON COLUMN CAMDNATS.TARS_ETS_TONS.COMPYEAR_DT IS 'COMPLIANCE YEAR';
COMMENT ON COLUMN CAMDNATS.TARS_ETS_TONS.PLANTID_ID IS 'ORIS CODE';
COMMENT ON COLUMN CAMDNATS.TARS_ETS_TONS.UNIT_STACK_ID IS 'UNIT STACK ID';
COMMENT ON COLUMN CAMDNATS.TARS_ETS_TONS.YEARTONS_CNT IS 'CALENDAR YEAR TONS';
