CREATE TABLE CAMDNATS.TARS_OVDFT_DED
(
  ACCTNUM_ID    CHAR(12)        NOT NULL,
  COMPYEAR_DT   CHAR(4)         NOT NULL,
  DEDTYPE_CD    CHAR(10),
  TRANEVNT_CNT  NUMERIC(10)     NOT NULL
);


COMMENT ON TABLE CAMDNATS.TARS_OVDFT_DED IS 'This table stores overdraft account deduction information.';

COMMENT ON COLUMN CAMDNATS.TARS_OVDFT_DED.ACCTNUM_ID IS 'ACCOUNT NUMERIC ID';
COMMENT ON COLUMN CAMDNATS.TARS_OVDFT_DED.COMPYEAR_DT IS 'COMPLIANCE YEAR';
COMMENT ON COLUMN CAMDNATS.TARS_OVDFT_DED.DEDTYPE_CD IS 'DEDUCTION TYPE CODE';
COMMENT ON COLUMN CAMDNATS.TARS_OVDFT_DED.TRANEVNT_CNT IS 'TRANSACTION EVENT NUMERIC';
