CREATE TABLE CAMDNATS.TARS_BANK_ALLW_PFC
(
  COMPYEAR_DT  CHAR(4)          NOT NULL,
  ALLWPFC_CNT  NUMERIC(3,2)     NOT NULL
);


COMMENT ON TABLE CAMDNATS.TARS_BANK_ALLW_PFC IS 'Stores the Progressive Flow Control Ratio for each year.';

COMMENT ON COLUMN CAMDNATS.TARS_BANK_ALLW_PFC.COMPYEAR_DT IS 'COMPLIANCE YEAR';
COMMENT ON COLUMN CAMDNATS.TARS_BANK_ALLW_PFC.ALLWPFC_CNT IS 'PFC RATION FOR YEAR';
