CREATE TABLE CAMDNATS.TARS_STACK_CONFIG
(
  COMPYEAR_DT  CHAR(4)  NOT NULL,
  PLANTID_ID   CHAR(6)  NOT NULL,
  STACKID_ID   CHAR(6)  NOT NULL,
  UNIT_ID      CHAR(6)  NOT NULL
);


COMMENT ON TABLE CAMDNATS.TARS_STACK_CONFIG IS 'This table stores the stack configuration for a given compliance year.';

COMMENT ON COLUMN CAMDNATS.TARS_STACK_CONFIG.COMPYEAR_DT IS 'COMPLIANCE YEAR';
COMMENT ON COLUMN CAMDNATS.TARS_STACK_CONFIG.PLANTID_ID IS 'PLANT ID';
COMMENT ON COLUMN CAMDNATS.TARS_STACK_CONFIG.STACKID_ID IS 'STACK ID';
COMMENT ON COLUMN CAMDNATS.TARS_STACK_CONFIG.UNIT_ID IS 'UNIT ID';
