CREATE TABLE CAMDNATS.TAUTHOR
(
  LIMITTYP_CD   CHAR(1)         NOT NULL,
  ACCTNUM_ID    CHAR(12)        NOT NULL,
  ACCTMAX_TOT   NUMERIC(10)     NOT NULL,
  ACCTISSU_TOT  NUMERIC(10)     NOT NULL
);


COMMENT ON TABLE CAMDNATS.TAUTHOR IS 'This table stores the allocations from a reserve account to a market account.';

COMMENT ON COLUMN CAMDNATS.TAUTHOR.LIMITTYP_CD IS 'LIMIT TYPE CODE';
COMMENT ON COLUMN CAMDNATS.TAUTHOR.ACCTNUM_ID IS 'ACCOUNT NUMERIC ID';
COMMENT ON COLUMN CAMDNATS.TAUTHOR.ACCTMAX_TOT IS 'ACCOUNT LIMIT';
COMMENT ON COLUMN CAMDNATS.TAUTHOR.ACCTISSU_TOT IS 'AMOUNT ALLOCATED';
