CREATE TABLE CAMDNATS.TSERIAL
(
  ALLWYEAR_DT       NUMERIC(4)  NOT NULL,
  SERSTART_CNT      NUMERIC(8)  NOT NULL,
  SEREND_CNT        NUMERIC(8)  NOT NULL,
  ALLWTYPE_CD       CHAR(2)     NOT NULL,
  ALLWSTAT_CD       CHAR(2)     NOT NULL,
  TRANTYPE_CD       CHAR(2)     NOT NULL,
  ACCTNUM_ID        CHAR(12)    NOT NULL,
  LAST_UPDATE_DATE  TIMESTAMP
);


COMMENT ON TABLE CAMDNATS.TSERIAL IS 'This table stores the serial NUMERICs of allowances and their current status.';

COMMENT ON COLUMN CAMDNATS.TSERIAL.ALLWYEAR_DT IS 'ALLOWANCE YEAR';
COMMENT ON COLUMN CAMDNATS.TSERIAL.SERSTART_CNT IS 'SERIAL START NUMERIC';
COMMENT ON COLUMN CAMDNATS.TSERIAL.SEREND_CNT IS 'SERIAL END NUMERIC';
COMMENT ON COLUMN CAMDNATS.TSERIAL.ALLWTYPE_CD IS 'ALLOWANCE TYPE CODE';
COMMENT ON COLUMN CAMDNATS.TSERIAL.ALLWSTAT_CD IS 'ALLOWANCE STATUS CODE';
COMMENT ON COLUMN CAMDNATS.TSERIAL.TRANTYPE_CD IS 'TRANSACTION TYPE CODE';
COMMENT ON COLUMN CAMDNATS.TSERIAL.ACCTNUM_ID IS 'ACCOUNT NUMERIC ID';
COMMENT ON COLUMN CAMDNATS.TSERIAL.LAST_UPDATE_DATE IS 'This is used by the Data Mart to determine which data to update.  It is populated by triggers on insert and on update.';
