CREATE TABLE CAMDNATS.TTOTALLOW
(
  ACCTNUM_ID    CHAR(12)    NOT NULL,
  ALLWYEAR_DT   NUMERIC(4)  NOT NULL,
  TOTALLOW_TOT  NUMERIC(8)  NOT NULL
);


COMMENT ON TABLE CAMDNATS.TTOTALLOW IS 'This tables stores the total NUMERIC of allowances owned by a given account for a given year.';

COMMENT ON COLUMN CAMDNATS.TTOTALLOW.ACCTNUM_ID IS 'ACCOUNT NUMERIC ID';
COMMENT ON COLUMN CAMDNATS.TTOTALLOW.ALLWYEAR_DT IS 'ALLOWANCE YEAR';
COMMENT ON COLUMN CAMDNATS.TTOTALLOW.TOTALLOW_TOT IS 'NUMERIC OF ALLOWANCES OWNED';
