CREATE TABLE CAMDNATS.TTRANTYPE
(
  TRANTYPE_CD    CHAR(2)        NOT NULL,
  TRANDESC_DESC  VARCHAR(46)    NOT NULL
);


COMMENT ON TABLE CAMDNATS.TTRANTYPE IS 'This is a lookup table for transaction type codes.';

COMMENT ON COLUMN CAMDNATS.TTRANTYPE.TRANTYPE_CD IS 'TRANSACTION EVENT TYPE CODE';
COMMENT ON COLUMN CAMDNATS.TTRANTYPE.TRANDESC_DESC IS 'TRANSACTION EVENT TYPE DESCRIPTION';
