CREATE TABLE CAMDNATS.TUNITDEDUCT
(
  DEDSQNCE_CNT  NUMERIC(5)      NOT NULL,
  ALLWYEAR_DT   NUMERIC(4)      NOT NULL,
  ACCTNUM_ID    CHAR(12)        NOT NULL,
  SERSTART_CNT  NUMERIC(8)      NOT NULL,
  SEREND_CNT    NUMERIC(8)      NOT NULL,
  COMPYEAR_DT   CHAR(4)         NOT NULL,
  DEDUCTCAT_CD  CHAR(2)         NOT NULL,
  USERID        VARCHAR(160)    DEFAULT 'ATS' NOT NULL,
  ADD_DATE      TIMESTAMP       DEFAULT now()::timestamp NOT NULL,
  UPDATE_DATE   TIMESTAMP
);


COMMENT ON TABLE CAMDNATS.TUNITDEDUCT IS 'This table tracks specific allowance deductions from accounts.';

COMMENT ON COLUMN CAMDNATS.TUNITDEDUCT.DEDSQNCE_CNT IS 'DEDUCTION SEQUENCE';
COMMENT ON COLUMN CAMDNATS.TUNITDEDUCT.ALLWYEAR_DT IS 'ALLOWANCE YEAR';
COMMENT ON COLUMN CAMDNATS.TUNITDEDUCT.ACCTNUM_ID IS 'ACCOUNT NUMERIC ID';
COMMENT ON COLUMN CAMDNATS.TUNITDEDUCT.SERSTART_CNT IS 'SERIAL START NUMERIC';
COMMENT ON COLUMN CAMDNATS.TUNITDEDUCT.SEREND_CNT IS 'SERIAL END NUMERIC';
COMMENT ON COLUMN CAMDNATS.TUNITDEDUCT.COMPYEAR_DT IS 'COMPLIANCE YEAR';
COMMENT ON COLUMN CAMDNATS.TUNITDEDUCT.DEDUCTCAT_CD IS 'DEDUCTION CATEGORY CODE';
COMMENT ON COLUMN CAMDNATS.TUNITDEDUCT.ADD_DATE IS 'Date the record was created.';
COMMENT ON COLUMN CAMDNATS.TUNITDEDUCT.UPDATE_DATE IS 'Date record was updated.';
COMMENT ON COLUMN CAMDNATS.TUNITDEDUCT.USERID IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
