-----------------
-- Constraints --
-----------------

ALTER TABLE CAMD.PRE_ECMPS_UNIT_QUARTER ADD CONSTRAINT PRE_ECMPS_UNIT_QUARTER_PK PRIMARY KEY ( UNIT_ID, OP_YEAR, OP_QUARTER );
ALTER TABLE CAMD.PRE_ECMPS_UNIT_QUARTER ADD CONSTRAINT PRE_ECMPS_UNIT_QUARTER_UQ UNIQUE ( UNIT_ID, RPT_PERIOD_ID );
ALTER TABLE CAMD.PRE_ECMPS_UNIT_QUARTER ADD CONSTRAINT PRE_ECMPS_UNIT_QUARTER_UNT_FK FOREIGN KEY ( UNIT_ID ) REFERENCES CAMD.UNIT ( UNIT_ID );
