CREATE TABLE IF NOT EXISTS CAMDDMW.STATE_ALLOCATION_FACT
(
  VINTAGE_YEAR  NUMERIC(4)      NOT NULL,
  STATE         CHAR(2)         NOT NULL,
  STATE_NAME    VARCHAR(20),
  PR_CAP        NUMERIC(10),
  PR_ISSUE      NUMERIC(10),
  OPTIN_CAP     NUMERIC(10),
  OPTIN_ISSUE   NUMERIC(10),
  ER_CAP        NUMERIC(10),
  ER_ISSUE      NUMERIC(10),
  TOTAL_CAP     NUMERIC(10),
  TOTAL_ISSUE   NUMERIC(10)
);


COMMENT ON TABLE CAMDDMW.STATE_ALLOCATION_FACT IS 'Allowances issued by state for the NBP';


COMMENT ON COLUMN CAMDDMW.STATE_ALLOCATION_FACT.VINTAGE_YEAR IS 'Year in which allowance was issued';
COMMENT ON COLUMN CAMDDMW.STATE_ALLOCATION_FACT.STATE IS 'State abbreviation';
COMMENT ON COLUMN CAMDDMW.STATE_ALLOCATION_FACT.STATE_NAME IS 'State name';
COMMENT ON COLUMN CAMDDMW.STATE_ALLOCATION_FACT.PR_CAP IS 'Number of primary allowances a state may allocate';
COMMENT ON COLUMN CAMDDMW.STATE_ALLOCATION_FACT.PR_ISSUE IS 'Number of primary allowances a state has allocated';
COMMENT ON COLUMN CAMDDMW.STATE_ALLOCATION_FACT.OPTIN_CAP IS 'Number of opt-in allowances a state may allocate';
COMMENT ON COLUMN CAMDDMW.STATE_ALLOCATION_FACT.OPTIN_ISSUE IS 'Number of opt-in allowances a state has already allocated';
COMMENT ON COLUMN CAMDDMW.STATE_ALLOCATION_FACT.ER_CAP IS 'Early Reduction budget';
COMMENT ON COLUMN CAMDDMW.STATE_ALLOCATION_FACT.ER_ISSUE IS 'Total Early reduction issued';
COMMENT ON COLUMN CAMDDMW.STATE_ALLOCATION_FACT.TOTAL_CAP IS 'Total number of allowances a state may allocate';
COMMENT ON COLUMN CAMDDMW.STATE_ALLOCATION_FACT.TOTAL_ISSUE IS 'Total number of allowances a state has allocated';
