DO $$
BEGIN
	INSERT INTO camdaux.missing_oris(id, oris_code, state_cd) VALUES ('1', 880056, 'TN');
	INSERT INTO camdaux.missing_oris(id, oris_code, state_cd) VALUES ('2', 880022, 'DE');
	INSERT INTO camdaux.missing_oris(id, oris_code, state_cd) VALUES ('3', 880026, 'TX');
	INSERT INTO camdaux.missing_oris(id, oris_code, state_cd) VALUES ('4', 55195, 'WI');
	INSERT INTO camdaux.missing_oris(id, oris_code, state_cd) VALUES ('5', 55209, 'ME');
	INSERT INTO camdaux.missing_oris(id, oris_code, state_cd) VALUES ('6', 55140, 'TX');
	INSERT INTO camdaux.missing_oris(id, oris_code, state_cd) VALUES ('7', 2387, 'MI');
	INSERT INTO camdaux.missing_oris(id, oris_code, state_cd) VALUES ('8', 880032, 'MN');
	INSERT INTO camdaux.missing_oris(id, oris_code, state_cd) VALUES ('9', 56186, 'WV');
	INSERT INTO camdaux.missing_oris(id, oris_code, state_cd) VALUES ('10', 880035, 'WV');
	INSERT INTO camdaux.missing_oris(id, oris_code, state_cd) VALUES ('11', 880081, 'NC');
	INSERT INTO camdaux.missing_oris(id, oris_code, state_cd) VALUES ('12', 55848, 'CA');
	INSERT INTO camdaux.missing_oris(id, oris_code, state_cd) VALUES ('13', 50232, 'CA');
	INSERT INTO camdaux.missing_oris(id, oris_code, state_cd) VALUES ('14', 7923, 'AL');
	INSERT INTO camdaux.missing_oris(id, oris_code, state_cd) VALUES ('15', 7911, 'MS');
	INSERT INTO camdaux.missing_oris(id, oris_code, state_cd) VALUES ('16', 8058, 'MS');
	INSERT INTO camdaux.missing_oris(id, oris_code, state_cd) VALUES ('17', 880027, 'VA');
	INSERT INTO camdaux.missing_oris(id, oris_code, state_cd) VALUES ('18', 2783, 'OH');
	INSERT INTO camdaux.missing_oris(id, oris_code, state_cd) VALUES ('19', 50468, 'CT');
	INSERT INTO camdaux.missing_oris(id, oris_code, state_cd) VALUES ('20', 3355, 'KS');
	INSERT INTO camdaux.missing_oris(id, oris_code, state_cd) VALUES ('21', 880034, 'SC');
	INSERT INTO camdaux.missing_oris(id, oris_code, state_cd) VALUES ('22', 14013, 'LA');
	INSERT INTO camdaux.missing_oris(id, oris_code, state_cd) VALUES ('23', 7996, 'AL');
	INSERT INTO camdaux.missing_oris(id, oris_code, state_cd) VALUES ('24', 1700, 'CO');
	INSERT INTO camdaux.missing_oris(id, oris_code, state_cd) VALUES ('25', 54001, 'CT');
	INSERT INTO camdaux.missing_oris(id, oris_code, state_cd) VALUES ('26', 880069, 'OH');
	INSERT INTO camdaux.missing_oris(id, oris_code, state_cd) VALUES ('27', 7864, 'NY');
	INSERT INTO camdaux.missing_oris(id, oris_code, state_cd) VALUES ('28', 55180, 'VA');
	INSERT INTO camdaux.missing_oris(id, oris_code, state_cd) VALUES ('29', 880046, 'OH');
	INSERT INTO camdaux.missing_oris(id, oris_code, state_cd) VALUES ('30', 7840, 'IL');
	INSERT INTO camdaux.missing_oris(id, oris_code, state_cd) VALUES ('31', 55461, 'UT');
	INSERT INTO camdaux.missing_oris(id, oris_code, state_cd) VALUES ('32', 880002, 'TN');
END $$;