CREATE OR REPLACE VIEW camdecmps.vw_locations_in_multiple_mps AS
SELECT 
    VMP.ORIS_CODE, 
    VMP.FACILITY_NAME,
    VMP.STATE,
    VMP.LOCATIONS,
    BRP.PERIOD_ABBREVIATION AS BEGIN_PERIOD,
    CASE 
         WHEN X.END_RPT_PERIOD_ID IS NOT NULL 
         THEN ERP.PERIOD_ABBREVIATION
         ELSE '' 
    END AS END_PERIOD,
    VMP2.LOCATIONS AS LOCATIONS2,
    BRP2.PERIOD_ABBREVIATION AS BEGIN_PERIOD2,
    CASE 
         WHEN X.END_RPT_PERIOD_ID2 IS NOT NULL 
         THEN ERP2.PERIOD_ABBREVIATION 
         ELSE '' 
    END AS END_PERIOD2
FROM (
    SELECT DISTINCT 
           MP.MON_PLAN_ID,
           MP2.MON_PLAN_ID AS MON_PLAN_ID2,
           MP.BEGIN_RPT_PERIOD_ID,
           MP.END_RPT_PERIOD_ID,
           MP2.BEGIN_RPT_PERIOD_ID AS BEGIN_RPT_PERIOD_ID2,
           MP2.END_RPT_PERIOD_ID AS END_RPT_PERIOD_ID2
    FROM camdecmpswks.VW_MONITOR_PLAN_LOCATION MPL
    JOIN camdecmps.MONITOR_PLAN_LOCATION MPL2 
         ON MPL.MON_LOC_ID = MPL2.MON_LOC_ID
    JOIN camdecmps.MONITOR_PLAN MP 
         ON MP.MON_PLAN_ID = MPL.MON_PLAN_ID
    JOIN camdecmps.MONITOR_PLAN MP2 
         ON MPL2.MON_PLAN_ID = MP2.MON_PLAN_ID
    WHERE MP.MON_PLAN_ID > MP2.MON_PLAN_ID
      AND (
           (MP.BEGIN_RPT_PERIOD_ID <= MP2.BEGIN_RPT_PERIOD_ID 
              AND COALESCE(MP.END_RPT_PERIOD_ID, 999) >= MP2.BEGIN_RPT_PERIOD_ID)
           OR 
           (MP.BEGIN_RPT_PERIOD_ID >= MP2.BEGIN_RPT_PERIOD_ID 
              AND MP.BEGIN_RPT_PERIOD_ID <= COALESCE(MP2.END_RPT_PERIOD_ID, 999))
          )
) X
JOIN camdecmps.VW_MONITOR_PLAN VMP 
    ON X.MON_PLAN_ID = VMP.MON_PLAN_ID
JOIN camdecmps.VW_MONITOR_PLAN VMP2 
    ON X.MON_PLAN_ID2 = VMP2.MON_PLAN_ID
JOIN camdecmpsmd.REPORTING_PERIOD BRP 
    ON X.BEGIN_RPT_PERIOD_ID = BRP.RPT_PERIOD_ID
LEFT JOIN camdecmpsmd.REPORTING_PERIOD ERP 
    ON X.END_RPT_PERIOD_ID = ERP.RPT_PERIOD_ID
JOIN camdecmpsmd.REPORTING_PERIOD BRP2 
    ON X.BEGIN_RPT_PERIOD_ID2 = BRP2.RPT_PERIOD_ID
LEFT JOIN camdecmpsmd.REPORTING_PERIOD ERP2 
    ON X.END_RPT_PERIOD_ID2 = ERP2.RPT_PERIOD_ID
ORDER BY VMP.ORIS_CODE, VMP.LOCATIONS;
