-- View: camdecmpswks.vw_qa_rata_run

DROP VIEW IF EXISTS camdecmpswks.vw_qa_rata_run;

CREATE OR REPLACE VIEW camdecmpswks.vw_qa_rata_run
 AS
 SELECT rr.rata_run_id,
    rr.rata_sum_id,
    rs.op_level_cd,
    rr.run_num,
    rr.begin_date,
    rr.begin_hour,
    rr.begin_min,
    rr.end_date,
    rr.end_hour,
    rr.end_min,
    rr.cem_value,
    rr.gross_unit_load,
    rr.run_status_cd,
    rr.rata_ref_value,
    rr.calc_rata_ref_value,
    rr.userid,
    rr.add_date,
    rr.update_date,
    rs.test_num,
    rs.gp_ind,
    rs.ref_method_cd,
    rs.test_reason_cd,
    rs.test_result_cd,
    rs.begin_date AS rata_begin_date,
    rs.begin_hour AS rata_begin_hour,
    rs.begin_min AS rata_begin_min,
    rs.end_date AS rata_end_date,
    rs.end_hour AS rata_end_hour,
    rs.end_min AS rata_end_min,
    rs.sys_type_cd,
    rs.system_identifier,
    rs.rata_id,
    rs.test_sum_id,
    rs.mon_sys_id,
    rs.mon_loc_id,
    rs.stack_diameter,
    rs.stack_area,
    rs.calc_waf AS level_calc_waf,
    rs.default_waf,
    rs.fac_id,
    rs.location_identifier,
    frr.flow_rata_run_id,
    frr.num_traverse_point,
    frr.barometric_pressure,
    frr.static_stack_pressure,
    frr.percent_co2,
    frr.percent_o2,
    frr.percent_moisture,
    frr.dry_molecular_weight,
    frr.wet_molecular_weight,
    frr.avg_vel_wo_wall,
    frr.avg_vel_w_wall,
    frr.calc_waf,
    frr.avg_stack_flow_rate
   FROM camdecmpswks.rata_run rr
     JOIN camdecmpswks.vw_qa_rata_summary rs ON rr.rata_sum_id::text = rs.rata_sum_id::text
     LEFT JOIN camdecmpswks.flow_rata_run frr ON rr.rata_run_id::text = frr.rata_run_id::text;
