CREATE TABLE IF NOT EXISTS camdws.account_program_ws
(
    account_program_ws_id bigint GENERATED BY DEFAULT AS IDENTITY,
    workspace_session_id numeric(38,0) NOT NULL,
    ws_added_ind numeric(1,0) NOT NULL,
    ws_updated_ind numeric(1,0) NOT NULL,
    account_prg_id numeric(38,0) NOT NULL,
    account_id numeric(38,0) NOT NULL,
    prg_cd varchar(7) NOT NULL,
    program_cd varchar(7) NOT NULL,
    account_status_cd varchar(7) NOT NULL,
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (account_program_ws_id)
);
COMMENT ON TABLE camdws.account_program_ws
    IS 'Links account_id with the prg_codes it can trade in.';
COMMENT ON COLUMN camdws.account_program_ws.account_program_ws_id
    IS 'unique id.';
COMMENT ON COLUMN camdws.account_program_ws.workspace_session_id
    IS 'FK to parent workspace session.';
COMMENT ON COLUMN camdws.account_program_ws.ws_added_ind
    IS '1 (true) if record was added during the WS session, other, otherwise 0.';
COMMENT ON COLUMN camdws.account_program_ws.ws_updated_ind
    IS '1 (true) if record was updated during the WS session, other, otherwise 0.';
COMMENT ON COLUMN camdws.account_program_ws.account_prg_id
    IS 'Identity key for account program table.';
COMMENT ON COLUMN camdws.account_program_ws.account_id
    IS 'Identity key for account table.';
COMMENT ON COLUMN camdws.account_program_ws.prg_cd
    IS 'Code used to identify regulatory program applicable to account.';
COMMENT ON COLUMN camdws.account_program_ws.program_cd
    IS 'Code used to identify regulatory program applicable to account. (String version for the domain!)';
COMMENT ON COLUMN camdws.account_program_ws.account_status_cd
    IS 'Account status code.';
COMMENT ON COLUMN camdws.account_program_ws.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camdws.account_program_ws.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camdws.account_program_ws.update_date
    IS 'Date of the last record update.';