CREATE TABLE IF NOT EXISTS camdws.account_ws
(
    account_ws_id bigint GENERATED BY DEFAULT AS IDENTITY,
    workspace_session_id numeric(38,0) NOT NULL,
    ws_added_ind numeric(1,0) NOT NULL,
    ws_updated_ind numeric(1,0) NOT NULL,
    account_id numeric(38,0) NOT NULL,
    account_name varchar(100) NOT NULL,
    account_number varchar(12),
    account_type_cd varchar(7) NOT NULL,
    contact_email_address varchar(70),
    contact_name varchar(100),
    state_cd varchar(2),
    tribal_land_cd varchar(7),
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (account_ws_id)
);
COMMENT ON TABLE camdws.account_ws
    IS 'Identifies all AMS accounts.';
COMMENT ON COLUMN camdws.account_ws.account_ws_id
    IS 'unique id.';
COMMENT ON COLUMN camdws.account_ws.workspace_session_id
    IS 'FK to parent workspace session.';
COMMENT ON COLUMN camdws.account_ws.ws_added_ind
    IS '1 (true) if record was added during the WS session, other, otherwise 0.';
COMMENT ON COLUMN camdws.account_ws.ws_updated_ind
    IS '1 (true) if record was updated during the WS session, other, otherwise 0.';
COMMENT ON COLUMN camdws.account_ws.account_id
    IS 'Identity key for account table.';
COMMENT ON COLUMN camdws.account_ws.account_name
    IS 'Name of account.';
COMMENT ON COLUMN camdws.account_ws.account_number
    IS 'Unique public identifier for account table.';
COMMENT ON COLUMN camdws.account_ws.account_type_cd
    IS 'Type of account.';
COMMENT ON COLUMN camdws.account_ws.contact_email_address
    IS 'Email address of state contact for state allocation accounts.';
COMMENT ON COLUMN camdws.account_ws.contact_name
    IS 'Contact name of state contact for state allocation accounts.';
COMMENT ON COLUMN camdws.account_ws.state_cd
    IS 'State abbreviation for state in which account is located. ';
COMMENT ON COLUMN camdws.account_ws.tribal_land_cd
    IS 'Tribal land abbreviation for tribal land in which account is located.';
COMMENT ON COLUMN camdws.account_ws.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camdws.account_ws.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camdws.account_ws.update_date
    IS 'Date of the last record update.';