CREATE TABLE IF NOT EXISTS camdws.account_person_ws
(
    account_ppl_ws_id bigint GENERATED BY DEFAULT AS IDENTITY,
    workspace_session_id numeric(38,0) NOT NULL,
    ws_added_ind numeric(1,0) NOT NULL,
    ws_updated_ind numeric(1,0) NOT NULL,
    account_ppl_id numeric(38,0) NOT NULL,
    account_id numeric(38,0) NOT NULL,
    ppl_id numeric(38,0) NOT NULL,
    responsibility_id varchar(7) NOT NULL,
    begin_date timestamp without time zone NOT NULL,
    end_date timestamp without time zone,
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (account_ppl_ws_id)
);
COMMENT ON TABLE camdws.account_person_ws
    IS 'Links account_id and the ppl_id of the representative.';
COMMENT ON COLUMN camdws.account_person_ws.account_ppl_ws_id
    IS 'unique id.';
COMMENT ON COLUMN camdws.account_person_ws.workspace_session_id
    IS 'FK to parent workspace session.';
COMMENT ON COLUMN camdws.account_person_ws.ws_added_ind
    IS '1 (true) if record was added during the WS session, other, otherwise 0.';
COMMENT ON COLUMN camdws.account_person_ws.ws_updated_ind
    IS '1 (true) if record was updated during the WS session, other, otherwise 0.';
COMMENT ON COLUMN camdws.account_person_ws.account_ppl_id
    IS 'Identity key for account people table.';
COMMENT ON COLUMN camdws.account_person_ws.account_id
    IS 'Identity key for account table.';
COMMENT ON COLUMN camdws.account_person_ws.ppl_id
    IS 'Identity key for people table.';
COMMENT ON COLUMN camdws.account_person_ws.responsibility_id
    IS 'Responsibility type code.';
COMMENT ON COLUMN camdws.account_person_ws.begin_date
    IS 'Date on which a relationship or an activity began. ';
COMMENT ON COLUMN camdws.account_person_ws.end_date
    IS 'Date on which a relationship or an activity ended. ';
COMMENT ON COLUMN camdws.account_person_ws.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camdws.account_person_ws.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camdws.account_person_ws.update_date
    IS 'Date of the last record update.';