CREATE TABLE IF NOT EXISTS camdws.agency_ws
(
    agency_ws_id bigint GENERATED BY DEFAULT AS IDENTITY,
    workspace_session_id numeric(38,0) NOT NULL,
    ws_added_ind numeric(1,0) NOT NULL,
    ws_updated_ind numeric(1,0) NOT NULL,
    agency_id numeric(38,0) NOT NULL,
    agency_type_cd varchar(7) NOT NULL,
    agency_name varchar(100) NOT NULL,
    agency_name2 varchar(100),
    address1 varchar(50),
    address2 varchar(50),
    city varchar(20),
    state_cd varchar(2) NOT NULL,
    zip_code varchar(10),
    phone_number varchar(18) NOT NULL,
    extension varchar(5),
    fax_number varchar(18),
    tribal_land_cd varchar(7),
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (agency_ws_id)
);
COMMENT ON TABLE camdws.agency_ws
    IS 'Identifies the regulatory agency which has responsibilities for Program implementation or support.';
COMMENT ON COLUMN camdws.agency_ws.agency_ws_id
    IS 'unique id.';
COMMENT ON COLUMN camdws.agency_ws.workspace_session_id
    IS 'FK to parent workspace session.';
COMMENT ON COLUMN camdws.agency_ws.ws_added_ind
    IS '1 (true) if record was added during the WS session, other, otherwise 0.';
COMMENT ON COLUMN camdws.agency_ws.ws_updated_ind
    IS '1 (true) if record was updated during the WS session, other, otherwise 0.';
COMMENT ON COLUMN camdws.agency_ws.agency_id
    IS 'AGENCY identity key.';
COMMENT ON COLUMN camdws.agency_ws.agency_type_cd
    IS 'Identifies the type of agency.';
COMMENT ON COLUMN camdws.agency_ws.agency_name
    IS 'Name of regulatory agency.';
COMMENT ON COLUMN camdws.agency_ws.agency_name2
    IS 'Second or alternative name of regulatory agency.';
COMMENT ON COLUMN camdws.agency_ws.address1
    IS 'Mailing or street address line 1. ';
COMMENT ON COLUMN camdws.agency_ws.address2
    IS 'Mailing or street address line 2. ';
COMMENT ON COLUMN camdws.agency_ws.city
    IS 'The city address for an AGENCY or individual. ';
COMMENT ON COLUMN camdws.agency_ws.state_cd
    IS 'State abbreviation for state in which FACILITY, CONTACT, AGENCY, ACCOUNT, REQUEST, PROGRAM, or STAFF is located.';
COMMENT ON COLUMN camdws.agency_ws.zip_code
    IS 'The US Postal Service zip code.';
COMMENT ON COLUMN camdws.agency_ws.phone_number
    IS 'Phone number for CONTACT or STAFF, AGENCY, and ACCOUNT REQUEST. ';
COMMENT ON COLUMN camdws.agency_ws.extension
    IS 'Extension of agency''s phone number.';
COMMENT ON COLUMN camdws.agency_ws.fax_number
    IS 'The facsimile number for an agency.';
COMMENT ON COLUMN camdws.agency_ws.tribal_land_cd
    IS 'The code that indicates the tribal land.';
COMMENT ON COLUMN camdws.agency_ws.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camdws.agency_ws.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camdws.agency_ws.update_date
    IS 'Date of the last record update.';