CREATE TABLE IF NOT EXISTS camdws.auction_bid_ws
(
    auction_bid_ws_id bigint GENERATED BY DEFAULT AS IDENTITY,
    workspace_session_id numeric NOT NULL,
    auction_bid_id numeric(38,0),
    bid_number numeric(38,0),
    auction_id numeric(38,0),
    account_id numeric(38,0),
    ppl_id numeric(38,0),
    bid_list_name varchar(100),
    bid_price numeric(8,2),
    bid_quantity numeric(6,0),
    fewer_ind numeric(38,0),
    payment_method_cd varchar(7),
    paid_ind numeric(38,0),
    add_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    userid varchar(160),
    bid_order numeric(2,0),
    amount_paid numeric(14,2),
    bid_status_cd varchar(8),
    letter_of_credit_number varchar(20),
    submitter_ppl_id numeric(38,0),
    edit_ind numeric DEFAULT 0,
    rep_display_name varchar(100) NOT NULL,
    account_number varchar(12) NOT NULL,
    auction_type_cd varchar(7) NOT NULL,
    ws_added_ind numeric(1,0) NOT NULL,
    ws_updated_ind numeric(1,0) NOT NULL,
    bid_date timestamp without time zone,
    bid_total numeric(14,2),
    PRIMARY KEY (auction_bid_ws_id)
);
COMMENT ON TABLE camdws.auction_bid_ws
    IS 'Workspace Table for auction bids.';
COMMENT ON COLUMN camdws.auction_bid_ws.auction_bid_ws_id
    IS 'Identity keu for workspace auction bid id';
COMMENT ON COLUMN camdws.auction_bid_ws.workspace_session_id
    IS 'Identity key for workspace table';
COMMENT ON COLUMN camdws.auction_bid_ws.auction_bid_id
    IS 'Identity key for auction bid table.';
COMMENT ON COLUMN camdws.auction_bid_ws.bid_number
    IS 'Public Identifier for auction bid by auction year.';
COMMENT ON COLUMN camdws.auction_bid_ws.auction_id
    IS 'Identity key for auction table.';
COMMENT ON COLUMN camdws.auction_bid_ws.account_id
    IS 'Identity key for account table.';
COMMENT ON COLUMN camdws.auction_bid_ws.ppl_id
    IS 'Identity key for people table.';
COMMENT ON COLUMN camdws.auction_bid_ws.bid_list_name
    IS 'Name the bid is listed by.';
COMMENT ON COLUMN camdws.auction_bid_ws.bid_price
    IS 'Bid price.';
COMMENT ON COLUMN camdws.auction_bid_ws.bid_quantity
    IS 'Number of allowances bid for.';
COMMENT ON COLUMN camdws.auction_bid_ws.fewer_ind
    IS 'Indicates if the bidder is willing to purchase fewer allowances.';
COMMENT ON COLUMN camdws.auction_bid_ws.payment_method_cd
    IS 'Code for method of payment.';
COMMENT ON COLUMN camdws.auction_bid_ws.paid_ind
    IS 'Indicates if the bidder has payed.';
COMMENT ON COLUMN camdws.auction_bid_ws.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camdws.auction_bid_ws.update_date
    IS 'Date of the last record update.';
COMMENT ON COLUMN camdws.auction_bid_ws.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camdws.auction_bid_ws.bid_order
    IS 'Order tied bids will win allowances.';
COMMENT ON COLUMN camdws.auction_bid_ws.amount_paid
    IS 'Amount paid.';
COMMENT ON COLUMN camdws.auction_bid_ws.bid_status_cd
    IS 'Status code for bid';
COMMENT ON COLUMN camdws.auction_bid_ws.letter_of_credit_number
    IS 'Credit number';
COMMENT ON COLUMN camdws.auction_bid_ws.submitter_ppl_id
    IS 'Identity key for the submitted people.';
COMMENT ON COLUMN camdws.auction_bid_ws.edit_ind
    IS 'Indicates if the bid has been edited during the current CBS session.';
COMMENT ON COLUMN camdws.auction_bid_ws.rep_display_name
    IS 'Display name for the auction bidder';
COMMENT ON COLUMN camdws.auction_bid_ws.account_number
    IS 'Referenced Account Number';
COMMENT ON COLUMN camdws.auction_bid_ws.auction_type_cd
    IS 'Referenced Auction Type from parent AUCTION_ID';
COMMENT ON COLUMN camdws.auction_bid_ws.ws_added_ind
    IS '1 (true) if record was added during the WS session, other, otherwise 0.';
COMMENT ON COLUMN camdws.auction_bid_ws.ws_updated_ind
    IS '1 (true) if record was updated during the WS session, other, otherwise 0.';
COMMENT ON COLUMN camdws.auction_bid_ws.bid_date
    IS 'Date of the last CBS update to the bid record.';
COMMENT ON COLUMN camdws.auction_bid_ws.bid_total
    IS 'Total of the BID_PRICE * BID_QUANTITY';