CREATE TABLE IF NOT EXISTS camdws.company_ws
(
    company_ws_id bigint GENERATED BY DEFAULT AS IDENTITY,
    workspace_session_id numeric(38,0) NOT NULL,
    ws_added_ind numeric(1,0) NOT NULL,
    ws_updated_ind numeric(1,0) NOT NULL,
    company_id numeric(38,0) NOT NULL,
    company_name varchar(100) NOT NULL,
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (company_ws_id)
);
COMMENT ON TABLE camdws.company_ws
    IS 'Identifies an electric generating or industrial facility consisting of UNITS known to or potentially subject to a trading program for workspace.';
COMMENT ON COLUMN camdws.company_ws.company_ws_id
    IS 'unique id.';
COMMENT ON COLUMN camdws.company_ws.workspace_session_id
    IS 'FK to parent workspace session.';
COMMENT ON COLUMN camdws.company_ws.ws_added_ind
    IS '1 (true) if record was added during the WS session, other, otherwise 0.';
COMMENT ON COLUMN camdws.company_ws.ws_updated_ind
    IS '1 (true) if record was updated during the WS session, other, otherwise 0.';
COMMENT ON COLUMN camdws.company_ws.company_id
    IS 'COMPANY_ID from the loaded COMPANY record OR the next available S_COMPANY sequence value for a record created during the workspace session.';
COMMENT ON COLUMN camdws.company_ws.company_name
    IS 'Name of company.';
COMMENT ON COLUMN camdws.company_ws.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camdws.company_ws.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camdws.company_ws.update_date
    IS 'Date of the last record update.';