CREATE TABLE IF NOT EXISTS camdws.generator_ws
(
    gen_ws_id bigint GENERATED BY DEFAULT AS IDENTITY,
    workspace_session_id numeric(38,0) NOT NULL,
    ws_added_ind numeric(1,0) NOT NULL,
    ws_updated_ind numeric(1,0) NOT NULL,
    gen_id numeric(38,0) NOT NULL,
    fac_id numeric(38,0) NOT NULL,
    genid varchar(8) NOT NULL,
    gen_source_cd varchar(7) NOT NULL,
    arp_nameplate_capacity numeric(7,3),
    other_nameplate_capacity numeric(7,3),
    utility_ind numeric(1,0),
    prime_mover_type_cd varchar(7),
    gen_capacity_factor numeric(5,3),
    online_year numeric(4,0),
    eia_year numeric(4,0),
    unitids varchar(4000),
    historical_unitids varchar(4000),
    industry_edit_list varchar(1000),
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    annual_generator_ind numeric(1,0) NOT NULL DEFAULT 0,
    PRIMARY KEY (gen_ws_id)
);
COMMENT ON TABLE camdws.generator_ws
    IS 'Identifies industrial boilers or electric generating units.';
COMMENT ON COLUMN camdws.generator_ws.gen_ws_id
    IS 'unique id.';
COMMENT ON COLUMN camdws.generator_ws.workspace_session_id
    IS 'FK to parent workspace session.';
COMMENT ON COLUMN camdws.generator_ws.ws_added_ind
    IS '1 (true) if record was added during the WS session, other, otherwise 0.';
COMMENT ON COLUMN camdws.generator_ws.ws_updated_ind
    IS '1 (true) if record was updated during the WS session, other, otherwise 0.';
COMMENT ON COLUMN camdws.generator_ws.gen_id
    IS 'Identity key for GENERATOR table.';
COMMENT ON COLUMN camdws.generator_ws.fac_id
    IS 'FACILITY ID identity key.';
COMMENT ON COLUMN camdws.generator_ws.genid
    IS 'Public identifier used for GENERATOR as reported to EIA and for New Unit Exemption purposes.';
COMMENT ON COLUMN camdws.generator_ws.gen_source_cd
    IS 'Source code of GENERATOR data.';
COMMENT ON COLUMN camdws.generator_ws.arp_nameplate_capacity
    IS 'Design nameplate capacity, in megawatts, of the GENERATOR.';
COMMENT ON COLUMN camdws.generator_ws.other_nameplate_capacity
    IS 'Nameplate capacity, in megawatts, of the GENERATOR as applicable to other programs such as CAIR.';
COMMENT ON COLUMN camdws.generator_ws.utility_ind
    IS 'Identifies whether a GENERATOR is a utility or a non-utility.';
COMMENT ON COLUMN camdws.generator_ws.prime_mover_type_cd
    IS 'Type, such as combined cycle, steam turbine, etc., of a GENERATOR.';
COMMENT ON COLUMN camdws.generator_ws.gen_capacity_factor
    IS 'Capacity factor based on actual operations.';
COMMENT ON COLUMN camdws.generator_ws.online_year
    IS 'Four digit year that the GENERATOR came online.';
COMMENT ON COLUMN camdws.generator_ws.eia_year
    IS 'The year for which EIA identification information is provided.';
COMMENT ON COLUMN camdws.generator_ws.unitids
    IS 'List of Active Unit Names associated with this generator.';
COMMENT ON COLUMN camdws.generator_ws.historical_unitids
    IS 'List of Historical Unit Names associated with this generator.';
COMMENT ON COLUMN camdws.generator_ws.industry_edit_list
    IS 'List of fields editable by an industry user.';
COMMENT ON COLUMN camdws.generator_ws.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camdws.generator_ws.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camdws.generator_ws.update_date
    IS 'Date of the last record update.';
COMMENT ON COLUMN camdws.generator_ws.annual_generator_ind
    IS '1 (true) if GENERATOR has annual generator data, otherwise 0 (false).';