CREATE TABLE IF NOT EXISTS camdws.general_account_attribute_ws
(
    account_ws_id bigint GENERATED BY DEFAULT AS IDENTITY,
    workspace_session_id numeric(38,0) NOT NULL,
    ws_added_ind numeric(1,0) NOT NULL,
    ws_updated_ind numeric(1,0) NOT NULL,
    account_id numeric(38,0) NOT NULL,
    form_received_date timestamp without time zone,
    broker_ind numeric(1,0) NOT NULL DEFAULT 0,
    broker_transfer_ind numeric(1,0) NOT NULL DEFAULT 0,
    broker_hold_ind numeric(1,0) NOT NULL DEFAULT 0,
    broker_other_ind numeric(1,0) NOT NULL DEFAULT 0,
    utility_ind numeric(1,0) NOT NULL DEFAULT 0,
    non_utility_ind numeric(1,0) NOT NULL DEFAULT 0,
    coal_ind numeric(1,0) NOT NULL DEFAULT 0,
    oil_ind numeric(1,0) NOT NULL DEFAULT 0,
    gas_ind numeric(1,0) NOT NULL DEFAULT 0,
    other_fuel_ind numeric(1,0) NOT NULL DEFAULT 0,
    pollution_ind numeric(1,0) NOT NULL DEFAULT 0,
    consumer_ind numeric(1,0) NOT NULL DEFAULT 0,
    environment_ind numeric(1,0) NOT NULL DEFAULT 0,
    public_other_ind numeric(1,0) NOT NULL DEFAULT 0,
    industrial_boiler_ind numeric(1,0) NOT NULL DEFAULT 0,
    other_ind numeric(1,0) NOT NULL DEFAULT 0,
    other_description varchar(1000),
    PRIMARY KEY (account_ws_id)
);
COMMENT ON TABLE camdws.general_account_attribute_ws
    IS 'Lists account information for general accounts.';
COMMENT ON COLUMN camdws.general_account_attribute_ws.account_ws_id
    IS 'unique id.';
COMMENT ON COLUMN camdws.general_account_attribute_ws.workspace_session_id
    IS 'FK to parent workspace session.';
COMMENT ON COLUMN camdws.general_account_attribute_ws.ws_added_ind
    IS '1 (true) if record was added during the WS session, other, otherwise 0.';
COMMENT ON COLUMN camdws.general_account_attribute_ws.ws_updated_ind
    IS '1 (true) if record was updated during the WS session, other, otherwise 0.';
COMMENT ON COLUMN camdws.general_account_attribute_ws.account_id
    IS 'Identity key for account table.';
COMMENT ON COLUMN camdws.general_account_attribute_ws.form_received_date
    IS 'Date account form was received.';
COMMENT ON COLUMN camdws.general_account_attribute_ws.broker_ind
    IS 'Indicates whether the authorized account rep is employed by an allowance brokerage firm.';
COMMENT ON COLUMN camdws.general_account_attribute_ws.broker_transfer_ind
    IS 'Indicates if the account is used to transfer allowances between clients.';
COMMENT ON COLUMN camdws.general_account_attribute_ws.broker_hold_ind
    IS 'Indicates if the account will be used to hold allowances for investment purposes.';
COMMENT ON COLUMN camdws.general_account_attribute_ws.broker_other_ind
    IS 'Indicates if the account will be used for other purposes.';
COMMENT ON COLUMN camdws.general_account_attribute_ws.utility_ind
    IS 'Indicates account owner represents a utility.';
COMMENT ON COLUMN camdws.general_account_attribute_ws.non_utility_ind
    IS 'Indicates account owner represents a non utility generator of electricity.';
COMMENT ON COLUMN camdws.general_account_attribute_ws.coal_ind
    IS 'Indicates account owner represents a fuel supplier that supplies coal.';
COMMENT ON COLUMN camdws.general_account_attribute_ws.oil_ind
    IS 'Indicates account owner represents a fuel supplier that supplies oil.';
COMMENT ON COLUMN camdws.general_account_attribute_ws.gas_ind
    IS 'Indicates account owner represents a fuel supplier that supplies gas.';
COMMENT ON COLUMN camdws.general_account_attribute_ws.other_fuel_ind
    IS 'Indicates account owner represents a fuel supplier that supplies other fuel types.';
COMMENT ON COLUMN camdws.general_account_attribute_ws.pollution_ind
    IS 'Indicates account owner represents a pollution control equipment business.';
COMMENT ON COLUMN camdws.general_account_attribute_ws.consumer_ind
    IS 'Indicates account owner represents a consumer public interest group.';
COMMENT ON COLUMN camdws.general_account_attribute_ws.environment_ind
    IS 'Indicates account owner represents an environmental public interest group.';
COMMENT ON COLUMN camdws.general_account_attribute_ws.public_other_ind
    IS 'Indicates account owner represents another type of public interest group.';
COMMENT ON COLUMN camdws.general_account_attribute_ws.industrial_boiler_ind
    IS 'Indicates account owner represents an industrial boiler.';
COMMENT ON COLUMN camdws.general_account_attribute_ws.other_ind
    IS 'Indicates account owner represents a different type of business.';
COMMENT ON COLUMN camdws.general_account_attribute_ws.other_description
    IS 'Text description of other business represented by account owner.';