CREATE TABLE IF NOT EXISTS camdws.person_ws
(
    person_ws_id bigint GENERATED BY DEFAULT AS IDENTITY,
    workspace_session_id numeric(38,0) NOT NULL,
    ws_added_ind numeric(1,0) NOT NULL,
    ws_updated_ind numeric(1,0) NOT NULL,
    ppl_id numeric(38,0) NOT NULL,
    person_type_cd varchar(7) NOT NULL,
    company_id numeric(38,0),
    agency_id numeric(38,0),
    email_address varchar(70),
    login varchar(8),
    password varchar(300),
    password_change_date timestamp without time zone,
    initial_password_ind numeric(1,0) DEFAULT 0,
    password_locked_ind numeric(1,0) DEFAULT 0,
    password_failed_cnt numeric(1,0) DEFAULT 0,
    reset_password_code varchar(100),
    reset_password_request_date timestamp without time zone,
    reset_password_fail_cnt numeric(1,0),
    security_group_cd varchar(7),
    subscriber_ind numeric(1,0) DEFAULT 0,
    hide_phishing_ind numeric(1,0) DEFAULT 0,
    consultant_ind numeric(1,0) DEFAULT 0,
    email_removed_date timestamp without time zone,
    ppl_comment varchar(4000),
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    acr_id numeric,
    cromerr_failed_cnt numeric(1,0) DEFAULT 0,
    cromerr_locked_ind numeric(1,0) DEFAULT 0,
    PRIMARY KEY (person_ws_id)
);
COMMENT ON TABLE camdws.person_ws
    IS 'The PERSON_WS table stores information on all AGENTS, REPS, STAFF, and CONTACTS IN WORKSPACE.';
COMMENT ON COLUMN camdws.person_ws.person_ws_id
    IS 'unique id.';
COMMENT ON COLUMN camdws.person_ws.workspace_session_id
    IS 'FK to parent workspace session.';
COMMENT ON COLUMN camdws.person_ws.ws_added_ind
    IS '1 (true) if record was added during the WS session, other, otherwise 0.';
COMMENT ON COLUMN camdws.person_ws.ws_updated_ind
    IS '1 (true) if record was updated during the WS session, other, otherwise 0.';
COMMENT ON COLUMN camdws.person_ws.ppl_id
    IS 'PPL_ID from the loaded PERSON record OR the next available S_PERSON sequence value for a record created during the workspace session.';
COMMENT ON COLUMN camdws.person_ws.person_type_cd
    IS 'Identifies the type of user in system.';
COMMENT ON COLUMN camdws.person_ws.company_id
    IS 'COMPANY identity key.';
COMMENT ON COLUMN camdws.person_ws.agency_id
    IS 'AGENCY identity key.';
COMMENT ON COLUMN camdws.person_ws.email_address
    IS 'The email address for an individual. ';
COMMENT ON COLUMN camdws.person_ws.login
    IS 'The User logon name or ID for CAMD databases assigned by CAMD to CONTACT and STAFF.';
COMMENT ON COLUMN camdws.person_ws.password
    IS 'The encrypted User Password assigned by CAMD and maintained by the CONTACT or STAFF to authenticate access to CAMD databases.';
COMMENT ON COLUMN camdws.person_ws.password_change_date
    IS 'Date user changed password.';
COMMENT ON COLUMN camdws.person_ws.initial_password_ind
    IS 'Indicates whether the user needs to change their password on next login.';
COMMENT ON COLUMN camdws.person_ws.password_locked_ind
    IS 'Identifies whether the user is locked out of the application for wrong password attempts.';
COMMENT ON COLUMN camdws.person_ws.password_failed_cnt
    IS 'Number of failed login attempts since last successful login attempt.';
COMMENT ON COLUMN camdws.person_ws.reset_password_code
    IS 'Unique code requested by user to use to reset their password.';
COMMENT ON COLUMN camdws.person_ws.reset_password_request_date
    IS 'Date the reset password code was requested.';
COMMENT ON COLUMN camdws.person_ws.reset_password_fail_cnt
    IS 'Number of times the user has entered the incorrect reset password code.';
COMMENT ON COLUMN camdws.person_ws.security_group_cd
    IS 'Indicates the person''s access group.';
COMMENT ON COLUMN camdws.person_ws.subscriber_ind
    IS 'Indicates the submission status the person''s subscriber agreement.';
COMMENT ON COLUMN camdws.person_ws.hide_phishing_ind
    IS 'Indicates if the user has chosen to hide the phishing notice.';
COMMENT ON COLUMN camdws.person_ws.consultant_ind
    IS 'Indicates if the user is identified as a consultant and has access to the Consultant Access module in CBS.';
COMMENT ON COLUMN camdws.person_ws.email_removed_date
    IS 'Date, if any, when CAMD removed a users email address. Null indicates not removed.';
COMMENT ON COLUMN camdws.person_ws.ppl_comment
    IS 'Text description of the PERSON record.';
COMMENT ON COLUMN camdws.person_ws.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camdws.person_ws.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camdws.person_ws.update_date
    IS 'Date of the last record update.';
COMMENT ON COLUMN camdws.person_ws.acr_id
    IS 'Identity key for ACCOUNT REQUEST.';
COMMENT ON COLUMN camdws.person_ws.cromerr_failed_cnt
    IS 'Number of failed CROMERR/challenge answer attempts since last successful attempt.';
COMMENT ON COLUMN camdws.person_ws.cromerr_locked_ind
    IS 'Identifies whether the user is locked out of the application for wrong challenge answers.';