CREATE TABLE IF NOT EXISTS camdws.plant_person_ws
(
    plant_person_ws_id bigint GENERATED BY DEFAULT AS IDENTITY,
    workspace_session_id numeric(38,0) NOT NULL,
    ws_added_ind numeric(1,0) NOT NULL,
    ws_updated_ind numeric(1,0) NOT NULL,
    fac_ppl_id numeric(38,0) NOT NULL,
    fac_id numeric(38,0),
    ppl_id numeric(38,0) NOT NULL,
    person_type_group_cd varchar(7) NOT NULL,
    responsibility_id varchar(3) NOT NULL,
    prg_cd varchar(8),
    begin_date timestamp without time zone NOT NULL,
    end_date timestamp without time zone,
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (plant_person_ws_id)
);
COMMENT ON TABLE camdws.plant_person_ws
    IS 'Links facilities to people (representatives, contacts, staff) FOR WORKSPACE.';
COMMENT ON COLUMN camdws.plant_person_ws.plant_person_ws_id
    IS 'unique id.';
COMMENT ON COLUMN camdws.plant_person_ws.workspace_session_id
    IS 'FK to parent workspace session.';
COMMENT ON COLUMN camdws.plant_person_ws.ws_added_ind
    IS '1 (true) if record was added during the WS session, other, otherwise 0.';
COMMENT ON COLUMN camdws.plant_person_ws.ws_updated_ind
    IS '1 (true) if record was updated during the WS session, other, otherwise 0.';
COMMENT ON COLUMN camdws.plant_person_ws.fac_ppl_id
    IS 'FAC_PPL_ID from the loaded PLANT_PERSON record OR the next available S_PLANT_PERSON sequence value for a record created during the workspace session.';
COMMENT ON COLUMN camdws.plant_person_ws.fac_id
    IS 'Identity key for FACILITY table.';
COMMENT ON COLUMN camdws.plant_person_ws.ppl_id
    IS 'PEOPLE identity key.';
COMMENT ON COLUMN camdws.plant_person_ws.person_type_group_cd
    IS 'The code that indicates the person type group for person type.';
COMMENT ON COLUMN camdws.plant_person_ws.responsibility_id
    IS 'Responsibility key.';
COMMENT ON COLUMN camdws.plant_person_ws.prg_cd
    IS 'Code used to identify regulatory PROGRAM applicable to UNIT.';
COMMENT ON COLUMN camdws.plant_person_ws.begin_date
    IS 'Date on which a relationship or an activity began. ';
COMMENT ON COLUMN camdws.plant_person_ws.end_date
    IS 'Date on which a relationship or an activity ended.';
COMMENT ON COLUMN camdws.plant_person_ws.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty. Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camdws.plant_person_ws.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camdws.plant_person_ws.update_date
    IS 'Date of the last record update.';