CREATE TABLE IF NOT EXISTS camdws.plant_alias_ws
(
    plant_alias_ws_id bigint GENERATED BY DEFAULT AS IDENTITY,
    workspace_session_id numeric(38,0) NOT NULL,
    ws_added_ind numeric(1,0) NOT NULL,
    ws_updated_ind numeric(1,0) NOT NULL,
    plant_alias_id numeric(38,0) NOT NULL,
    fac_id numeric(38,0) NOT NULL,
    alias_type varchar(7) NOT NULL,
    alias_date timestamp without time zone,
    old_value varchar(40),
    ampd_ind numeric(1,0) NOT NULL DEFAULT 0,
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (plant_alias_ws_id)
);
COMMENT ON TABLE camdws.plant_alias_ws
    IS 'Identifies an electric generating or industrial facility consisting of UNITS known to or potentially subject to a trading program for workspace.';
COMMENT ON COLUMN camdws.plant_alias_ws.plant_alias_ws_id
    IS 'unique id.';
COMMENT ON COLUMN camdws.plant_alias_ws.workspace_session_id
    IS 'FK to parent workspace session.';
COMMENT ON COLUMN camdws.plant_alias_ws.ws_added_ind
    IS '1 (true) if record was added during the WS session, other, otherwise 0.';
COMMENT ON COLUMN camdws.plant_alias_ws.ws_updated_ind
    IS '1 (true) if record was updated during the WS session, other, otherwise 0.';
COMMENT ON COLUMN camdws.plant_alias_ws.plant_alias_id
    IS 'PLANT_ALIAS ID identity key.';
COMMENT ON COLUMN camdws.plant_alias_ws.fac_id
    IS 'FACILITY ID identity key.';
COMMENT ON COLUMN camdws.plant_alias_ws.alias_type
    IS 'Type of alias, NAME (PLANT) or ORIS (ORIS_CODE).';
COMMENT ON COLUMN camdws.plant_alias_ws.alias_date
    IS 'Date on which FACILITY or UNIT alias was created.';
COMMENT ON COLUMN camdws.plant_alias_ws.old_value
    IS 'Old oris code or name of FACILITY, as reported by representative on Certification of Representation forms or equivalent.';
COMMENT ON COLUMN camdws.plant_alias_ws.ampd_ind
    IS 'Indicates if the plant alias should be shown in AMPD.';
COMMENT ON COLUMN camdws.plant_alias_ws.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camdws.plant_alias_ws.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camdws.plant_alias_ws.update_date
    IS 'Date of the last record update.';