CREATE TABLE IF NOT EXISTS camdws.plant_ws
(
    plant_ws_id bigint GENERATED BY DEFAULT AS IDENTITY,
    workspace_session_id numeric(38,0) NOT NULL,
    ws_added_ind numeric(1,0) NOT NULL,
    ws_updated_ind numeric(1,0) NOT NULL,
    fac_id numeric(38,0) NOT NULL,
    oris_code numeric(6,0),
    facility_name varchar(40) NOT NULL,
    description varchar(4000),
    state varchar(2) NOT NULL,
    county_cd varchar(8),
    sic_code numeric(4,0),
    epa_region numeric(2,0),
    nerc_region varchar(5),
    airsid varchar(10),
    findsid varchar(12),
    stateid varchar(15),
    latitude numeric(7,4),
    longitude numeric(8,4),
    frs_id varchar(12),
    payee_id numeric(6,0),
    permit_exp_date timestamp without time zone,
    latlon_source varchar(200),
    tribal_land_cd varchar(7),
    first_ecmps_rpt_period_id numeric(38,0),
    industry_edit_list varchar(1000),
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (plant_ws_id)
);
COMMENT ON TABLE camdws.plant_ws
    IS 'Identifies an electric generating or industrial facility consisting of UNITS known to or potentially subject to a trading program for workspace.';
COMMENT ON COLUMN camdws.plant_ws.plant_ws_id
    IS 'unique id.';
COMMENT ON COLUMN camdws.plant_ws.workspace_session_id
    IS 'FK to parent workspace session.';
COMMENT ON COLUMN camdws.plant_ws.ws_added_ind
    IS '1 (true) if record was added during the WS session, other, otherwise 0.';
COMMENT ON COLUMN camdws.plant_ws.ws_updated_ind
    IS '1 (true) if record was updated during the WS session, other, otherwise 0.';
COMMENT ON COLUMN camdws.plant_ws.fac_id
    IS 'FACILITY ID identity key.';
COMMENT ON COLUMN camdws.plant_ws.oris_code
    IS 'EIA-assigned identifier or FACILITY ID assigned by CAMD (if EIA number is not applicable).';
COMMENT ON COLUMN camdws.plant_ws.facility_name
    IS 'Name of FACILITY, as reported by representative on Certification of Representation forms or equivalent.';
COMMENT ON COLUMN camdws.plant_ws.description
    IS 'Text description of FACILITY or FACILITY configuration.';
COMMENT ON COLUMN camdws.plant_ws.state
    IS 'State abbreviation for state in which FACILITY, CONTACT, AGENCY, ACCOUNT REQUEST, PROGRAM, or STAFF is located. ';
COMMENT ON COLUMN camdws.plant_ws.county_cd
    IS 'Concatenation of State and county code.';
COMMENT ON COLUMN camdws.plant_ws.epa_region
    IS 'The EPA Region in which a FACILITY is located.';
COMMENT ON COLUMN camdws.plant_ws.nerc_region
    IS 'Code for one of thirteen regions as specified by the  North American Electric Reliability Council.';
COMMENT ON COLUMN camdws.plant_ws.airsid
    IS 'The identifier for the FACILITY in the AIRS Facility Subsystem (AFS).';
COMMENT ON COLUMN camdws.plant_ws.findsid
    IS 'Cross-reference field for FINDS database.';
COMMENT ON COLUMN camdws.plant_ws.stateid
    IS 'The State identification number for a FACILITY or UNIT.';
COMMENT ON COLUMN camdws.plant_ws.latitude
    IS 'The latitude at which a FACILITY is located.';
COMMENT ON COLUMN camdws.plant_ws.longitude
    IS 'The longitude at which a FACILITY is located.';
COMMENT ON COLUMN camdws.plant_ws.frs_id
    IS 'The cross-media Facility Registry System identifier for a FACILITY.';
COMMENT ON COLUMN camdws.plant_ws.payee_id
    IS 'ID of a payee entity.';
COMMENT ON COLUMN camdws.plant_ws.permit_exp_date
    IS 'Date permit expires.';
COMMENT ON COLUMN camdws.plant_ws.latlon_source
    IS 'Source of latitude/longitude data.';
COMMENT ON COLUMN camdws.plant_ws.tribal_land_cd
    IS 'Tribal Land abbreviation for tribal land in which FACILITY, CONTACT, AGENCY, ACCOUNT REQUEST, PROGRAM or STAFF is located.';
COMMENT ON COLUMN camdws.plant_ws.first_ecmps_rpt_period_id
    IS 'Identity key from REPORTING_PERIOD for the first quarter a facility reports via ECMPS.';
COMMENT ON COLUMN camdws.plant_ws.industry_edit_list
    IS 'List of fields editable by an industry user.';
COMMENT ON COLUMN camdws.plant_ws.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camdws.plant_ws.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camdws.plant_ws.update_date
    IS 'Date of the last record update.';