CREATE TABLE IF NOT EXISTS camdws.rep_agent_ws
(
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    workspace_session_id numeric(38,0) NOT NULL,
    rep_agent_id numeric(38,0) NOT NULL,
    rep_agent_unit_id numeric(38,0),
    agent_id numeric(38,0) NOT NULL,
    agent_search_name varchar(100) NOT NULL,
    agent_display_name varchar(100) NOT NULL,
    agent_sort_name varchar(100) NOT NULL,
    company_id numeric(38,0),
    company_display_name varchar(150),
    company_sort_name varchar(150),
    rep_id numeric(38,0) NOT NULL,
    rep_search_name varchar(100) NOT NULL,
    rep_display_name varchar(100) NOT NULL,
    rep_sort_name varchar(100) NOT NULL,
    relation_type_display_name varchar(100) NOT NULL,
    relation_type_sort_name varchar(100) NOT NULL,
    plant_display_name varchar(150) NOT NULL,
    plant_sort_name varchar(150) NOT NULL,
    begin_date timestamp without time zone,
    end_date timestamp without time zone,
    relation_type_cd varchar(25) NOT NULL,
    unit_id numeric(38,0),
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    ws_added_ind numeric(1,0) NOT NULL,
    ws_updated_ind numeric(1,0) NOT NULL,
    fac_id numeric(38,0),
    account_id numeric(38,0),
    PRIMARY KEY (id)
);
COMMENT ON TABLE camdws.rep_agent_ws
    IS 'Table is the combination of the old contact_relation_WS and agent_unit_access_WS. This table should contain all of the data in those two tables and combine them together in order to create an easily accessible table.';
COMMENT ON COLUMN camdws.rep_agent_ws.id
    IS 'unique id.';
COMMENT ON COLUMN camdws.rep_agent_ws.workspace_session_id
    IS 'FK to parent workspace session.';
COMMENT ON COLUMN camdws.rep_agent_ws.rep_agent_id
    IS 'Identity key for CONTACT_RELATION table.';
COMMENT ON COLUMN camdws.rep_agent_ws.rep_agent_unit_id
    IS 'Identity key for AGENT_UNIT_ACCESS table';
COMMENT ON COLUMN camdws.rep_agent_ws.agent_id
    IS 'PEOPLE ID for agent.';
COMMENT ON COLUMN camdws.rep_agent_ws.agent_search_name
    IS 'PEOPLE search name for agent.';
COMMENT ON COLUMN camdws.rep_agent_ws.agent_display_name
    IS 'PEOPLE display name for agent.';
COMMENT ON COLUMN camdws.rep_agent_ws.agent_sort_name
    IS 'PEOPLE sort name for agent.';
COMMENT ON COLUMN camdws.rep_agent_ws.company_id
    IS 'ID for agent''s company (COMPANY_WS.COMPANY_ID).';
COMMENT ON COLUMN camdws.rep_agent_ws.company_display_name
    IS 'Display name for agent''s company (COMPANY_WS.COMPANY_NAME).';
COMMENT ON COLUMN camdws.rep_agent_ws.company_sort_name
    IS 'Sort name for agent''s company (Upper of COMPANY_WS.COMPANY_NAME).';
COMMENT ON COLUMN camdws.rep_agent_ws.rep_id
    IS 'PEOPLE ID for rep.';
COMMENT ON COLUMN camdws.rep_agent_ws.rep_search_name
    IS 'PEOPLE search name for rep.';
COMMENT ON COLUMN camdws.rep_agent_ws.rep_display_name
    IS 'PEOPLE display name for rep.';
COMMENT ON COLUMN camdws.rep_agent_ws.rep_sort_name
    IS 'PEOPLE display name for rep.';
COMMENT ON COLUMN camdws.rep_agent_ws.relation_type_display_name
    IS 'Display name for RELATION_TYPE_CD.';
COMMENT ON COLUMN camdws.rep_agent_ws.relation_type_sort_name
    IS 'Sort name for RELATION_TYPE_CD.';
COMMENT ON COLUMN camdws.rep_agent_ws.plant_display_name
    IS 'PLANT display name for agents plant';
COMMENT ON COLUMN camdws.rep_agent_ws.plant_sort_name
    IS 'PLANT sort name for agents plant';
COMMENT ON COLUMN camdws.rep_agent_ws.begin_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camdws.rep_agent_ws.end_date
    IS 'Date of the last record update.';
COMMENT ON COLUMN camdws.rep_agent_ws.relation_type_cd
    IS 'Code look up for relation_type_cd table.';
COMMENT ON COLUMN camdws.rep_agent_ws.unit_id
    IS 'Id of the unit related to this relation';
COMMENT ON COLUMN camdws.rep_agent_ws.userid
    IS 'Id of last person who edited table';
COMMENT ON COLUMN camdws.rep_agent_ws.add_date
    IS 'Date added to WS';
COMMENT ON COLUMN camdws.rep_agent_ws.update_date
    IS 'Date updated in WS';
COMMENT ON COLUMN camdws.rep_agent_ws.ws_added_ind
    IS 'Was this added to the WS?.';
COMMENT ON COLUMN camdws.rep_agent_ws.ws_updated_ind
    IS 'Was this updated in the WS?';
COMMENT ON COLUMN camdws.rep_agent_ws.fac_id
    IS 'Facility ID for the associated plant.';
COMMENT ON COLUMN camdws.rep_agent_ws.account_id
    IS 'Account ID for the associated account.';