CREATE TABLE IF NOT EXISTS camdws.unit_program_ws
(
    up_ws_id bigint GENERATED BY DEFAULT AS IDENTITY,
    workspace_session_id numeric(38,0) NOT NULL,
    ws_added_ind numeric(1,0) NOT NULL,
    ws_updated_ind numeric(1,0) NOT NULL,
    up_id numeric(38,0) NOT NULL,
    unit_id numeric(38,0) NOT NULL,
    prg_id numeric(38,0) NOT NULL,
    prg_cd varchar(7),
    class_cd varchar(7),
    app_status_cd varchar(7),
    optin_ind numeric(1,0) NOT NULL DEFAULT 0,
    def_ind numeric(1,0) NOT NULL DEFAULT 0,
    def_ind_orig numeric(1,0) NOT NULL DEFAULT 0,
    def_end_date timestamp without time zone,
    up_comment varchar(1000),
    unit_monitor_cert_begin_date timestamp without time zone,
    unit_monitor_cert_deadline timestamp without time zone,
    emissions_recording_begin_date timestamp without time zone,
    trueup_begin_year numeric(4,0),
    unit_mntr_cert_begin_date_orig timestamp without time zone,
    unit_mntr_cert_deadline_orig timestamp without time zone,
    emission_recrd_begin_date_orig timestamp without time zone,
    trueup_begin_year_orig numeric(4,0),
    end_date timestamp without time zone,
    non_egu_ind numeric(1,0) NOT NULL DEFAULT 0,
    nonstandard_cd varchar(7),
    nonstandard_comment varchar(1000),
    unitid varchar(6) NOT NULL,
    exemption_type_description varchar(1000),
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (up_ws_id)
);
COMMENT ON TABLE camdws.unit_program_ws
    IS 'Identifies industrial boilers or electric generating units.';
COMMENT ON COLUMN camdws.unit_program_ws.up_ws_id
    IS 'unique id.';
COMMENT ON COLUMN camdws.unit_program_ws.workspace_session_id
    IS 'FK to parent workspace session.';
COMMENT ON COLUMN camdws.unit_program_ws.ws_added_ind
    IS '1 (true) if record was added during the WS session, other, otherwise 0.';
COMMENT ON COLUMN camdws.unit_program_ws.ws_updated_ind
    IS '1 (true) if record was added during the WS session, other, otherwise 0.';
COMMENT ON COLUMN camdws.unit_program_ws.up_id
    IS 'UNIT and PROGRAM relationship identity key.';
COMMENT ON COLUMN camdws.unit_program_ws.unit_id
    IS 'Identity key for UNIT table.';
COMMENT ON COLUMN camdws.unit_program_ws.prg_id
    IS 'PROGRAM identity key.';
COMMENT ON COLUMN camdws.unit_program_ws.prg_cd
    IS 'Code used to identify regulatory PROGRAM applicable to UNIT.';
COMMENT ON COLUMN camdws.unit_program_ws.class_cd
    IS 'The regulatory category with respect to a specific PROGRAM for a UNIT.';
COMMENT ON COLUMN camdws.unit_program_ws.app_status_cd
    IS 'Status of applicability (Unknown, Interim, Final).';
COMMENT ON COLUMN camdws.unit_program_ws.optin_ind
    IS 'Indicator that UNIT is an opt-in unit.';
COMMENT ON COLUMN camdws.unit_program_ws.def_ind
    IS 'An indicator that a UNIT has not operated since the day on which it was affected by the PROGRAM.';
COMMENT ON COLUMN camdws.unit_program_ws.def_ind_orig
    IS 'Deferred indicator from UNIT_PROGRAM at beginning of workspace session.';
COMMENT ON COLUMN camdws.unit_program_ws.def_end_date
    IS 'The date on which the UNIT became operational after the program participation date and was therefore subject to the PROGRAM''s regulatory requirements.';
COMMENT ON COLUMN camdws.unit_program_ws.up_comment
    IS 'Comment for unit program record.';
COMMENT ON COLUMN camdws.unit_program_ws.unit_monitor_cert_begin_date
    IS 'Date beginning timeline for completion of certification testing.';
COMMENT ON COLUMN camdws.unit_program_ws.unit_monitor_cert_deadline
    IS 'Date by which monitor certification must be completed.';
COMMENT ON COLUMN camdws.unit_program_ws.emissions_recording_begin_date
    IS 'Date a unit first begins recording hourly emissions data.';
COMMENT ON COLUMN camdws.unit_program_ws.trueup_begin_year
    IS 'First year the unit was expected for true up.';
COMMENT ON COLUMN camdws.unit_program_ws.unit_mntr_cert_begin_date_orig
    IS 'UMCBD value at start of workspace session.';
COMMENT ON COLUMN camdws.unit_program_ws.unit_mntr_cert_deadline_orig
    IS 'UMCD value at start of workspace session.';
COMMENT ON COLUMN camdws.unit_program_ws.emission_recrd_begin_date_orig
    IS 'ERBD value at start of workspace session.';
COMMENT ON COLUMN camdws.unit_program_ws.trueup_begin_year_orig
    IS 'TBY value at start of workspace session.';
COMMENT ON COLUMN camdws.unit_program_ws.end_date
    IS 'Date on which a relationship or an activity ended.';
COMMENT ON COLUMN camdws.unit_program_ws.non_egu_ind
    IS 'Identifies whether unit is electric-generating.';
COMMENT ON COLUMN camdws.unit_program_ws.nonstandard_cd
    IS 'Code used to identify type of nonstandard unit program situation.';
COMMENT ON COLUMN camdws.unit_program_ws.nonstandard_comment
    IS 'Comment for nonstandard unit program situation.';
COMMENT ON COLUMN camdws.unit_program_ws.exemption_type_description
    IS 'Description of current exemption affecting this unit.';
COMMENT ON COLUMN camdws.unit_program_ws.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camdws.unit_program_ws.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camdws.unit_program_ws.update_date
    IS 'Date of the last record update.';