CREATE TABLE IF NOT EXISTS camdws.unit_owner_ws
(
    unit_owner_ws_id bigint GENERATED BY DEFAULT AS IDENTITY,
    workspace_session_id numeric(38,0) NOT NULL,
    ws_added_ind numeric(1,0) NOT NULL,
    ws_updated_ind numeric(1,0) NOT NULL,
    unit_owner_id numeric(38,0) NOT NULL,
    unit_id numeric(38,0) NOT NULL,
    unitid varchar(6) NOT NULL,
    comp_id numeric(38,0) NOT NULL,
    company_name varchar(100) NOT NULL,
    owner_type_cd varchar(7) NOT NULL,
    begin_date timestamp without time zone DEFAULT '01/Jan/1995',
    end_date timestamp without time zone,
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (unit_owner_ws_id)
);
COMMENT ON TABLE camdws.unit_owner_ws
    IS 'Used to track operating status for a unit.';
COMMENT ON COLUMN camdws.unit_owner_ws.unit_owner_ws_id
    IS 'Identity key.';
COMMENT ON COLUMN camdws.unit_owner_ws.workspace_session_id
    IS 'FK to parent workspace session.';
COMMENT ON COLUMN camdws.unit_owner_ws.ws_added_ind
    IS '1 (true) if record was added during the WS session, other, otherwise 0.';
COMMENT ON COLUMN camdws.unit_owner_ws.ws_updated_ind
    IS '1 (true) if record was updated during the WS session, other, otherwise 0.';
COMMENT ON COLUMN camdws.unit_owner_ws.unit_owner_id
    IS 'Identity key for UNIT_OWNER table.';
COMMENT ON COLUMN camdws.unit_owner_ws.unit_id
    IS 'Identity key for UNIT table.';
COMMENT ON COLUMN camdws.unit_owner_ws.unitid
    IS 'Public identifier used for the UNIT table for PROGRAM identification purposes.';
COMMENT ON COLUMN camdws.unit_owner_ws.comp_id
    IS 'Identity key for COMPANY table.';
COMMENT ON COLUMN camdws.unit_owner_ws.company_name
    IS 'NAME field from COMPANY table.';
COMMENT ON COLUMN camdws.unit_owner_ws.owner_type_cd
    IS 'Indicates type of owner, operator or both.';
COMMENT ON COLUMN camdws.unit_owner_ws.begin_date
    IS 'Date on which a relationship or an activity began.';
COMMENT ON COLUMN camdws.unit_owner_ws.end_date
    IS 'Date on which a relationship or an activity ended.';
COMMENT ON COLUMN camdws.unit_owner_ws.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty. Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camdws.unit_owner_ws.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camdws.unit_owner_ws.update_date
    IS 'Date of the last record update.';