CREATE TABLE IF NOT EXISTS camdws.unit_alias_ws
(
    unit_alias_ws_id bigint GENERATED BY DEFAULT AS IDENTITY,
    workspace_session_id numeric(38,0) NOT NULL,
    ws_added_ind numeric(1,0) NOT NULL,
    ws_updated_ind numeric(1,0) NOT NULL,
    unit_alias_id numeric(38,0) NOT NULL,
    unit_id numeric(38,0) NOT NULL,
    old_unitid varchar(6) NOT NULL,
    alias_date timestamp without time zone NOT NULL,
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (unit_alias_ws_id)
);
COMMENT ON TABLE camdws.unit_alias_ws
    IS 'Identifies an electric generating or industrial facility consisting of UNITS known to or potentially subject to a trading program for workspace.';
COMMENT ON COLUMN camdws.unit_alias_ws.unit_alias_ws_id
    IS 'unique id.';
COMMENT ON COLUMN camdws.unit_alias_ws.workspace_session_id
    IS 'FK to parent workspace session.';
COMMENT ON COLUMN camdws.unit_alias_ws.ws_added_ind
    IS '1 (true) if record was added during the WS session, other, otherwise 0.';
COMMENT ON COLUMN camdws.unit_alias_ws.ws_updated_ind
    IS '1 (true) if record was updated during the WS session, other, otherwise 0.';
COMMENT ON COLUMN camdws.unit_alias_ws.unit_alias_id
    IS 'UNIT_ALIAS ID identity key.';
COMMENT ON COLUMN camdws.unit_alias_ws.unit_id
    IS 'Identity key for UNIT table.';
COMMENT ON COLUMN camdws.unit_alias_ws.old_unitid
    IS 'The old UNITID for the UNIT.';
COMMENT ON COLUMN camdws.unit_alias_ws.alias_date
    IS 'Date on which FACILITY or UNIT alias was created.';
COMMENT ON COLUMN camdws.unit_alias_ws.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camdws.unit_alias_ws.add_date
    IS 'Date the record was created.';