CREATE TABLE IF NOT EXISTS camdws.unit_generator_ws
(
    unit_gen_ws_id bigint GENERATED BY DEFAULT AS IDENTITY,
    workspace_session_id numeric(38,0) NOT NULL,
    ws_added_ind numeric(1,0) NOT NULL,
    ws_updated_ind numeric(1,0) NOT NULL,
    unit_gen_id numeric(38,0) NOT NULL,
    unit_id numeric(38,0) NOT NULL,
    gen_id numeric(38,0) NOT NULL,
    arp_nameplate_capacity numeric(7,3),
    other_nameplate_capacity numeric(7,3),
    genid varchar(8) NOT NULL,
    unitid varchar(6) NOT NULL,
    fac_id numeric(38,0) NOT NULL,
    begin_date timestamp without time zone NOT NULL,
    end_date timestamp without time zone,
    programs varchar(150),
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (unit_gen_ws_id)
);
COMMENT ON TABLE camdws.unit_generator_ws
    IS 'Identifies industrial boilers or electric generating units.';
COMMENT ON COLUMN camdws.unit_generator_ws.unit_gen_ws_id
    IS 'unique id.';
COMMENT ON COLUMN camdws.unit_generator_ws.workspace_session_id
    IS 'FK to parent workspace session.';
COMMENT ON COLUMN camdws.unit_generator_ws.ws_added_ind
    IS '1 (true) if record was added during the WS session, other, otherwise 0.';
COMMENT ON COLUMN camdws.unit_generator_ws.ws_updated_ind
    IS '1 (true) if record was updated during the WS session, other, otherwise 0.';
COMMENT ON COLUMN camdws.unit_generator_ws.unit_gen_id
    IS 'Identity key for UNIT_GENERATOR table.';
COMMENT ON COLUMN camdws.unit_generator_ws.unit_id
    IS 'Identity key for UNIT table.';
COMMENT ON COLUMN camdws.unit_generator_ws.gen_id
    IS 'The identifier used to identify a GENERATOR, as reported to EIA and for New Unit Exemption purposes.';
COMMENT ON COLUMN camdws.unit_generator_ws.arp_nameplate_capacity
    IS 'Design nameplate capacity, in megawatts, of the GENERATOR.';
COMMENT ON COLUMN camdws.unit_generator_ws.other_nameplate_capacity
    IS 'Nameplate capacity, in megawatts, of the GENERATOR as applicable to other programs such as CAIR.';
COMMENT ON COLUMN camdws.unit_generator_ws.genid
    IS 'Public identifier used for GENERATOR as reported to EIA and for New Unit Exemption purposes.';
COMMENT ON COLUMN camdws.unit_generator_ws.unitid
    IS 'Public identifier used for UNIT as reported to EIA and for New Unit Exemption purposes.';
COMMENT ON COLUMN camdws.unit_generator_ws.fac_id
    IS 'Public identifier used for PLANT as reported to EIA and for New Unit Exemption purposes.';
COMMENT ON COLUMN camdws.unit_generator_ws.begin_date
    IS 'Date on which a relationship or an activity began.';
COMMENT ON COLUMN camdws.unit_generator_ws.end_date
    IS 'Date on which a relationship or an activity ended.';
COMMENT ON COLUMN camdws.unit_generator_ws.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camdws.unit_generator_ws.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camdws.unit_generator_ws.update_date
    IS 'Date of the last record update.';