CREATE TABLE IF NOT EXISTS camdws.unit_ws
(
    unit_ws_id bigint GENERATED BY DEFAULT AS IDENTITY,
    workspace_session_id numeric(38,0) NOT NULL,
    ws_added_ind numeric(1,0) NOT NULL,
    ws_updated_ind numeric(1,0) NOT NULL,
    unit_id numeric(38,0) NOT NULL,
    fac_id numeric(38,0) NOT NULL,
    unitid varchar(6) NOT NULL,
    unit_description varchar(4000),
    indian_country_ind numeric(1,0) NOT NULL DEFAULT 0,
    stateid varchar(6),
    boiler_sequence_number numeric(38,0),
    comm_op_date timestamp without time zone,
    comm_op_date_cd varchar(1),
    comr_op_date timestamp without time zone,
    comr_op_date_cd varchar(1),
    source_category_cd varchar(7),
    naics_cd numeric(6,0),
    naics_description varchar(1000),
    no_active_gen_ind numeric(1,0) NOT NULL DEFAULT 0,
    non_load_based_ind numeric(1,0),
    actual_90th_op_date timestamp without time zone,
    moved_ind numeric(1,0) NOT NULL DEFAULT 0,
    op_status_cd varchar(7),
    op_status_description varchar(1000),
    op_status_begin_date timestamp without time zone,
    unit_type_description varchar(1000),
    unitid_orig varchar(6),
    op_status_cd_orig varchar(7),
    op_status_begin_date_orig timestamp without time zone,
    industry_edit_list varchar(1000),
    relevant_ind numeric(1,0) NOT NULL DEFAULT 0,
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (unit_ws_id)
);
COMMENT ON TABLE camdws.unit_ws
    IS 'Identifies industrial boilers or electric generating units.';
COMMENT ON COLUMN camdws.unit_ws.unit_ws_id
    IS 'unique id.';
COMMENT ON COLUMN camdws.unit_ws.workspace_session_id
    IS 'FK to parent workspace session.';
COMMENT ON COLUMN camdws.unit_ws.ws_added_ind
    IS '1 (true) if record was added during the WS session, other, otherwise 0.';
COMMENT ON COLUMN camdws.unit_ws.ws_updated_ind
    IS '1 (true) if record was updated during the WS session, other, otherwise 0.';
COMMENT ON COLUMN camdws.unit_ws.unit_id
    IS 'Identity key for UNIT table.';
COMMENT ON COLUMN camdws.unit_ws.fac_id
    IS 'FACILITY ID identity key.';
COMMENT ON COLUMN camdws.unit_ws.unitid
    IS 'Public identifier used for UNIT for PROGRAM identification purposes.';
COMMENT ON COLUMN camdws.unit_ws.unit_description
    IS 'Text description of UNIT or UNIT configuration.';
COMMENT ON COLUMN camdws.unit_ws.indian_country_ind
    IS 'Indicates whether of not a unit is located in Indian Country.';
COMMENT ON COLUMN camdws.unit_ws.stateid
    IS 'The state identification number for a FACILITY or UNIT.';
COMMENT ON COLUMN camdws.unit_ws.boiler_sequence_number
    IS 'A CAMD assigned unique identifier for each boiler or unit.';
COMMENT ON COLUMN camdws.unit_ws.comm_op_date
    IS 'First day of operation that a UNIT generated electricity for sale, including the sale of test generation.';
COMMENT ON COLUMN camdws.unit_ws.comm_op_date_cd
    IS 'Code indicating whether the UNIT initial operation date is projected or actual.';
COMMENT ON COLUMN camdws.unit_ws.comr_op_date
    IS 'First day of commercial operation for a UNIT.';
COMMENT ON COLUMN camdws.unit_ws.comr_op_date_cd
    IS 'Code indicating whether the commercial operation date for a UNIT is projected or actual.';
COMMENT ON COLUMN camdws.unit_ws.source_category_cd
    IS 'General description of FACILITY type.';
COMMENT ON COLUMN camdws.unit_ws.naics_description
    IS 'Temporary description for NAICS_CODE (Other) stored for user edit during session.';
COMMENT ON COLUMN camdws.unit_ws.no_active_gen_ind
    IS 'Indicator to show that the unit does not currently have an active generator (1) or that the unit does currently have an active generator (0).';
COMMENT ON COLUMN camdws.unit_ws.non_load_based_ind
    IS 'Non load based unit indicator.';
COMMENT ON COLUMN camdws.unit_ws.actual_90th_op_date
    IS 'Stores the actual 90th operating date for a unit.  Supplied by sources via SMS/CBS.';
COMMENT ON COLUMN camdws.unit_ws.moved_ind
    IS 'Indicates whether or not a unit was moved from another facility.';
COMMENT ON COLUMN camdws.unit_ws.op_status_cd
    IS 'Key of the OPERATING_STATUS_CODE entry associated with this UNIT.';
COMMENT ON COLUMN camdws.unit_ws.op_status_description
    IS 'Description of the OPERATING_STATUS_CODE entry associated with this UNIT.';
COMMENT ON COLUMN camdws.unit_ws.op_status_begin_date
    IS 'Begin Date of the OPERATING_STATUS_CODE entry associated with this UNIT.';
COMMENT ON COLUMN camdws.unit_ws.unit_type_description
    IS 'Description of the UNIT_OP_STATUS entry associated with this UNIT.';
COMMENT ON COLUMN camdws.unit_ws.unitid_orig
    IS 'UNITID for this UNIT at the beginning of the workspace session.';
COMMENT ON COLUMN camdws.unit_ws.op_status_cd_orig
    IS 'Key of the OPERATING_STATUS_CODE entry associated with this UNIT at beginning of this workspace session.';
COMMENT ON COLUMN camdws.unit_ws.op_status_begin_date_orig
    IS 'Begin Date of the OPERATING_STATUS_CODE entry associated with this UNIT at beginning of this workspace session.';
COMMENT ON COLUMN camdws.unit_ws.industry_edit_list
    IS 'List of fields editable by an industry user.';
COMMENT ON COLUMN camdws.unit_ws.relevant_ind
    IS 'Indicator to show that the unit should be validated (1) or that the unit should not be validated (0).';
COMMENT ON COLUMN camdws.unit_ws.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camdws.unit_ws.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camdws.unit_ws.update_date
    IS 'Date of the last record update.';