CREATE TABLE IF NOT EXISTS camdws.workspace_load
(
    ws_load_id bigint GENERATED BY DEFAULT AS IDENTITY,
    workspace_session_id numeric(38,0) NOT NULL,
    id numeric(38,0) NOT NULL,
    key_type varchar(30) NOT NULL,
    PRIMARY KEY (ws_load_id)
);
COMMENT ON TABLE camdws.workspace_load
    IS 'Holds ID values needed to load FOR WORKSPACE.';
COMMENT ON COLUMN camdws.workspace_load.ws_load_id
    IS 'unique id.';
COMMENT ON COLUMN camdws.workspace_load.workspace_session_id
    IS 'FK to parent workspace session.';
COMMENT ON COLUMN camdws.workspace_load.id
    IS 'ID value used in load function.';
COMMENT ON COLUMN camdws.workspace_load.key_type
    IS 'The type of ID used in load function. Could be "PLANT", "PERSON", "PP", "COMPANY".';