CREATE TABLE IF NOT EXISTS camdws.workspace_session
(
    workspace_session_id bigint GENERATED BY DEFAULT AS IDENTITY,
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expiration_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (workspace_session_id)
);
COMMENT ON TABLE camdws.workspace_session
    IS 'The WORKSPACE_SESSION table stores pending data for submission to EPA.';
COMMENT ON COLUMN camdws.workspace_session.workspace_session_id
    IS 'WORKSPACE_SESSION identity key.';
COMMENT ON COLUMN camdws.workspace_session.userid
    IS 'The user name of the person or process that created the record.';
COMMENT ON COLUMN camdws.workspace_session.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camdws.workspace_session.expiration_date
    IS 'Date this record should be removed. Defaults to 60 days from today.';