CREATE TABLE IF NOT EXISTS camdeasey.locked_units
(
    unit_id numeric NOT NULL,
    activity_id varchar(32) NOT NULL,
    lock_time timestamp without time zone NOT NULL,
    PRIMARY KEY (unit_id)
);
COMMENT ON TABLE camdeasey.locked_units
    IS 'Maintains locks on units during editing.';
COMMENT ON COLUMN camdeasey.locked_units.unit_id
    IS ' Unique identifier of a unit record which is generated by the EPA Host System. ';
COMMENT ON COLUMN camdeasey.locked_units.activity_id
    IS ' Unique identifier of an activity.';
COMMENT ON COLUMN camdeasey.locked_units.lock_time
    IS ' The time the lock was set.';