CREATE TABLE IF NOT EXISTS camdeasey.locked_units_failed
(
    locked_units_fail_id numeric(38,0) NOT NULL,
    unit_id numeric(38,0) NOT NULL,
    activity_id_lock_held varchar(32) NOT NULL,
    activity_id_lock_attempt varchar(32) NOT NULL,
    lock_attempt_time timestamp without time zone NOT NULL,
    PRIMARY KEY (locked_units_fail_id)
);
COMMENT ON TABLE camdeasey.locked_units_failed
    IS 'Logs units that failed to lock during a lock acquisition by the client.';
COMMENT ON COLUMN camdeasey.locked_units_failed.locked_units_fail_id
    IS ' Unique identifier of a locked units failed record.';
COMMENT ON COLUMN camdeasey.locked_units_failed.unit_id
    IS ' Unique identifier of a unit record which is generated by the EPA Host System. ';
COMMENT ON COLUMN camdeasey.locked_units_failed.activity_id_lock_held
    IS ' The activity ID associated with a lock.';
COMMENT ON COLUMN camdeasey.locked_units_failed.activity_id_lock_attempt
    IS ' The activity ID associated with the attempt to lock.';
COMMENT ON COLUMN camdeasey.locked_units_failed.lock_attempt_time
    IS ' Time in which lock was attempted.';