CREATE TABLE IF NOT EXISTS camdeasey.locked_units_log
(
    unit_id numeric NOT NULL,
    activity_id varchar(32) NOT NULL,
    lock_time timestamp without time zone NOT NULL,
    unlock_time timestamp without time zone NOT NULL,
    PRIMARY KEY (unit_id, activity_id)
);
COMMENT ON TABLE camdeasey.locked_units_log
    IS 'Logs unit lock and unlock times.';
COMMENT ON COLUMN camdeasey.locked_units_log.unit_id
    IS ' Unique identifier of a unit record which is generated by the EPA Host System. ';
COMMENT ON COLUMN camdeasey.locked_units_log.activity_id
    IS ' Unique identifier of an activity.';
COMMENT ON COLUMN camdeasey.locked_units_log.lock_time
    IS ' Time in which lock was set.';
COMMENT ON COLUMN camdeasey.locked_units_log.unlock_time
    IS ' Time in which lock was removed.';