CREATE TABLE IF NOT EXISTS camdeasey.monitor_location
(
    mon_loc_id varchar(45) NOT NULL,
    stack_pipe_id varchar(45),
    unit_id numeric(38,0),
    load_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (mon_loc_id)
);
COMMENT ON TABLE camdeasey.monitor_location
    IS 'Stack characteristic data applicable for the configuration type identified in the monitoring plan.  Name of stack must being with &quot;CS&quot; followed by up to four alphanumeric characters. Record Type 503.';
COMMENT ON COLUMN camdeasey.monitor_location.mon_loc_id
    IS 'Unique identifier of a monitoring location record. ';
COMMENT ON COLUMN camdeasey.monitor_location.stack_pipe_id
    IS 'Unique identifier of a stack or pipe record. ';
COMMENT ON COLUMN camdeasey.monitor_location.unit_id
    IS 'Unique identifier of a unit record which is generated by the EPA Host System. ';
COMMENT ON COLUMN camdeasey.monitor_location.load_date
    IS 'Date and time at which record was loaded from source. ';