CREATE TABLE IF NOT EXISTS camdeasey.monitor_plan
(
    mon_plan_id varchar(45) NOT NULL,
    fac_id numeric(38,0) NOT NULL,
    begin_rpt_period_id numeric(38,0) NOT NULL,
    end_rpt_period_id numeric(38,0),
    load_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (mon_plan_id)
);
COMMENT ON TABLE camdeasey.monitor_plan
    IS 'Table of monitoring plan(s) created by the user.';
COMMENT ON COLUMN camdeasey.monitor_plan.mon_plan_id
    IS 'Unique identifier of a monitoring plan record. ';
COMMENT ON COLUMN camdeasey.monitor_plan.fac_id
    IS 'Unique identifier of a facility record which is generated by the EPA Host System. ';
COMMENT ON COLUMN camdeasey.monitor_plan.begin_rpt_period_id
    IS 'Unique identifier of a reporting period record. ';
COMMENT ON COLUMN camdeasey.monitor_plan.end_rpt_period_id
    IS 'Unique identifier of a reporting period record. ';
COMMENT ON COLUMN camdeasey.monitor_plan.load_date
    IS 'Date and time at which record was loaded from source. ';