CREATE TABLE IF NOT EXISTS camdeasey.stack_pipe
(
    stack_pipe_id varchar(45) NOT NULL,
    fac_id numeric(38,0) NOT NULL,
    stack_name varchar(6) NOT NULL,
    load_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (stack_pipe_id)
);
COMMENT ON TABLE camdeasey.stack_pipe
    IS 'Stack characteristic data applicable for the configuration type identified in the monitoring plan.  Name of stack must being with &quot;CS&quot; followed by up to four alphanumeric characters.';
COMMENT ON COLUMN camdeasey.stack_pipe.stack_pipe_id
    IS 'Unique identifier of a stack or pipe record. ';
COMMENT ON COLUMN camdeasey.stack_pipe.fac_id
    IS 'Unique identifier of a facility record which is generated by the EPA Host System. ';
COMMENT ON COLUMN camdeasey.stack_pipe.stack_name
    IS 'Three to six alphanumeric character code which is assigned by the source to identify a stack or pipe. ';
COMMENT ON COLUMN camdeasey.stack_pipe.load_date
    IS 'Date and time at which record was loaded from source. ';