CREATE TABLE IF NOT EXISTS camdeasey.synchronization_management
(
    synchronization_management_id numeric(38,0) NOT NULL,
    mon_plan_id varchar(45) NOT NULL,
    mon_plan_last_updated timestamp without time zone,
    used_id_last_updated timestamp without time zone,
    qa_supp_last_updated timestamp without time zone,
    qa_cert_event_last_updated timestamp without time zone,
    test_ext_exempt_last_updated timestamp without time zone,
    em_submission_last_updated timestamp without time zone,
    op_supp_data_last_updated timestamp without time zone,
    mp_submission_last_updated timestamp without time zone,
    mp_supp_data_last_updated timestamp without time zone,
    mp_comment_last_updated timestamp without time zone,
    generate_dm_ind numeric(1,0) NOT NULL DEFAULT 1,
    apport_formula_last_updated timestamp without time zone,
    sorbent_trap_last_updated timestamp without time zone,
    comp_op_supp_data_last_updated timestamp without time zone,
    qa_val_supp_data_last_updated timestamp without time zone,
    qa_cert_supp_data_last_updated timestamp without time zone,
    sys_op_supp_data_last_updated timestamp without time zone,
    daily_test_supp_last_updated timestamp without time zone,
    PRIMARY KEY (synchronization_management_id)
);
COMMENT ON TABLE camdeasey.synchronization_management
    IS 'Maintains the current state of monitor plans for synchronization.';
COMMENT ON COLUMN camdeasey.synchronization_management.synchronization_management_id
    IS ' Unique identifier of a synchronization management record.';
COMMENT ON COLUMN camdeasey.synchronization_management.mon_plan_id
    IS ' Unique identifier of a monitoring plan record. ';
COMMENT ON COLUMN camdeasey.synchronization_management.mon_plan_last_updated
    IS ' The date and time in which the monitoring plan data were last updated.';
COMMENT ON COLUMN camdeasey.synchronization_management.used_id_last_updated
    IS ' The date and time in which the used identifier data were last updated.';
COMMENT ON COLUMN camdeasey.synchronization_management.qa_supp_last_updated
    IS ' The date and time in which the QA supplemental data were last updated.';
COMMENT ON COLUMN camdeasey.synchronization_management.qa_cert_event_last_updated
    IS ' The date and time in which the QA certification event data were last updated.';
COMMENT ON COLUMN camdeasey.synchronization_management.test_ext_exempt_last_updated
    IS ' The date and time in which the test extension exemption data were last updated.';
COMMENT ON COLUMN camdeasey.synchronization_management.em_submission_last_updated
    IS ' The date and time in which the emissions submission data were last updated.';
COMMENT ON COLUMN camdeasey.synchronization_management.op_supp_data_last_updated
    IS ' The date and time in which the operational hour data were last updated.';
COMMENT ON COLUMN camdeasey.synchronization_management.mp_submission_last_updated
    IS 'Last update date for a monitor plan submission';
COMMENT ON COLUMN camdeasey.synchronization_management.mp_supp_data_last_updated
    IS 'Last update date for monitor plan supplemental data';
COMMENT ON COLUMN camdeasey.synchronization_management.mp_comment_last_updated
    IS 'Last update date for a monitor plan comment';
COMMENT ON COLUMN camdeasey.synchronization_management.generate_dm_ind
    IS 'Indicator used to determine if the Data and Maps data should be generated by the Client Tool for this MP.';
COMMENT ON COLUMN camdeasey.synchronization_management.apport_formula_last_updated
    IS 'The date and time when the apportionment formulae were last updated.';
COMMENT ON COLUMN camdeasey.synchronization_management.sorbent_trap_last_updated
    IS 'Last update date for sorbent trap supplemental data';
COMMENT ON COLUMN camdeasey.synchronization_management.comp_op_supp_data_last_updated
    IS 'Last update date for component operating supplement data';
COMMENT ON COLUMN camdeasey.synchronization_management.qa_val_supp_data_last_updated
    IS 'Last update date for QA value supplement data';
COMMENT ON COLUMN camdeasey.synchronization_management.qa_cert_supp_data_last_updated
    IS 'Last update date for QA certification supplement data';
COMMENT ON COLUMN camdeasey.synchronization_management.sys_op_supp_data_last_updated
    IS 'Last update date for system operating supplement data';
COMMENT ON COLUMN camdeasey.synchronization_management.daily_test_supp_last_updated
    IS 'Last update date for daily test supplement data';