CREATE TABLE IF NOT EXISTS camdeasey.unit_stack_configuration
(
    config_id varchar(45) NOT NULL,
    unit_id numeric(38,0) NOT NULL,
    stack_pipe_id varchar(45) NOT NULL,
    begin_date timestamp without time zone NOT NULL,
    end_date timestamp without time zone,
    load_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (config_id)
);
COMMENT ON TABLE camdeasey.unit_stack_configuration
    IS 'Identifies the units, stacks or pipes that are associated with a specific monitoring plan.';
COMMENT ON COLUMN camdeasey.unit_stack_configuration.config_id
    IS 'Unique identifier of a monitoring configuration record. ';
COMMENT ON COLUMN camdeasey.unit_stack_configuration.unit_id
    IS 'Unique identifier of a unit record which is generated by the EPA Host System. ';
COMMENT ON COLUMN camdeasey.unit_stack_configuration.stack_pipe_id
    IS 'Unique identifier of a stack or pipe record. ';
COMMENT ON COLUMN camdeasey.unit_stack_configuration.begin_date
    IS 'Date in which information became effective or activity started. ';
COMMENT ON COLUMN camdeasey.unit_stack_configuration.end_date
    IS 'Last date in which information was effective or date in which activity ended. ';
COMMENT ON COLUMN camdeasey.unit_stack_configuration.load_date
    IS 'Date and time at which record was loaded from source. ';