---------------------
-- General Indexes --
---------------------

CREATE INDEX IF NOT EXISTS ACCOUNT_REP_DIM_PPL_ACC_PRG_NME_IX ON CAMDDMW.ACCOUNT_REP_DIM ( PPL_ID, ACCOUNT_NUMBER, PRG_CODE, DISPLAY_NAME );


-----------------
-- Constraints --
-----------------

ALTER TABLE CAMDDMW.ACCOUNT_REP_DIM ADD CONSTRAINT ACCOUNT_REP_DIM_PK PRIMARY KEY ( PRG_CODE, ACCOUNT_NUMBER, PPL_ID, REP_CODE );
