---------------------
-- General Indexes --
---------------------

CREATE INDEX OP_STATUS_YR_DIM_IDX1 ON CAMDDMW.OP_STATUS_YEAR_DIM ( UNIT_ID, OP_STATUS);


-----------------
-- Constraints --
-----------------

ALTER TABLE CAMDDMW.OP_STATUS_YEAR_DIM ADD CONSTRAINT OP_STATUS_YEAR_DIM_PK PRIMARY KEY ( UNIT_ID, OP_YEAR );
ALTER TABLE CAMDDMW.OP_STATUS_YEAR_DIM ADD CONSTRAINT OP_STATUS_YEAR_DIM_FK FOREIGN KEY ( UNIT_ID, OP_YEAR ) REFERENCES UNIT_FACT ( UNIT_ID, OP_YEAR ) ON DELETE CASCADE;
