-- PROCEDURE: camdecmpswks.refresh_emission_view_co2appd(character varying, numeric)

-- DROP PROCEDURE camdecmpswks.refresh_emission_view_co2appd(character varying, numeric);

CREATE OR REPLACE PROCEDURE camdecmpswks.refresh_emission_view_co2appd(
	vmonplanid character varying,
	vrptperiodid numeric)
LANGUAGE 'plpgsql'
AS $BODY$
BEGIN
	DELETE FROM camdecmpswks.EMISSION_VIEW_CO2APPD 
		WHERE MON_PLAN_ID = vmonplanid AND RPT_PERIOD_ID = vrptperiodid;

	INSERT INTO camdecmpswks.EMISSION_VIEW_CO2APPD
		(
			MON_PLAN_ID,
			MON_LOC_ID,
			RPT_PERIOD_ID,
			DATE_HOUR,
			OP_TIME,
			FUEL_SYS_ID,
			FUEL_TYPE,
			FUEL_USE_TIME,
			UNIT_LOAD,
			LOAD_UOM,
			CALC_HI_RATE,
			FC_FACTOR,
			FORMULA_CD,
			RPT_CO2_MASS_RATE,
			CALC_CO2_MASS_RATE,
			SUMMATION_FORMULA_CD,
			RPT_CO2_MASS_RATE_ALL_FUELS,
			CALC_CO2_MASS_RATE_ALL_FUELS,
			ERROR_CODES
		)
		
		SELECT DISTINCT 
				HOD.MON_PLAN_ID, 
				HOD.MON_LOC_ID, 
				HOD.RPT_PERIOD_ID,
				camdecmpswks.format_date_hour(hod.BEGIN_DATE, hod.BEGIN_HOUR, null), 
				HOD.OP_TIME,
				MS.SYSTEM_IDENTIFIER AS FUEL_SYS_ID,
				HFF.FUEL_CD AS FUEL_TYPE,
				HFF.FUEL_USAGE_TIME AS FUEL_USE_TIME,
				HOD.HR_LOAD AS UNIT_LOAD, 
				HOD.LOAD_UOM_CD AS LOAD_UOM, 
				HPFF_HI.CALC_PARAM_VAL_FUEL AS CALC_HI_RATE,
				HPFF_FC.PARAM_VAL_FUEL AS FC_FACTOR,
				MF.EQUATION_CD AS FORMULA_CD,
				HPFF_CO2.PARAM_VAL_FUEL AS RPT_CO2_MASS_RATE,
				HPFF_CO2.CALC_PARAM_VAL_FUEL AS CALC_CO2_MASS_RATE,
				SUMMATION_MF.EQUATION_CD AS SUMMATION_FORMULA_CD,
				DHV_CO2.ADJUSTED_HRLY_VALUE AS RPT_CO2_MASS_RATE_ALL_FUELS,
				DHV_CO2.CALC_ADJUSTED_HRLY_VALUE AS CALC_CO2_MASS_RATE_ALL_FUELS,
				HOD.ERROR_CODES
			FROM	temp_hourly_errors AS HOD 
					INNER JOIN camdecmpswks.HRLY_FUEL_FLOW HFF ON HOD.HOUR_ID = HFF.HOUR_ID
					LEFT OUTER JOIN camdecmpswks.HRLY_PARAM_FUEL_FLOW HPFF_CO2 ON ((HFF.HRLY_FUEL_FLOW_ID = HPFF_CO2.HRLY_FUEL_FLOW_ID) AND (HPFF_CO2.PARAMETER_CD = 'CO2'))		
					LEFT OUTER JOIN camdecmpswks.HRLY_PARAM_FUEL_FLOW HPFF_HI ON ((HFF.HRLY_FUEL_FLOW_ID = HPFF_HI.HRLY_FUEL_FLOW_ID) AND (HPFF_HI.PARAMETER_CD = 'HI'))
					LEFT OUTER JOIN camdecmpswks.HRLY_PARAM_FUEL_FLOW HPFF_FC ON ((HFF.HRLY_FUEL_FLOW_ID = HPFF_FC.HRLY_FUEL_FLOW_ID) AND (HPFF_FC.PARAMETER_CD = 'FC'))
					LEFT OUTER JOIN camdecmpswks.DERIVED_HRLY_VALUE DHV_CO2 ON ((DHV_CO2.HOUR_ID = HOD.HOUR_ID) AND (DHV_CO2.PARAMETER_CD = 'CO2'))
					LEFT OUTER JOIN camdecmpswks.MONITOR_SYSTEM MS ON HFF.MON_SYS_ID = MS.MON_SYS_ID
					LEFT OUTER JOIN camdecmpswks.MONITOR_FORMULA MF ON HPFF_CO2.MON_FORM_ID = MF.MON_FORM_ID
					LEFT OUTER JOIN camdecmpswks.MONITOR_FORMULA SUMMATION_MF ON DHV_CO2.MON_FORM_ID = SUMMATION_MF.MON_FORM_ID
			WHERE	HPFF_CO2.HRLY_FUEL_FLOW_ID IS NOT NULL 
					OR ((HPFF_CO2.HRLY_FUEL_FLOW_ID IS NULL) AND (HPFF_HI.HRLY_FUEL_FLOW_ID IS NOT NULL AND DHV_CO2.PARAMETER_CD IS NOT NULL));
END
$BODY$;
