DROP PROCEDURE IF EXISTS camdecmpswks.refresh_emission_view_all(character varying, numeric);

CREATE OR REPLACE PROCEDURE camdecmpswks.refresh_emission_view_all(
	vmonplanid character varying,
	vrptperiodid numeric
)
LANGUAGE 'plpgsql'
AS $BODY$
BEGIN
	CALL camdecmpswks.load_temp_hourly_test_errors(vMonPlanId, vRptPeriodId);

	DELETE FROM camdecmpswks.EMISSION_VIEW_ALL
	WHERE MON_PLAN_ID = vMonPlanId AND RPT_PERIOD_ID = vRptPeriodId;

	INSERT INTO camdecmpswks.EMISSION_VIEW_ALL(
		MON_PLAN_ID,
		MON_LOC_ID,
		RPT_PERIOD_ID,
		HOUR_ID,
		DATE_HOUR,
		OP_TIME,
		UNIT_LOAD,
		LOAD_UOM,
		HI_FORMULA_cd,
		RPT_HI_RATE,
		CALC_HI_RATE,
		SO2_FORMULA_cd,
		RPT_SO2_MASS_RATE,
		CALC_SO2_MASS_RATE,
		nox_rate_formula_cd,
		RPT_ADJ_NOX_RATE,
		CALC_ADJ_NOX_RATE,
		nox_mass_formula_cd,
		RPT_NOX_MASS,
		CALC_NOX_MASS,
		CO2_FORMULA_cd,
		RPT_CO2_MASS_RATE,
		CALC_CO2_MASS_RATE,
		ADJ_FLOW_USED,
		RPT_ADJ_FLOW,
		UNADJ_FLOW,
		ERROR_CODES
	)
	SELECT
		hod.MON_PLAN_ID, 
		hod.MON_LOC_ID, 
		hod.RPT_PERIOD_ID,
		hod.HOUR_ID,
		camdecmpswks.format_date_hour(hod.BEGIN_DATE, hod.BEGIN_HOUR, null) AS DATE_HOUR,
		hod.OP_TIME,
		hod.HR_LOAD,
		hod.LOAD_UOM_CD,
		mf_hi.EQUATION_CD,
		dhv_hi.ADJUSTED_HRLY_VALUE,
		dhv_hi.CALC_ADJUSTED_HRLY_VALUE,
		mf_SO2.EQUATION_CD,
		dhv_SO2.ADJUSTED_HRLY_VALUE,
		dhv_SO2.CALC_ADJUSTED_HRLY_VALUE,
		mf_NOXR.EQUATION_CD,
		dhv_NOXR.ADJUSTED_HRLY_VALUE,
		dhv_NOXR.CALC_ADJUSTED_HRLY_VALUE,
		mf_NOX.EQUATION_CD,
		dhv_NOX.ADJUSTED_HRLY_VALUE,
		dhv_NOX.CALC_ADJUSTED_HRLY_VALUE,
		mf_CO2.EQUATION_CD,
		dhv_CO2.ADJUSTED_HRLY_VALUE,
		dhv_CO2.CALC_ADJUSTED_HRLY_VALUE,
		mhv_FLOW.CALC_ADJUSTED_HRLY_VALUE AS ADJ_FLOW_USED,
		mhv_FLOW.ADJUSTED_HRLY_VALUE AS RPT_ADJ_FLOW, 
		mhv_FLOW.UNADJUSTED_HRLY_VALUE AS UNADJ_FLOW, 
		hod.ERROR_CODES
	FROM temp_hourly_test_errors AS hod
	LEFT JOIN (
		SELECT
			HOUR_ID, MON_LOC_ID, RPT_PERIOD_ID,
			MON_FORM_ID, ADJUSTED_HRLY_VALUE, CALC_ADJUSTED_HRLY_VALUE
		FROM camdecmpswks.DERIVED_HRLY_VALUE
		WHERE RPT_PERIOD_ID = vrptperiodid AND PARAMETER_CD = 'HI'
	) AS dhv_HI
		ON dhv_HI.HOUR_ID = hod.HOUR_ID
		AND dhv_HI.MON_LOC_ID = hod.MON_LOC_ID
		AND dhv_HI.RPT_PERIOD_ID = hod.RPT_PERIOD_ID
	LEFT JOIN camdecmpswks.MONITOR_FORMULA mf_HI
		ON mf_HI.MON_FORM_ID = dhv_HI.MON_FORM_ID
	LEFT JOIN (
		SELECT
			HOUR_ID, MON_LOC_ID, RPT_PERIOD_ID,
			MON_FORM_ID, ADJUSTED_HRLY_VALUE, CALC_ADJUSTED_HRLY_VALUE
		FROM camdecmpswks.DERIVED_HRLY_VALUE
		WHERE RPT_PERIOD_ID = vrptperiodid AND PARAMETER_CD = 'SO2'
	) AS dhv_SO2
		ON dhv_SO2.HOUR_ID = hod.HOUR_ID
		AND dhv_SO2.MON_LOC_ID = hod.MON_LOC_ID
		AND dhv_SO2.RPT_PERIOD_ID = hod.RPT_PERIOD_ID
	LEFT JOIN camdecmpswks.MONITOR_FORMULA mf_SO2
		ON mf_SO2.MON_FORM_ID = dhv_SO2.MON_FORM_ID
	LEFT JOIN (
		SELECT
			HOUR_ID, MON_LOC_ID, RPT_PERIOD_ID,
			MON_FORM_ID, ADJUSTED_HRLY_VALUE, CALC_ADJUSTED_HRLY_VALUE
		FROM camdecmpswks.DERIVED_HRLY_VALUE
		WHERE RPT_PERIOD_ID = vrptperiodid AND PARAMETER_CD = 'NOXR'
	) AS dhv_NOXR
		ON dhv_NOXR.HOUR_ID = hod.HOUR_ID
		AND dhv_NOXR.MON_LOC_ID = hod.MON_LOC_ID
		AND dhv_NOXR.RPT_PERIOD_ID = hod.RPT_PERIOD_ID
	LEFT JOIN camdecmpswks.MONITOR_FORMULA mf_NOXR
		ON mf_NOXR.MON_FORM_ID = dhv_NOXR.MON_FORM_ID
	LEFT JOIN (
		SELECT
			HOUR_ID, MON_LOC_ID, RPT_PERIOD_ID,
			MON_FORM_ID, ADJUSTED_HRLY_VALUE, CALC_ADJUSTED_HRLY_VALUE
		FROM camdecmpswks.DERIVED_HRLY_VALUE
		WHERE RPT_PERIOD_ID = vrptperiodid AND PARAMETER_CD = 'NOX'
	) AS dhv_NOX
		ON dhv_NOX.HOUR_ID = hod.HOUR_ID
		AND dhv_NOX.MON_LOC_ID = hod.MON_LOC_ID
		AND dhv_NOX.RPT_PERIOD_ID = hod.RPT_PERIOD_ID
	LEFT JOIN camdecmpswks.MONITOR_FORMULA mf_NOX
		ON mf_NOX.MON_FORM_ID = dhv_NOX.MON_FORM_ID
	LEFT JOIN (
		SELECT
			HOUR_ID, MON_LOC_ID, RPT_PERIOD_ID,
			MON_FORM_ID, ADJUSTED_HRLY_VALUE, CALC_ADJUSTED_HRLY_VALUE
		FROM camdecmpswks.DERIVED_HRLY_VALUE
		WHERE RPT_PERIOD_ID = vrptperiodid AND PARAMETER_CD = 'CO2'
	) AS dhv_CO2
		ON dhv_CO2.HOUR_ID = hod.HOUR_ID
		AND dhv_CO2.MON_LOC_ID = hod.MON_LOC_ID
		AND dhv_CO2.RPT_PERIOD_ID = hod.RPT_PERIOD_ID
	LEFT JOIN camdecmpswks.MONITOR_FORMULA mf_CO2
		ON mf_CO2.MON_FORM_ID = dhv_CO2.MON_FORM_ID
	LEFT JOIN (
		SELECT
			HOUR_ID, MON_LOC_ID, RPT_PERIOD_ID,
			ADJUSTED_HRLY_VALUE, UNADJUSTED_HRLY_VALUE, CALC_ADJUSTED_HRLY_VALUE
		FROM camdecmpswks.MONITOR_HRLY_VALUE
		WHERE RPT_PERIOD_ID = vrptperiodid AND PARAMETER_CD = 'FLOW'
	) AS mhv_FLOW
		ON mhv_FLOW.HOUR_ID = hod.HOUR_ID
		AND mhv_FLOW.MON_LOC_ID = hod.MON_LOC_ID
		AND mhv_FLOW.RPT_PERIOD_ID = hod.RPT_PERIOD_ID;

  CALL camdecmpswks.refresh_emission_view_count(vmonplanid, vrptperiodid, 'ALL');
END
$BODY$;

/*
----------------------------------------------------------------------------------------
FOR TESTING PURPOSES ONLY
----------------------------------------------------------------------------------------
DROP TABLE temp_hourly_test_errors;
CALL camdecmpswks.load_temp_hourly_test_errors('MDC-F05B2E8CD7804BBEB27146024D0D2095', 120);
select * from temp_hourly_test_errors

SELECT DISTINCT
	mpl.MON_PLAN_ID, mpl.MON_LOC_ID
FROM (
	SELECT HOUR_ID, MON_LOC_ID, RPT_PERIOD_ID
	FROM camdecmps.DERIVED_HRLY_VALUE
	WHERE RPT_PERIOD_ID = 120 AND PARAMETER_CD IN ('HI','SO2','NOXR','NOX','CO2')
) AS dhv
JOIN (
	SELECT HOUR_ID, MON_LOC_ID, RPT_PERIOD_ID
	FROM camdecmps.MONITOR_HRLY_VALUE
	WHERE RPT_PERIOD_ID = 120 AND PARAMETER_CD = 'FLOW'
) AS mhv
	ON mhv.HOUR_ID = dhv.HOUR_ID
	AND mhv.MON_LOC_ID = dhv.MON_LOC_ID
	AND mhv.RPT_PERIOD_ID = dhv.RPT_PERIOD_ID	
JOIN camdecmps.monitor_plan_location mpl
	ON mpl.MON_LOC_ID = dhv.MON_LOC_ID
ORDER BY mpl.MON_LOC_ID
*/
