-- PROCEDURE: camdecmpswks.refresh_emission_view_massoilcalc(character varying, numeric)

-- DROP PROCEDURE camdecmpswks.refresh_emission_view_massoilcalc(character varying, numeric);

CREATE OR REPLACE PROCEDURE camdecmpswks.refresh_emission_view_massoilcalc(
	vmonplanid character varying,
	vrptperiodid numeric)
LANGUAGE 'plpgsql'
AS $BODY$
BEGIN
	DELETE FROM camdecmpswks.EMISSION_VIEW_MASSOILCALC 
		WHERE MON_PLAN_ID = vmonplanid AND RPT_PERIOD_ID = vrptperiodid;

	INSERT INTO camdecmpswks.EMISSION_VIEW_MASSOILCALC
           (MON_PLAN_ID
           ,MON_LOC_ID
           ,RPT_PERIOD_ID
           ,DATE_HOUR
           ,OP_TIME
           ,FUEL_SYS_ID
           ,OIL_TYPE
           ,FUEL_USE_TIME
           ,RPT_VOLUMETRIC_OIL_FLOW
           ,CALC_VOLUMETRIC_OIL_FLOW
           ,VOLUMETRIC_OIL_FLOW_UOM
           ,VOLUMETRIC_OIL_FLOW_SODC
           ,OIL_DENSITY
           ,OIL_DENSITY_UOM
           ,OIL_DENSITY_SAMPLING_TYPE
           ,RPT_MASS_OIL_FLOW
           ,CALC_MASS_OIL_FLOW
           ,ERROR_CODES)
		
		SELECT DISTINCT
				HOD.MON_PLAN_ID, 
				HOD.MON_LOC_ID, 
				HOD.RPT_PERIOD_ID,
				camdecmpswks.format_date_hour(hod.BEGIN_DATE, hod.BEGIN_HOUR, null),
				HOD.OP_TIME,
				MS.SYSTEM_IDENTIFIER AS FUEL_SYS_ID,
				HFF.FUEL_CD AS OIL_TYPE,
				HFF.FUEL_USAGE_TIME AS FUEL_USE_TIME,
				HFF.VOLUMETRIC_FLOW_RATE AS RPT_VOLUMETRIC_OIL_FLOW,
				HFF.CALC_VOLUMETRIC_FLOW_RATE AS CALC_VOLUMETRIC_OIL_FLOW,
				HFF.VOLUMETRIC_UOM_CD AS VOLUMETRIC_OIL_FLOW_UOM,
				HFF.SOD_VOLUMETRIC_CD AS VOLUMETRIC_OIL_FLOW_SODC,
				HPFF_DENSOIL.PARAM_VAL_FUEL AS OIL_DENSITY,
				HPFF_DENSOIL.PARAMETER_UOM_CD AS OIL_DENSITY_UOM,
				HPFF_DENSOIL.SAMPLE_TYPE_CD AS OIL_DENSITY_SAMPLING_TYPE,
				HFF.MASS_FLOW_RATE AS RPT_MASS_OIL_FLOW,
				HFF.CALC_MASS_FLOW_RATE AS CALC_MASS_OIL_FLOW,
				HOD.ERROR_CODES
		FROM temp_hourly_errors AS HOD 
				INNER JOIN camdecmpswks.HRLY_FUEL_FLOW HFF ON HOD.HOUR_ID = HFF.HOUR_ID
				INNER JOIN camdecmpswks.HRLY_PARAM_FUEL_FLOW HPFF_DENSOIL ON ((HFF.HRLY_FUEL_FLOW_ID = HPFF_DENSOIL.HRLY_FUEL_FLOW_ID) AND (HPFF_DENSOIL.PARAMETER_CD = 'DENSOIL') AND (HFF.VOLUMETRIC_FLOW_RATE > 0) AND (HFF.MASS_FLOW_RATE > 0))
				LEFT OUTER JOIN camdecmpswks.MONITOR_SYSTEM MS ON HFF.MON_SYS_ID = MS.MON_SYS_ID;
END
$BODY$;
