-- PROCEDURE: camdecmpswks.refresh_emission_view_noxratecems(character varying, numeric)

-- DROP PROCEDURE camdecmpswks.refresh_emission_view_noxratecems(character varying, numeric);

CREATE OR REPLACE PROCEDURE camdecmpswks.refresh_emission_view_noxratecems(
	vmonplanid character varying,
	vrptperiodid numeric)
LANGUAGE 'plpgsql'
AS $BODY$
BEGIN
	DELETE FROM camdecmpswks.EMISSION_VIEW_NOXRATECEMS 
		WHERE MON_PLAN_ID = vmonplanid AND RPT_PERIOD_ID = vrptperiodid;

	INSERT INTO camdecmpswks.EMISSION_VIEW_NOXRATECEMS
           (MON_PLAN_ID
           ,MON_LOC_ID
           ,RPT_PERIOD_ID
           ,DATE_HOUR
           ,OP_TIME
           ,UNIT_LOAD
           ,LOAD_UOM
           ,NOX_RATE_MODC
           ,NOX_RATE_PMA
           ,UNADJ_NOX
           ,NOX_MODC
           ,DILUENT_PARAM
           ,PCT_DILUENT_USED
           ,DILUENT_MODC
           ,RPT_DILUENT
           ,PCT_H2O_USED
           ,SOURCE_H2O_VALUE
           ,F_FACTOR
           ,nox_rate_formula_cd
           ,RPT_UNADJ_NOX_RATE
           ,CALC_UNADJ_NOX_RATE
           ,CALC_NOX_BAF
           ,RPT_ADJ_NOX_RATE
           ,CALC_ADJ_NOX_RATE
           ,CALC_HI_RATE
           ,nox_mass_formula_cd
           ,RPT_NOX_MASS
           ,CALC_NOX_MASS
           ,ERROR_CODES)
		
		SELECT DISTINCT
				HOD.MON_PLAN_ID, 
				HOD.MON_LOC_ID, 
				HOD.RPT_PERIOD_ID, 
				camdecmpswks.format_date_hour(hod.BEGIN_DATE, hod.BEGIN_HOUR, null),
				HOD.OP_TIME, 
				HOD.HR_LOAD AS UNIT_LOAD, 
		        HOD.LOAD_UOM_CD AS LOAD_UOM, 
				DHV.MODC_CD AS NOX_RATE_MODC, 
				DHV.PCT_AVAILABLE AS NOX_RATE_PMA,
				NOXC_MHV.UNADJUSTED_HRLY_VALUE AS UNADJ_NOX, 
		        NOXC_MHV.MODC_CD AS NOX_MODC, 
				CASE WHEN (MF.EQUATION_CD IN ('19-6', '19-7', '19-8', '19-9', 'F-6')) THEN 'CO2' 
					 WHEN (MF.EQUATION_CD IN ('19-1', '19-2', '19-3', '19-3D', '19-4', '19-5', '19-5D', 'F-5')) THEN 'O2' 
					 ELSE NULL 
				END AS DILUENT_PARAM, 
				DHV.CALC_PCT_DILUENT AS PCT_DILUENT_USED, 
				CASE WHEN (MF.EQUATION_CD IN ('19-6', '19-7', '19-8', '19-9', 'F-6')) THEN MHV_CO2C.MODC_CD
					 WHEN (MF.EQUATION_CD IN ('19-1', '19-4', 'F-5')) THEN MHV_O2C_DRY.MODC_CD
					 WHEN (MF.EQUATION_CD IN ('19-2', '19-3', '19-5', '19-3D', '19-5D')) THEN MHV_O2C_WET.MODC_CD		 
				END AS DILUENT_MODC, 
				CASE WHEN (MF.EQUATION_CD IN ('19-6', '19-7', '19-8', '19-9', 'F-6')) THEN MHV_CO2C.UNADJUSTED_HRLY_VALUE
					 WHEN (MF.EQUATION_CD IN ('19-1', '19-4', 'F-5')) THEN MHV_O2C_DRY.UNADJUSTED_HRLY_VALUE
					 WHEN (MF.EQUATION_CD IN ('19-2', '19-3', '19-5', '19-3D', '19-5D')) THEN MHV_O2C_WET.UNADJUSTED_HRLY_VALUE		 
				END as RPT_DILUENT,
		        DHV.CALC_PCT_MOISTURE AS PCT_H2O_USED, 
				CASE 
					WHEN (DHV.CALC_PCT_MOISTURE IS NOT NULL) THEN 
						CASE WHEN (H2O_DHV.MODC_CD IS NOT NULL) THEN H2O_DHV.MODC_CD 
							 WHEN (H2O_MHV.MODC_CD IS NOT NULL) THEN H2O_MHV.MODC_CD 
							 ELSE 'DF'
						END 
					ELSE NULL
				END AS SOURCE_H2O_VALUE, 
		        CASE WHEN (MF.EQUATION_CD IN ('19-6', '19-7', '19-8', '19-9', 'F-6')) THEN HOD.FC_FACTOR 
					 WHEN (MF.EQUATION_CD IN ('19-1', '19-3', '19-3D', '19-4', '19-5', '19-5D', 'F-5')) THEN HOD.FD_FACTOR 
					 WHEN (MF.EQUATION_CD = '19-2') THEN FW_FACTOR 
				END AS F_FACTOR, 
		        MF.EQUATION_CD AS nox_rate_formula_cd, 
				DHV.UNADJUSTED_HRLY_VALUE AS RPT_UNADJ_NOX_RATE, 
				DHV.CALC_UNADJUSTED_HRLY_VALUE AS CALC_UNADJ_NOX_RATE, 
				DHV.APPLICABLE_BIAS_ADJ_FACTOR AS CALC_NOX_BAF, 
				DHV.ADJUSTED_HRLY_VALUE AS RPT_ADJ_NOX_RATE, 
				DHV.CALC_ADJUSTED_HRLY_VALUE AS CALC_ADJ_NOX_RATE, 
				CASE WHEN NOX_MF.EQUATION_CD = 'F-24A' THEN HI_DHV.CALC_ADJUSTED_HRLY_VALUE 
					 ELSE NULL
				END AS CALC_HI_RATE, 
				CASE WHEN NOX_MF.EQUATION_CD = 'F-24A' THEN NOX_MF.EQUATION_CD
					 ELSE NULL
				END AS nox_mass_formula_cd,
				CASE WHEN NOX_MF.EQUATION_CD = 'F-24A' THEN NOX_DHV.ADJUSTED_HRLY_VALUE
					 ELSE NULL
				END AS RPT_NOX_MASS, 
				CASE WHEN NOX_MF.EQUATION_CD = 'F-24A' THEN NOX_DHV.CALC_ADJUSTED_HRLY_VALUE
					 ELSE NULL
				END AS CALC_NOX_MASS, 
				HOD.ERROR_CODES
		FROM temp_hourly_errors AS HOD 
				INNER JOIN camdecmpswks.DERIVED_HRLY_VALUE AS DHV ON DHV.HOUR_ID = HOD.HOUR_ID AND DHV.PARAMETER_CD = 'NOXR' AND DHV.MODC_CD IS NOT NULL
				LEFT OUTER JOIN camdecmpswks.DERIVED_HRLY_VALUE AS NOX_DHV ON HOD.HOUR_ID = NOX_DHV.HOUR_ID AND NOX_DHV.PARAMETER_CD = 'NOX' 
				LEFT OUTER JOIN camdecmpswks.DERIVED_HRLY_VALUE AS HI_DHV ON HOD.HOUR_ID = HI_DHV.HOUR_ID AND HI_DHV.PARAMETER_CD = 'HI' 
				LEFT OUTER JOIN camdecmpswks.MONITOR_HRLY_VALUE AS NOXC_MHV ON HOD.HOUR_ID = NOXC_MHV.HOUR_ID AND NOXC_MHV.PARAMETER_CD = 'NOXC' AND NOXC_MHV.MODC_CD NOT IN ('47', '48')
				LEFT OUTER JOIN camdecmpswks.MONITOR_FORMULA AS MF ON DHV.MON_FORM_ID = MF.MON_FORM_ID 
				LEFT OUTER JOIN camdecmpswks.MONITOR_FORMULA AS NOX_MF ON NOX_DHV.MON_FORM_ID = NOX_MF.MON_FORM_ID
				LEFT OUTER JOIN camdecmpswks.MONITOR_HRLY_VALUE AS MHV_CO2C ON DHV.HOUR_ID = MHV_CO2C.HOUR_ID AND MHV_CO2C.PARAMETER_CD = 'CO2C' AND MHV_CO2C.MODC_CD NOT IN ('47', '48')
		        LEFT OUTER JOIN camdecmpswks.MONITOR_HRLY_VALUE AS MHV_O2C_DRY ON DHV.HOUR_ID = MHV_O2C_DRY.HOUR_ID AND MHV_O2C_DRY.PARAMETER_CD = 'O2C' AND ((MHV_O2C_DRY.MOISTURE_BASIS IS NULL) OR (MHV_O2C_DRY.MOISTURE_BASIS = 'D')) AND MHV_O2C_DRY.MODC_CD NOT IN ('47', '48') 
				LEFT OUTER JOIN camdecmpswks.MONITOR_HRLY_VALUE AS MHV_O2C_WET ON DHV.HOUR_ID = MHV_O2C_WET.HOUR_ID AND MHV_O2C_WET.PARAMETER_CD = 'O2C' AND ((MHV_O2C_WET.MOISTURE_BASIS IS NULL) OR (MHV_O2C_WET.MOISTURE_BASIS = 'W')) AND MHV_O2C_WET.MODC_CD NOT IN ('47', '48')                              
				LEFT OUTER JOIN camdecmpswks.MONITOR_HRLY_VALUE AS H2O_MHV ON DHV.HOUR_ID = H2O_MHV.HOUR_ID AND H2O_MHV.PARAMETER_CD = 'H2O' 
				LEFT OUTER JOIN camdecmpswks.DERIVED_HRLY_VALUE AS H2O_DHV ON DHV.HOUR_ID = H2O_DHV.HOUR_ID AND H2O_DHV.PARAMETER_CD = 'H2O' 
				LEFT OUTER JOIN camdecmpswks.MONITOR_DEFAULT AS H2O_MD ON HOD.MON_LOC_ID = H2O_MD.MON_LOC_ID AND H2O_MD.DEFAULT_PURPOSE_CD = 'PM' AND H2O_MD.PARAMETER_CD = 'H2O' AND (camdecmpswks.emissions_monitor_default_active(H2O_MD.BEGIN_DATE, H2O_MD.BEGIN_HOUR, H2O_MD.END_DATE, H2O_MD.END_HOUR, HOD.BEGIN_DATE, HOD.BEGIN_HOUR) = 1)
				LEFT OUTER JOIN camdecmpswks.MONITOR_DEFAULT AS DEF_CO2N ON HOD.MON_LOC_ID = DEF_CO2N.MON_LOC_ID AND DEF_CO2N.DEFAULT_PURPOSE_CD = 'DC' AND DEF_CO2N.PARAMETER_CD = 'CO2N' AND (camdecmpswks.emissions_monitor_default_active(DEF_CO2N.BEGIN_DATE, DEF_CO2N.BEGIN_HOUR, DEF_CO2N.END_DATE, DEF_CO2N.END_HOUR, HOD.BEGIN_DATE, HOD.BEGIN_HOUR) = 1)
				LEFT OUTER JOIN camdecmpswks.MONITOR_DEFAULT AS DEF_O2X ON HOD.MON_LOC_ID = DEF_O2X.MON_LOC_ID AND DEF_O2X.DEFAULT_PURPOSE_CD = 'DC' AND DEF_O2X.PARAMETER_CD = 'O2X' AND (camdecmpswks.emissions_monitor_default_active(DEF_O2X.BEGIN_DATE, DEF_O2X.BEGIN_HOUR, DEF_O2X.END_DATE, DEF_O2X.END_HOUR, HOD.BEGIN_DATE, HOD.BEGIN_HOUR) = 1);
END
$BODY$;
