-- PROCEDURE: camdecmpswks.refresh_emission_view_lme(character varying, numeric)

-- DROP PROCEDURE camdecmpswks.refresh_emission_view_lme(character varying, numeric);

CREATE OR REPLACE PROCEDURE camdecmpswks.refresh_emission_view_lme(
	vmonplanid character varying,
	vrptperiodid numeric)
LANGUAGE 'plpgsql'
AS $BODY$
BEGIN
	DELETE FROM camdecmpswks.EMISSION_VIEW_LME 
		WHERE MON_PLAN_ID = vmonplanid AND RPT_PERIOD_ID = vrptperiodid;

	INSERT INTO camdecmpswks.EMISSION_VIEW_LME
           (MON_PLAN_ID
           ,MON_LOC_ID
           ,RPT_PERIOD_ID
           ,DATE_HOUR
           ,OP_TIME
           ,UNIT_LOAD
           ,LOAD_UOM
           ,HOUR_ID
		   ,HI_MODC
           ,RPT_HEAT_INPUT
           ,CALC_HEAT_INPUT
           ,SO2M_FUEL_TYPE
           ,SO2_EMISS_RATE
           ,RPT_SO2_MASS
           ,CALC_SO2_MASS
           ,NOXM_FUEL_TYPE
           ,OPERATING_CONDITION_CD
           ,NOX_EMISS_RATE
           ,RPT_NOX_MASS
           ,CALC_NOX_MASS
           ,CO2M_FUEL_TYPE
           ,CO2_EMISS_RATE
           ,RPT_CO2_MASS
           ,CALC_CO2_MASS
           ,ERROR_CODES)
		
		SELECT DISTINCT
				HOD.MON_PLAN_ID,
				HOD.MON_LOC_ID,
				HOD.RPT_PERIOD_ID,
				camdecmpswks.format_date_hour(hod.BEGIN_DATE, hod.BEGIN_HOUR, null),
				HOD.OP_TIME,
				HOD.HR_LOAD as UNIT_LOAD,
				HOD.LOAD_UOM_CD as LOAD_UOM,
				HOD.HOUR_ID,
				HIT_DHV.MODC_CD as HI_MODC,
				HIT_DHV.ADJUSTED_HRLY_VALUE AS RPT_HEAT_INPUT,
				HIT_DHV.CALC_ADJUSTED_HRLY_VALUE AS CALC_HEAT_INPUT,
				SO2M_DHV.FUEL_CD as SO2M_FUEL_TYPE,
				SO2R_MD.DEFAULT_VALUE as SO2_EMISS_RATE,
				SO2M_DHV.ADJUSTED_HRLY_VALUE AS RPT_SO2_MASS,
				SO2M_DHV.CALC_ADJUSTED_HRLY_VALUE AS CALC_SO2_MASS,
				NOXM_DHV.FUEL_CD as NOXM_FUEL_TYPE,
				NOXM_DHV.OPERATING_CONDITION_CD,
				CASE
					WHEN NOXR_MD.MON_LOC_ID IS NOT NULL THEN NOXR_MD.DEFAULT_VALUE
					WHEN NORX_MD.MON_LOC_ID IS NOT NULL THEN NORX_MD.DEFAULT_VALUE
					ELSE NULL
				END as NOX_EMISS_RATE,
				NOXM_DHV.ADJUSTED_HRLY_VALUE as RPT_NOX_MASS,
				NOXM_DHV.CALC_ADJUSTED_HRLY_VALUE as CALC_NOX_MASS,
				CO2M_DHV.FUEL_CD as CO2M_FUEL_TYPE,
				CO2R_MD.DEFAULT_VALUE as CO2_EMISS_RATE,
				CO2M_DHV.ADJUSTED_HRLY_VALUE as RPT_CO2_MASS,
				CO2M_DHV.CALC_ADJUSTED_HRLY_VALUE as CALC_CO2_MASS,
				HOD.ERROR_CODES
		FROM temp_hourly_errors AS HOD 
				LEFT OUTER JOIN camdecmpswks.DERIVED_HRLY_VALUE AS HIT_DHV ON HOD.HOUR_ID = HIT_DHV.HOUR_ID AND HIT_DHV.PARAMETER_CD = 'HIT' --'HIT'
				LEFT OUTER JOIN camdecmpswks.DERIVED_HRLY_VALUE AS SO2M_DHV on HOD.HOUR_ID = SO2M_DHV.HOUR_ID AND SO2M_DHV.PARAMETER_CD = 'SO2M' --'SO2M'
				LEFT OUTER JOIN camdecmpswks.MONITOR_DEFAULT as SO2R_MD on HOD.MON_LOC_ID = SO2R_MD.MON_LOC_ID AND (camdecmpswks.emissions_monitor_default_active(SO2R_MD.BEGIN_DATE, SO2R_MD.BEGIN_HOUR, SO2R_MD.END_DATE, SO2R_MD.END_HOUR, HOD.BEGIN_DATE, HOD.BEGIN_HOUR) = 1) 
					AND SO2R_MD.DEFAULT_PURPOSE_CD = 'LM' AND SO2R_MD.DEFAULT_UOM_CD = 'LBMMBTU' AND SO2R_MD.FUEL_CD = SO2M_DHV.FUEL_CD AND SO2R_MD.PARAMETER_CD = 'SO2R' -- 'SO2R' 
				LEFT OUTER JOIN camdecmpswks.DERIVED_HRLY_VALUE AS NOXM_DHV on HOD.HOUR_ID = NOXM_DHV.HOUR_ID AND NOXM_DHV.PARAMETER_CD = 'NOXM' -- 'NOXM'
				LEFT OUTER JOIN camdecmpswks.MONITOR_DEFAULT as NOXR_MD 
					on	NOXR_MD.MON_LOC_ID = HOD.MON_LOC_ID 
						AND (camdecmpswks.emissions_monitor_default_active(NOXR_MD.BEGIN_DATE, NOXR_MD.BEGIN_HOUR, NOXR_MD.END_DATE, NOXR_MD.END_HOUR, HOD.BEGIN_DATE, HOD.BEGIN_HOUR) = 1) 
						AND NOXR_MD.PARAMETER_CD = 'NOXR'
						AND NOXR_MD.DEFAULT_PURPOSE_CD = 'LM' 
						AND NOXR_MD.DEFAULT_UOM_CD = 'LBMMBTU' 
						AND NOXR_MD.FUEL_CD = NOXM_DHV.FUEL_CD 
						AND NOXR_MD.OPERATING_CONDITION_CD != 'U'
						AND NOXR_MD.OPERATING_CONDITION_CD = Coalesce(NOXM_DHV.OPERATING_CONDITION_CD,'A')  
				LEFT OUTER JOIN camdecmpswks.MONITOR_DEFAULT as NORX_MD 
					on	NORX_MD.MON_LOC_ID = HOD.MON_LOC_ID 
						AND (camdecmpswks.emissions_monitor_default_active(NORX_MD.BEGIN_DATE, NORX_MD.BEGIN_HOUR, NORX_MD.END_DATE, NORX_MD.END_HOUR, HOD.BEGIN_DATE, HOD.BEGIN_HOUR) = 1) 
						AND NORX_MD.PARAMETER_CD = 'NORX'
						AND NORX_MD.DEFAULT_PURPOSE_CD = 'MD' 
						AND NORX_MD.DEFAULT_UOM_CD = 'LBMMBTU' 
						AND NORX_MD.FUEL_CD = NOXM_DHV.FUEL_CD 
						AND NORX_MD.OPERATING_CONDITION_CD = 'U' 
				LEFT OUTER JOIN camdecmpswks.DERIVED_HRLY_VALUE as CO2M_DHV on HOD.HOUR_ID = CO2M_DHV.HOUR_ID AND CO2M_DHV.PARAMETER_CD = 'CO2M' --'CO2M'
				LEFT OUTER JOIN camdecmpswks.MONITOR_DEFAULT as CO2R_MD on HOD.MON_LOC_ID = CO2R_MD.MON_LOC_ID AND (camdecmpswks.emissions_monitor_default_active(CO2R_MD.BEGIN_DATE, CO2R_MD.BEGIN_HOUR, CO2R_MD.END_DATE, CO2R_MD.END_HOUR, HOD.BEGIN_DATE, HOD.BEGIN_HOUR) = 1) 
					AND CO2R_MD.DEFAULT_PURPOSE_CD = 'LM' AND CO2R_MD.DEFAULT_UOM_CD ='TNMMBTU' AND CO2R_MD.FUEL_CD = CO2M_DHV.FUEL_CD AND CO2R_MD.PARAMETER_CD = 'CO2R' -- 'CO2R' 
		WHERE HOD.HOUR_ID in (SELECT HOUR_ID FROM camdecmpswks.DERIVED_HRLY_VALUE WHERE PARAMETER_CD in ('SO2M', 'NOXM', 'CO2M','HIT'));
END
$BODY$;
