-- PROCEDURE: camdecmpswks.refresh_emission_view_matsso2(character varying, numeric)

DROP PROCEDURE IF EXISTS camdecmpswks.refresh_emission_view_matsso2(character varying, numeric);

CREATE OR REPLACE PROCEDURE camdecmpswks.refresh_emission_view_matsso2(
	vmonplanid character varying,
	vrptperiodid numeric
)
LANGUAGE 'plpgsql'
AS $BODY$
BEGIN
	CALL camdecmpswks.load_temp_hourly_test_errors(vMonPlanId, vRptPeriodId);

	DELETE FROM camdecmpswks.EMISSION_VIEW_MATSSO2
	WHERE MON_PLAN_ID = vmonplanid AND RPT_PERIOD_ID = vrptperiodid;

	INSERT INTO camdecmpswks.EMISSION_VIEW_MATSSO2(
		MON_PLAN_ID,
		MON_LOC_ID,
		RPT_PERIOD_ID,
		DATE_HOUR,
		OP_TIME,
		MATS_LOAD,
		MATS_STARTUP_SHUTDOWN,
		SO2_CONC_VALUE,
		SO2_CONC_MODC_CD,
		SO2_CONC_PMA,
		FLOW_RATE,
		FLOW_MODC,
		FLOW_PMA,
		RPT_PCT_DILUENT,
		DILUENT_PARAMETER,
		CALC_PCT_DILUENT,
		DILUENT_MODC,
		CALC_PCT_H2O,
		H2O_SOURCE,
		F_FACTOR,
		SO2_FORMULA_CD,
		RPT_SO2_RATE,
		CALC_SO2_RATE,
		SO2_UOM,
		SO2_MODC_CD,
		ERROR_CODES
	)
	SELECT
		HOD.MON_PLAN_ID, 
		HOD.MON_LOC_ID, 
		HOD.RPT_PERIOD_ID, 
		camdecmpswks.format_date_hour(hod.BEGIN_DATE, hod.BEGIN_HOUR, null),
		HOD.OP_TIME, 
		HOD.MATS_LOAD,
		HOD.MATS_STARTUP_SHUTDOWN,
		SO2C_MHV.UNADJUSTED_HRLY_VALUE AS SO2_CONC_VALUE,
		SO2C_MHV.MODC_CD AS SO2_CONC_MODC_CD,
		SO2C_MHV.PCT_AVAILABLE AS SO2_CONC_PMA, 
		FLOW.UNADJUSTED_HRLY_VALUE AS FLOW_RATE,
		FLOW.MODC_CD AS FLOW_MODC,
		FLOW.PCT_AVAILABLE AS FLOW_PMA,
		CASE 
			WHEN (DHV.PARAMETER_CD IN ('HCLRE', 'SO2RE', 'HGRE' )) THEN NULL
		    WHEN (DHV.PARAMETER_CD IN ('HCLRH', 'SO2RH', 'HGRH' )) THEN 
				CASE
					WHEN MF.EQUATION_CD IN ('19-6', '19-7', '19-8', '19-9') THEN CO2C.UNADJUSTED_HRLY_VALUE
				    WHEN MF.EQUATION_CD IN ('19-1', '19-4') THEN O2D.UNADJUSTED_HRLY_VALUE
					WHEN MF.EQUATION_CD IN ('19-2', '19-3', '19-3D', '19-5', '19-5D') THEN O2W.UNADJUSTED_HRLY_VALUE
					ELSE NULL
				END
			ELSE NULL
		END AS RPT_PCT_DILUENT,
		CASE 
			WHEN (DHV.PARAMETER_CD IN ('HCLRE', 'SO2RE', 'HGRE' )) THEN NULL
		    WHEN (DHV.PARAMETER_CD IN ('HCLRH', 'SO2RH', 'HGRH' )) THEN 
				CASE 
					WHEN MF.EQUATION_CD IN ('19-6', '19-7', '19-8', '19-9') THEN 'CO2'
					WHEN MF.EQUATION_CD IN ('19-1', '19-2', '19-3', '19-3D', '19-4', '19-5', '19-5D') THEN 'O2'
					ELSE NULL
				END
			ELSE NULL
		END AS DILUENT_PARAMETER,
		DHV.CALC_PCT_DILUENT AS CALC_PCT_DILUENT,
		CASE 
			WHEN (DHV.PARAMETER_CD IN ('HCLRE', 'SO2RE', 'HGRE' )) THEN NULL
		    WHEN (DHV.PARAMETER_CD IN ('HCLRH', 'SO2RH', 'HGRH' )) THEN 
				CASE 
					WHEN MF.EQUATION_CD IN ('19-6', '19-7', '19-8', '19-9') THEN CO2C.MODC_CD 
				    WHEN MF.EQUATION_CD IN ('19-1', '19-4') THEN O2D.MODC_CD
					WHEN MF.EQUATION_CD IN ('19-2', '19-3', '19-3D', '19-5', '19-5D') THEN O2W.MODC_CD
					ELSE NULL 
				END
			ELSE NULL
		END AS DILUENT_MODC,
		DHV.CALC_PCT_MOISTURE AS CALC_PCT_H2O,
		CASE 
			WHEN DHV.CALC_PCT_MOISTURE IS NULL THEN NULL 
			WHEN H2OD.MODC_CD IS NOT NULL THEN H2OD.MODC_CD
			WHEN H2OM.MODC_CD IS NOT NULL THEN H2OM.MODC_CD
			ELSE 'DF'
		END AS H2O_SOURCE,
		CASE 
			WHEN (DHV.PARAMETER_CD IN ('HCLRE', 'SO2RE', 'HGRE' )) THEN NULL
		    WHEN (DHV.PARAMETER_CD IN ('HCLRH', 'SO2RH', 'HGRH' )) THEN 
				CASE
					WHEN MF.EQUATION_CD IN ('19-6', '19-7', '19-8', '19-9') THEN HOD.FC_FACTOR
					WHEN MF.EQUATION_CD IN ('19-1', '19-3', '19-3D', '19-4', '19-5', '19-5D') THEN HOD.FD_FACTOR
				    WHEN MF.EQUATION_CD IN ('19-2') THEN HOD.FW_FACTOR
					ELSE NULL
				END
			ELSE NULL
		END AS F_FACTOR,
		MF.EQUATION_CD AS SO2_FORMULA_CD,
		DHV.UNADJUSTED_HRLY_VALUE AS RPT_SO2_RATE,
		DHV.CALC_UNADJUSTED_HRLY_VALUE AS CALC_RPT_SO2_RATE,
		CASE 
			WHEN DHV.PARAMETER_CD = 'HGRE' THEN 'lb/GWh'
			WHEN DHV.PARAMETER_CD = 'HGRH' THEN 'lb/TBtu'
			WHEN DHV.PARAMETER_CD IN ('HCLRE', 'HFRE', 'SO2RE') THEN 'lb/MWh'
			WHEN DHV.PARAMETER_CD IN ('HCLRH', 'HFRH', 'SO2RH') THEN 'lb/mmBtu'
		END AS SO2_UOM,
		DHV.MODC_CD SO2_MODC_CD,
		HOD.ERROR_CODES
	FROM temp_hourly_test_errors AS HOD 
	JOIN camdecmpswks.MATS_DERIVED_HRLY_VALUE AS DHV 
		ON HOD.HOUR_ID = DHV.HOUR_ID
		AND HOD.MON_LOC_ID = DHV.MON_LOC_ID
		AND HOD.RPT_PERIOD_ID = DHV.RPT_PERIOD_ID
		AND DHV.PARAMETER_CD IN ( 'SO2RE', 'SO2RH' )
	LEFT JOIN camdecmpswks.MONITOR_HRLY_VALUE AS SO2C_MHV 
		ON HOD.HOUR_ID = SO2C_MHV.HOUR_ID
		AND HOD.MON_LOC_ID = SO2C_MHV.MON_LOC_ID
		AND HOD.RPT_PERIOD_ID = SO2C_MHV.RPT_PERIOD_ID
		AND SO2C_MHV.PARAMETER_CD = 'SO2C'
	LEFT JOIN camdecmpswks.DERIVED_HRLY_VALUE AS H2OD 
		ON HOD.HOUR_ID = H2OD.HOUR_ID
		AND HOD.MON_LOC_ID = H2OD.MON_LOC_ID
		AND HOD.RPT_PERIOD_ID = H2OD.RPT_PERIOD_ID
		AND H2OD.PARAMETER_CD = 'H2O'
	LEFT JOIN camdecmpswks.MONITOR_FORMULA AS MF 
		ON MF.MON_FORM_ID = DHV.MON_FORM_ID
	LEFT JOIN camdecmpswks.MONITOR_HRLY_VALUE AS CO2C 
		ON HOD.HOUR_ID = CO2C.HOUR_ID
		AND HOD.MON_LOC_ID = CO2C.MON_LOC_ID
		AND HOD.RPT_PERIOD_ID = CO2C.RPT_PERIOD_ID
		AND CO2C.PARAMETER_CD = 'CO2C'
	LEFT JOIN camdecmpswks.MONITOR_HRLY_VALUE AS FLOW 
		ON HOD.HOUR_ID = FLOW.HOUR_ID
		AND HOD.MON_LOC_ID = FLOW.MON_LOC_ID
		AND HOD.RPT_PERIOD_ID = FLOW.RPT_PERIOD_ID
		AND FLOW.PARAMETER_CD = 'FLOW'
	LEFT JOIN camdecmpswks.MONITOR_HRLY_VALUE AS H2OM 
		ON HOD.HOUR_ID = H2OM.HOUR_ID
		AND HOD.MON_LOC_ID = H2OM.MON_LOC_ID
		AND HOD.RPT_PERIOD_ID = H2OM.RPT_PERIOD_ID
		AND H2OM.PARAMETER_CD = 'H2O'
	LEFT JOIN camdecmpswks.MONITOR_HRLY_VALUE AS O2D 
		ON HOD.HOUR_ID = O2D.HOUR_ID
		AND HOD.MON_LOC_ID = O2D.MON_LOC_ID
		AND HOD.RPT_PERIOD_ID = O2D.RPT_PERIOD_ID
		AND O2D.PARAMETER_CD = 'O2'
		AND O2D.MOISTURE_BASIS = 'D'
	LEFT JOIN camdecmpswks.MONITOR_HRLY_VALUE AS O2W 
		ON HOD.HOUR_ID = O2W.HOUR_ID
		AND HOD.MON_LOC_ID = O2W.MON_LOC_ID
		AND HOD.RPT_PERIOD_ID = O2W.RPT_PERIOD_ID
		AND O2W.PARAMETER_CD = 'O2'
		AND O2W.MOISTURE_BASIS = 'W';

  CALL camdecmpswks.refresh_emission_view_count(vmonplanid, vrptperiodid, 'MATSSO2');
END
$BODY$;
