-- PROCEDURE: camdecmpswks.refresh_emission_view_noxmasscems(character varying, numeric)

DROP PROCEDURE IF EXISTS camdecmpswks.refresh_emission_view_noxmasscems(character varying, numeric);

CREATE OR REPLACE PROCEDURE camdecmpswks.refresh_emission_view_noxmasscems(
	vmonplanid character varying,
	vrptperiodid numeric
)
LANGUAGE 'plpgsql'
AS $BODY$
BEGIN
	DELETE FROM camdecmpswks.EMISSION_VIEW_NOXMASSCEMS 
	WHERE MON_PLAN_ID = vmonplanid AND RPT_PERIOD_ID = vrptperiodid;

	INSERT INTO camdecmpswks.EMISSION_VIEW_NOXMASSCEMS(
		MON_PLAN_ID,
		MON_LOC_ID,
		RPT_PERIOD_ID,
		DATE_HOUR,
		OP_TIME,
		UNIT_LOAD,
		LOAD_UOM,
		UNADJ_NOX,
		CALC_NOX_BAF,
		RPT_ADJ_NOX,
		ADJ_NOX_USED,
		NOX_MODC,
		NOX_PMA,
		UNADJ_FLOW,
		CALC_FLOW_BAF,
		RPT_ADJ_FLOW,
		ADJ_FLOW_USED,
		FLOW_MODC,
		FLOW_PMA,
		PCT_H2O_USED,
		SOURCE_H2O_VALUE,
		NOX_MASS_FORMULA_CD,
		RPT_NOX_MASS,
		CALC_NOX_MASS,
		ERROR_CODES
	)
	SELECT DISTINCT
		HOD.MON_PLAN_ID, 
		HOD.MON_LOC_ID, 
		HOD.RPT_PERIOD_ID, 
		camdecmpswks.format_date_hour(hod.BEGIN_DATE, hod.BEGIN_HOUR, null) AS DATE_HOUR,
		HOD.OP_TIME, 
		HOD.HR_LOAD AS UNIT_LOAD, 
		HOD.LOAD_UOM_CD AS LOAD_UOM, 
		NOXC_MHV.UNADJUSTED_HRLY_VALUE AS UNADJ_NOX,
		NOXC_MHV.APPLICABLE_BIAS_ADJ_FACTOR AS CALC_NOX_BAF,
		NOXC_MHV.ADJUSTED_HRLY_VALUE AS RPT_ADJ_NOX,
		NOXC_MHV.CALC_ADJUSTED_HRLY_VALUE AS ADJ_NOX_USED,
		NOXC_MHV.MODC_CD AS NOX_MODC,
		NOXC_MHV.PCT_AVAILABLE AS NOX_PMA,
		FLOW_MHV.UNADJUSTED_HRLY_VALUE AS UNADJ_FLOW,
		FLOW_MHV.APPLICABLE_BIAS_ADJ_FACTOR AS CALC_FLOW_BAF,
		FLOW_MHV.ADJUSTED_HRLY_VALUE AS RPT_ADJ_FLOW,
		FLOW_MHV.CALC_ADJUSTED_HRLY_VALUE AS ADJ_FLOW_USED,
		FLOW_MHV.MODC_CD AS FLOW_MODC,
		FLOW_MHV.PCT_AVAILABLE AS FLOW_PMA,
		DHV.CALC_PCT_MOISTURE AS PCT_H2O_USED, 
		CASE 
			WHEN (DHV.CALC_PCT_MOISTURE IS NOT NULL) THEN 
				CASE 
					WHEN (H2O_MHV.MODC_CD IS NOT NULL) THEN H2O_MHV.MODC_CD 
					WHEN (H2O_DHV.MODC_CD IS NOT NULL) THEN H2O_DHV.MODC_CD 
					ELSE 'DF'
				END 
			ELSE NULL
		END AS SOURCE_H2O_VALUE, 
		MF.EQUATION_CD AS NOX_MASS_FORMULA_CD,
		DHV.ADJUSTED_HRLY_VALUE AS RPT_NOX_MASS,
		DHV.CALC_ADJUSTED_HRLY_VALUE AS CALC_NOX_MASS,
		HOD.ERROR_CODES
	FROM temp_hourly_errors HOD 
	INNER JOIN camdecmpswks.DERIVED_HRLY_VALUE  DHV 
		ON DHV.HOUR_ID = HOD.HOUR_ID AND DHV.PARAMETER_CD = 'NOX'
	INNER JOIN camdecmpswks.MONITOR_HRLY_VALUE  FLOW_MHV 
		ON DHV.HOUR_ID = FLOW_MHV.HOUR_ID AND FLOW_MHV.PARAMETER_CD = 'FLOW'
	INNER JOIN camdecmpswks.MONITOR_FORMULA  MF 
		ON DHV.MON_FORM_ID = MF.MON_FORM_ID AND MF.EQUATION_CD LIKE 'F-26%'		
	LEFT OUTER JOIN camdecmpswks.MONITOR_HRLY_VALUE  NOXC_MHV 
		ON DHV.HOUR_ID = NOXC_MHV.HOUR_ID AND NOXC_MHV.PARAMETER_CD = 'NOXC'
	LEFT OUTER JOIN camdecmpswks.MONITOR_HRLY_VALUE  H2O_MHV 
		ON DHV.HOUR_ID = H2O_MHV.HOUR_ID AND H2O_MHV.PARAMETER_CD = 'H2O' 
	LEFT OUTER JOIN camdecmpswks.DERIVED_HRLY_VALUE  H2O_DHV 
		ON DHV.HOUR_ID = H2O_DHV.HOUR_ID AND H2O_DHV.PARAMETER_CD = 'H2O' 
	LEFT OUTER JOIN camdecmpswks.MONITOR_DEFAULT  H2O_MD 
		ON HOD.MON_LOC_ID = H2O_MD.MON_LOC_ID AND H2O_MD.DEFAULT_PURPOSE_CD = 'PM' AND H2O_MD.PARAMETER_CD = 'H2O' 
		AND camdecmpswks.emissions_monitor_default_active(H2O_MD.BEGIN_DATE, H2O_MD.BEGIN_HOUR, H2O_MD.END_DATE, H2O_MD.END_HOUR, HOD.BEGIN_DATE, HOD.BEGIN_HOUR) = 1
	LEFT OUTER JOIN camdecmpswks.DERIVED_HRLY_VALUE  NOXR_DHV 
		ON DHV.HOUR_ID = NOXR_DHV.HOUR_ID AND NOXR_DHV.PARAMETER_CD = 'NOXR';
END
$BODY$;
