-- PROCEDURE: camdecmpswks.refresh_emission_view_noxappesinglefuel(character varying, numeric)

DROP PROCEDURE IF EXISTS camdecmpswks.refresh_emission_view_noxappesinglefuel(character varying, numeric);

CREATE OR REPLACE PROCEDURE camdecmpswks.refresh_emission_view_noxappesinglefuel(
	vmonplanid character varying,
	vrptperiodid numeric)
LANGUAGE 'plpgsql'
AS $BODY$
BEGIN
	DELETE FROM camdecmpswks.EMISSION_VIEW_NOXAPPESINGLEFUEL 
		WHERE MON_PLAN_ID = vmonplanid AND RPT_PERIOD_ID = vrptperiodid;

	INSERT INTO camdecmpswks.EMISSION_VIEW_NOXAPPESINGLEFUEL
           (MON_PLAN_ID
           ,MON_LOC_ID
           ,RPT_PERIOD_ID
           ,DATE_HOUR
           ,OP_TIME
           ,FUEL_SYS_ID
           ,FUEL_TYPE
           ,FUEL_USE_TIME
           ,UNIT_LOAD
           ,LOAD_UOM
           ,CALC_HI_RATE
           ,OPERATING_CONDITION_CD
           ,SEGMENT_NUMBER
           ,APP_E_SYS_ID
           ,RPT_NOX_EMISSION_RATE
           ,CALC_NOX_EMISSION_RATE
           ,SUMMATION_FORMULA_CD
           ,RPT_NOX_EMISSION_RATE_ALL_FUELS
           ,CALC_NOX_EMISSION_RATE_ALL_FUELS
           ,CALC_HI_RATE_ALL_FUELS
           ,NOX_MASS_RATE_FORMULA_CD
           ,RPT_NOX_MASS_ALL_FUELS
           ,CALC_NOX_MASS_ALL_FUELS
           ,ERROR_CODES)
		
		SELECT DISTINCT
				HOD.MON_PLAN_ID, 
				HOD.MON_LOC_ID, 
				HOD.RPT_PERIOD_ID,
				camdecmpswks.format_date_hour(hod.BEGIN_DATE, hod.BEGIN_HOUR, null),
				HOD.OP_TIME,
				MS.SYSTEM_IDENTIFIER AS FUEL_SYS_ID,
				HFF.FUEL_CD AS FUEL_TYPE,
				HFF.FUEL_USAGE_TIME AS FUEL_USE_TIME,
				HOD.HR_LOAD AS UNIT_LOAD, 
				HOD.LOAD_UOM_CD AS LOAD_UOM, 
				HPFF_HI.CALC_PARAM_VAL_FUEL AS CALC_HI_RATE,
				HPFF_NOXR.OPERATING_CONDITION_CD,
				HPFF_NOXR.SEGMENT_NUM AS SEGMENT_NUMBER,
				MS_NOXR.SYSTEM_IDENTIFIER AS APP_E_SYS_ID,
				HPFF_NOXR.PARAM_VAL_FUEL AS RPT_NOX_EMISSION_RATE,
				HPFF_NOXR.CALC_PARAM_VAL_FUEL AS CALC_NOX_EMISSION_RATE,
				NOXR_MF.EQUATION_CD AS SUMMATION_FORMULA_CD,
				DHV_NOXR.ADJUSTED_HRLY_VALUE AS RPT_NOX_EMISSION_RATE_ALL_FUELS,
				DHV_NOXR.CALC_ADJUSTED_HRLY_VALUE AS CALC_NOX_EMISSION_RATE_ALL_FUELS,
				CASE WHEN (DHV_NOX.HOUR_ID IS NOT NULL) THEN DHV_HI.CALC_ADJUSTED_HRLY_VALUE END AS CALC_HI_RATE_ALL_FUELS,
				NOX_MF.EQUATION_CD AS NOX_MASS_RATE_FORMULA_CD,
				DHV_NOX.ADJUSTED_HRLY_VALUE AS RPT_NOX_MASS_ALL_FUELS,
				DHV_NOX.CALC_ADJUSTED_HRLY_VALUE AS CALC_NOX_MASS_ALL_FUELS,
				HOD.ERROR_CODES
		FROM temp_hourly_errors AS HOD 
				INNER JOIN camdecmpswks.HRLY_FUEL_FLOW HFF ON HOD.HOUR_ID = HFF.HOUR_ID
				INNER JOIN camdecmpswks.HRLY_PARAM_FUEL_FLOW HPFF_NOXR ON ((HFF.HRLY_FUEL_FLOW_ID = HPFF_NOXR.HRLY_FUEL_FLOW_ID) AND (HPFF_NOXR.PARAMETER_CD = 'NOXR'))
				LEFT OUTER JOIN camdecmpswks.HRLY_PARAM_FUEL_FLOW HPFF_HI ON ((HFF.HRLY_FUEL_FLOW_ID = HPFF_HI.HRLY_FUEL_FLOW_ID) AND (HPFF_HI.PARAMETER_CD = 'HI'))
				LEFT OUTER JOIN camdecmpswks.DERIVED_HRLY_VALUE DHV_NOXR ON ((DHV_NOXR.HOUR_ID = HOD.HOUR_ID) AND (DHV_NOXR.PARAMETER_CD = 'NOXR'))
				LEFT OUTER JOIN camdecmpswks.DERIVED_HRLY_VALUE DHV_HI ON ((DHV_HI.HOUR_ID = HOD.HOUR_ID) AND (DHV_HI.PARAMETER_CD = 'HI'))
				LEFT OUTER JOIN camdecmpswks.DERIVED_HRLY_VALUE DHV_NOX ON ((DHV_NOX.HOUR_ID = HOD.HOUR_ID) AND (DHV_NOX.PARAMETER_CD = 'NOX'))
				LEFT OUTER JOIN camdecmpswks.MONITOR_SYSTEM MS ON HFF.MON_SYS_ID = MS.MON_SYS_ID
				LEFT OUTER JOIN camdecmpswks.MONITOR_SYSTEM MS_NOXR ON HPFF_NOXR.MON_SYS_ID = MS_NOXR.MON_SYS_ID
				LEFT OUTER JOIN camdecmpswks.MONITOR_FORMULA NOXR_MF ON DHV_NOXR.MON_FORM_ID = NOXR_MF.MON_FORM_ID
				LEFT OUTER JOIN camdecmpswks.MONITOR_FORMULA NOX_MF ON DHV_NOX.MON_FORM_ID = NOX_MF.MON_FORM_ID;
END
$BODY$;
