-- PROCEDURE: camdecmpswks.refresh_emission_view_hicems(character varying, numeric)

-- DROP PROCEDURE camdecmpswks.refresh_emission_view_hicems(character varying, numeric);

CREATE OR REPLACE PROCEDURE camdecmpswks.refresh_emission_view_matshcl(
	vmonplanid character varying,
	vrptperiodid numeric)
LANGUAGE 'plpgsql'
AS $BODY$
BEGIN
	DELETE FROM camdecmpswks.EMISSION_VIEW_MATS_HCL 
		WHERE MON_PLAN_ID = vmonplanid AND RPT_PERIOD_ID = vrptperiodid;

	INSERT INTO camdecmpswks.EMISSION_VIEW_MATS_HCL
           (MON_PLAN_ID
           ,MON_LOC_ID
           ,RPT_PERIOD_ID
           ,DATE_HOUR
           ,OP_TIME
           ,MATS_LOAD
           ,MATS_STARTUP_SHUTDOWN
           ,HCL_CONC_VALUE
           ,HCL_CONC_MODC_CD
           ,HCL_CONC_PMA
           ,FLOW_RATE
           ,FLOW_MODC
           ,FLOW_PMA
           ,RPT_PCT_DILUENT
           ,DILUENT_PARAMETER
           ,CALC_PCT_DILUENT
           ,DILUENT_MODC
           ,CALC_PCT_H2O
           ,H2O_SOURCE
           ,F_FACTOR
           ,HCL_FORMULA_CD
           ,RPT_HCL_RATE
           ,CALC_HCL_RATE
           ,HCL_UOM
           ,HCL_MODC_CD
           ,ERROR_CODES)
		SELECT DISTINCT
				HOD.MON_PLAN_ID, 
				HOD.MON_LOC_ID, 
				HOD.RPT_PERIOD_ID, 
				camdecmpswks.format_date_hour(hod.BEGIN_DATE, hod.BEGIN_HOUR, null), 
				HOD.OP_TIME, 
				HOD.MATS_LOAD,		--	MJ EC-2508
                HOD.MATS_STARTUP_SHUTDOWN,
		        MHV.UNADJUSTED_HRLY_VALUE AS HCL_CONC_VALUE, 
				MHV.MODC_CD AS HCL_CONC_MODC_CD,
				MHV.PCT_AVAILABLE AS HCL_CONC_PMA,
				FLOW.UNADJUSTED_HRLY_VALUE AS FLOW_RATE,
				FLOW.MODC_CD AS FLOW_MODC,
				FLOW.PCT_AVAILABLE AS FLOW_PMA,
				CASE WHEN (DHV.PARAMETER_CD IN ('HCLRE', 'HFRE', 'HGRE' )) THEN NULL
				     WHEN (DHV.PARAMETER_CD IN ('HCLRH', 'HFRH', 'HGRH' )) THEN 
						CASE WHEN MF.EQUATION_CD IN ('19-6', '19-7', '19-8', '19-9') THEN CO2C.UNADJUSTED_HRLY_VALUE
						     WHEN MF.EQUATION_CD IN ('19-1', '19-4') THEN O2D.UNADJUSTED_HRLY_VALUE
							 WHEN MF.EQUATION_CD IN ('19-2', '19-3', '19-3D', '19-5', '19-5D') THEN O2W.UNADJUSTED_HRLY_VALUE
							 ELSE NULL END
					 ELSE NULL
					 END AS RPT_PCT_DILUENT,
				CASE WHEN (DHV.PARAMETER_CD IN ('HCLRE', 'HFRE', 'HGRE' )) THEN NULL
				     WHEN (DHV.PARAMETER_CD IN ('HCLRH', 'HFRH', 'HGRH' )) THEN 
						CASE WHEN MF.EQUATION_CD IN ('19-6', '19-7', '19-8', '19-9') THEN 'CO2'
							 WHEN MF.EQUATION_CD IN ('19-1', '19-2', '19-3', '19-3D', '19-4', '19-5', '19-5D') THEN 'O2'
							 ELSE NULL END
					 ELSE NULL
					 END AS DILUENT_PARAMETER,
				DHV.CALC_PCT_DILUENT AS CALC_PCT_DILUENT,
				CASE WHEN (DHV.PARAMETER_CD IN ('HCLRE', 'HFRE', 'HGRE' )) THEN NULL
				     WHEN (DHV.PARAMETER_CD IN ('HCLRH', 'HFRH', 'HGRH' )) THEN 
						CASE WHEN MF.EQUATION_CD IN ('19-6', '19-7', '19-8', '19-9') THEN CO2C.MODC_CD 
						     WHEN MF.EQUATION_CD IN ('19-1', '19-4') THEN O2D.MODC_CD
							 WHEN MF.EQUATION_CD IN ('19-2', '19-3', '19-3D', '19-5', '19-5D') THEN O2W.MODC_CD
							 ELSE NULL END
					 ELSE NULL
					 END AS DILUENT_MODC,
				DHV.CALC_PCT_MOISTURE AS CALC_PCT_H2O,
				CASE 
					WHEN DHV.CALC_PCT_MOISTURE IS NULL THEN NULL 
					WHEN H2OD.MODC_CD IS NOT NULL THEN H2OD.MODC_CD
					WHEN H2OM.MODC_CD IS NOT NULL THEN H2OM.MODC_CD
					ELSE 'DF'
			    END AS H2O_SOURCE,
				CASE WHEN (DHV.PARAMETER_CD IN ('HCLRE', 'HFRE', 'HGRE' )) THEN NULL
				     WHEN (DHV.PARAMETER_CD IN ('HCLRH', 'HFRH', 'HGRH' )) THEN 
						CASE WHEN MF.EQUATION_CD IN ('19-6', '19-7', '19-8', '19-9') THEN HOD.FC_FACTOR
							 WHEN MF.EQUATION_CD IN ('19-1', '19-3', '19-3D', '19-4', '19-5', '19-5D') THEN HOD.FD_FACTOR
						     WHEN MF.EQUATION_CD IN ('19-2') THEN HOD.FW_FACTOR
							 ELSE NULL END
					 ELSE NULL
					END AS F_FACTOR,
				MF.EQUATION_CD AS HCL_FORMULA_CD,
				DHV.UNADJUSTED_HRLY_VALUE AS RPT_HCL_RATE,
				DHV.CALC_UNADJUSTED_HRLY_VALUE AS CALC_HCL_RATE,
 				CASE WHEN DHV.PARAMETER_CD = 'HGRE' THEN 'lb/GWh'
					 WHEN DHV.PARAMETER_CD = 'HGRH' THEN 'lb/TBtu'
					 WHEN DHV.PARAMETER_CD IN ('HCLRE', 'HFRE', 'SO2RE') THEN 'lb/MWh'
					 WHEN DHV.PARAMETER_CD IN ('HCLRH', 'HFRH', 'SO2RH') THEN 'lb/mmBtu'
					 END AS HCL_UOM,
				DHV.MODC_CD HCL_MODC_CD,
				HOD.ERROR_CODES
		FROM temp_hourly_errors AS HOD 
				INNER JOIN camdecmpswks.MATS_MONITOR_HRLY_VALUE AS MHV ON MHV.HOUR_ID = HOD.HOUR_ID AND MHV.PARAMETER_CD = 'HCLC'
				INNER JOIN camdecmpswks.MATS_DERIVED_HRLY_VALUE AS DHV ON DHV.HOUR_ID = HOD.HOUR_ID AND DHV.PARAMETER_CD IN ( 'HCLRE', 'HCLRH' )
				LEFT OUTER JOIN camdecmpswks.DERIVED_HRLY_VALUE AS H2OD ON H2OD.HOUR_ID = HOD.HOUR_ID AND H2OD.PARAMETER_CD = 'H2O'
				LEFT OUTER JOIN camdecmpswks.MONITOR_FORMULA AS MF ON MF.MON_FORM_ID = DHV.MON_FORM_ID
				LEFT OUTER JOIN camdecmpswks.MONITOR_HRLY_VALUE AS CO2C ON CO2C.HOUR_ID = HOD.HOUR_ID AND CO2C.PARAMETER_CD = 'CO2C'
				LEFT OUTER JOIN camdecmpswks.MONITOR_HRLY_VALUE AS FLOW ON FLOW.HOUR_ID = HOD.HOUR_ID AND FLOW.PARAMETER_CD = 'FLOW'
				LEFT OUTER JOIN camdecmpswks.MONITOR_HRLY_VALUE AS H2OM ON H2OM.HOUR_ID = HOD.HOUR_ID AND H2OM.PARAMETER_CD = 'H2O'
				LEFT OUTER JOIN camdecmpswks.MONITOR_HRLY_VALUE AS O2D ON O2D.HOUR_ID = HOD.HOUR_ID AND O2D.PARAMETER_CD = 'O2' AND O2D.MOISTURE_BASIS = 'D'
				LEFT OUTER JOIN camdecmpswks.MONITOR_HRLY_VALUE AS O2W ON O2W.HOUR_ID = HOD.HOUR_ID AND O2W.PARAMETER_CD = 'O2' AND O2W.MOISTURE_BASIS = 'W';
END
$BODY$;
