-- PROCEDURE: camdecmpswks.refresh_emission_view_co2calc(character varying, numeric)

DROP PROCEDURE IF EXISTS camdecmpswks.refresh_emission_view_co2calc(character varying, numeric);

CREATE OR REPLACE PROCEDURE camdecmpswks.refresh_emission_view_co2calc(
	vmonplanid character varying,
	vrptperiodid numeric
)
LANGUAGE 'plpgsql'
AS $BODY$
BEGIN
	DELETE FROM camdecmpswks.EMISSION_VIEW_CO2CALC 
	WHERE MON_PLAN_ID = vmonplanid AND RPT_PERIOD_ID = vrptperiodid;

	INSERT INTO camdecmpswks.EMISSION_VIEW_CO2CALC(
		MON_PLAN_ID,
		MON_LOC_ID,
		RPT_PERIOD_ID,
		DATE_HOUR,
		OP_TIME,
		CO2C_MODC,
		CO2C_PMA,
		RPT_PCT_O2,
		PCT_O2_USED,
		O2_MODC,
		PCT_H2O_USED,
		SOURCE_H2O_VALUE,
		FC_FACTOR,
		FD_FACTOR,
		FORMULA_CD,
		RPT_PCT_CO2,
		CALC_PCT_CO2,
		ERROR_CODES
	)
	SELECT DISTINCT
		HOD.MON_PLAN_ID, 
		HOD.MON_LOC_ID, 
		HOD.RPT_PERIOD_ID, 
		camdecmpswks.format_date_hour(hod.BEGIN_DATE, hod.BEGIN_HOUR, null),
		HOD.OP_TIME,	
		DHV.MODC_CD AS CO2C_MODC,
		DHV.PCT_AVAILABLE AS CO2C_PMA,
		CASE (MF.EQUATION_CD)
			WHEN 'F-14A' THEN DRY_MHV.UNADJUSTED_HRLY_VALUE
			WHEN 'F-14B' THEN WET_MHV.UNADJUSTED_HRLY_VALUE
		END AS RPT_PCT_O2,
		DHV.CALC_PCT_DILUENT AS PCT_O2_USED,
		CASE (MF.EQUATION_CD)
			WHEN 'F-14A' THEN DRY_MHV.MODC_CD
			WHEN 'F-14B' THEN WET_MHV.MODC_CD
		END AS O2_MODC,
		DHV.CALC_PCT_MOISTURE AS PCT_H2O_USED,
		CASE 
			WHEN (DHV.CALC_PCT_MOISTURE IS NOT NULL) THEN 
				CASE 
					WHEN (H2O_DHV.HOUR_ID IS NOT NULL) THEN H2O_DHV.MODC_CD 
					WHEN (H2O_MHV.HOUR_ID IS NOT NULL) THEN H2O_MHV.MODC_CD 
					ELSE 'DF'
				END 
			ELSE NULL
		END AS SOURCE_H2O_VALUE, 
		HOD.FC_FACTOR AS FC_FACTOR,
		HOD.FD_FACTOR AS FD_FACTOR,
		MF.EQUATION_CD AS FORMULA_CD,
		DHV.ADJUSTED_HRLY_VALUE AS RPT_PCT_CO2,
		DHV.CALC_ADJUSTED_HRLY_VALUE AS CALC_PCT_CO2,
		HOD.ERROR_CODES
	FROM temp_hourly_test_errors AS HOD 
	INNER JOIN camdecmpswks.DERIVED_HRLY_VALUE AS DHV 
		ON DHV.HOUR_ID = HOD.HOUR_ID AND DHV.PARAMETER_CD = 'CO2C'
	LEFT OUTER JOIN camdecmpswks.MONITOR_FORMULA AS MF 
		ON DHV.MON_FORM_ID = MF.MON_FORM_ID 
	LEFT OUTER JOIN camdecmpswks.MONITOR_HRLY_VALUE AS H2O_MHV 
		ON DHV.HOUR_ID = H2O_MHV.HOUR_ID AND H2O_MHV.PARAMETER_CD = 'H2O' 
	LEFT OUTER JOIN camdecmpswks.DERIVED_HRLY_VALUE AS H2O_DHV 
		ON DHV.HOUR_ID = H2O_DHV.HOUR_ID AND H2O_DHV.PARAMETER_CD = 'H2O' 
	LEFT OUTER JOIN camdecmpswks.MONITOR_DEFAULT AS H2O_MD 
		ON HOD.MON_LOC_ID = H2O_MD.MON_LOC_ID AND H2O_MD.DEFAULT_PURPOSE_CD = 'PM' AND H2O_MD.PARAMETER_CD = 'H2O' AND
		camdecmpswks.emissions_monitor_default_active(H2O_MD.BEGIN_DATE, H2O_MD.BEGIN_HOUR, H2O_MD.END_DATE, H2O_MD.END_HOUR, HOD.BEGIN_DATE, HOD.BEGIN_HOUR) = 1
	LEFT OUTER JOIN camdecmpswks.MONITOR_HRLY_VALUE AS DRY_MHV 
		ON DHV.HOUR_ID = DRY_MHV.HOUR_ID AND DRY_MHV.PARAMETER_CD = 'O2C' AND DRY_MHV.MOISTURE_BASIS = 'D'
	LEFT OUTER JOIN camdecmpswks.MONITOR_HRLY_VALUE AS WET_MHV 
		ON DHV.HOUR_ID = WET_MHV.HOUR_ID AND WET_MHV.PARAMETER_CD = 'O2C' AND WET_MHV.MOISTURE_BASIS = 'W';
END
$BODY$;
