INSERT INTO camdmd.naics_code (naics_cd, naics_description) VALUES (1, '1 - Other');
INSERT INTO camdmd.naics_code (naics_cd, naics_description) VALUES (221111, '221111 - Hydroelectric power generation');
INSERT INTO camdmd.naics_code (naics_cd, naics_description) VALUES (221112, '221112 - Fossil fuel electric power generation');
INSERT INTO camdmd.naics_code (naics_cd, naics_description) VALUES (221113, '221113 - Nuclear electric power generation');
INSERT INTO camdmd.naics_code (naics_cd, naics_description) VALUES (221117, '221117 - Biomass Electric Power Generation');
INSERT INTO camdmd.naics_code (naics_cd, naics_description) VALUES (221119, '221119 - Other electric power generation');
INSERT INTO camdmd.naics_code (naics_cd, naics_description) VALUES (221121, '221121 - Electric bulk power transmission & control');
INSERT INTO camdmd.naics_code (naics_cd, naics_description) VALUES (221122, '221122 - Electric power distribution');
INSERT INTO camdmd.naics_code (naics_cd, naics_description) VALUES (221210, '221210 - Natural gas distribution');
INSERT INTO camdmd.naics_code (naics_cd, naics_description) VALUES (221320, '221320 - Sewage treatment facilities');
INSERT INTO camdmd.naics_code (naics_cd, naics_description) VALUES (221330, '221330 - Steam & air-conditioning supply');
INSERT INTO camdmd.naics_code (naics_cd, naics_description) VALUES (311221, '311221 - Wet Corn Milling');
INSERT INTO camdmd.naics_code (naics_cd, naics_description) VALUES (311224, '311224 - Soybean and Other Oilseed Processing');
INSERT INTO camdmd.naics_code (naics_cd, naics_description) VALUES (311999, '311999 - All Other Miscellaneous Food Manufacturing');
INSERT INTO camdmd.naics_code (naics_cd, naics_description) VALUES (313210, '313210 - Broadwoven Fabric Mills');
INSERT INTO camdmd.naics_code (naics_cd, naics_description) VALUES (322110, '322110 - Pulp mills');
INSERT INTO camdmd.naics_code (naics_cd, naics_description) VALUES (322121, '322121 - Paper (except newsprint) mills');
INSERT INTO camdmd.naics_code (naics_cd, naics_description) VALUES (322122, '322122 - Newsprint mills');
INSERT INTO camdmd.naics_code (naics_cd, naics_description) VALUES (322130, '322130 - Paperboard mills');
INSERT INTO camdmd.naics_code (naics_cd, naics_description) VALUES (322211, '322211 - Corrugated & solid fiber box mfg');
INSERT INTO camdmd.naics_code (naics_cd, naics_description) VALUES (324110, '324110 - Petroleum refineries');
INSERT INTO camdmd.naics_code (naics_cd, naics_description) VALUES (324199, '324199 - All Other Petroleum and Coal Products Manufacturing');
INSERT INTO camdmd.naics_code (naics_cd, naics_description) VALUES (325110, '325110 - Petrochemical Manufacturing');
INSERT INTO camdmd.naics_code (naics_cd, naics_description) VALUES (325180, '325180 - Other Basic Inorganic Chemical Manufacturing');
INSERT INTO camdmd.naics_code (naics_cd, naics_description) VALUES (325193, '325193 - Ethyl alcohol mfg');
INSERT INTO camdmd.naics_code (naics_cd, naics_description) VALUES (325199, '325199 - All other basic organic chemical mfg');
INSERT INTO camdmd.naics_code (naics_cd, naics_description) VALUES (325211, '325211 - Plastics Material and Resin Manufacturing');
INSERT INTO camdmd.naics_code (naics_cd, naics_description) VALUES (325220, '325220 - Artificial and Synthetic Fibers and Filaments Manufacturing');
INSERT INTO camdmd.naics_code (naics_cd, naics_description) VALUES (325411, '325411 - Medicinal & botanical mfg');
INSERT INTO camdmd.naics_code (naics_cd, naics_description) VALUES (325412, '325412 - Pharmaceutical preparation mfg');
INSERT INTO camdmd.naics_code (naics_cd, naics_description) VALUES (325611, '325611 - Soap & other detergent mfg');
INSERT INTO camdmd.naics_code (naics_cd, naics_description) VALUES (325992, '325992 - Photographic film, paper, plate, & chemical mfg');
INSERT INTO camdmd.naics_code (naics_cd, naics_description) VALUES (327310, '327310 - Cement Manufacturing');
INSERT INTO camdmd.naics_code (naics_cd, naics_description) VALUES (331111, '331111 - Iron & steel mills');
INSERT INTO camdmd.naics_code (naics_cd, naics_description) VALUES (331419, '331419 - Other nonferrous metal primary smelting & refining');
INSERT INTO camdmd.naics_code (naics_cd, naics_description) VALUES (331524, '331524 - Aluminum foundries (except die-casting)');
INSERT INTO camdmd.naics_code (naics_cd, naics_description) VALUES (333611, '333611 - Turbine & turbine generator set unit mfg');
INSERT INTO camdmd.naics_code (naics_cd, naics_description) VALUES (336412, '336412 - Aircraft engine & engine parts mfg');
INSERT INTO camdmd.naics_code (naics_cd, naics_description) VALUES (531110, '531110 - Lessors of Residential Buildings and Dwellings');
INSERT INTO camdmd.naics_code (naics_cd, naics_description) VALUES (611310, '611310 - Colleges, Universities, and Professional Schools');
INSERT INTO camdmd.naics_code (naics_cd, naics_description) VALUES (713110, '713110 - Amusement & theme parks');
INSERT INTO camdmd.naics_code (naics_cd, naics_description) VALUES (928110, '928110 - National Security');
