INSERT INTO camdmd.prime_mover_type_code (prime_mover_type_cd, prime_mover_type_description) VALUES ('AB', 'Atmospheric or pressurized fluidized bed combustion');
INSERT INTO camdmd.prime_mover_type_code (prime_mover_type_cd, prime_mover_type_description) VALUES ('CA', 'Combined Cycle');
INSERT INTO camdmd.prime_mover_type_code (prime_mover_type_cd, prime_mover_type_description) VALUES ('CC', 'Combined Cycle');
INSERT INTO camdmd.prime_mover_type_code (prime_mover_type_cd, prime_mover_type_description) VALUES ('CE', 'Compressed air energy storage');
INSERT INTO camdmd.prime_mover_type_code (prime_mover_type_cd, prime_mover_type_description) VALUES ('CH', 'Steam turbine, common header');
INSERT INTO camdmd.prime_mover_type_code (prime_mover_type_cd, prime_mover_type_description) VALUES ('CS', 'Combined Cycle');
INSERT INTO camdmd.prime_mover_type_code (prime_mover_type_cd, prime_mover_type_description) VALUES ('CT', 'Combined Cycle');
INSERT INTO camdmd.prime_mover_type_code (prime_mover_type_cd, prime_mover_type_description) VALUES ('CW', 'Combined Cycle');
INSERT INTO camdmd.prime_mover_type_code (prime_mover_type_cd, prime_mover_type_description) VALUES ('FC', 'Fuel Cell');
INSERT INTO camdmd.prime_mover_type_code (prime_mover_type_cd, prime_mover_type_description) VALUES ('GB', 'Geothermal Binary');
INSERT INTO camdmd.prime_mover_type_code (prime_mover_type_cd, prime_mover_type_description) VALUES ('GE', 'Geothermal');
INSERT INTO camdmd.prime_mover_type_code (prime_mover_type_cd, prime_mover_type_description) VALUES ('GT', 'Gas turbine');
INSERT INTO camdmd.prime_mover_type_code (prime_mover_type_cd, prime_mover_type_description) VALUES ('HL', 'Hydraulic turbine (hydro)');
INSERT INTO camdmd.prime_mover_type_code (prime_mover_type_cd, prime_mover_type_description) VALUES ('HY', 'Hydraulic turbine (hydro)');
INSERT INTO camdmd.prime_mover_type_code (prime_mover_type_cd, prime_mover_type_description) VALUES ('IC', 'Internal Combustion');
INSERT INTO camdmd.prime_mover_type_code (prime_mover_type_cd, prime_mover_type_description) VALUES ('IG', 'Integrated coal gasification');
INSERT INTO camdmd.prime_mover_type_code (prime_mover_type_cd, prime_mover_type_description) VALUES ('JE', 'Jet engine');
INSERT INTO camdmd.prime_mover_type_code (prime_mover_type_cd, prime_mover_type_description) VALUES ('NB', 'Nuclear');
INSERT INTO camdmd.prime_mover_type_code (prime_mover_type_cd, prime_mover_type_description) VALUES ('NP', 'Nuclear');
INSERT INTO camdmd.prime_mover_type_code (prime_mover_type_cd, prime_mover_type_description) VALUES ('OT', 'Other');
INSERT INTO camdmd.prime_mover_type_code (prime_mover_type_cd, prime_mover_type_description) VALUES ('PS', 'Pumped storage');
INSERT INTO camdmd.prime_mover_type_code (prime_mover_type_cd, prime_mover_type_description) VALUES ('PV', 'Photovoltaic');
INSERT INTO camdmd.prime_mover_type_code (prime_mover_type_cd, prime_mover_type_description) VALUES ('SF', 'Steam');
INSERT INTO camdmd.prime_mover_type_code (prime_mover_type_cd, prime_mover_type_description) VALUES ('SO', 'Solar');
INSERT INTO camdmd.prime_mover_type_code (prime_mover_type_cd, prime_mover_type_description) VALUES ('ST', 'Steam');
INSERT INTO camdmd.prime_mover_type_code (prime_mover_type_cd, prime_mover_type_description) VALUES ('WT', 'Wind');
