INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3446, 'Architectural Metal Work');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3448, 'Prefabricated Metal Buildings');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3449, 'Miscellaneous Metal Work');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3451, 'Screw Machine Products');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3452, 'Bolts Nuts Rivets & Washers');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3462, 'Iron and Steel Forgings');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3463, 'Nonferrous Forgings');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3465, 'Automotive Stampings');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3466, 'Crowns and Closures');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3469, 'Metal Stampings, Nec');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3471, 'Electroplating, Polishing, Anodizing, and Coloring');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3479, 'Metal Coating and Allied Services,Nec');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3482, 'Small Arms Ammunition');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3483, 'Ammunition, Exc. for Small Arm');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3484, 'Small Arms');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3489, 'Ordnance and Accessories, Nec');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3491, 'Industrial Valves');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3492, 'Fluid Power Valves and Hose Fittings');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3493, 'Steel Springs, Except Wire');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3494, 'Valves and Pipe Fittings');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3495, 'Wire Springs');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3496, 'Misc. Fabricated Wire Products');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3497, 'Metal Foil and Leaf');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3498, 'Fabricated Pipe and Fittings');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3499, 'Fabricated Metal Products, Nec');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3511, 'Turbines and Turbine Generator');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3519, 'Internal Combustion Engines');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3523, 'Farm Machinery and Equipment');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3524, 'Lawn and Garden Equipment');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3531, 'Construction Machinery');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3532, 'Mining Machinery');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3533, 'Oil Field Machinery');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3534, 'Elevators and Moving Stairways');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3535, 'Conveyors and Conveying Equipment');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3536, 'Hoists, Cranes, and Monorails');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3537, 'Industrial Trucks and Tractors');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3541, 'Machine Tools Metal Cutting Types');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3542, 'Machine Tools Metal Forming Types');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3543, 'Industrial Patterns');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3544, 'Special Dies/Tools/Jigs/Fixtures');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3545, 'Machine Tool Accessories');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3546, 'Power Driven Hand Tools');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3547, 'Rolling Mill Machinery');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3548, 'Welding Apparatus');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3549, 'Metalworking Machinery, Nec');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3551, 'Food Products Machinery');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3552, 'Textile Machinery');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3553, 'Woodworking Machinery');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3554, 'Paper Industries Machinery');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3555, 'Printing Trades Machinery');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3556, 'Food Products Machinery');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3559, 'Special Industry Machinery Nec');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3561, 'Pumps and Pumping Equipment');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3562, 'Ball and Roller Bearings');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3563, 'Air and Gas Compressors');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3564, 'Blowers and Fans');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3565, 'Packaging Machinery');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3566, 'Speed Changers Drives & Gears');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3567, 'Industrial Furnaces and Ovens');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3568, 'Power Transmission Equipment');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3569, 'Gen Industrial Machinery, Nec');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3571, 'Electronic Computers');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3572, 'Computer Storage Devices');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3573, 'Electronic Computing Equipment(1977)');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3574, 'Calculating & Accounting Mach(1977)');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3575, 'Computer Terminals');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3576, 'Scales & Balances Exc Lab(1977)');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3577, 'Computer Peripheral Equipment, Nec');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3578, 'Calculating and Accounting Equipment');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3579, 'Office Machines, Nec');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3581, 'Automatic Vending Machines');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3582, 'Commercial Laundry Equipment');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3585, 'Refrigeration & Heating Equipment');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3586, 'Measuring and Dispensing Pumps');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3589, 'Service Industry Machinery Nec');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3592, 'Carburetors/Pistons/Rings/Valves');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3593, 'Fluid Power Cylinders and Actuators');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3594, 'Fluid Power Pumps and Motors');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3596, 'Scales and Balances, Except Laboratory');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3599, 'Machinery Exc Electrical Nec');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3612, 'Transformers');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3613, 'Switchgear & Switchboard Apparatus');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3621, 'Motors and Generators');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3622, 'Industrial Controls(1977)');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3623, 'Welding Apparatus, Electric(1977)');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3624, 'Carbon and Graphite Products');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3625, 'Relays and Industrial Controls');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3629, 'Elec Industrial Apparatus, Nec');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3721, 'Aircraft');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3724, 'Aircraft Engines & Engine Parts');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3728, 'Aircraft Equipment, Nec');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3731, 'Ship Building and Repairing');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3732, 'Boat Building and Repairing');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3743, 'Railroad Equipment');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3751, 'Motorcycles Bicycles & Parts');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3761, 'Guided Missiles & Space Vehicle');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3764, 'Space Propulsion Units & Parts');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3769, 'Space Vehicle Equipment, Nec');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3792, 'Travel Trailers and Campers');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3795, 'Tanks and Tank Components');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3799, 'Transportation Equipment, Nec.');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3811, 'Engineering & Scientific Instruments(197');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3812, 'Search and Navigation Equipment');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3821, 'Laboratory Apparatus and Furniture');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3822, 'Environmental Controls');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3823, 'Process Control Instruments');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3824, 'Fluid Meters & Counting Device');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3825, 'Instruments To Measure Electricity');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3826, 'Analytical Instruments');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3827, 'Optical Instruments and Lenses');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3829, 'Measuring & Controlling Device');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3832, 'Optical Instruments and Lenses(1977)');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3861, 'Manufacturing of Photographic Supplies');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (4899, 'Communication Services, Nec');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (4911, 'Electric Services');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (4922, 'Natural Gas Transmission');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (4923, 'Gas Transmission and Distribution');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (4924, 'Natural Gas Distribution');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (4925, 'Gas Production/Distribution');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (4931, 'Elec & Other Services Combined');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (4932, 'Gas & Other Services Combined');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (4939, 'Combination Utility Services');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (4941, 'Water Supply');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (4952, 'Sewerage Systems');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (4953, 'Refuse Systems');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (4959, 'Sanitary Services, Nec');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (4961, 'Steam Supply');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (4971, 'Irrigation Systems');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (5012, 'Autos & Other Motor Vehicles');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (5013, 'Automotive Parts and Supplies');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (5014, 'Tires and Tubes');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (5015, 'Motor Vehicle Parts, Used');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (5021, 'Furniture');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (5023, 'Home Furnishings');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (5031, 'Lumber, Plywood and Millwork');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (5032, 'Brick, Stove, and Related Materials');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (5033, 'Roofing, Siding and Insulation');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (5039, 'Construction Materials, Nec');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (5041, 'Sporting & Recreational Goods(1977)');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (5042, 'Toys & Hobby Goods and Supplies(1977)');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (5043, 'Photograph Equipment & Supply');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (5044, 'Office Equipment');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (5045, 'Computers, Peripherals, and Software');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (5046, 'Commercial Equipment, Nec');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (5047, 'Medical and Hospital Equipment');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (5048, 'Ophthalmic Goods');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (5049, 'Professional Equipment, Nec');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (5051, 'Metals Serv Centers & Offices');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (5052, 'Coal & Other Minerals & Ores');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (5063, 'Elec Apparatus & Equipment');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (5064, 'Elec Appliances TV & Radios');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (5065, 'Electronic Parts and Equipment');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (5072, 'Hardware');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (5074, 'Plumbing/Hydrolic Heat Supply');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (5075, 'Warm Air Heat & Air Condition');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (5078, 'Refrigeration Equip & Supplies');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (5081, 'Commercial Machines & Equipmnt(1977)');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (5082, 'Construction & Mining Machiner');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (5083, 'Farm Machinery and Equipment');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (5084, 'Industrial Machinery & Equipment');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (5085, 'Industrial Supplies');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (5086, 'Professional Equipment and Supplies(1977');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (5087, 'Service Establishment Equipmen');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (5088, 'Transportation Equipment & Supplies');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (5091, 'Sporting and Recreational Goods');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (5092, 'Toys and Hobby Goods and Supplies');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (5093, 'Scrap and Waste Materials');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (5094, 'Jewelry, Watches, & Precious Stones');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (5099, 'Durable Goods, Nec');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (5111, 'Printing and Writing Paper');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (5112, 'Stationery Supplies');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (5113, 'Industrial & Personal Service');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (5171, 'Petroleum Bulk Stations & Terminals');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (5172, 'Petroleum Products, Nec');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (7996, 'Amusement Parks');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (9111, 'Executive Offices');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (9121, 'Legislative Bodies');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (9131, 'Executive and Legislative Combined');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (9199, 'General Government, Nec');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (9211, 'Courts');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (9221, 'Police Protection');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (9222, 'Legal Counsel and Prosecution');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (9223, 'Correctional Institutions');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (9224, 'Fire Protection');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (9229, 'Public Order and Safety, Nec');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (9311, 'Finance, Taxation & Monetary Policy');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (9411, 'Admin. of Educational Programs');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (9431, 'Admin. of Public Health Programs');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (9441, 'Admin. of Social & Manpower Programs');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (9451, 'Administration of Veterans'' Affairs');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (9511, 'Air, Water & Solid Waste Management');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (9512, 'Land, Mineral, Wildlife Conservation');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (9531, 'Housing Programs');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (9532, 'Urban and Community Development');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (9611, 'Admin. of General Economic Programs');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (9621, 'Regulation, Admin. of Transportation');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (9631, 'Regulation, Admin. of Utilities');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (9641, 'Regulation of Agricultural Marketing & Commodities');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (9651, 'Regulation Misc. Commercial Sectors');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (9661, 'Space Research and Technology');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (9711, 'National Security');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (9721, 'International Affairs');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (9999, 'Nonclassifiable Establishments');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3241, 'Hydraulic Cement Manufacture ');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (2823, 'Cellulosic Man-Made Fibers');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (8221, 'Colleges, Universities, and Professional Schools');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (2621, 'Paper Mills Exc Building Paper');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (2631, 'Paperboard Mills');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (2641, 'Paper Coating and Glazing(1977)');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (2642, 'Envelopes(1977)');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (2643, 'Bags, Except Textile Bags(1977)');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (2645, 'Die-Cut Paper and Board(1977)');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (2646, 'Pressed and Molded Pulp Goods(1977)');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (2647, 'Sanitary Paper Products(1977)');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (2648, 'Stationery Products(1977)');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (2649, 'Converted Paper Products, Nec(1977)');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (2651, 'Folding Paperboard Boxes(1977)');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (2652, 'Set-Up Paperboard Boxes');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (2653, 'Corrugated and Solid Fiber Box');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (2654, 'Sanitary Food Containers(1977)');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (2655, 'Fiber Cans Drums Like Products');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (2656, 'Sanitary Food Containers');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (2657, 'Folding Paperboard Boxes');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (2661, 'Building Paper and Board Mills(1977)');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (2831, 'Biological Products(1977)');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (2833, 'Medicinals and Botanicals');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (2834, 'Pharmaceutical Preparations');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (2835, 'Diagnostic Substances');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (2611, 'Pulp Mills');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (2836, 'Biological Products, Except Diagnostic');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (2841, 'Soap and Other Detergents');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (2842, 'Polishes and Sanitation Goods');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (2843, 'Surface Active Agents');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (2844, 'Toilet Preparations');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (2851, 'Paints and Allied Products');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (2861, 'Gum and Wood Chemicals');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (2865, 'Cyclic Crudes and Intermediate');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (2869, 'Industrial Organic Chemicals,Nec');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (2873, 'Nitrogenous Fertilizers');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (2874, 'Phosphatic Fertilizers');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (2875, 'Fertilizers, Mixing Only');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (2879, 'Agricultural Chemicals, Nec');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (2891, 'Adhesives and Sealants');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (2892, 'Explosives');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (2893, 'Printing Ink');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (2895, 'Carbon Black');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (2899, 'Chemical Preparations, Nec');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (2911, 'Petroleum Refining');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (2951, 'Paving Mixtures and Blocks');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (2952, 'Asphalt Felts and Coatings');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (2992, 'Lubricating Oils and Greases');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (2999, 'Petroleum and Coal Products, Nec');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3011, 'Tires and Inner Tubes');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3021, 'Rubber and Plastics Footwear');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3031, 'Reclaimed Rubber(1977)');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3041, 'Rubber and Plastics Hose and Belting(197');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3052, 'Rubber and Plastics Hose and Belting');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3053, 'Gaskets, Packing and Sealing Devices');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3061, 'Mechanical Rubber Goods');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3069, 'Fabricated Rubber Products, Nec');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3079, 'Miscellaneous Plastics Products(1977)');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3081, 'Unsupported Plastics Film and Sheet');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3082, 'Unsupported Plastics Profile Shapes');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3083, 'Laminated Plastics Plate and Sheet');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3084, 'Plastics Pipe');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3085, 'Plastics Bottles');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3086, 'Plastics Foam Products');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3087, 'Custom Compound Purchased Resins');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3088, 'Plastics Plumbing Fixtures');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3089, 'Plastics Products, Nec');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3111, 'Leather Tanning and Finishing');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3131, 'Boot and Shoe Cut Stock and Findings');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3312, 'Blast Furnaces and Steel Mills');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3313, 'Electrometallurgical Products');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3315, 'Steel Wire and Related Product');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3316, 'Cold Finishing of Steel Shapes');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3317, 'Steel Pipe and Tubes');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3321, 'Gray Iron Foundries');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3322, 'Malleable Iron Foundries');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3324, 'Steel Investment Foundries');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3325, 'Steel Foundries, Nec');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3339, 'Primary Nonferrous Metals, Nec');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3351, 'Copper Rolling and Drawing');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3353, 'Aluminum Sheet Plate & Foil');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3354, 'Aluminum Extruded Products');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3355, 'Aluminum Rolling & Drawing Nec');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3356, 'Nonferrous Rolling and Drawing');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3357, 'Nonferrous Wire Drawing/Insulating');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3361, 'Aluminum Foundries(1977)');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3362, 'Brass Bronze & Copper Foundry(1977)');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3363, 'Aluminum Die-Castings');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3364, 'Nonferrous Die-Castings, Except Aluminum');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3365, 'Aluminum Foundries');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3366, 'Copper Foundries');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3369, 'Nonferrous Foundries, Nec');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3398, 'Metal Heat Treating');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3399, 'Primary Metal Products, Nec');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3443, 'Fabricated Plate Work (Boiler Shops)');
INSERT INTO camdmd.sic_code (sic_code, sic_code_description) VALUES (3444, 'Sheet Metal Work');

