INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('UM', 'Midway Islands', 0, 1, 9);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('AL', 'Alabama', 1, 1, 4);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('AK', 'Alaska', 1, 1, 10);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('AS', 'American Samoa', 0, 1, 9);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('AZ', 'Arizona', 1, 1, 9);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('AR', 'Arkansas', 1, 1, 6);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('CA', 'California', 1, 1, 9);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('CO', 'Colorado', 1, 1, 8);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('CT', 'Connecticut', 1, 1, 1);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('DE', 'Delaware', 1, 1, 3);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('DC', 'District Of Columbia', 1, 1, 3);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('FM', 'States Of Micronesia', 0, 1, 9);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('FL', 'Florida', 1, 1, 4);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('GA', 'Georgia', 1, 1, 4);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('GU', 'Guam', 0, 1, 9);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('HI', 'Hawaii', 1, 1, 9);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('ID', 'Idaho', 1, 1, 10);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('IL', 'Illinois', 1, 1, 5);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('IA', 'Iowa', 1, 1, 7);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('IN', 'Indiana', 1, 1, 5);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('KS', 'Kansas', 1, 1, 7);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('KY', 'Kentucky', 1, 1, 4);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('LA', 'Louisiana', 1, 1, 6);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('ME', 'Maine', 1, 1, 1);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('MH', 'Marshall Islands', 0, 1, 9);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('MD', 'Maryland', 1, 1, 3);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('MA', 'Massachusetts', 1, 1, 1);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('MI', 'Michigan', 1, 1, 5);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('MN', 'Minnesota', 1, 1, 5);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('MS', 'Mississippi', 1, 1, 4);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('MO', 'Missouri', 1, 1, 7);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('MT', 'Montana', 1, 1, 8);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('NE', 'Nebraska', 1, 1, 7);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('NV', 'Nevada', 1, 1, 9);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('NH', 'New Hampshire', 1, 1, 1);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('NJ', 'New Jersey', 1, 1, 2);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('NM', 'New Mexico', 1, 1, 6);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('NY', 'New York', 1, 1, 2);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('NC', 'North Carolina', 1, 1, 4);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('ND', 'North Dakota', 1, 1, 8);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('MP', 'Northern Mariana Isl', 0, 1, 9);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('OH', 'Ohio', 1, 1, 5);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('OK', 'Oklahoma', 1, 1, 6);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('OR', 'Oregon', 1, 1, 10);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('PW', 'Palau', 0, 1, 9);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('PA', 'Pennsylvania', 1, 1, 3);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('PR', 'Puerto Rico', 0, 1, 2);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('RI', 'Rhode Island', 1, 1, 1);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('SC', 'South Carolina', 1, 1, 4);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('SD', 'South Dakota', 1, 1, 8);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('TN', 'Tennessee', 1, 1, 4);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('TX', 'Texas', 1, 1, 6);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('UT', 'Utah', 1, 1, 8);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('VT', 'Vermont', 1, 1, 1);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('VI', 'Virgin Islands', 0, 1, 2);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('VA', 'Virginia', 1, 1, 3);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('WA', 'Washington', 1, 1, 10);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('WV', 'West Virginia', 1, 1, 3);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('WI', 'Wisconsin', 1, 1, 5);
INSERT INTO camdmd.state_code (state_cd, state_name, domestic_ind, indian_country_ind, epa_region) VALUES ('WY', 'Wyoming', 1, 1, 8);
