INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('AD', 'Activate Conditional Allowances', 0);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('AT', 'Transfer Due to Corrected Energy Conservation', 0);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('CC', 'Substitution Control by Contract Deduction', 0);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('CR', 'Conservation Issuance', 1);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('DE', 'Reallocation Transfer', 1);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('DI', 'Reallocation Surrender', -1);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('EB', 'Energy Biomass Issuance', 1);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('EG', 'Energy Geothermal Issuance', 1);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('EMADJ', 'Emissions Adjustment Deduction', 0);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('EMISS', 'Emissions Deduction', 0);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('ENFSURR', 'Enforcement Surrender', 0);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('EP', 'Phase 1 Extension Issuance', 1);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('EPAAUCT', 'Purchase at EPA Auction', 0);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('ERLYRED', 'Early Reduction Issuance', 1);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('ERRCORR', 'Error Correction', 0);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('ERRREV', 'Error Reversal', 0);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('ES', 'Energy Solar Issuance', 1);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('EW', 'Energy Wind Issuance', 1);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('FP', 'Phase 1 Extension Projected Emission Deduction', 0);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('INITALL', 'Initial Allocation', 1);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('INTOESC', 'Contribute to Auction', 0);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('JC', 'July Confirmation Credit', 0);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('JD', 'July Confirmation Deduction', 0);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('LEGACY', 'Transfer from Legacy System', 0);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('LO', 'Deduction of Loaned Allowances', 0);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('NBPADJ', 'NBP Additional Emissions Deduction from CAIROS Account', 0);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('NBPALL', 'CAIROS Transfer from NBP', 0);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('NBPOS', 'Conversion of NBP allowances into CAIROS', 0);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('NBPPEN', 'NBP Penalty Deduction From CAIROS Account', 0);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('NUSAALL', 'New Unit Set Aside Allocation', 1);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('OFFPEN', 'Offset/Penalty Deduction', 0);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('OPTALL', 'Opt-In Allocation', 1);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('OPTIN', 'Opt-in Transfer to Replacement Unit', 0);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('OTHALL', 'Other Reserve Allocation', 1);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('OUTESC', 'Return Contributed Allowances', 0);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('PRIAUCT', 'Purchase at Private Auction', 0);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('PRIVATE', 'Private Transfer', 0);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('PX', 'Phase 1 Extension Control Failure Deduction', 0);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('REISSUE', 'Distribute Revintaged Allowances', 0);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('REMOVAL', 'Remove for Reissuance', 0);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('RETURN', 'Return of Unsold Allowances from EPA Auction Reserve', 0);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('RP', 'Phase 2 Early Reduction Payback', -1);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('RR', 'Reverse Reduced Utilization Payback', 0);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('RS', 'Reduced Utilization Payback', -1);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('RTNCAIR', 'Return of CAIR Allowances', 0);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('RTNCRER', 'Return of unused allowances from the Conservation and Renewable Energy Reserve', 1);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('RU', 'Reduced Utilization Issuance', 1);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('SC', 'State Cap Issuance', 1);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('SD', 'Substitution Distribution', 0);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('SE', 'State Cap Deduction', 0);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('SM', 'Small Diesel Issuance', 1);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('SP', 'State Cap Payback', -1);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('SR', 'Reverse Substitution Payback', 1);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('SS', 'Substitution Payback', -1);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('ST', 'Substitution Termination', -1);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('STATE', 'State Reallocation', 1);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('SU', 'Substitution Issuance', 1);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('TAKEBCK', 'Takeback for Underutilization', 0);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('TD', 'Transfer from Direct Sale to Auction', 0);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('TERM', 'Terminate State Program Allowances', 0);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('TF', 'Internal Transfer to Reduce Offset', 0);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('TM', 'Reduced Utilization Termination', -1);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('UNDERUT', 'Underutilization Deduction', 0);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('VOLSURR', 'Voluntary Surrender', 0);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('NEWPROG', 'Distribute Allowances for New Program', 0);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('OSADJ', 'CSAPR Ozone Season Emissions Adjustment Deduction', 0);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('OSPEN', 'CSAPR Ozone Season Offset/Penalty Deduction', 0);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('RECALL', 'Recall State Program Allowances', 0);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('REMCSR', 'Remove for Revised CSAPR Update Reissuance', 0);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('NEWCSR', 'Distribute Allowances for Revised CSAPR Update', 0);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('REISCSR', 'Distribute Revintaged Allowances for Revised CSAPR Update', 0);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('CASURR', 'Compliance Assurance Surrender', 0);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('NC', 'Termination of NBP allowances into CAIROS', 0);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('TC', 'Terminate to CAIROS', 0);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('TN', 'Terminate NOx Budget Programs Allowances', 0);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('REMGNP', 'Remove for Good Neighbor Plan Reissuance', 0);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('REISGNP', 'Distribute Revintaged Allowances for Good Neighbor Plan', 0);
INSERT INTO camdmd.transaction_type_code (trans_type_cd, trans_type_description, allocation_ind) VALUES ('EUSAALL', 'Existing Unit Set Aside Allocation', 1);
