INSERT INTO camdmd.unit_type_code (unit_type_cd, unit_type_description, sort_order, unit_type_group_cd) VALUES ('CC', 'Combined cycle', NULL, 'T');
INSERT INTO camdmd.unit_type_code (unit_type_cd, unit_type_description, sort_order, unit_type_group_cd) VALUES ('CT', 'Combustion turbine', NULL, 'T');
INSERT INTO camdmd.unit_type_code (unit_type_cd, unit_type_description, sort_order, unit_type_group_cd) VALUES ('ICE', 'Internal combustion engine', NULL, 'T');
INSERT INTO camdmd.unit_type_code (unit_type_cd, unit_type_description, sort_order, unit_type_group_cd) VALUES ('IGC', 'Integrated gasification combined cycle', NULL, 'T');
INSERT INTO camdmd.unit_type_code (unit_type_cd, unit_type_description, sort_order, unit_type_group_cd) VALUES ('OT', 'Other turbine', NULL, 'T');
INSERT INTO camdmd.unit_type_code (unit_type_cd, unit_type_description, sort_order, unit_type_group_cd) VALUES ('AF', 'Arch-fired boiler', NULL, 'B');
INSERT INTO camdmd.unit_type_code (unit_type_cd, unit_type_description, sort_order, unit_type_group_cd) VALUES ('BFB', 'Bubbling fluidized bed boiler', NULL, 'B');
INSERT INTO camdmd.unit_type_code (unit_type_cd, unit_type_description, sort_order, unit_type_group_cd) VALUES ('C', 'Cyclone boiler', NULL, 'B');
INSERT INTO camdmd.unit_type_code (unit_type_cd, unit_type_description, sort_order, unit_type_group_cd) VALUES ('CB', 'Cell burner boiler', NULL, 'B');
INSERT INTO camdmd.unit_type_code (unit_type_cd, unit_type_description, sort_order, unit_type_group_cd) VALUES ('CFB', 'Circulating fluidized bed boiler', NULL, 'B');
INSERT INTO camdmd.unit_type_code (unit_type_cd, unit_type_description, sort_order, unit_type_group_cd) VALUES ('DB', 'Dry bottom wall-fired boiler', NULL, 'B');
INSERT INTO camdmd.unit_type_code (unit_type_cd, unit_type_description, sort_order, unit_type_group_cd) VALUES ('DTF', 'Dry bottom turbo-fired boiler', NULL, 'B');
INSERT INTO camdmd.unit_type_code (unit_type_cd, unit_type_description, sort_order, unit_type_group_cd) VALUES ('DVF', 'Dry bottom vertically-fired boiler', NULL, 'B');
INSERT INTO camdmd.unit_type_code (unit_type_cd, unit_type_description, sort_order, unit_type_group_cd) VALUES ('OB', 'Other boiler', NULL, 'B');
INSERT INTO camdmd.unit_type_code (unit_type_cd, unit_type_description, sort_order, unit_type_group_cd) VALUES ('PFB', 'Pressurized fluidized bed boiler', NULL, 'B');
INSERT INTO camdmd.unit_type_code (unit_type_cd, unit_type_description, sort_order, unit_type_group_cd) VALUES ('S', 'Stoker', NULL, 'B');
INSERT INTO camdmd.unit_type_code (unit_type_cd, unit_type_description, sort_order, unit_type_group_cd) VALUES ('T', 'Tangentially-fired', NULL, 'B');
INSERT INTO camdmd.unit_type_code (unit_type_cd, unit_type_description, sort_order, unit_type_group_cd) VALUES ('WBF', 'Wet bottom wall-fired boiler', NULL, 'B');
INSERT INTO camdmd.unit_type_code (unit_type_cd, unit_type_description, sort_order, unit_type_group_cd) VALUES ('WBT', 'Wet bottom turbo-fired boiler', NULL, 'B');
INSERT INTO camdmd.unit_type_code (unit_type_cd, unit_type_description, sort_order, unit_type_group_cd) VALUES ('WVF', 'Wet bottom vertically-fired boiler', NULL, 'B');
INSERT INTO camdmd.unit_type_code (unit_type_cd, unit_type_description, sort_order, unit_type_group_cd) VALUES ('KLN', 'Cement Kiln', NULL, 'F');
INSERT INTO camdmd.unit_type_code (unit_type_cd, unit_type_description, sort_order, unit_type_group_cd) VALUES ('PRH', 'Process Heater', NULL, 'F');
