-- Table: camdecmps.monitor_plan

-- DROP TABLE camdecmps.monitor_plan;

CREATE TABLE IF NOT EXISTS camdecmps.monitor_plan
(
    mon_plan_id character varying(45) COLLATE pg_catalog."default" NOT NULL,
    fac_id numeric(38,0) NOT NULL,
    config_type_cd character varying(7) COLLATE pg_catalog."default",
    last_updated timestamp without time zone,
    updated_status_flg character varying(1) COLLATE pg_catalog."default",
    needs_eval_flg character varying(1) COLLATE pg_catalog."default",
    chk_session_id character varying(45) COLLATE pg_catalog."default",
    userid character varying(25) COLLATE pg_catalog."default",
    add_date timestamp without time zone,
    update_date timestamp without time zone,
    submission_id numeric(38,0),
    submission_availability_cd character varying(7) COLLATE pg_catalog."default",
    begin_rpt_period_id numeric(38,0) NOT NULL,
    end_rpt_period_id numeric(38,0),
    last_evaluated_date timestamp without time zone,
    CONSTRAINT pk_monitor_plan PRIMARY KEY (mon_plan_id),
    CONSTRAINT fk_monitor_plan_plant FOREIGN KEY (fac_id)
        REFERENCES camd.plant (fac_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_monitor_plan_reporting_period_begin_rpt_period FOREIGN KEY (begin_rpt_period_id)
        REFERENCES camdecmpsmd.reporting_period (rpt_period_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_monitor_plan_reporting_period_end_rpt_period FOREIGN KEY (end_rpt_period_id)
        REFERENCES camdecmpsmd.reporting_period (rpt_period_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_monitor_plan_submission_availability_code FOREIGN KEY (submission_availability_cd)
        REFERENCES camdecmpsmd.submission_availability_code (submission_availability_cd) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

COMMENT ON TABLE camdecmps.monitor_plan
    IS 'Table of monitoring plan(s) created by the user.';

COMMENT ON COLUMN camdecmps.monitor_plan.mon_plan_id
    IS 'Unique identifier of a monitoring plan record. ';

COMMENT ON COLUMN camdecmps.monitor_plan.fac_id
    IS 'Unique identifier of a facility record which is generated by the EPA Host System. ';

COMMENT ON COLUMN camdecmps.monitor_plan.config_type_cd
    IS 'Code used to identify the configuration type ';

COMMENT ON COLUMN camdecmps.monitor_plan.last_updated
    IS 'Date and time in which either one of the flags was last triggered. ';

COMMENT ON COLUMN camdecmps.monitor_plan.updated_status_flg
    IS 'If set to true, identifies that changes have been made to the monitoring plan from within the client tool, consequently data must be submitted to the Host. ';

COMMENT ON COLUMN camdecmps.monitor_plan.needs_eval_flg
    IS 'Identifies whether the data need to have checks run against it. ';

COMMENT ON COLUMN camdecmps.monitor_plan.chk_session_id
    IS 'Identifies the most recent check session used for the evaluation. ';

COMMENT ON COLUMN camdecmps.monitor_plan.userid
    IS 'User account or source of data that added or updated record. ';

COMMENT ON COLUMN camdecmps.monitor_plan.add_date
    IS 'Date and time in which record was added. ';

COMMENT ON COLUMN camdecmps.monitor_plan.update_date
    IS 'Date and time in which record was last updated. ';

COMMENT ON COLUMN camdecmps.monitor_plan.submission_id
    IS 'Unique identifier of a submission.';

COMMENT ON COLUMN camdecmps.monitor_plan.submission_availability_cd
    IS 'Unique code value for a lookup table.';

COMMENT ON COLUMN camdecmps.monitor_plan.begin_rpt_period_id
    IS 'Unique identifier of a reporting period record. ';

COMMENT ON COLUMN camdecmps.monitor_plan.end_rpt_period_id
    IS 'Unique identifier of a reporting period record. ';

-- Index: idx_monitor_plan_chk_session

-- DROP INDEX camdecmps.idx_monitor_plan_chk_session;

CREATE INDEX IF NOT EXISTS idx_monitor_plan_chk_session
    ON camdecmps.monitor_plan USING btree
    (chk_session_id COLLATE pg_catalog."default" ASC NULLS LAST);

-- Index: idx_monitor_plan_submission

-- DROP INDEX camdecmps.idx_monitor_plan_submission;

CREATE INDEX IF NOT EXISTS idx_monitor_plan_submission
    ON camdecmps.monitor_plan USING btree
    (submission_id ASC NULLS LAST);
