-- Table: camdecmps.unit_stack_configuration

-- DROP TABLE camdecmps.unit_stack_configuration;

CREATE TABLE IF NOT EXISTS camdecmps.unit_stack_configuration
(
    config_id character varying(45) COLLATE pg_catalog."default" NOT NULL,
    unit_id numeric(38,0) NOT NULL,
    stack_pipe_id character varying(45) COLLATE pg_catalog."default" NOT NULL,
    begin_date date NOT NULL,
    end_date date,
    userid character varying(25) COLLATE pg_catalog."default",
    add_date timestamp without time zone,
    update_date timestamp without time zone,
    CONSTRAINT pk_unit_stack_configuration PRIMARY KEY (config_id),
    CONSTRAINT fk_unit_stack_configuration_stack_pipe FOREIGN KEY (stack_pipe_id)
        REFERENCES camdecmps.stack_pipe (stack_pipe_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_unit_stack_configuration_unit FOREIGN KEY (unit_id)
        REFERENCES camd.unit (unit_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

COMMENT ON TABLE camdecmps.unit_stack_configuration
    IS 'Identifies the units, stacks or pipes that are associated with a specific monitoring plan.';

COMMENT ON COLUMN camdecmps.unit_stack_configuration.config_id
    IS 'Unique identifier of a monitoring configuration record. ';

COMMENT ON COLUMN camdecmps.unit_stack_configuration.unit_id
    IS 'Unique identifier of a unit record which is generated by the EPA Host System. ';

COMMENT ON COLUMN camdecmps.unit_stack_configuration.stack_pipe_id
    IS 'Unique identifier of a stack or pipe record. ';

COMMENT ON COLUMN camdecmps.unit_stack_configuration.begin_date
    IS 'Date in which information became effective or activity started. ';

COMMENT ON COLUMN camdecmps.unit_stack_configuration.end_date
    IS 'Last date in which information was effective or date in which activity ended. ';

COMMENT ON COLUMN camdecmps.unit_stack_configuration.userid
    IS 'User account or source of data that added or updated record. ';

COMMENT ON COLUMN camdecmps.unit_stack_configuration.add_date
    IS 'Date and time in which record was added. ';

COMMENT ON COLUMN camdecmps.unit_stack_configuration.update_date
    IS 'Date and time in which record was last updated. ';

-- Index: idx_unit_stack_configuration_b

-- DROP INDEX camdecmps.idx_unit_stack_configuration_b;

CREATE INDEX IF NOT EXISTS idx_unit_stack_configuration_b
    ON camdecmps.unit_stack_configuration USING btree
    (stack_pipe_id COLLATE pg_catalog."default" ASC NULLS LAST, unit_id ASC NULLS LAST);

-- Index: idx_unit_stack_configuration_s

-- DROP INDEX camdecmps.idx_unit_stack_configuration_s;

CREATE INDEX IF NOT EXISTS idx_unit_stack_configuration_s
    ON camdecmps.unit_stack_configuration USING btree
    (stack_pipe_id COLLATE pg_catalog."default" ASC NULLS LAST);

-- Index: idx_unit_stack_configuration_u

-- DROP INDEX camdecmps.idx_unit_stack_configuration_u;

CREATE INDEX IF NOT EXISTS idx_unit_stack_configuration_u
    ON camdecmps.unit_stack_configuration USING btree
    (unit_id ASC NULLS LAST);
