-- ------------ Write CREATE-TABLE-stage scripts -----------

CREATE TABLE IF NOT EXISTS camdecmps.ae_correlation_test_run(
    ae_corr_test_run_id CHARACTER VARYING(45) NOT NULL,
    ae_corr_test_sum_id CHARACTER VARYING(45) NOT NULL,
    begin_date DATE,
    begin_hour NUMERIC(2,0),
    begin_min NUMERIC(2,0),
    end_date DATE,
    end_hour NUMERIC(2,0),
    end_min NUMERIC(2,0),
    run_num NUMERIC(2,0) NOT NULL,
    ref_value NUMERIC(8,3),
    response_time NUMERIC(3,0),
    total_hi NUMERIC(7,1),
    calc_total_hi NUMERIC(7,1),
    hourly_hi_rate NUMERIC(7,1),
    calc_hourly_hi_rate NUMERIC(7,1),
    userid CHARACTER VARYING(8),
    add_date TIMESTAMP WITHOUT TIME ZONE,
    update_date TIMESTAMP WITHOUT TIME ZONE
)
        WITH (
        OIDS=FALSE
        );
COMMENT ON TABLE camdecmps.ae_correlation_test_run
     IS 'Reported test runs for establishing an Appendix E correlation curve (for gas or oil fired peaking units) or a unit or fuel specific NOx emission rate (for LME units).  Record Type 650.';
COMMENT ON COLUMN camdecmps.ae_correlation_test_run.ae_corr_test_run_id
     IS 'Unique identifier of an Appendix E correlation run record. ';
COMMENT ON COLUMN camdecmps.ae_correlation_test_run.ae_corr_test_sum_id
     IS 'Unique combination of DB_Token and identity key generated by sequence generator.';
COMMENT ON COLUMN camdecmps.ae_correlation_test_run.begin_date
     IS 'Date on which the run started. ';
COMMENT ON COLUMN camdecmps.ae_correlation_test_run.begin_hour
     IS 'Hour in which the run started. ';
COMMENT ON COLUMN camdecmps.ae_correlation_test_run.begin_min
     IS 'Minute in which the run started. ';
COMMENT ON COLUMN camdecmps.ae_correlation_test_run.end_date
     IS 'Last date in which information was effective or date in which activity ended. ';
COMMENT ON COLUMN camdecmps.ae_correlation_test_run.end_hour
     IS 'Last hour in which information was effective or hour in which activity ended. ';
COMMENT ON COLUMN camdecmps.ae_correlation_test_run.end_min
     IS 'Last minute in which information was effective or minute in which activity ended. ';
COMMENT ON COLUMN camdecmps.ae_correlation_test_run.run_num
     IS 'Run number. ';
COMMENT ON COLUMN camdecmps.ae_correlation_test_run.ref_value
     IS 'Value from reference method during run. ';
COMMENT ON COLUMN camdecmps.ae_correlation_test_run.response_time
     IS 'Reference method response time during run. ';
COMMENT ON COLUMN camdecmps.ae_correlation_test_run.total_hi
     IS 'Total heat input during the run. ';
COMMENT ON COLUMN camdecmps.ae_correlation_test_run.calc_total_hi
     IS 'Total heat input during the run. ';
COMMENT ON COLUMN camdecmps.ae_correlation_test_run.hourly_hi_rate
     IS 'Hourly heat input rate during the run. ';
COMMENT ON COLUMN camdecmps.ae_correlation_test_run.calc_hourly_hi_rate
     IS 'Hourly heat input rate during the run. ';
COMMENT ON COLUMN camdecmps.ae_correlation_test_run.userid
     IS 'User account or source of data that added or updated record. ';
COMMENT ON COLUMN camdecmps.ae_correlation_test_run.add_date
     IS 'Date and time in which record was added. ';
COMMENT ON COLUMN camdecmps.ae_correlation_test_run.update_date
     IS 'Date and time in which record was last updated. ';



-- ------------ Write CREATE-INDEX-stage scripts -----------

CREATE INDEX idx_ae_correlation_ae_corr_te
ON camdecmps.ae_correlation_test_run
USING BTREE (ae_corr_test_sum_id ASC);



-- ------------ Write CREATE-CONSTRAINT-stage scripts -----------

ALTER TABLE camdecmps.ae_correlation_test_run
ADD CONSTRAINT pk_ae_correlation_test_run PRIMARY KEY (ae_corr_test_run_id);



-- ------------ Write CREATE-FOREIGN-KEY-CONSTRAINT-stage scripts -----------

ALTER TABLE camdecmps.ae_correlation_test_run
ADD CONSTRAINT fk_ae_correlatio_ae_correlatio FOREIGN KEY (ae_corr_test_sum_id) 
REFERENCES camdecmps.ae_correlation_test_sum (ae_corr_test_sum_id)
ON DELETE NO ACTION;
