-- ------------ Write CREATE-TABLE-stage scripts -----------

CREATE TABLE IF NOT EXISTS camdecmps.qa_supp_attribute(
    qa_supp_attribute_id CHARACTER VARYING(45) NOT NULL,
    qa_supp_data_id CHARACTER VARYING(45),
    attribute_name CHARACTER VARYING(30),
    attribute_value CHARACTER VARYING(30),
    userid CHARACTER VARYING(8),
    add_date TIMESTAMP WITHOUT TIME ZONE,
    update_date TIMESTAMP WITHOUT TIME ZONE
)
        WITH (
        OIDS=FALSE
        );
COMMENT ON TABLE camdecmps.qa_supp_attribute
     IS 'Attribute data associated with QA supplemental data.';
COMMENT ON COLUMN camdecmps.qa_supp_attribute.qa_supp_attribute_id
     IS 'Identify key.';
COMMENT ON COLUMN camdecmps.qa_supp_attribute.qa_supp_data_id
     IS 'Unique combination of DB_Token and identity key generated by sequence generator. ';
COMMENT ON COLUMN camdecmps.qa_supp_attribute.attribute_name
     IS 'Name of the QA supplemental data element.';
COMMENT ON COLUMN camdecmps.qa_supp_attribute.attribute_value
     IS 'Value of the QA supplemental data element.';
COMMENT ON COLUMN camdecmps.qa_supp_attribute.userid
     IS 'User account or source of data that added or updated record.';
COMMENT ON COLUMN camdecmps.qa_supp_attribute.add_date
     IS 'Date and time in which record was added.';
COMMENT ON COLUMN camdecmps.qa_supp_attribute.update_date
     IS 'Date and time in which record was last updated.';



-- ------------ Write CREATE-INDEX-stage scripts -----------

CREATE INDEX qa_supp_attribute_idx001
ON camdecmps.qa_supp_attribute
USING BTREE (qa_supp_data_id ASC);



-- ------------ Write CREATE-CONSTRAINT-stage scripts -----------

ALTER TABLE camdecmps.qa_supp_attribute
ADD CONSTRAINT pk_qa_supp_attribute PRIMARY KEY (qa_supp_attribute_id);



-- ------------ Write CREATE-FOREIGN-KEY-CONSTRAINT-stage scripts -----------

ALTER TABLE camdecmps.qa_supp_attribute
ADD CONSTRAINT fk_qa_supp_data_qa_supp_attri FOREIGN KEY (qa_supp_data_id) 
REFERENCES camdecmps.qa_supp_data (qa_supp_data_id)
ON DELETE NO ACTION;
