-- Table: camdecmps.qa_supp_attribute

-- DROP TABLE camdecmps.qa_supp_attribute;

CREATE TABLE IF NOT EXISTS camdecmps.qa_supp_attribute
(
    qa_supp_attribute_id character varying(45) COLLATE pg_catalog."default" NOT NULL,
    qa_supp_data_id character varying(45) COLLATE pg_catalog."default",
    attribute_name character varying(30) COLLATE pg_catalog."default",
    attribute_value character varying(30) COLLATE pg_catalog."default",
    userid character varying(25) COLLATE pg_catalog."default",
    add_date timestamp without time zone,
    update_date timestamp without time zone,
    CONSTRAINT pk_qa_supp_attribute PRIMARY KEY (qa_supp_attribute_id),
    CONSTRAINT fk_qa_supp_attribute_qa_supp_data FOREIGN KEY (qa_supp_data_id)
        REFERENCES camdecmps.qa_supp_data (qa_supp_data_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);

COMMENT ON TABLE camdecmps.qa_supp_attribute
    IS 'Attribute data associated with QA supplemental data.';

COMMENT ON COLUMN camdecmps.qa_supp_attribute.qa_supp_attribute_id
    IS 'Identify key.';

COMMENT ON COLUMN camdecmps.qa_supp_attribute.qa_supp_data_id
    IS 'Unique combination of DB_Token and identity key generated by sequence generator. ';

COMMENT ON COLUMN camdecmps.qa_supp_attribute.attribute_name
    IS 'Name of the QA supplemental data element.';

COMMENT ON COLUMN camdecmps.qa_supp_attribute.attribute_value
    IS 'Value of the QA supplemental data element.';

COMMENT ON COLUMN camdecmps.qa_supp_attribute.userid
    IS 'User account or source of data that added or updated record.';

COMMENT ON COLUMN camdecmps.qa_supp_attribute.add_date
    IS 'Date and time in which record was added.';

COMMENT ON COLUMN camdecmps.qa_supp_attribute.update_date
    IS 'Date and time in which record was last updated.';

-- Index: qa_supp_attribute_idx001

-- DROP INDEX camdecmps.qa_supp_attribute_idx001;

CREATE INDEX IF NOT EXISTS qa_supp_attribute_idx001
    ON camdecmps.qa_supp_attribute USING btree
    (qa_supp_data_id COLLATE pg_catalog."default" ASC NULLS LAST);
