-- ------------ Write CREATE-TABLE-stage scripts -----------

CREATE TABLE IF NOT EXISTS camdecmps.unit_default_test_run(
    unit_default_test_run_id CHARACTER VARYING(45) NOT NULL,
    unit_default_test_sum_id CHARACTER VARYING(45) NOT NULL,
    op_level_num NUMERIC(2,0),
    run_num NUMERIC(2,0) NOT NULL,
    begin_date DATE,
    begin_hour NUMERIC(2,0),
    begin_min NUMERIC(2,0),
    end_date DATE,
    end_hour NUMERIC(2,0),
    end_min NUMERIC(2,0),
    response_time NUMERIC(3,0),
    ref_value NUMERIC(8,3),
    userid CHARACTER VARYING(8),
    add_date TIMESTAMP WITHOUT TIME ZONE,
    update_date TIMESTAMP WITHOUT TIME ZONE,
    run_used_ind NUMERIC(38,0)
)
        WITH (
        OIDS=FALSE
        );
COMMENT ON TABLE camdecmps.unit_default_test_run
     IS 'Unit default test run data.';
COMMENT ON COLUMN camdecmps.unit_default_test_run.unit_default_test_run_id
     IS 'Unique identifier of a unit default test run record. ';
COMMENT ON COLUMN camdecmps.unit_default_test_run.unit_default_test_sum_id
     IS 'Unique combination of DB_Token and identity key generated by sequence generator.';
COMMENT ON COLUMN camdecmps.unit_default_test_run.op_level_num
     IS 'Identifies the operating level for this run of a unit default test. ';
COMMENT ON COLUMN camdecmps.unit_default_test_run.run_num
     IS 'Run number. ';
COMMENT ON COLUMN camdecmps.unit_default_test_run.begin_date
     IS 'Date in which information became effective or activity started.';
COMMENT ON COLUMN camdecmps.unit_default_test_run.begin_hour
     IS 'Hour in which information became effective or activity started.';
COMMENT ON COLUMN camdecmps.unit_default_test_run.begin_min
     IS 'Minute in which information became effective or activity started.';
COMMENT ON COLUMN camdecmps.unit_default_test_run.end_date
     IS 'Last date in which information was effective or date in which activity ended.';
COMMENT ON COLUMN camdecmps.unit_default_test_run.end_hour
     IS 'Last hour n which information was effective or hour in which activity ended.';
COMMENT ON COLUMN camdecmps.unit_default_test_run.end_min
     IS 'Last minute in which information was effective or minute in which activity ended.';
COMMENT ON COLUMN camdecmps.unit_default_test_run.response_time
     IS 'Response time in seconds according to Method 20 of Appendix A to Part 60. ';
COMMENT ON COLUMN camdecmps.unit_default_test_run.ref_value
     IS 'The reference method value for the run. ';
COMMENT ON COLUMN camdecmps.unit_default_test_run.userid
     IS 'User account or source of data that added or updated record.';
COMMENT ON COLUMN camdecmps.unit_default_test_run.add_date
     IS 'Date and time in which record was added.';
COMMENT ON COLUMN camdecmps.unit_default_test_run.update_date
     IS 'Date and time in which record was last updated.';
COMMENT ON COLUMN camdecmps.unit_default_test_run.run_used_ind
     IS 'Used to indicate that this run is used to calculate highest 3-run NOx emission rate average at any tested load level. ';



-- ------------ Write CREATE-INDEX-stage scripts -----------

CREATE INDEX idx_unit_default_te_unit_defau
ON camdecmps.unit_default_test_run
USING BTREE (unit_default_test_sum_id ASC);



-- ------------ Write CREATE-CONSTRAINT-stage scripts -----------

ALTER TABLE camdecmps.unit_default_test_run
ADD CONSTRAINT pk_unit_default_test_run PRIMARY KEY (unit_default_test_run_id);



-- ------------ Write CREATE-FOREIGN-KEY-CONSTRAINT-stage scripts -----------

ALTER TABLE camdecmps.unit_default_test_run
ADD CONSTRAINT fk_unt_default_t_unit_default_ FOREIGN KEY (unit_default_test_sum_id) 
REFERENCES camdecmps.unit_default_test (unit_default_test_sum_id)
ON DELETE NO ACTION;
