-- ------------ Write CREATE-TABLE-stage scripts -----------

CREATE TABLE IF NOT EXISTS camdecmps.ae_hi_gas(
    ae_hi_gas_id CHARACTER VARYING(45) NOT NULL,
    ae_corr_test_run_id CHARACTER VARYING(45) NOT NULL,
    gas_volume NUMERIC(10,1),
    gas_gcv NUMERIC(10,1),
    gas_hi NUMERIC(7,1),
    calc_gas_hi NUMERIC(7,1),
    userid CHARACTER VARYING(8),
    add_date TIMESTAMP WITHOUT TIME ZONE,
    update_date TIMESTAMP WITHOUT TIME ZONE,
    mon_sys_id CHARACTER VARYING(45) NOT NULL
)
        WITH (
        OIDS=FALSE
        );
COMMENT ON TABLE camdecmps.ae_hi_gas
     IS 'Heat input from gas combusted during an Appendix E test.  Record Type 653.';
COMMENT ON COLUMN camdecmps.ae_hi_gas.ae_hi_gas_id
     IS 'Unique identifier of an Appendix E heat input from gas record. ';
COMMENT ON COLUMN camdecmps.ae_hi_gas.ae_corr_test_run_id
     IS 'Unique combination of DB_Token and identity key generated by sequence generator.';
COMMENT ON COLUMN camdecmps.ae_hi_gas.gas_volume
     IS 'Volume of gas combusted during run. ';
COMMENT ON COLUMN camdecmps.ae_hi_gas.gas_gcv
     IS 'Gross calorific value (GCV) of gas. ';
COMMENT ON COLUMN camdecmps.ae_hi_gas.gas_hi
     IS 'Heat input from gas during run. ';
COMMENT ON COLUMN camdecmps.ae_hi_gas.calc_gas_hi
     IS 'Heat input from gas during run. ';
COMMENT ON COLUMN camdecmps.ae_hi_gas.userid
     IS 'User account or source of data that added or updated record. ';
COMMENT ON COLUMN camdecmps.ae_hi_gas.add_date
     IS 'Date and time in which record was added. ';
COMMENT ON COLUMN camdecmps.ae_hi_gas.update_date
     IS 'Date and time in which record was last updated. ';
COMMENT ON COLUMN camdecmps.ae_hi_gas.mon_sys_id
     IS 'Unique identifier of a monitoring system record. ';



-- ------------ Write CREATE-INDEX-stage scripts -----------

CREATE INDEX idx_ae_hi_gas_ae_corr_te
ON camdecmps.ae_hi_gas
USING BTREE (ae_corr_test_run_id ASC);



CREATE INDEX idx_ae_hi_gas_mon_sys_id
ON camdecmps.ae_hi_gas
USING BTREE (mon_sys_id ASC);



-- ------------ Write CREATE-CONSTRAINT-stage scripts -----------

ALTER TABLE camdecmps.ae_hi_gas
ADD CONSTRAINT pk_ae_hi_gas PRIMARY KEY (ae_hi_gas_id);



-- ------------ Write CREATE-FOREIGN-KEY-CONSTRAINT-stage scripts -----------

ALTER TABLE camdecmps.ae_hi_gas
ADD CONSTRAINT fk_ae_correlatio_ae_hi_gas FOREIGN KEY (ae_corr_test_run_id) 
REFERENCES camdecmps.ae_correlation_test_run (ae_corr_test_run_id)
ON DELETE NO ACTION;



ALTER TABLE camdecmps.ae_hi_gas
ADD CONSTRAINT fk_monitor_system_ae_hi_gas FOREIGN KEY (mon_sys_id) 
REFERENCES camdecmps.monitor_system (mon_sys_id)
ON DELETE NO ACTION;
