-- ------------ Write CREATE-TABLE-stage scripts -----------

CREATE TABLE IF NOT EXISTS camdecmps.ae_hi_oil(
    ae_hi_oil_id CHARACTER VARYING(45) NOT NULL,
    ae_corr_test_run_id CHARACTER VARYING(45) NOT NULL,
    oil_mass NUMERIC(10,1),
    oil_hi NUMERIC(7,1),
    calc_oil_hi NUMERIC(7,1),
    oil_gcv NUMERIC(10,1),
    oil_volume NUMERIC(10,1),
    oil_density NUMERIC(11,6),
    userid CHARACTER VARYING(8),
    add_date TIMESTAMP WITHOUT TIME ZONE,
    update_date TIMESTAMP WITHOUT TIME ZONE,
    oil_gcv_uom_cd CHARACTER VARYING(7),
    oil_volume_uom_cd CHARACTER VARYING(7),
    oil_density_uom_cd CHARACTER VARYING(7),
    mon_sys_id CHARACTER VARYING(45) NOT NULL,
    calc_oil_mass NUMERIC(10,1)
)
        WITH (
        OIDS=FALSE
        );
COMMENT ON TABLE camdecmps.ae_hi_oil
     IS 'Heat input from oil combusted during an Appendix E test.  Record Type 652.';
COMMENT ON COLUMN camdecmps.ae_hi_oil.ae_hi_oil_id
     IS 'Unique identifier of an Appendix E heat input from oil record. ';
COMMENT ON COLUMN camdecmps.ae_hi_oil.ae_corr_test_run_id
     IS 'Unique combination of DB_Token and identity key generated by sequence generator.';
COMMENT ON COLUMN camdecmps.ae_hi_oil.oil_mass
     IS 'Mass of oil combusted during run. ';
COMMENT ON COLUMN camdecmps.ae_hi_oil.oil_hi
     IS 'Heat input from oil during run. ';
COMMENT ON COLUMN camdecmps.ae_hi_oil.calc_oil_hi
     IS 'Heat input from oil during run. ';
COMMENT ON COLUMN camdecmps.ae_hi_oil.oil_gcv
     IS 'Gross calorific value (GCV) of oil. ';
COMMENT ON COLUMN camdecmps.ae_hi_oil.oil_volume
     IS 'Volume of oil combusted during run. ';
COMMENT ON COLUMN camdecmps.ae_hi_oil.oil_density
     IS 'Density of oil. ';
COMMENT ON COLUMN camdecmps.ae_hi_oil.userid
     IS 'User account or source of data that added or updated record. ';
COMMENT ON COLUMN camdecmps.ae_hi_oil.add_date
     IS 'Date and time in which record was added. ';
COMMENT ON COLUMN camdecmps.ae_hi_oil.update_date
     IS 'Date and time in which record was last updated. ';
COMMENT ON COLUMN camdecmps.ae_hi_oil.oil_gcv_uom_cd
     IS 'Code used to identify units of measure for GCV of oil. ';
COMMENT ON COLUMN camdecmps.ae_hi_oil.oil_volume_uom_cd
     IS 'Code used to identify units of measure for volume of oil. ';
COMMENT ON COLUMN camdecmps.ae_hi_oil.oil_density_uom_cd
     IS 'Code used to identify units of measure for density of oil. ';
COMMENT ON COLUMN camdecmps.ae_hi_oil.mon_sys_id
     IS 'Unique identifier of a monitoring system record. ';
COMMENT ON COLUMN camdecmps.ae_hi_oil.calc_oil_mass
     IS 'Calculated mass of oil combusted during run. ';



-- ------------ Write CREATE-INDEX-stage scripts -----------

CREATE INDEX idx_ae_hi_oil_ae_corr_te
ON camdecmps.ae_hi_oil
USING BTREE (ae_corr_test_run_id ASC);



CREATE INDEX idx_ae_hi_oil_mon_sys_id
ON camdecmps.ae_hi_oil
USING BTREE (mon_sys_id ASC);



CREATE INDEX idx_ae_hi_oil_oil_densit
ON camdecmps.ae_hi_oil
USING BTREE (oil_density_uom_cd ASC);



CREATE INDEX idx_ae_hi_oil_oil_gcv_uo
ON camdecmps.ae_hi_oil
USING BTREE (oil_gcv_uom_cd ASC);



CREATE INDEX idx_ae_hi_oil_oil_volume
ON camdecmps.ae_hi_oil
USING BTREE (oil_volume_uom_cd ASC);



-- ------------ Write CREATE-CONSTRAINT-stage scripts -----------

ALTER TABLE camdecmps.ae_hi_oil
ADD CONSTRAINT pk_ae_hi_oil PRIMARY KEY (ae_hi_oil_id);



-- ------------ Write CREATE-FOREIGN-KEY-CONSTRAINT-stage scripts -----------

ALTER TABLE camdecmps.ae_hi_oil
ADD CONSTRAINT fk_ae_correlatio_ae_hi_oil FOREIGN KEY (ae_corr_test_run_id) 
REFERENCES camdecmps.ae_correlation_test_run (ae_corr_test_run_id)
ON DELETE NO ACTION;



ALTER TABLE camdecmps.ae_hi_oil
ADD CONSTRAINT fk_monitor_system_ae_hi_oil FOREIGN KEY (mon_sys_id) 
REFERENCES camdecmps.monitor_system (mon_sys_id)
ON DELETE NO ACTION;



ALTER TABLE camdecmps.ae_hi_oil
ADD CONSTRAINT fk_units_of_meas_ae_hi144 FOREIGN KEY (oil_volume_uom_cd) 
REFERENCES camdecmpsmd.units_of_measure_code (uom_cd)
ON DELETE NO ACTION;



ALTER TABLE camdecmps.ae_hi_oil
ADD CONSTRAINT fk_units_of_meas_ae_hi146 FOREIGN KEY (oil_gcv_uom_cd) 
REFERENCES camdecmpsmd.units_of_measure_code (uom_cd)
ON DELETE NO ACTION;



ALTER TABLE camdecmps.ae_hi_oil
ADD CONSTRAINT fk_units_of_meas_ae_hi_oil FOREIGN KEY (oil_density_uom_cd) 
REFERENCES camdecmpsmd.units_of_measure_code (uom_cd)
ON DELETE NO ACTION;
