CREATE TABLE IF NOT EXISTS camdecmps.monitor_location
(
    mon_loc_id character varying(45) COLLATE pg_catalog."default" NOT NULL,
    stack_pipe_id character varying(45) COLLATE pg_catalog."default",
    unit_id numeric(38,0),
    userid character varying(160) COLLATE pg_catalog."default",
    add_date timestamp without time zone,
    update_date timestamp without time zone
);

COMMENT ON TABLE camdecmps.monitor_location
    IS 'Stack characteristic data applicable for the configuration type identified in the monitoring plan.  Name of stack must being with "CS" followed by up to four alphanumeric characters. Record Type 503.';

COMMENT ON COLUMN camdecmps.monitor_location.mon_loc_id
    IS 'Unique identifier of a monitoring location record. ';

COMMENT ON COLUMN camdecmps.monitor_location.stack_pipe_id
    IS 'Unique identifier of a stack or pipe record. ';

COMMENT ON COLUMN camdecmps.monitor_location.unit_id
    IS 'Unique identifier of a unit record which is generated by the EPA Host System. ';

COMMENT ON COLUMN camdecmps.monitor_location.userid
    IS 'User account or source of data that added or updated record. ';

COMMENT ON COLUMN camdecmps.monitor_location.add_date
    IS 'Date and time in which record was added. ';

COMMENT ON COLUMN camdecmps.monitor_location.update_date
    IS 'Date and time in which record was last updated. ';
