CREATE TABLE IF NOT EXISTS camdecmps.qa_supp_data
(
    qa_supp_data_id character varying(45) COLLATE pg_catalog."default" NOT NULL,
    mon_loc_id character varying(45) COLLATE pg_catalog."default" NOT NULL,
    mon_sys_id character varying(45) COLLATE pg_catalog."default",
    component_id character varying(45) COLLATE pg_catalog."default",
    test_type_cd character varying(7) COLLATE pg_catalog."default" NOT NULL,
    test_sum_id character varying(45) COLLATE pg_catalog."default",
    test_reason_cd character varying(7) COLLATE pg_catalog."default",
    test_num character varying(18) COLLATE pg_catalog."default",
    span_scale character varying(10) COLLATE pg_catalog."default",
    begin_date date,
    begin_hour numeric(2,0),
    begin_min numeric(2,0),
    end_date date,
    end_hour numeric(2,0),
    end_min numeric(2,0),
    rpt_period_id numeric(38,0),
    test_result_cd character varying(7) COLLATE pg_catalog."default",
    gp_ind numeric(38,0),
    reinstallation_date date,
    reinstallation_hour numeric(2,0),
    test_expire_date date,
    test_expire_hour numeric(2,0),
    userid character varying(25) COLLATE pg_catalog."default",
    add_date timestamp without time zone,
    update_date timestamp without time zone,
    op_level_cd character varying(7) COLLATE pg_catalog."default",
    submission_id numeric(38,0),
    submission_availability_cd character varying(7) COLLATE pg_catalog."default",
    chk_session_id character varying(45) COLLATE pg_catalog."default",
    operating_condition_cd character varying(7) COLLATE pg_catalog."default",
    fuel_cd character varying(7) COLLATE pg_catalog."default",
    resub_explanation character varying(4000) COLLATE pg_catalog."default"
);

COMMENT ON TABLE camdecmps.qa_supp_data
    IS 'Contains all test summary information needed to evaluate hourly data';

COMMENT ON COLUMN camdecmps.qa_supp_data.qa_supp_data_id
    IS 'Unique combination of DB_Token and identity key generated by sequence generator. ';

COMMENT ON COLUMN camdecmps.qa_supp_data.mon_loc_id
    IS 'Unique identifier of a monitoring location record. ';

COMMENT ON COLUMN camdecmps.qa_supp_data.mon_sys_id
    IS 'Unique identifier of a monitoring system record. ';

COMMENT ON COLUMN camdecmps.qa_supp_data.component_id
    IS 'Unique identifier of a monitoring component record. ';

COMMENT ON COLUMN camdecmps.qa_supp_data.test_type_cd
    IS 'Code used to identify test type. ';

COMMENT ON COLUMN camdecmps.qa_supp_data.test_sum_id
    IS 'Unique identifier of a test summary record. ';

COMMENT ON COLUMN camdecmps.qa_supp_data.test_reason_cd
    IS 'Code used to identify test reason. ';

COMMENT ON COLUMN camdecmps.qa_supp_data.test_num
    IS 'Test number. ';

COMMENT ON COLUMN camdecmps.qa_supp_data.span_scale
    IS 'Span scale. ';

COMMENT ON COLUMN camdecmps.qa_supp_data.begin_date
    IS 'Date in which information became effective or activity started. ';

COMMENT ON COLUMN camdecmps.qa_supp_data.begin_hour
    IS 'Hour in which information became effective or activity started. ';

COMMENT ON COLUMN camdecmps.qa_supp_data.begin_min
    IS 'Minute in which information became effective or activity started.';

COMMENT ON COLUMN camdecmps.qa_supp_data.end_date
    IS 'Last date in which information was effective or date in which activity ended. ';

COMMENT ON COLUMN camdecmps.qa_supp_data.end_hour
    IS 'Last hour n which information was effective or hour in which activity ended. ';

COMMENT ON COLUMN camdecmps.qa_supp_data.end_min
    IS 'Last minute in which information was effective or minute in which activity ended.';

COMMENT ON COLUMN camdecmps.qa_supp_data.rpt_period_id
    IS 'Unique identifier of a reporting period record. ';

COMMENT ON COLUMN camdecmps.qa_supp_data.test_result_cd
    IS 'Code used to identify reported test result. ';

COMMENT ON COLUMN camdecmps.qa_supp_data.gp_ind
    IS 'Indication that test was performed in a grace period. ';

COMMENT ON COLUMN camdecmps.qa_supp_data.reinstallation_date
    IS 'Date in which information became effective or activity started.  Applicable for fuel flowmeter test data only. ';

COMMENT ON COLUMN camdecmps.qa_supp_data.reinstallation_hour
    IS 'Hour in which information became effective or activity started. Applicable of fuel flowmeter test data only. ';

COMMENT ON COLUMN camdecmps.qa_supp_data.test_expire_date
    IS 'Test Expiration Date. ';

COMMENT ON COLUMN camdecmps.qa_supp_data.test_expire_hour
    IS 'Hour in which information became effective or activity started. ';

COMMENT ON COLUMN camdecmps.qa_supp_data.userid
    IS 'User account or source of data that added or updated record.';

COMMENT ON COLUMN camdecmps.qa_supp_data.add_date
    IS 'Date and time in which record was added.';

COMMENT ON COLUMN camdecmps.qa_supp_data.update_date
    IS 'Date and time in which record was last updated.';

COMMENT ON COLUMN camdecmps.qa_supp_data.op_level_cd
    IS 'Code used to identify the operating level. ';

COMMENT ON COLUMN camdecmps.qa_supp_data.submission_id
    IS 'Unique identifier of a submission.';

COMMENT ON COLUMN camdecmps.qa_supp_data.submission_availability_cd
    IS 'Unique code value for a lookup table.';

COMMENT ON COLUMN camdecmps.qa_supp_data.chk_session_id
    IS 'Unique combination of DB_Token and identity key generated by sequence generator.';

COMMENT ON COLUMN camdecmps.qa_supp_data.operating_condition_cd
    IS 'Code used to identify the operating condition. ';

COMMENT ON COLUMN camdecmps.qa_supp_data.fuel_cd
    IS 'Code used to identify the type of fuel. ';
