CREATE TABLE IF NOT EXISTS camdecmps.unit_stack_configuration
(
    config_id character varying(45) COLLATE pg_catalog."default" NOT NULL,
    unit_id numeric(38,0) NOT NULL,
    stack_pipe_id character varying(45) COLLATE pg_catalog."default" NOT NULL,
    begin_date date NOT NULL,
    end_date date,
    userid character varying(25) COLLATE pg_catalog."default",
    add_date timestamp without time zone,
    update_date timestamp without time zone
);

COMMENT ON TABLE camdecmps.unit_stack_configuration
    IS 'Identifies the units, stacks or pipes that are associated with a specific monitoring plan.';

COMMENT ON COLUMN camdecmps.unit_stack_configuration.config_id
    IS 'Unique identifier of a monitoring configuration record. ';

COMMENT ON COLUMN camdecmps.unit_stack_configuration.unit_id
    IS 'Unique identifier of a unit record which is generated by the EPA Host System. ';

COMMENT ON COLUMN camdecmps.unit_stack_configuration.stack_pipe_id
    IS 'Unique identifier of a stack or pipe record. ';

COMMENT ON COLUMN camdecmps.unit_stack_configuration.begin_date
    IS 'Date in which information became effective or activity started. ';

COMMENT ON COLUMN camdecmps.unit_stack_configuration.end_date
    IS 'Last date in which information was effective or date in which activity ended. ';

COMMENT ON COLUMN camdecmps.unit_stack_configuration.userid
    IS 'User account or source of data that added or updated record. ';

COMMENT ON COLUMN camdecmps.unit_stack_configuration.add_date
    IS 'Date and time in which record was added. ';

COMMENT ON COLUMN camdecmps.unit_stack_configuration.update_date
    IS 'Date and time in which record was last updated. ';
