CREATE TABLE CAMDNATS.TACCT_OWNER
(
  ACCT_OWN_ID  NUMERIC(38)    NOT NULL,
  OWN_ID       NUMERIC(38),
  ACCTNUM_ID   CHAR(12)         NOT NULL,
  START_DATE   TIMESTAMP        NOT NULL,
  END_DATE     TIMESTAMP,
  ONT_TYPE_CD  CHAR(3)          NOT NULL,
  USERID       VARCHAR(160)     NOT NULL,
  UPDATE_DATE  TIMESTAMP        NOT NULL,
  PPL_ID       NUMERIC(38)
);


COMMENT ON TABLE CAMDNATS.TACCT_OWNER IS 'This table stores the Owner-Account relationships for Non-Unit Accounts.  Unit Accounts will have this information tracked in SMS.';

COMMENT ON COLUMN CAMDNATS.TACCT_OWNER.ACCT_OWN_ID IS 'ACCOUNT OWNER ID';
COMMENT ON COLUMN CAMDNATS.TACCT_OWNER.OWN_ID IS 'OWNER ID';
COMMENT ON COLUMN CAMDNATS.TACCT_OWNER.ACCTNUM_ID IS 'ACCOUNT NUMBER ID';
COMMENT ON COLUMN CAMDNATS.TACCT_OWNER.START_DATE IS 'START DATE';
COMMENT ON COLUMN CAMDNATS.TACCT_OWNER.END_DATE IS 'END DATE';
COMMENT ON COLUMN CAMDNATS.TACCT_OWNER.ONT_TYPE_CD IS 'OWNER TYPE CODE';
COMMENT ON COLUMN CAMDNATS.TACCT_OWNER.USERID IS 'USER ID';
COMMENT ON COLUMN CAMDNATS.TACCT_OWNER.UPDATE_DATE IS 'UPDATE DATE';
COMMENT ON COLUMN CAMDNATS.TACCT_OWNER.PPL_ID IS 'People id of account owner.';
