CREATE TABLE CAMDNATS.TACCTCHG
(
  ACCTNUM_ID    CHAR(12)                   NOT NULL,
  CHGFIELD_NME  CHAR(12)                   NOT NULL,
  DATE_DT       CHAR(8)                    NOT NULL,
  TIME_TM       CHAR(6)                    NOT NULL,
  OLDVALUE_NME  VARCHAR(50)               NOT NULL,
  NEWVALUE_NME  VARCHAR(50)               NOT NULL,
  USERID_ID     VARCHAR(160)              NOT NULL
);


COMMENT ON TABLE CAMDNATS.TACCTCHG IS 'This table tracks changes to the account table.';

COMMENT ON COLUMN CAMDNATS.TACCTCHG.ACCTNUM_ID IS 'ACCOUNT NUMBER ID';
COMMENT ON COLUMN CAMDNATS.TACCTCHG.CHGFIELD_NME IS 'NAME OF MODIFIED FIELD';
COMMENT ON COLUMN CAMDNATS.TACCTCHG.DATE_DT IS 'MODIFICATION DATE';
COMMENT ON COLUMN CAMDNATS.TACCTCHG.TIME_TM IS 'MODIFICATION TIME';
COMMENT ON COLUMN CAMDNATS.TACCTCHG.OLDVALUE_NME IS 'OLD VALUE OF FIELD';
COMMENT ON COLUMN CAMDNATS.TACCTCHG.NEWVALUE_NME IS 'NEW VALUE OF FIELD';
COMMENT ON COLUMN CAMDNATS.TACCTCHG.USERID_ID IS 'USER ID';
