CREATE TABLE CAMDNATS.TARS_ALLW_MSID
(
  COMPYEAR_DT   CHAR(4)         NOT NULL,
  ACCTNUM_ID    CHAR(12)        NOT NULL,
  MSID_ID       CHAR(6)         NOT NULL,
  CMMNTDCT_CNT  NUMERIC(8,7)    NOT NULL,
  USERID        VARCHAR(160)    DEFAULT 'ATS' NOT NULL,
  ADD_DATE      TIMESTAMP       DEFAULT now()::timestamp NOT NULL,
  UPDATE_DATE   TIMESTAMP
);


COMMENT ON TABLE CAMDNATS.TARS_ALLW_MSID IS 'This table stores information about the percentage of emissions contributed by a unit to a monitoring location.';

COMMENT ON COLUMN CAMDNATS.TARS_ALLW_MSID.COMPYEAR_DT IS 'COMPLIANCE YEAR';
COMMENT ON COLUMN CAMDNATS.TARS_ALLW_MSID.ACCTNUM_ID IS 'ACCOUNT NUMERIC ID';
COMMENT ON COLUMN CAMDNATS.TARS_ALLW_MSID.MSID_ID IS 'MONITORING LOCATION ID';
COMMENT ON COLUMN CAMDNATS.TARS_ALLW_MSID.CMMNTDCT_CNT IS 'PERCENTAGE EMISSIONS TO DEDUCT';
COMMENT ON COLUMN CAMDNATS.TARS_ALLW_MSID.ADD_DATE IS 'Date the record was created.';
COMMENT ON COLUMN CAMDNATS.TARS_ALLW_MSID.UPDATE_DATE IS 'Date record was updated.';
COMMENT ON COLUMN CAMDNATS.TARS_ALLW_MSID.USERID IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
