CREATE TABLE CAMDNATS.TARS_ALLW_DED
(
  COMPYEAR_DT   CHAR(4)         NOT NULL,
  ACCTNUM_ID    CHAR(12)        NOT NULL,
  DEDTYPE_CD    CHAR(2)         NOT NULL,
  ALLWYEAR_DT   NUMERIC(4)      NOT NULL,
  ALLWCRED_TOT  NUMERIC(6)      NOT NULL,
  ALLWDCT_CNT   NUMERIC(10)     NOT NULL
);


COMMENT ON TABLE CAMDNATS.TARS_ALLW_DED IS 'This table stores allowances deductions for accounts.';

COMMENT ON COLUMN CAMDNATS.TARS_ALLW_DED.COMPYEAR_DT IS 'COMPLIANCE YEAR';
COMMENT ON COLUMN CAMDNATS.TARS_ALLW_DED.ACCTNUM_ID IS 'ACCOUNT NUMERIC ID';
COMMENT ON COLUMN CAMDNATS.TARS_ALLW_DED.DEDTYPE_CD IS 'DEDUCTION TYPE CODE';
COMMENT ON COLUMN CAMDNATS.TARS_ALLW_DED.ALLWYEAR_DT IS 'ALLOWANCE YEAR';
COMMENT ON COLUMN CAMDNATS.TARS_ALLW_DED.ALLWCRED_TOT IS 'NUMERIC OF ALLOWANCES CREDITED';
COMMENT ON COLUMN CAMDNATS.TARS_ALLW_DED.ALLWDCT_CNT IS 'NUMERIC OF ALLOWANCES DEDUCTED';
