CREATE TABLE CAMDNATS.TARS_BAL_DED
(
  ACCTNUM_ID   CHAR(12)     NOT NULL,
  COMPYEAR_DT  CHAR(4)      NOT NULL,
  ALLWYEAR_DT  NUMERIC(4)   NOT NULL,
  BALANCE_TOT  NUMERIC(8)   NOT NULL
);


COMMENT ON TABLE CAMDNATS.TARS_BAL_DED IS 'Stores the Balance for an account for a given compliance and allowance year.';

COMMENT ON COLUMN CAMDNATS.TARS_BAL_DED.ACCTNUM_ID IS 'ACCOUNT NUMERIC ID';
COMMENT ON COLUMN CAMDNATS.TARS_BAL_DED.COMPYEAR_DT IS 'COMPLIANCE YEAR';
COMMENT ON COLUMN CAMDNATS.TARS_BAL_DED.ALLWYEAR_DT IS 'ALLOWANCE YEAR';
COMMENT ON COLUMN CAMDNATS.TARS_BAL_DED.BALANCE_TOT IS 'BALANCE TOTAL';
