CREATE TABLE CAMDNATS.TAUTHYR
(
  LIMITTYP_CD   CHAR(1)         NOT NULL,
  ALLWYEAR_DT   NUMERIC(4)      NOT NULL,
  ACCTNUM_ID    CHAR(12)        NOT NULL,
  YEARMAX_TOT   NUMERIC(10)     NOT NULL,
  YEARISSU_TOT  NUMERIC(10)     NOT NULL,
  PARACCT_ID    CHAR(12)
);


COMMENT ON TABLE CAMDNATS.TAUTHYR IS 'This table stores the authorized limits for reserve accounts on a yearly basis.';

COMMENT ON COLUMN CAMDNATS.TAUTHYR.LIMITTYP_CD IS 'LIMIT TYPE CODE';
COMMENT ON COLUMN CAMDNATS.TAUTHYR.ALLWYEAR_DT IS 'ALLOWANCE YEAR';
COMMENT ON COLUMN CAMDNATS.TAUTHYR.ACCTNUM_ID IS 'ACCOUNT NUMERIC ID';
COMMENT ON COLUMN CAMDNATS.TAUTHYR.YEARMAX_TOT IS 'ACCOUNT LIMIT FOR YEAR';
COMMENT ON COLUMN CAMDNATS.TAUTHYR.YEARISSU_TOT IS 'AMOUNT ALLOCATED IN YEAR';
COMMENT ON COLUMN CAMDNATS.TAUTHYR.PARACCT_ID IS 'PARENT ACCOUNT ID';
