CREATE TABLE CAMDNATS.TAUTHCHG
(
  ALLWYEAR_DT   NUMERIC(4)      NOT NULL,
  MODDATE_DT    CHAR(8)         NOT NULL,
  TIME_TM       CHAR(6)         NOT NULL,
  ACCTNUM_ID    CHAR(12)        NOT NULL,
  OLDLIMIT_TOT  NUMERIC(10)     NOT NULL,
  NEWLIMIT_TOT  NUMERIC(10)     NOT NULL,
  USERID_ID     VARCHAR(160)    NOT NULL
);


COMMENT ON TABLE CAMDNATS.TAUTHCHG IS 'This table tracks changes to the authorized limits for a reserve account.';

COMMENT ON COLUMN CAMDNATS.TAUTHCHG.ALLWYEAR_DT IS 'ALLOWANCE YEAR';
COMMENT ON COLUMN CAMDNATS.TAUTHCHG.MODDATE_DT IS 'MODIFICATION DATE';
COMMENT ON COLUMN CAMDNATS.TAUTHCHG.TIME_TM IS 'MODIFICATION TIME';
COMMENT ON COLUMN CAMDNATS.TAUTHCHG.ACCTNUM_ID IS 'ACCOUNT NUMERIC ID';
COMMENT ON COLUMN CAMDNATS.TAUTHCHG.OLDLIMIT_TOT IS 'OLD ACCOUNT LIMIT';
COMMENT ON COLUMN CAMDNATS.TAUTHCHG.NEWLIMIT_TOT IS 'NEW ACCOUNT LIMIT';
COMMENT ON COLUMN CAMDNATS.TAUTHCHG.USERID_ID IS 'USER ID';
