CREATE TABLE CAMDNATS.TSYSDATA
(
  COMPYEAR_DT       CHAR(4)     NOT NULL,
  QUARTER           CHAR(1)     NOT NULL,
  STATUS_IND        CHAR(1)     NOT NULL,
  ATS_FREEZE_IND    CHAR(1)     NOT NULL,
  NATS_FREEZE_IND   CHAR(1)     NOT NULL,
  EMIS_LOAD_DATE    CHAR(8),
  EMIS_IMPORT_DATE  CHAR(8),
  NOXCOMP_DT        CHAR(8)
);


COMMENT ON TABLE CAMDNATS.TSYSDATA IS 'This table stores system data.';

COMMENT ON COLUMN CAMDNATS.TSYSDATA.COMPYEAR_DT IS 'COMPLIANCE YEAR';
COMMENT ON COLUMN CAMDNATS.TSYSDATA.QUARTER IS 'QUARTER';
COMMENT ON COLUMN CAMDNATS.TSYSDATA.STATUS_IND IS 'STATUS FLAG';
COMMENT ON COLUMN CAMDNATS.TSYSDATA.ATS_FREEZE_IND IS 'ATS FREEZE FLAG';
COMMENT ON COLUMN CAMDNATS.TSYSDATA.NATS_FREEZE_IND IS 'NATS FREEZE FLAG';
COMMENT ON COLUMN CAMDNATS.TSYSDATA.EMIS_LOAD_DATE IS 'EMISSIONS LOAD DATE';
COMMENT ON COLUMN CAMDNATS.TSYSDATA.EMIS_IMPORT_DATE IS 'EMISSIONS IMPO';
COMMENT ON COLUMN CAMDNATS.TSYSDATA.NOXCOMP_DT IS 'The date on which the NOx Compliance Assessment was last executed.';
