CREATE TABLE CAMDNATS.TTRANSACT
(
  TRANEVNT_CNT  NUMERIC(10)     NOT NULL,
  TRANTYPE_CD   CHAR(2)         NOT NULL,
  BUYACCT_ID    CHAR(12)        NOT NULL,
  SELLACCT_ID   CHAR(12)        NOT NULL,
  BUYREP_ID     NUMERIC(38)     NOT NULL,
  SELLREP_ID    NUMERIC(38)     NOT NULL,
  CHGDTRAN_CNT  NUMERIC(10),
  NUMTRANS_TOT  NUMERIC(8)      NOT NULL,
  RECPTDTE_DT   CHAR(8)         NOT NULL,
  CNFRMDTE_DT   CHAR(8)         NOT NULL,
  TRANSTAT_CD   CHAR(2)         NOT NULL,
  USERID1_ID    VARCHAR(160)    NOT NULL,
  USERID2_ID    VARCHAR(160),
  COMPYEAR_DT   CHAR(4)
);


COMMENT ON TABLE CAMDNATS.TTRANSACT IS 'This table stores information pertaining to a given transaction.';

COMMENT ON COLUMN CAMDNATS.TTRANSACT.TRANEVNT_CNT IS 'TRANSACTION EVENT NUMERIC';
COMMENT ON COLUMN CAMDNATS.TTRANSACT.TRANTYPE_CD IS 'TRANSACTION EVENT TYPE CODE';
COMMENT ON COLUMN CAMDNATS.TTRANSACT.BUYACCT_ID IS 'BUYER ACCOUNT';
COMMENT ON COLUMN CAMDNATS.TTRANSACT.SELLACCT_ID IS 'SELLER ACCOUNT';
COMMENT ON COLUMN CAMDNATS.TTRANSACT.BUYREP_ID IS 'BUYER PEOPLE ID';
COMMENT ON COLUMN CAMDNATS.TTRANSACT.SELLREP_ID IS 'SELLER PEOPLE ID';
COMMENT ON COLUMN CAMDNATS.TTRANSACT.CHGDTRAN_CNT IS 'CHANGED TRANSACTION NUMERIC';
COMMENT ON COLUMN CAMDNATS.TTRANSACT.NUMTRANS_TOT IS 'NUMERIC OF ALLOWANCES TRANSFERRED';
COMMENT ON COLUMN CAMDNATS.TTRANSACT.RECPTDTE_DT IS 'TRANSACTION EVENT RECEIPT DATE';
COMMENT ON COLUMN CAMDNATS.TTRANSACT.CNFRMDTE_DT IS 'TRANSACTION EVENT CONFIRMED DATE';
COMMENT ON COLUMN CAMDNATS.TTRANSACT.TRANSTAT_CD IS 'TRANSACTION EVENT STATUS CODE';
COMMENT ON COLUMN CAMDNATS.TTRANSACT.USERID1_ID IS 'DATA ENTRY USER IDENTIFICATION NUMERIC';
COMMENT ON COLUMN CAMDNATS.TTRANSACT.USERID2_ID IS 'DATA CONFIRMATION USER IDENTIFICATION NUMERIC';
COMMENT ON COLUMN CAMDNATS.TTRANSACT.COMPYEAR_DT IS 'Compliance Year.';
