CREATE TABLE CAMDNATS.TTRANERR
(
  SEQUENCE_CNT  NUMERIC(4)      NOT NULL,
  ERRCODE_CD    NUMERIC(4)      NOT NULL,
  TRANEVNT_CNT  NUMERIC(10)     NOT NULL,
  ERRFIELD_NME  VARCHAR(20)     NOT NULL,
  ERRVALUE_NME  VARCHAR(50)     NOT NULL
);


COMMENT ON TABLE CAMDNATS.TTRANERR IS 'This table stores transaction errors.';

COMMENT ON COLUMN CAMDNATS.TTRANERR.SEQUENCE_CNT IS 'TRANSACTION EVENT SEQUENCE NUMERIC';
COMMENT ON COLUMN CAMDNATS.TTRANERR.ERRCODE_CD IS 'TRANSACTION ERROR CODE';
COMMENT ON COLUMN CAMDNATS.TTRANERR.TRANEVNT_CNT IS 'TRANSACTION EVENT NUMERIC';
COMMENT ON COLUMN CAMDNATS.TTRANERR.ERRFIELD_NME IS 'TRANSACTION EVENT ERROR FIELD';
COMMENT ON COLUMN CAMDNATS.TTRANERR.ERRVALUE_NME IS 'TRANSACTION EVENT ERROR VALUE';
