-----------------
-- Constraints --
-----------------

ALTER TABLE CAMDNATS.TACCT_OWNER ADD CONSTRAINT TACCT_OWNER_PK PRIMARY KEY (ACCT_OWN_ID);
ALTER TABLE CAMDNATS.TACCT_OWNER ADD CONSTRAINT TACCT_OWNER_ACC_FK FOREIGN KEY (ACCTNUM_ID) REFERENCES CAMDNATS.TACCOUNT (ACCTNUM_ID);
