-----------------
-- Constraints --
-----------------

ALTER TABLE CAMDNATS.TARS_BAL_DED ADD CONSTRAINT TARS_BAL_DED_PK PRIMARY KEY (ACCTNUM_ID, COMPYEAR_DT, ALLWYEAR_DT);
ALTER TABLE CAMDNATS.TARS_BAL_DED ADD CONSTRAINT TARS_BAL_DED_ACC_FK FOREIGN KEY (ACCTNUM_ID) REFERENCES CAMDNATS.TACCOUNT (ACCTNUM_ID);
