-----------------
-- Constraints --
-----------------

ALTER TABLE CAMDNATS.TUNITDEDUCT ADD CONSTRAINT TUNITDEDUCT_PK PRIMARY KEY (ACCTNUM_ID, COMPYEAR_DT, DEDSQNCE_CNT, DEDUCTCAT_CD);
ALTER TABLE CAMDNATS.TUNITDEDUCT ADD CONSTRAINT TUNITDEDUCT_ACC_FK FOREIGN KEY (ACCTNUM_ID) REFERENCES CAMDNATS.TACCOUNT (ACCTNUM_ID);
