CREATE TABLE IF NOT EXISTS camdams.account_compliance_block
(
    account_comp_block_id bigint GENERATED BY DEFAULT AS IDENTITY,
    account_comp_id numeric(38,0) NOT NULL,
    prg_vintage_id numeric(38,0) NOT NULL,
    begin_number numeric(19,0) NOT NULL,
    end_number numeric(19,0) NOT NULL,
    deduction_order numeric(38,0) NOT NULL,
    block_role varchar(7) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    userid varchar(160) NOT NULL,
    trans_type_cd varchar(7),
    balance_cd varchar(7) NOT NULL DEFAULT '1TO1',
    trans_ind numeric(1,0) NOT NULL DEFAULT 1,
    PRIMARY KEY (account_comp_block_id)
);
COMMENT ON TABLE camdams.account_compliance_block
    IS 'Lists allowance blocks deducted for compliance by account_comp_id.';
COMMENT ON COLUMN camdams.account_compliance_block.account_comp_block_id
    IS 'Identity key for the account compliance block table.';
COMMENT ON COLUMN camdams.account_compliance_block.account_comp_id
    IS 'Identity key for account compliance table.';
COMMENT ON COLUMN camdams.account_compliance_block.prg_vintage_id
    IS 'Identity key for program vintage table.';
COMMENT ON COLUMN camdams.account_compliance_block.begin_number
    IS 'Beginning serial number for the allowance block.';
COMMENT ON COLUMN camdams.account_compliance_block.end_number
    IS 'Ending serial number for an allowance block.';
COMMENT ON COLUMN camdams.account_compliance_block.deduction_order
    IS 'Order the allowances were deducted for compliance.';
COMMENT ON COLUMN camdams.account_compliance_block.block_role
    IS 'Reason allowance block was staged for deduction.';
COMMENT ON COLUMN camdams.account_compliance_block.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camdams.account_compliance_block.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camdams.account_compliance_block.trans_type_cd
    IS 'Code for type of transaction.';
COMMENT ON COLUMN camdams.account_compliance_block.balance_cd
    IS 'Balance code.';
COMMENT ON COLUMN camdams.account_compliance_block.trans_ind
    IS 'Indicates if a block needs to be deducted via a transfer.  If 0, then the block does not need to be part of a transaction.';