CREATE TABLE IF NOT EXISTS camdams.account_person
(
    account_ppl_id bigint GENERATED BY DEFAULT AS IDENTITY,
    account_id numeric(38,0) NOT NULL,
    ppl_id numeric(38,0) NOT NULL,
    responsibility_id varchar(7) NOT NULL,
    begin_date timestamp without time zone NOT NULL,
    end_date timestamp without time zone,
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (account_ppl_id)
);
COMMENT ON TABLE camdams.account_person
    IS 'Links account_id and the ppl_id of the representative.';
COMMENT ON COLUMN camdams.account_person.account_ppl_id
    IS 'Identity key for account people table.';
COMMENT ON COLUMN camdams.account_person.account_id
    IS 'Identity key for account table.';
COMMENT ON COLUMN camdams.account_person.ppl_id
    IS 'Identity key for people table.';
COMMENT ON COLUMN camdams.account_person.responsibility_id
    IS 'Responsibility type code.';
COMMENT ON COLUMN camdams.account_person.begin_date
    IS 'Date on which a relationship or an activity began. ';
COMMENT ON COLUMN camdams.account_person.end_date
    IS 'Date on which a relationship or an activity ended. ';
COMMENT ON COLUMN camdams.account_person.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camdams.account_person.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camdams.account_person.update_date
    IS 'Date of the last record update.';