CREATE TABLE IF NOT EXISTS camdams.account
(
    account_id bigint GENERATED BY DEFAULT AS IDENTITY,
    account_name varchar(100) NOT NULL,
    account_number varchar(12) NOT NULL,
    account_type_cd varchar(7) NOT NULL,
    contact_email_address varchar(70),
    contact_name varchar(100),
    state_cd varchar(2),
    tribal_land_cd varchar(7),
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (account_id)
);
COMMENT ON TABLE camdams.account
    IS 'Identifies all AMS accounts.';
COMMENT ON COLUMN camdams.account.account_id
    IS 'Identity key for account table.';
COMMENT ON COLUMN camdams.account.account_name
    IS 'Name of account.';
COMMENT ON COLUMN camdams.account.account_number
    IS 'Unique public identifier for account table.';
COMMENT ON COLUMN camdams.account.account_type_cd
    IS 'Type of account.';
COMMENT ON COLUMN camdams.account.contact_email_address
    IS 'Email address of state contact for state allocation accounts.';
COMMENT ON COLUMN camdams.account.contact_name
    IS 'Contact name of state contact for state allocation accounts.';
COMMENT ON COLUMN camdams.account.state_cd
    IS 'State abbreviation for state in which account is located. ';
COMMENT ON COLUMN camdams.account.tribal_land_cd
    IS 'Tribal land abbreviation for tribal land in which account is located.';
COMMENT ON COLUMN camdams.account.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camdams.account.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camdams.account.update_date
    IS 'Date of the last record update.';