CREATE TABLE IF NOT EXISTS camdams.account_compliance_assurance
(
    account_comp_assurance_id bigint GENERATED BY DEFAULT AS IDENTITY,
    account_comp_id numeric(38,0) NOT NULL,
    trans_id numeric(38,0) NOT NULL,
    assurance_liability numeric(15,0) NOT NULL,
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (account_comp_assurance_id)
);
COMMENT ON TABLE camdams.account_compliance_assurance
    IS 'Compliance Assurance Liability for account compliance records for CSAPR programs.';
COMMENT ON COLUMN camdams.account_compliance_assurance.account_comp_assurance_id
    IS 'Identity key for account compliance assurance table.';
COMMENT ON COLUMN camdams.account_compliance_assurance.account_comp_id
    IS 'Identity key for account compliance table.';
COMMENT ON COLUMN camdams.account_compliance_assurance.trans_id
    IS 'Identity key for transaction table.';
COMMENT ON COLUMN camdams.account_compliance_assurance.assurance_liability
    IS 'Compliance Assurance Liability amount.';
COMMENT ON COLUMN camdams.account_compliance_assurance.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camdams.account_compliance_assurance.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camdams.account_compliance_assurance.update_date
    IS 'Date of the last record update.';