CREATE TABLE IF NOT EXISTS camdams.account_allowance_deduction
(
    account_allow_deduction_id bigint GENERATED BY DEFAULT AS IDENTITY,
    account_id numeric(38,0) NOT NULL,
    comp_period_id numeric(38,0) NOT NULL,
    deduction_order numeric(4,0) NOT NULL,
    begin_number numeric(19,0) NOT NULL,
    end_number numeric(19,0) NOT NULL,
    prg_vintage_id numeric(38,0) NOT NULL,
    deduction_type_cd varchar(7),
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (account_allow_deduction_id)
);
COMMENT ON TABLE camdams.account_allowance_deduction
    IS 'Tracks allowance blocks designated for deduction for a specific account and compliance year.';
COMMENT ON COLUMN camdams.account_allowance_deduction.account_allow_deduction_id
    IS 'Identity key for account allowance deduction table.';
COMMENT ON COLUMN camdams.account_allowance_deduction.account_id
    IS 'Identity key for account table.';
COMMENT ON COLUMN camdams.account_allowance_deduction.comp_period_id
    IS 'Identity key for compliance period table.';
COMMENT ON COLUMN camdams.account_allowance_deduction.deduction_order
    IS 'Order the allowances will be deducted for compliance.';
COMMENT ON COLUMN camdams.account_allowance_deduction.begin_number
    IS 'Beginning serial number for the allowance block.';
COMMENT ON COLUMN camdams.account_allowance_deduction.end_number
    IS 'Ending serial number for an allowance block.';
COMMENT ON COLUMN camdams.account_allowance_deduction.prg_vintage_id
    IS 'Identity key for program vintage table.';
COMMENT ON COLUMN camdams.account_allowance_deduction.deduction_type_cd
    IS 'Deduction type code.';
COMMENT ON COLUMN camdams.account_allowance_deduction.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camdams.account_allowance_deduction.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camdams.account_allowance_deduction.update_date
    IS 'Date of the last record update.';