CREATE TABLE IF NOT EXISTS camdams.account_compliance_liability
(
    account_comp_liability_id bigint GENERATED BY DEFAULT AS IDENTITY,
    account_comp_id numeric(38,0) NOT NULL,
    liability_type_cd varchar(7) NOT NULL,
    liability_amount numeric(15,3) NOT NULL,
    PRIMARY KEY (account_comp_liability_id)
);
COMMENT ON TABLE camdams.account_compliance_liability
    IS 'Liability for account compliance records for liability types unique to pre 2006 compliance.';
COMMENT ON COLUMN camdams.account_compliance_liability.account_comp_liability_id
    IS 'Identity key for account compliance liability table.';
COMMENT ON COLUMN camdams.account_compliance_liability.account_comp_id
    IS 'Identity key for account compliance table.';
COMMENT ON COLUMN camdams.account_compliance_liability.liability_type_cd
    IS 'Liability type code.';
COMMENT ON COLUMN camdams.account_compliance_liability.liability_amount
    IS 'Liability amount at the time of compliance.';