CREATE TABLE IF NOT EXISTS camdams.account_compliance_balance
(
    account_comp_bal_id bigint GENERATED BY DEFAULT AS IDENTITY,
    account_comp_id numeric(38,0) NOT NULL,
    balance_cd varchar(7) NOT NULL,
    begin_balance numeric(15,0) NOT NULL,
    end_balance numeric(15,0),
    prg_vintage_id numeric(38,0),
    PRIMARY KEY (account_comp_bal_id)
);
COMMENT ON TABLE camdams.account_compliance_balance
    IS 'Lists begin balance and end balance for a specific compliance record at the time of compliance.';
COMMENT ON COLUMN camdams.account_compliance_balance.account_comp_bal_id
    IS 'Identity key for account compliance balance table.';
COMMENT ON COLUMN camdams.account_compliance_balance.account_comp_id
    IS 'Identity key for account compliance table.';
COMMENT ON COLUMN camdams.account_compliance_balance.balance_cd
    IS 'Balance code.';
COMMENT ON COLUMN camdams.account_compliance_balance.begin_balance
    IS 'Number of allowances of the current vintage or earlier held at compliance.';
COMMENT ON COLUMN camdams.account_compliance_balance.end_balance
    IS 'Number of allowances of the current vintage or earlier held after compliance.';
COMMENT ON COLUMN camdams.account_compliance_balance.prg_vintage_id
    IS 'Identity key for program vintage table.';