CREATE TABLE IF NOT EXISTS camdams.account_block
(
    account_block_id bigint GENERATED BY DEFAULT AS IDENTITY,
    account_id numeric(38,0) NOT NULL,
    allow_block_id numeric(38,0) NOT NULL,
    acquisition_date timestamp without time zone,
    trans_id numeric(38,0),
    userid varchar(160) NOT NULL,
    PRIMARY KEY (account_block_id)
);
COMMENT ON TABLE camdams.account_block
    IS 'Links account id with allowance blocks it holds.';
COMMENT ON COLUMN camdams.account_block.account_block_id
    IS 'Identity key for account block table.';
COMMENT ON COLUMN camdams.account_block.account_id
    IS 'Identity key for account table.';
COMMENT ON COLUMN camdams.account_block.allow_block_id
    IS 'Identity key for allowance block table.';
COMMENT ON COLUMN camdams.account_block.acquisition_date
    IS 'Date allowance block was transferred into the account.';
COMMENT ON COLUMN camdams.account_block.trans_id
    IS 'Identity key for transaction table.';
COMMENT ON COLUMN camdams.account_block.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';