CREATE TABLE IF NOT EXISTS camdams.account_compliance_settings
(
    account_comp_set_id bigint GENERATED BY DEFAULT AS IDENTITY,
    account_id numeric(38,0),
    comp_period_id numeric(38,0),
    petition_ind numeric(1,0) DEFAULT 0,
    petition_explanation varchar(4000),
    userid varchar(160),
    add_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (account_comp_set_id)
);
COMMENT ON TABLE camdams.account_compliance_settings
    IS 'Contains compliance settings and information for and individual account and compliance period.';
COMMENT ON COLUMN camdams.account_compliance_settings.account_comp_set_id
    IS 'Identity key for account compliance settings table.';
COMMENT ON COLUMN camdams.account_compliance_settings.account_id
    IS 'Identity key for account table.';
COMMENT ON COLUMN camdams.account_compliance_settings.comp_period_id
    IS 'Identity key for account compliance table.';
COMMENT ON COLUMN camdams.account_compliance_settings.petition_ind
    IS 'Indicates whether an unhandled petition exists for the account and compliance period.';
COMMENT ON COLUMN camdams.account_compliance_settings.petition_explanation
    IS 'Explains the current or last petition for the account and compliance period.';
COMMENT ON COLUMN camdams.account_compliance_settings.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camdams.account_compliance_settings.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camdams.account_compliance_settings.update_date
    IS 'Date of the last record update.';