CREATE TABLE IF NOT EXISTS camdams.account_program
(
    account_prg_id bigint GENERATED BY DEFAULT AS IDENTITY,
    account_id numeric(38,0) NOT NULL,
    prg_cd varchar(7) NOT NULL,
    account_status_cd varchar(7) NOT NULL,
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (account_prg_id)
);
COMMENT ON TABLE camdams.account_program
    IS 'Links account_id with the prg_codes it can trade in.';
COMMENT ON COLUMN camdams.account_program.account_prg_id
    IS 'Identity key for account program table.';
COMMENT ON COLUMN camdams.account_program.account_id
    IS 'Identity key for account table.';
COMMENT ON COLUMN camdams.account_program.prg_cd
    IS 'Code used to identify regulatory program applicable to account.  ';
COMMENT ON COLUMN camdams.account_program.account_status_cd
    IS 'Account status code.';
COMMENT ON COLUMN camdams.account_program.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camdams.account_program.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camdams.account_program.update_date
    IS 'Date of the last record update.';