CREATE TABLE IF NOT EXISTS camdams.account_plant
(
    account_plant_id bigint GENERATED BY DEFAULT AS IDENTITY,
    account_id numeric(38,0) NOT NULL,
    fac_id numeric(38,0) NOT NULL,
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (account_plant_id)
);
COMMENT ON TABLE camdams.account_plant
    IS 'Links account id and fac id for facility accounts.';
COMMENT ON COLUMN camdams.account_plant.account_plant_id
    IS 'Identity key for account_facility table.';
COMMENT ON COLUMN camdams.account_plant.account_id
    IS 'Identity key for account table.';
COMMENT ON COLUMN camdams.account_plant.fac_id
    IS 'Identity key for facility table.';
COMMENT ON COLUMN camdams.account_plant.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camdams.account_plant.add_date
    IS 'Date the record was created.';