CREATE TABLE IF NOT EXISTS camdams.account_unit
(
    account_unit_id bigint GENERATED BY DEFAULT AS IDENTITY,
    account_id numeric(38,0),
    unit_id numeric(38,0) NOT NULL,
    account_number varchar(12) NOT NULL,
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (account_unit_id)
);
COMMENT ON TABLE camdams.account_unit
    IS 'Links account id and unit id for unit accounts.';
COMMENT ON COLUMN camdams.account_unit.account_unit_id
    IS 'Identity key for account_unit table.';
COMMENT ON COLUMN camdams.account_unit.account_id
    IS 'Identity key for account table (if the unit account is an ARP unit account; will be NULL for OTC/NBP-only unit accounts).';
COMMENT ON COLUMN camdams.account_unit.unit_id
    IS 'Identity key for unit table.';
COMMENT ON COLUMN camdams.account_unit.account_number
    IS 'Unique public identifier for account table.';
COMMENT ON COLUMN camdams.account_unit.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camdams.account_unit.add_date
    IS 'Date the record was created.';