CREATE TABLE IF NOT EXISTS  camdams.account
(
    account_id              int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    account_name            varchar(100) NOT NULL,
    account_number          varchar(12) NOT NULL,
    account_type_cd         varchar(7) NOT NULL,
    contact_email_address   varchar(70) NULL,
    contact_name            varchar(100) NULL,
    state_cd                varchar(2) NULL,
    tribal_land_cd          varchar(7) NULL,
    userid                  varchar(160) NOT NULL,
    add_date                timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
    update_date             timestamp NULL
);
