CREATE TABLE IF NOT EXISTS camdams.account_compliance
(
    account_comp_id bigint GENERATED BY DEFAULT AS IDENTITY,
    account_id numeric(38,0) NOT NULL,
    comp_period_id numeric(38,0) NOT NULL,
    comp_status_cd varchar(7) NOT NULL,
    emiss_liability numeric(15,3),
    takeback_liability numeric(15,3),
    underutilization_liability numeric(15,3),
    credit_total numeric(15,3),
    offset_liability numeric(15,0),
    last_run_date timestamp without time zone,
    last_run_userid varchar(160),
    deducted_emiss_liability numeric(15,3),
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (account_comp_id)
);
COMMENT ON TABLE camdams.account_compliance
    IS 'Lists compliance records by account id and compliance period.';
COMMENT ON COLUMN camdams.account_compliance.account_comp_id
    IS 'Identity key for account compliance table.';
COMMENT ON COLUMN camdams.account_compliance.account_id
    IS 'Identity key for account table.';
COMMENT ON COLUMN camdams.account_compliance.comp_period_id
    IS 'Identity key for account compliance table.';
COMMENT ON COLUMN camdams.account_compliance.comp_status_cd
    IS 'Compliance status code.';
COMMENT ON COLUMN camdams.account_compliance.emiss_liability
    IS 'Emissions liability at compliance.';
COMMENT ON COLUMN camdams.account_compliance.takeback_liability
    IS 'Takeback liability.';
COMMENT ON COLUMN camdams.account_compliance.underutilization_liability
    IS 'Underutilization liability.';
COMMENT ON COLUMN camdams.account_compliance.credit_total
    IS 'Number of allowances deducted at compliance.';
COMMENT ON COLUMN camdams.account_compliance.offset_liability
    IS 'Emissions not offset at compliance.';
COMMENT ON COLUMN camdams.account_compliance.last_run_date
    IS 'The date when compliance was last run (draft or final) for this record.  Will be NULL for records that have not yet had compliance run after updates to liability values.';
COMMENT ON COLUMN camdams.account_compliance.last_run_userid
    IS 'The user name of the person who last ran compliance (draft or final) on this record.  Will be NULL for records that have not yet had compliance run after updates to liability values.';
COMMENT ON COLUMN camdams.account_compliance.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camdams.account_compliance.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camdams.account_compliance.update_date
    IS 'Date of the last record update.';