CREATE TABLE IF NOT EXISTS camdams.account_owner
(
    account_owner_id bigint GENERATED BY DEFAULT AS IDENTITY,
    account_id numeric(38,0) NOT NULL,
    ppl_id numeric(38,0),
    company_id numeric(38,0),
    agency_id numeric(38,0),
    begin_date timestamp without time zone NOT NULL,
    end_date timestamp without time zone,
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (account_owner_id)
);
COMMENT ON TABLE camdams.account_owner
    IS 'Links account id and the ppl_id or comp_id of the owner.';
COMMENT ON COLUMN camdams.account_owner.account_owner_id
    IS 'Identity key for account owner table.';
COMMENT ON COLUMN camdams.account_owner.account_id
    IS 'Identity key for account table.';
COMMENT ON COLUMN camdams.account_owner.ppl_id
    IS 'Identity key for people table.';
COMMENT ON COLUMN camdams.account_owner.company_id
    IS 'Identity key for company table.';
COMMENT ON COLUMN camdams.account_owner.agency_id
    IS 'Identity key for agency table.';
COMMENT ON COLUMN camdams.account_owner.begin_date
    IS 'Date on which a relationship or an activity began. ';
COMMENT ON COLUMN camdams.account_owner.end_date
    IS 'Date on which a relationship or an activity ended. ';
COMMENT ON COLUMN camdams.account_owner.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camdams.account_owner.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camdams.account_owner.update_date
    IS 'Date of the last record update.';