CREATE TABLE IF NOT EXISTS camdams.allowance_block
(
    allow_block_id bigint GENERATED BY DEFAULT AS IDENTITY,
    prg_vintage_id numeric(38,0) NOT NULL,
    begin_number numeric(15,0) NOT NULL,
    end_number numeric(15,0) NOT NULL,
    allow_type_cd varchar(7) NOT NULL,
    allow_status_cd varchar(7) NOT NULL,
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (allow_block_id)
);
COMMENT ON TABLE camdams.allowance_block
    IS 'Identifies allowance blocks by beginning and ending serial numbers, and prg_vintage_id.';
COMMENT ON COLUMN camdams.allowance_block.allow_block_id
    IS 'Identity key for allowance block table.';
COMMENT ON COLUMN camdams.allowance_block.prg_vintage_id
    IS 'Identity key for program vintage table.';
COMMENT ON COLUMN camdams.allowance_block.begin_number
    IS 'Beginning serial number for the allowance block.';
COMMENT ON COLUMN camdams.allowance_block.end_number
    IS 'Ending serial number for an allowance block.';
COMMENT ON COLUMN camdams.allowance_block.allow_type_cd
    IS 'Allowance type code.';
COMMENT ON COLUMN camdams.allowance_block.allow_status_cd
    IS 'Allowance status code.';
COMMENT ON COLUMN camdams.allowance_block.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camdams.allowance_block.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camdams.allowance_block.update_date
    IS 'Date of the last record update.';