CREATE TABLE IF NOT EXISTS camdams.allowance_origin
(
    allow_origin_id bigint GENERATED BY DEFAULT AS IDENTITY,
    comp_year numeric(4,0) NOT NULL,
    prg_cd varchar(7) NOT NULL,
    allow_origin_type_cd varchar(7) NOT NULL,
    allow_type_cd varchar(7),
    num_allow numeric(15,0) NOT NULL,
    PRIMARY KEY (allow_origin_id)
);
COMMENT ON TABLE camdams.allowance_origin
    IS 'Stores yearly Origin of Allowances data.';
COMMENT ON COLUMN camdams.allowance_origin.comp_year
    IS 'Compliance year for this value.';
COMMENT ON COLUMN camdams.allowance_origin.prg_cd
    IS 'Program code for this value.';
COMMENT ON COLUMN camdams.allowance_origin.allow_origin_type_cd
    IS 'Indicates whether this record represents an allocated value (ALLOC) or a banked allowances value (BANKED).';
COMMENT ON COLUMN camdams.allowance_origin.allow_type_cd
    IS 'Allowance type code that identifies the allocation type.';
COMMENT ON COLUMN camdams.allowance_origin.num_allow
    IS 'Number of allowances allocated/banked.';