CREATE TABLE IF NOT EXISTS camdams.auction_winner
(
    auction_winner_id bigint GENERATED BY DEFAULT AS IDENTITY,
    auction_bid_id numeric(38,0) NOT NULL,
    auction_offer_id numeric(38,0) NOT NULL,
    win_price numeric(8,2) NOT NULL,
    win_quantity numeric(6,0) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    userid varchar(160) NOT NULL,
    trans_id numeric(38,0),
    PRIMARY KEY (auction_winner_id)
);
COMMENT ON TABLE camdams.auction_winner
    IS 'Identifies winning auction bids.';
COMMENT ON COLUMN camdams.auction_winner.auction_winner_id
    IS 'Identity key for auction winner table.';
COMMENT ON COLUMN camdams.auction_winner.auction_bid_id
    IS 'Identity key for auction bid table.';
COMMENT ON COLUMN camdams.auction_winner.auction_offer_id
    IS 'Identity key for auction offer table.';
COMMENT ON COLUMN camdams.auction_winner.win_price
    IS 'Price paid for allowances.';
COMMENT ON COLUMN camdams.auction_winner.win_quantity
    IS 'number of allowances won.';
COMMENT ON COLUMN camdams.auction_winner.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camdams.auction_winner.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camdams.auction_winner.trans_id
    IS 'Identity key for transaction table.';