CREATE TABLE IF NOT EXISTS camdams.auction_offer
(
    auction_offer_id bigint GENERATED BY DEFAULT AS IDENTITY,
    auction_id numeric(38,0) NOT NULL,
    account_id numeric(38,0) NOT NULL,
    ppl_id numeric(38,0),
    offer_number numeric(38,0) NOT NULL,
    offer_price numeric(8,2) NOT NULL,
    fewer_ind integer NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    userid varchar(160) NOT NULL,
    PRIMARY KEY (auction_offer_id)
);
COMMENT ON TABLE camdams.auction_offer
    IS 'Identifies offers of allowances for each auction.';
COMMENT ON COLUMN camdams.auction_offer.auction_offer_id
    IS 'Identity key for auction offer table.';
COMMENT ON COLUMN camdams.auction_offer.auction_id
    IS 'Identity key for auction table.';
COMMENT ON COLUMN camdams.auction_offer.account_id
    IS 'Identity key for account table.';
COMMENT ON COLUMN camdams.auction_offer.ppl_id
    IS 'Identity key for people table.';
COMMENT ON COLUMN camdams.auction_offer.offer_number
    IS 'Public Identifier for auction offer by auction year.';
COMMENT ON COLUMN camdams.auction_offer.offer_price
    IS 'Lowest price willing to sell allowances for.';
COMMENT ON COLUMN camdams.auction_offer.fewer_ind
    IS 'Indicates if the offerer will sell few allowances than offered for sale.';
COMMENT ON COLUMN camdams.auction_offer.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camdams.auction_offer.update_date
    IS 'Date of the last record update.';
COMMENT ON COLUMN camdams.auction_offer.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';