CREATE TABLE IF NOT EXISTS camdams.auction_bid
(
    auction_bid_id bigint GENERATED BY DEFAULT AS IDENTITY,
    bid_number numeric(38,0) NOT NULL,
    auction_id numeric(38,0) NOT NULL,
    account_id numeric(38,0) NOT NULL,
    ppl_id numeric(38,0) NOT NULL,
    bid_list_name varchar(100) NOT NULL,
    bid_price numeric(8,2) NOT NULL,
    bid_quantity numeric(6,0) NOT NULL,
    fewer_ind integer NOT NULL,
    payment_method_cd varchar(7) NOT NULL,
    paid_ind integer NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    userid varchar(160) NOT NULL,
    bid_order numeric(2,0),
    amount_paid numeric(14,2),
    bid_status_cd varchar(8),
    submitter_ppl_id numeric(38,0),
    letter_of_credit_number varchar(20),
    bid_date timestamp without time zone,
    PRIMARY KEY (auction_bid_id)
);
COMMENT ON TABLE camdams.auction_bid
    IS 'Identifies auction bids.';
COMMENT ON COLUMN camdams.auction_bid.auction_bid_id
    IS 'Identity key for auction bid table.';
COMMENT ON COLUMN camdams.auction_bid.bid_number
    IS 'Public Identifier for auction bid by auction year.';
COMMENT ON COLUMN camdams.auction_bid.auction_id
    IS 'Identity key for auction table.';
COMMENT ON COLUMN camdams.auction_bid.account_id
    IS 'Identity key for account table.';
COMMENT ON COLUMN camdams.auction_bid.ppl_id
    IS 'Identity key for people table.';
COMMENT ON COLUMN camdams.auction_bid.bid_list_name
    IS 'Name the bid is listed by.';
COMMENT ON COLUMN camdams.auction_bid.bid_price
    IS 'Bid price.';
COMMENT ON COLUMN camdams.auction_bid.bid_quantity
    IS 'Number of allowances bid for.';
COMMENT ON COLUMN camdams.auction_bid.fewer_ind
    IS 'Indicates if the bidder is willing to purchase fewer allowances.';
COMMENT ON COLUMN camdams.auction_bid.payment_method_cd
    IS 'Code for method of payment.';
COMMENT ON COLUMN camdams.auction_bid.paid_ind
    IS 'Indicates if the bidder has played.';
COMMENT ON COLUMN camdams.auction_bid.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camdams.auction_bid.update_date
    IS 'Date of the last record update.';
COMMENT ON COLUMN camdams.auction_bid.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camdams.auction_bid.bid_order
    IS 'Order tied bids will win allowances.';
COMMENT ON COLUMN camdams.auction_bid.amount_paid
    IS 'Amount paid.';
COMMENT ON COLUMN camdams.auction_bid.bid_status_cd
    IS 'Status code for the bid';
COMMENT ON COLUMN camdams.auction_bid.submitter_ppl_id
    IS 'Identity for Submitted people table';
COMMENT ON COLUMN camdams.auction_bid.letter_of_credit_number
    IS 'Credit number.';
COMMENT ON COLUMN camdams.auction_bid.bid_date
    IS 'Date of the last CBS update to the bid record.';