CREATE TABLE IF NOT EXISTS camdams.auction
(
    auction_id bigint GENERATED BY DEFAULT AS IDENTITY,
    auction_type_cd varchar(7) NOT NULL,
    final_ind integer NOT NULL,
    auction_name varchar(100) NOT NULL,
    auction_year numeric(4,0) NOT NULL,
    auction_date timestamp without time zone,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    userid varchar(160) NOT NULL,
    run_date timestamp without time zone,
    bid_begin_date timestamp without time zone,
    bid_deadline timestamp without time zone,
    payee_final_date timestamp without time zone,
    PRIMARY KEY (auction_id)
);
COMMENT ON TABLE camdams.auction
    IS 'Identifies auctions by auction type and year.';
COMMENT ON COLUMN camdams.auction.auction_id
    IS 'Identity key for auction table.';
COMMENT ON COLUMN camdams.auction.auction_type_cd
    IS 'Indicates the type of auction.';
COMMENT ON COLUMN camdams.auction.final_ind
    IS 'Indicates if the auction is final.';
COMMENT ON COLUMN camdams.auction.auction_name
    IS 'Name of auction.';
COMMENT ON COLUMN camdams.auction.auction_year
    IS 'Year of auction.';
COMMENT ON COLUMN camdams.auction.auction_date
    IS 'Date auction was finalized.';
COMMENT ON COLUMN camdams.auction.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camdams.auction.update_date
    IS 'Date of the last record update.';
COMMENT ON COLUMN camdams.auction.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camdams.auction.run_date
    IS 'Date the Auction was run ';
COMMENT ON COLUMN camdams.auction.bid_begin_date
    IS 'Begin date for the Auction Bid';
COMMENT ON COLUMN camdams.auction.bid_deadline
    IS 'Bid deadline date for the Auction Bid';
COMMENT ON COLUMN camdams.auction.payee_final_date
    IS 'Date on which payee data for the auction is finalized.';