CREATE TABLE IF NOT EXISTS camdams.auction_offer_block
(
    auction_offer_block_id bigint GENERATED BY DEFAULT AS IDENTITY,
    auction_offer_id numeric(38,0) NOT NULL,
    prg_vintage_id numeric(38,0) NOT NULL,
    begin_number numeric(15,0) NOT NULL,
    end_number numeric(15,0) NOT NULL,
    PRIMARY KEY (auction_offer_block_id)
);
COMMENT ON TABLE camdams.auction_offer_block
    IS 'Links auction offer id and allowance block information.';
COMMENT ON COLUMN camdams.auction_offer_block.auction_offer_block_id
    IS 'Identity key for auction offer block table.';
COMMENT ON COLUMN camdams.auction_offer_block.auction_offer_id
    IS 'Identity key for auction offer table.';
COMMENT ON COLUMN camdams.auction_offer_block.prg_vintage_id
    IS 'Identity key for program vintage table.';
COMMENT ON COLUMN camdams.auction_offer_block.begin_number
    IS 'Beginning serial number for the allowance block.';
COMMENT ON COLUMN camdams.auction_offer_block.end_number
    IS 'Ending serial number for an allowance block.';