CREATE TABLE IF NOT EXISTS camdams.auction_payee
(
    auction_payee_id bigint GENERATED BY DEFAULT AS IDENTITY,
    auction_payee_name varchar(100) NOT NULL,
    tax_number numeric(12,0),
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    userid varchar(160) NOT NULL,
    PRIMARY KEY (auction_payee_id)
);
COMMENT ON TABLE camdams.auction_payee
    IS 'Identifies auction payee name and tax number.';
COMMENT ON COLUMN camdams.auction_payee.auction_payee_id
    IS 'Identity key for auction payee table.';
COMMENT ON COLUMN camdams.auction_payee.auction_payee_name
    IS 'Name of auction payee.';
COMMENT ON COLUMN camdams.auction_payee.tax_number
    IS 'Tax id of payee.';
COMMENT ON COLUMN camdams.auction_payee.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camdams.auction_payee.update_date
    IS 'Date of the last record update.';
COMMENT ON COLUMN camdams.auction_payee.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';