CREATE TABLE IF NOT EXISTS camdams.authority_year
(
    authority_year_id bigint GENERATED BY DEFAULT AS IDENTITY,
    authority_id numeric(38,0) NOT NULL,
    prg_vintage_id numeric(38,0) NOT NULL,
    authority_amount numeric(15,0) NOT NULL,
    issued_amount numeric(15,0) NOT NULL,
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (authority_year_id)
);
COMMENT ON TABLE camdams.authority_year
    IS 'This table stores the authorized limits for reserve accounts on a yearly basis.';
COMMENT ON COLUMN camdams.authority_year.authority_year_id
    IS 'Identity key for authority year table.';
COMMENT ON COLUMN camdams.authority_year.authority_id
    IS 'Identity key for authority table.';
COMMENT ON COLUMN camdams.authority_year.prg_vintage_id
    IS 'Identity key for program vintage table.';
COMMENT ON COLUMN camdams.authority_year.authority_amount
    IS 'Total number of allowances the account can allocate for the specific year.';
COMMENT ON COLUMN camdams.authority_year.issued_amount
    IS 'Number of allowances issued by the account for the year.';
COMMENT ON COLUMN camdams.authority_year.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camdams.authority_year.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camdams.authority_year.update_date
    IS 'Date of the last record update.';