CREATE TABLE IF NOT EXISTS camdams.authority
(
    authority_id bigint GENERATED BY DEFAULT AS IDENTITY,
    account_prg_id numeric(38,0) NOT NULL,
    authority_type_cd varchar(7) NOT NULL,
    limit_type_cd varchar(7) NOT NULL,
    authority_amount numeric(15,0),
    issued_amount numeric(15,0),
    parent_authority_id numeric(38,0),
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (authority_id)
);
COMMENT ON TABLE camdams.authority
    IS 'Stores the allocations from a reserve account to a market account.';
COMMENT ON COLUMN camdams.authority.authority_id
    IS 'Identity key for authority table.';
COMMENT ON COLUMN camdams.authority.account_prg_id
    IS 'Identity key for account program table.';
COMMENT ON COLUMN camdams.authority.authority_type_cd
    IS 'Indicates if the authority is tracked by year.';
COMMENT ON COLUMN camdams.authority.limit_type_cd
    IS 'Type of authority limit.';
COMMENT ON COLUMN camdams.authority.authority_amount
    IS 'Total number of allowances the account can allocate.';
COMMENT ON COLUMN camdams.authority.issued_amount
    IS 'Number of allowances issued by the account.';
COMMENT ON COLUMN camdams.authority.parent_authority_id
    IS 'Authority id of the parent account.';
COMMENT ON COLUMN camdams.authority.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camdams.authority.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camdams.authority.update_date
    IS 'Date of the last record update.';