CREATE TABLE IF NOT EXISTS camdams.compliance_emission_detail
(
    comp_emiss_detail_id bigint GENERATED BY DEFAULT AS IDENTITY,
    comp_period_id numeric(38,0) NOT NULL,
    mon_plan_id varchar(45) NOT NULL,
    mon_loc_id varchar(45) NOT NULL,
    rpt_period_id numeric(38,0) NOT NULL,
    parameter_cd varchar(7) NOT NULL,
    emiss_value numeric(15,3),
    value_source_cd varchar(7),
    detail_status varchar(4000),
    submission_id numeric(38,0),
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (comp_emiss_detail_id)
);
COMMENT ON TABLE camdams.compliance_emission_detail
    IS 'Contains the location/reporting period data used (or that can be used) to determine compliance emission values';
COMMENT ON COLUMN camdams.compliance_emission_detail.comp_emiss_detail_id
    IS 'Identity key for compliance emission detail table.';
COMMENT ON COLUMN camdams.compliance_emission_detail.comp_period_id
    IS 'Identity key for compliance period table.';
COMMENT ON COLUMN camdams.compliance_emission_detail.mon_plan_id
    IS 'Unique identifier of a monitoring plan record. ';
COMMENT ON COLUMN camdams.compliance_emission_detail.mon_loc_id
    IS 'Unique identifier of a monitoring location record. ';
COMMENT ON COLUMN camdams.compliance_emission_detail.rpt_period_id
    IS 'Unique identifier of a reporting period record. ';
COMMENT ON COLUMN camdams.compliance_emission_detail.parameter_cd
    IS 'Type of emissions or pollutant measured.';
COMMENT ON COLUMN camdams.compliance_emission_detail.emiss_value
    IS 'Emissions.';
COMMENT ON COLUMN camdams.compliance_emission_detail.value_source_cd
    IS 'ECMPS source used to determine EMISS_VALUE.';
COMMENT ON COLUMN camdams.compliance_emission_detail.detail_status
    IS 'Indicates the status of determining EMISS_VALUE.';
COMMENT ON COLUMN camdams.compliance_emission_detail.submission_id
    IS 'Unique identifier of a submission.';
COMMENT ON COLUMN camdams.compliance_emission_detail.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camdams.compliance_emission_detail.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camdams.compliance_emission_detail.update_date
    IS 'Date of the last record update.';