CREATE TABLE IF NOT EXISTS camdams.compliance_period
(
    comp_period_id bigint GENERATED BY DEFAULT AS IDENTITY,
    prg_vintage_id numeric(38,0) NOT NULL,
    freeze_ind numeric(38,0) NOT NULL,
    freeze_date timestamp without time zone,
    cbs_end_date timestamp without time zone,
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (comp_period_id)
);
COMMENT ON TABLE camdams.compliance_period
    IS 'Links prg_vintage_id to a compliance_period_id.';
COMMENT ON COLUMN camdams.compliance_period.comp_period_id
    IS 'Identity key for compliance period table.';
COMMENT ON COLUMN camdams.compliance_period.prg_vintage_id
    IS 'Identity key for program vintage table.';
COMMENT ON COLUMN camdams.compliance_period.freeze_ind
    IS 'Indicates if the freeze is on for the compliance period.';
COMMENT ON COLUMN camdams.compliance_period.freeze_date
    IS 'Transfer Deadline/Freeze Date for the compliance period.';
COMMENT ON COLUMN camdams.compliance_period.cbs_end_date
    IS 'Last day that CBS users can run compliance.';
COMMENT ON COLUMN camdams.compliance_period.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camdams.compliance_period.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camdams.compliance_period.update_date
    IS 'Date of the last record update.';