CREATE TABLE IF NOT EXISTS camdams.compliance_freeze_balance
(
    comp_freeze_bal_id bigint GENERATED BY DEFAULT AS IDENTITY,
    account_id numeric(38,0) NOT NULL,
    comp_period_id numeric(38,0) NOT NULL,
    balance_cd varchar(7) NOT NULL,
    prg_vintage_id numeric(38,0),
    balance numeric(15,0) NOT NULL,
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (comp_freeze_bal_id)
);
COMMENT ON TABLE camdams.compliance_freeze_balance
    IS 'Lists freeze balances for all General and Facility accounts as of the freeze date for a particular COMP PERIOD ID.';
COMMENT ON COLUMN camdams.compliance_freeze_balance.comp_freeze_bal_id
    IS 'Identity key for compliance_freeze_balance table.';
COMMENT ON COLUMN camdams.compliance_freeze_balance.account_id
    IS 'Identity key for account table.';
COMMENT ON COLUMN camdams.compliance_freeze_balance.comp_period_id
    IS 'Identity key for compliance period table.';
COMMENT ON COLUMN camdams.compliance_freeze_balance.balance_cd
    IS 'Balance code.';
COMMENT ON COLUMN camdams.compliance_freeze_balance.prg_vintage_id
    IS 'Identity key for program vintage table.';
COMMENT ON COLUMN camdams.compliance_freeze_balance.balance
    IS 'Number of allowances of the current vintage or earlier (for the identified balance code) held at the time of the compliance freeze.';
COMMENT ON COLUMN camdams.compliance_freeze_balance.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camdams.compliance_freeze_balance.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camdams.compliance_freeze_balance.update_date
    IS 'Date of the last record update.';