CREATE TABLE IF NOT EXISTS camdams.corrected_transaction
(
    corrected_trans_id bigint GENERATED BY DEFAULT AS IDENTITY,
    trans_id numeric(38,0),
    tranevnt_cnt numeric(10,0),
    correction_type_cd varchar(3) NOT NULL,
    correction_comment varchar(4000) NOT NULL,
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (corrected_trans_id)
);
COMMENT ON TABLE camdams.corrected_transaction
    IS 'Documents manual transaction updates.';
COMMENT ON COLUMN camdams.corrected_transaction.corrected_trans_id
    IS 'Identity key for corrected transaction table.  Populated using S_CORRECTED_TRANSACTION.';
COMMENT ON COLUMN camdams.corrected_transaction.trans_id
    IS 'Transaction ID of the problem transaction.  Populated for ARP, CAIR, CSAPR, TXSO2 transaction corrections.';
COMMENT ON COLUMN camdams.corrected_transaction.tranevnt_cnt
    IS 'Transaction ID of the problem transaction.  Populated for OTC, NBP transaction corrections.';
COMMENT ON COLUMN camdams.corrected_transaction.correction_type_cd
    IS 'Type of transaction correction.  Valid values are INS, UPD, DEL.';
COMMENT ON COLUMN camdams.corrected_transaction.correction_comment
    IS 'Description of transaction correction.';
COMMENT ON COLUMN camdams.corrected_transaction.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camdams.corrected_transaction.add_date
    IS 'Date transaction was added.';
COMMENT ON COLUMN camdams.corrected_transaction.update_date
    IS 'Date of the last record update.';