CREATE TABLE IF NOT EXISTS camdams.csapr_ozone_deduction
(
    csapr_ozone_deduction_id bigint GENERATED BY DEFAULT AS IDENTITY,
    trans_id numeric(38,0) NOT NULL,
    account_comp_id numeric(38,0) NOT NULL,
    block_total numeric(15,0) NOT NULL,
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (csapr_ozone_deduction_id)
);
COMMENT ON TABLE camdams.csapr_ozone_deduction
    IS 'Lists CSAPR ozone deduction that apply to one or more account compliance records.';
COMMENT ON COLUMN camdams.csapr_ozone_deduction.csapr_ozone_deduction_id
    IS 'Identity key for CSAPR ozone deduction table.';
COMMENT ON COLUMN camdams.csapr_ozone_deduction.trans_id
    IS 'Transaction ID of the CSAPR ozone deduction transaction.';
COMMENT ON COLUMN camdams.csapr_ozone_deduction.account_comp_id
    IS 'Identity key for account compliance table.';
COMMENT ON COLUMN camdams.csapr_ozone_deduction.block_total
    IS 'Total number of allowances deducted in this transaction for this account compliance record.';
COMMENT ON COLUMN camdams.csapr_ozone_deduction.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camdams.csapr_ozone_deduction.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camdams.csapr_ozone_deduction.update_date
    IS 'Date of the last record update.';