CREATE TABLE IF NOT EXISTS camdams.csosg2_remaining_conv_gnp
(
    csosg2_remaining_conv_id bigint GENERATED BY DEFAULT AS IDENTITY,
    account_id numeric(38,0) NOT NULL,
    vintage_year numeric(4,0) NOT NULL,
    csosg2_total numeric(10,0) NOT NULL,
    trans_id numeric(38,0),
    general_account_id numeric(38,0),
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (csosg2_remaining_conv_id)
);
COMMENT ON TABLE camdams.csosg2_remaining_conv_gnp
    IS 'Stores account-level information related to the GNP conversion of banked CSOSG2 allowances.';
COMMENT ON COLUMN camdams.csosg2_remaining_conv_gnp.csosg2_remaining_conv_id
    IS 'Identity key for CSOSG2 safety valve conversion table.';
COMMENT ON COLUMN camdams.csosg2_remaining_conv_gnp.account_id
    IS 'Identity key for account table.';
COMMENT ON COLUMN camdams.csosg2_remaining_conv_gnp.vintage_year
    IS 'Vintage year of the CSOSG2 allowances.';
COMMENT ON COLUMN camdams.csosg2_remaining_conv_gnp.csosg2_total
    IS 'Number of 2017-2022 CSOSG2 allowances held by the account.';
COMMENT ON COLUMN camdams.csosg2_remaining_conv_gnp.trans_id
    IS 'Identity key for transaction table.';
COMMENT ON COLUMN camdams.csosg2_remaining_conv_gnp.general_account_id
    IS 'Identity key for account table.';
COMMENT ON COLUMN camdams.csosg2_remaining_conv_gnp.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camdams.csosg2_remaining_conv_gnp.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camdams.csosg2_remaining_conv_gnp.update_date
    IS 'Date of the last record update.';