CREATE TABLE IF NOT EXISTS camdams.csosg2_recall_block
(
    csosg2_recall_block_id bigint GENERATED BY DEFAULT AS IDENTITY,
    recall_round numeric(1,0) NOT NULL,
    account_id numeric(38,0) NOT NULL,
    prg_vintage_id numeric(38,0) NOT NULL,
    begin_number numeric(19,0) NOT NULL,
    end_number numeric(19,0) NOT NULL,
    allocation_ind numeric(1,0) NOT NULL,
    acquisition_date timestamp without time zone NOT NULL,
    deduct_ind numeric(1,0) NOT NULL DEFAULT 0,
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (csosg2_recall_block_id)
);
COMMENT ON TABLE camdams.csosg2_recall_block
    IS 'Stores block information related to the RCU recall of CSOSG2 allowances from plant accounts.';
COMMENT ON COLUMN camdams.csosg2_recall_block.csosg2_recall_block_id
    IS 'Identity key for CSOSG2 recall block table.';
COMMENT ON COLUMN camdams.csosg2_recall_block.prg_vintage_id
    IS 'Identity key for program vintage table.';
COMMENT ON COLUMN camdams.csosg2_recall_block.begin_number
    IS 'Beginning serial number for the allowance block.';
COMMENT ON COLUMN camdams.csosg2_recall_block.end_number
    IS 'Ending serial number for an allowance block.';
COMMENT ON COLUMN camdams.csosg2_recall_block.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camdams.csosg2_recall_block.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camdams.csosg2_recall_block.update_date
    IS 'Date of the last record update.';