CREATE TABLE IF NOT EXISTS camdams.csosg2_recall_gnp
(
    csosg2_recall_id bigint GENERATED BY DEFAULT AS IDENTITY,
    account_id numeric(38,0) NOT NULL,
    vintage_year numeric(4,0) NOT NULL,
    allocation_amount numeric(6,0),
    allowance_total_round_1 numeric(6,0),
    allowance_total_round_2 numeric(6,0),
    trans_id_round_1 numeric(38,0),
    trans_id_round_2 numeric(38,0),
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (csosg2_recall_id)
);
COMMENT ON TABLE camdams.csosg2_recall_gnp
    IS 'Stores information related to the GNP recall of CSOSG2 allowances from plant accounts.';
COMMENT ON COLUMN camdams.csosg2_recall_gnp.csosg2_recall_id
    IS 'Identity key for CSOSG2 recall table.';
COMMENT ON COLUMN camdams.csosg2_recall_gnp.account_id
    IS 'Identity key for account table.';
COMMENT ON COLUMN camdams.csosg2_recall_gnp.vintage_year
    IS 'Vintage year.';
COMMENT ON COLUMN camdams.csosg2_recall_gnp.allocation_amount
    IS 'Total allocation amount received by this unit for this program and year.';
COMMENT ON COLUMN camdams.csosg2_recall_gnp.allowance_total_round_1
    IS 'Number of allowances identified for recall during main recall.';
COMMENT ON COLUMN camdams.csosg2_recall_gnp.allowance_total_round_2
    IS 'Number of allowances identified for recall during remaining recall.';
COMMENT ON COLUMN camdams.csosg2_recall_gnp.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camdams.csosg2_recall_gnp.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camdams.csosg2_recall_gnp.update_date
    IS 'Date of the last record update.';