CREATE TABLE IF NOT EXISTS camdams.nox_comp_plan
(
    comp_plan_id bigint GENERATED BY DEFAULT AS IDENTITY,
    unit_id numeric(38,0) NOT NULL,
    begin_date timestamp without time zone NOT NULL,
    end_date timestamp without time zone,
    comp_plan_type_cd varchar(7) NOT NULL,
    sign_date timestamp without time zone,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    userid varchar(160) NOT NULL,
    notes varchar(4000),
    line_l numeric(1,0),
    line_m numeric(1,0),
    line_k numeric(1,0),
    PRIMARY KEY (comp_plan_id)
);
COMMENT ON TABLE camdams.nox_comp_plan
    IS 'Stores ARP NOx compliance plan data.';
COMMENT ON COLUMN camdams.nox_comp_plan.comp_plan_id
    IS 'Identity key for NOx comp plan table.';
COMMENT ON COLUMN camdams.nox_comp_plan.unit_id
    IS 'Identity key for unit table.';
COMMENT ON COLUMN camdams.nox_comp_plan.begin_date
    IS 'Date on which a relationship or an activity began. ';
COMMENT ON COLUMN camdams.nox_comp_plan.end_date
    IS 'Date on which a relationship or an activity ended. ';
COMMENT ON COLUMN camdams.nox_comp_plan.comp_plan_type_cd
    IS 'Compliance plan type.';
COMMENT ON COLUMN camdams.nox_comp_plan.sign_date
    IS 'Date compliance plan was signed.';
COMMENT ON COLUMN camdams.nox_comp_plan.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camdams.nox_comp_plan.update_date
    IS 'Date of the last record update.';
COMMENT ON COLUMN camdams.nox_comp_plan.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camdams.nox_comp_plan.notes
    IS 'Text description of compliance plan.';
COMMENT ON COLUMN camdams.nox_comp_plan.line_l
    IS 'Indicator of whether or not the user is complying via Line L.';
COMMENT ON COLUMN camdams.nox_comp_plan.line_m
    IS 'Indicator of whether or not the user is complying via Line M.';
COMMENT ON COLUMN camdams.nox_comp_plan.line_k
    IS 'Indicator of whether or not the user is complying via Line K.';