CREATE TABLE IF NOT EXISTS camdams.nox_avg_plan
(
    avg_plan_id bigint GENERATED BY DEFAULT AS IDENTITY,
    begin_date timestamp without time zone NOT NULL,
    end_date timestamp without time zone,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    userid varchar(160) NOT NULL,
    sign_date timestamp without time zone,
    notes varchar(4000),
    PRIMARY KEY (avg_plan_id)
);
COMMENT ON TABLE camdams.nox_avg_plan
    IS 'Identifies averaging plan information.';
COMMENT ON COLUMN camdams.nox_avg_plan.avg_plan_id
    IS 'Identity key for NOx avg plan table.';
COMMENT ON COLUMN camdams.nox_avg_plan.begin_date
    IS 'Date on which a relationship or an activity began. ';
COMMENT ON COLUMN camdams.nox_avg_plan.end_date
    IS 'Date on which a relationship or an activity ended. ';
COMMENT ON COLUMN camdams.nox_avg_plan.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camdams.nox_avg_plan.update_date
    IS 'Date of the last record update.';
COMMENT ON COLUMN camdams.nox_avg_plan.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camdams.nox_avg_plan.sign_date
    IS 'Date averaging plan form was signed.';
COMMENT ON COLUMN camdams.nox_avg_plan.notes
    IS 'Text description of averaging plan.';