CREATE TABLE IF NOT EXISTS camdams.nox_comp_plan_renewal
(
    comp_plan_renewal_id bigint GENERATED BY DEFAULT AS IDENTITY,
    comp_plan_id numeric(38,0) NOT NULL,
    renewal_date timestamp without time zone NOT NULL,
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (comp_plan_renewal_id)
);
COMMENT ON TABLE camdams.nox_comp_plan_renewal
    IS 'Stores ARP NOx compliance plan renewals.';
COMMENT ON COLUMN camdams.nox_comp_plan_renewal.comp_plan_renewal_id
    IS 'Identity key for NOx comp plan renewal table.';
COMMENT ON COLUMN camdams.nox_comp_plan_renewal.comp_plan_id
    IS 'Identity key for NOx comp plan table.';
COMMENT ON COLUMN camdams.nox_comp_plan_renewal.renewal_date
    IS 'Date compliance plan renewal was signed.';
COMMENT ON COLUMN camdams.nox_comp_plan_renewal.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camdams.nox_comp_plan_renewal.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camdams.nox_comp_plan_renewal.update_date
    IS 'Date of the last record update.';