CREATE TABLE IF NOT EXISTS camdams.nox_permit
(
    permit_id bigint GENERATED BY DEFAULT AS IDENTITY,
    unit_id numeric(38,0) NOT NULL,
    begin_date timestamp without time zone NOT NULL,
    end_date timestamp without time zone,
    sign_date timestamp without time zone,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    userid varchar(160) NOT NULL,
    PRIMARY KEY (permit_id)
);
COMMENT ON TABLE camdams.nox_permit
    IS 'Structure for storing permit data associated with ARP NOx compliance and replaces parts of old structure CAMDATS.TNOXPERMIT';
COMMENT ON COLUMN camdams.nox_permit.permit_id
    IS 'Unique identifier for a NOx permit record.';
COMMENT ON COLUMN camdams.nox_permit.unit_id
    IS 'Identity key for unit table.';
COMMENT ON COLUMN camdams.nox_permit.begin_date
    IS 'Date on which a relationship or an activity began. ';
COMMENT ON COLUMN camdams.nox_permit.end_date
    IS 'Date on which a relationship or an activity ended. ';
COMMENT ON COLUMN camdams.nox_permit.sign_date
    IS 'Date permit was signed.';
COMMENT ON COLUMN camdams.nox_permit.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camdams.nox_permit.update_date
    IS 'Date of the last record update.';
COMMENT ON COLUMN camdams.nox_permit.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';