CREATE TABLE IF NOT EXISTS camdams.nusa_emission
(
    nusa_emission_id bigint GENERATED BY DEFAULT AS IDENTITY,
    unit_id numeric(38,0) NOT NULL,
    prg_cd varchar(7) NOT NULL,
    calendar_year numeric(4,0) NOT NULL,
    quarter numeric(1,0) NOT NULL,
    submission_id numeric(38,0),
    value_source_cd varchar(7),
    emiss_value numeric(15,3),
    emiss_date timestamp without time zone,
    adj_emiss_value numeric(15,3),
    edit_reason clob,
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (nusa_emission_id)
);
COMMENT ON TABLE camdams.nusa_emission
    IS 'Table of emissions data by unit, program, and year/quarter for the NUSA program.';
COMMENT ON COLUMN camdams.nusa_emission.nusa_emission_id
    IS 'Identity key for NUSA_EMISSION table.';
COMMENT ON COLUMN camdams.nusa_emission.unit_id
    IS 'Identity key for UNIT table.';
COMMENT ON COLUMN camdams.nusa_emission.prg_cd
    IS 'Code used to identify regulatory PROGRAM applicable to UNIT.';
COMMENT ON COLUMN camdams.nusa_emission.calendar_year
    IS 'Reporting Year.';
COMMENT ON COLUMN camdams.nusa_emission.quarter
    IS 'Reporting Quarter.';
COMMENT ON COLUMN camdams.nusa_emission.submission_id
    IS 'Unique identifier of a submission.';
COMMENT ON COLUMN camdams.nusa_emission.value_source_cd
    IS 'ECMPS source used to determine EMISS_VALUE.';
COMMENT ON COLUMN camdams.nusa_emission.emiss_value
    IS 'Emissions liability at compliance.';
COMMENT ON COLUMN camdams.nusa_emission.emiss_date
    IS 'Date and time in which EMISS_VALUE was updated.';
COMMENT ON COLUMN camdams.nusa_emission.adj_emiss_value
    IS 'Manually Adjusted Emissions liability at compliance.';
COMMENT ON COLUMN camdams.nusa_emission.edit_reason
    IS 'Comment entered for the unit.';
COMMENT ON COLUMN camdams.nusa_emission.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camdams.nusa_emission.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camdams.nusa_emission.update_date
    IS 'Date of the last record update.';