CREATE TABLE IF NOT EXISTS camdams.perpetuity_block
(
    perpetuity_block_id bigint GENERATED BY DEFAULT AS IDENTITY,
    begin_number numeric(15,0) NOT NULL,
    end_number numeric(15,0) NOT NULL,
    account_id numeric(38,0) NOT NULL,
    original_account_id numeric(38,0) NOT NULL,
    prg_cd varchar(7) NOT NULL,
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (perpetuity_block_id)
);
COMMENT ON TABLE camdams.perpetuity_block
    IS 'Lists serial numbers for allowances held in perpetuity by account id.';
COMMENT ON COLUMN camdams.perpetuity_block.perpetuity_block_id
    IS 'Identity key for perpetuity block table.';
COMMENT ON COLUMN camdams.perpetuity_block.begin_number
    IS 'Beginning serial number for the allowance block.';
COMMENT ON COLUMN camdams.perpetuity_block.end_number
    IS 'Ending serial number for an allowance block.';
COMMENT ON COLUMN camdams.perpetuity_block.account_id
    IS 'Identity key for account table.';
COMMENT ON COLUMN camdams.perpetuity_block.original_account_id
    IS 'Account ID of account that originally held allowances in perpetuity.';
COMMENT ON COLUMN camdams.perpetuity_block.prg_cd
    IS 'Code used to identify regulatory program applicable to allowance block.  ';
COMMENT ON COLUMN camdams.perpetuity_block.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camdams.perpetuity_block.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camdams.perpetuity_block.update_date
    IS 'Date of the last record update.';