CREATE TABLE IF NOT EXISTS camdams.plant_payee
(
    plant_payee_id bigint GENERATED BY DEFAULT AS IDENTITY,
    fac_id numeric(38,0) NOT NULL,
    auction_payee_id numeric(38,0) NOT NULL,
    begin_date timestamp without time zone NOT NULL,
    end_date timestamp without time zone,
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (plant_payee_id)
);
COMMENT ON TABLE camdams.plant_payee
    IS 'Links fac_id and auction payee';
COMMENT ON COLUMN camdams.plant_payee.plant_payee_id
    IS 'Identity key for facility payee table.';
COMMENT ON COLUMN camdams.plant_payee.fac_id
    IS 'Identity key for facility table.';
COMMENT ON COLUMN camdams.plant_payee.auction_payee_id
    IS 'Identity key for auction payee table.';
COMMENT ON COLUMN camdams.plant_payee.begin_date
    IS 'Date on which a relationship or an activity began. ';
COMMENT ON COLUMN camdams.plant_payee.end_date
    IS 'Date on which a relationship or an activity ended. ';
COMMENT ON COLUMN camdams.plant_payee.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camdams.plant_payee.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camdams.plant_payee.update_date
    IS 'Date of the last record update.';