CREATE TABLE IF NOT EXISTS camdams.program_vintage
(
    prg_vintage_id bigint GENERATED BY DEFAULT AS IDENTITY,
    prg_cd varchar(7) NOT NULL,
    prg_vintage_name varchar(100) NOT NULL,
    vintage_year numeric DEFAULT EXTRACT(YEAR FROM "BEGIN_DATE"),
    begin_date timestamp without time zone NOT NULL,
    end_date timestamp without time zone NOT NULL,
    allocation_ind numeric(1,0) NOT NULL DEFAULT 0,
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (prg_vintage_id)
);
COMMENT ON TABLE camdams.program_vintage
    IS 'Identifies program and year for each prg_vintage_id.';
COMMENT ON COLUMN camdams.program_vintage.prg_vintage_id
    IS 'Identity key for program vintage table.';
COMMENT ON COLUMN camdams.program_vintage.prg_cd
    IS 'Code used to identify regulatory program applicable to allowance vintage.  ';
COMMENT ON COLUMN camdams.program_vintage.prg_vintage_name
    IS 'Name of vintage year.';
COMMENT ON COLUMN camdams.program_vintage.vintage_year
    IS 'Vintage year.';
COMMENT ON COLUMN camdams.program_vintage.begin_date
    IS 'Date on which a relationship or an activity began. ';
COMMENT ON COLUMN camdams.program_vintage.end_date
    IS 'Date on which a relationship or an activity ended. ';
COMMENT ON COLUMN camdams.program_vintage.allocation_ind
    IS 'Indicates allowances have been allocated for the program vintage.';
COMMENT ON COLUMN camdams.program_vintage.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camdams.program_vintage.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camdams.program_vintage.update_date
    IS 'Date of the last record update.';