CREATE TABLE IF NOT EXISTS camdams.state_unit_allocation
(
    state_unit_alloc_id bigint GENERATED BY DEFAULT AS IDENTITY,
    unit_id numeric(38,0) NOT NULL,
    prg_vintage_id numeric(38,0) NOT NULL,
    trans_type_cd varchar(7) NOT NULL,
    allocation_amount numeric(6,0) NOT NULL,
    zero_allocation_ind numeric(1,0) NOT NULL,
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (state_unit_alloc_id)
);
COMMENT ON TABLE camdams.state_unit_allocation
    IS 'Table of allocations received for the unit by program, year, and allocation type.';
COMMENT ON COLUMN camdams.state_unit_allocation.state_unit_alloc_id
    IS 'Identity key for state_unit_allocation table.';
COMMENT ON COLUMN camdams.state_unit_allocation.unit_id
    IS 'Identity key for UNIT table.';
COMMENT ON COLUMN camdams.state_unit_allocation.prg_vintage_id
    IS 'Identity key for program vintage table.';
COMMENT ON COLUMN camdams.state_unit_allocation.trans_type_cd
    IS 'Code for type of transaction.';
COMMENT ON COLUMN camdams.state_unit_allocation.allocation_amount
    IS 'Total allocation amount received by this unit for this program, year and allocation type.';
COMMENT ON COLUMN camdams.state_unit_allocation.zero_allocation_ind
    IS 'Indicates whether or not the first allocation of this type for this program and year was an amount of 0.  Only applies to INITALL allocations.   A value of 1 means that the first INITALL allocation was an amount of 0.  Will be 0 for all allocation types other than INITALL.';
COMMENT ON COLUMN camdams.state_unit_allocation.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camdams.state_unit_allocation.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camdams.state_unit_allocation.update_date
    IS 'Date of the last record update.';