CREATE TABLE IF NOT EXISTS camdams.transaction_block
(
    trans_block_id bigint GENERATED BY DEFAULT AS IDENTITY,
    trans_id numeric(38,0) NOT NULL,
    begin_number numeric(15,0) NOT NULL,
    end_number numeric(15,0) NOT NULL,
    prg_vintage_id numeric(38,0) NOT NULL,
    PRIMARY KEY (trans_block_id)
);
COMMENT ON TABLE camdams.transaction_block
    IS 'Lists allowance blocks transferred by transaction.';
COMMENT ON COLUMN camdams.transaction_block.trans_block_id
    IS 'Identity key for transaction block table.';
COMMENT ON COLUMN camdams.transaction_block.trans_id
    IS 'Identity key for transaction table.';
COMMENT ON COLUMN camdams.transaction_block.begin_number
    IS 'Beginning serial number for the allowance block.';
COMMENT ON COLUMN camdams.transaction_block.end_number
    IS 'Ending serial number for an allowance block.';
COMMENT ON COLUMN camdams.transaction_block.prg_vintage_id
    IS 'Identity key for program vintage table.';