CREATE TABLE IF NOT EXISTS camdams.transfer_session_transaction
(
    transfer_session_trans_id bigint GENERATED BY DEFAULT AS IDENTITY,
    transfer_session_id numeric(38,0) NOT NULL,
    prg_cd varchar(7) NOT NULL,
    xml_log_id numeric(38,0),
    trans_status_cd varchar(7) NOT NULL,
    trans_id numeric(38,0),
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (transfer_session_trans_id)
);
COMMENT ON TABLE camdams.transfer_session_transaction
    IS 'Identifies allowance transfer transaction information.';
COMMENT ON COLUMN camdams.transfer_session_transaction.transfer_session_trans_id
    IS 'Identity key for Transfer Session Transaction table.';
COMMENT ON COLUMN camdams.transfer_session_transaction.transfer_session_id
    IS 'Identity key for Transfer Session table.';
COMMENT ON COLUMN camdams.transfer_session_transaction.prg_cd
    IS 'Code used to identify regulatory program applicable to transaction.';
COMMENT ON COLUMN camdams.transfer_session_transaction.xml_log_id
    IS 'XML_LOG identity key for XML containing the Allowance Tranfer Transaction data.';
COMMENT ON COLUMN camdams.transfer_session_transaction.trans_status_cd
    IS 'Transaction status code.';
COMMENT ON COLUMN camdams.transfer_session_transaction.trans_id
    IS 'Identity key for transaction table.';
COMMENT ON COLUMN camdams.transfer_session_transaction.userid
    IS 'User account or source of data that added or updated record.';
COMMENT ON COLUMN camdams.transfer_session_transaction.add_date
    IS 'Date and time in which record was added.';
COMMENT ON COLUMN camdams.transfer_session_transaction.update_date
    IS 'Date and time in which record was last updated.';