CREATE TABLE IF NOT EXISTS camdams.transaction
(
    trans_id bigint GENERATED BY DEFAULT AS IDENTITY,
    trans_number numeric(19,0) NOT NULL,
    prg_cd varchar(7) NOT NULL,
    trans_type_cd varchar(7) NOT NULL,
    trans_status_cd varchar(7) NOT NULL,
    buy_account_id numeric(38,0) NOT NULL,
    buy_ppl_id numeric(38,0),
    sell_account_id numeric(38,0) NOT NULL,
    sell_ppl_id numeric(38,0),
    perpetuity_ind numeric(1,0) NOT NULL,
    changed_trans_id numeric(38,0),
    account_comp_id numeric(38,0),
    trans_date timestamp without time zone NOT NULL,
    form_received_date timestamp without time zone NOT NULL,
    allocation_log_id numeric(38,0),
    unit_id numeric(38,0),
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (trans_id)
);
COMMENT ON TABLE camdams.transaction
    IS 'Identifies allowance transaction information.';
COMMENT ON COLUMN camdams.transaction.trans_id
    IS 'Identity key for transaction table.';
COMMENT ON COLUMN camdams.transaction.trans_number
    IS 'Public identifier for the transaction.';
COMMENT ON COLUMN camdams.transaction.prg_cd
    IS 'Code used to identify regulatory program applicable to transaction.';
COMMENT ON COLUMN camdams.transaction.trans_type_cd
    IS 'Code for type of transaction.';
COMMENT ON COLUMN camdams.transaction.trans_status_cd
    IS 'Transaction status code.';
COMMENT ON COLUMN camdams.transaction.buy_account_id
    IS 'Account ID of the buying account.';
COMMENT ON COLUMN camdams.transaction.buy_ppl_id
    IS 'People ID of the authorizing rep for the buying account.';
COMMENT ON COLUMN camdams.transaction.sell_account_id
    IS 'Account ID of the selling account.';
COMMENT ON COLUMN camdams.transaction.sell_ppl_id
    IS 'People ID of the authorizing rep for the selling account.';
COMMENT ON COLUMN camdams.transaction.perpetuity_ind
    IS 'Indicates if the transaction was in perpetuity.';
COMMENT ON COLUMN camdams.transaction.changed_trans_id
    IS 'Transaction ID of transaction changed.';
COMMENT ON COLUMN camdams.transaction.account_comp_id
    IS 'Identity key for account compliance table.';
COMMENT ON COLUMN camdams.transaction.trans_date
    IS 'Date of transaction.';
COMMENT ON COLUMN camdams.transaction.form_received_date
    IS 'Date transaction form was received.';
COMMENT ON COLUMN camdams.transaction.allocation_log_id
    IS 'Identity key for account table.';
COMMENT ON COLUMN camdams.transaction.unit_id
    IS 'Identity key for UNIT table.';
COMMENT ON COLUMN camdams.transaction.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camdams.transaction.add_date
    IS 'Date transaction was added.';
COMMENT ON COLUMN camdams.transaction.update_date
    IS 'Date of the last record update.';