CREATE TABLE IF NOT EXISTS camdams.transaction_error
(
    trans_error_id bigint GENERATED BY DEFAULT AS IDENTITY,
    trans_id numeric(38,0) NOT NULL,
    trans_error_cd varchar(7) NOT NULL,
    trans_error_order integer NOT NULL,
    trans_error_text varchar(1000) NOT NULL,
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (trans_error_id)
);
COMMENT ON TABLE camdams.transaction_error
    IS 'Lists errors by transaction.';
COMMENT ON COLUMN camdams.transaction_error.trans_error_id
    IS 'Identity key for transaction error table.';
COMMENT ON COLUMN camdams.transaction_error.trans_id
    IS 'Identity key for transaction table.';
COMMENT ON COLUMN camdams.transaction_error.trans_error_cd
    IS 'Transaction error code.';
COMMENT ON COLUMN camdams.transaction_error.trans_error_order
    IS 'Sequence for a transaction error.';
COMMENT ON COLUMN camdams.transaction_error.trans_error_text
    IS 'Error message displayed in application.';
COMMENT ON COLUMN camdams.transaction_error.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camdams.transaction_error.add_date
    IS 'Date the record was created.';