CREATE TABLE IF NOT EXISTS camdams.transfer_session
(
    transfer_session_id bigint GENERATED BY DEFAULT AS IDENTITY,
    ppl_id numeric(38,0) NOT NULL,
    xml_log_id numeric(38,0),
    trans_session_status_cd varchar(7) NOT NULL,
    test_mode_ind varchar(1) NOT NULL DEFAULT 0,
    job_name varchar(32),
    priority numeric,
    interactive_ind numeric(1,0) NOT NULL DEFAULT 0,
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (transfer_session_id)
);
COMMENT ON TABLE camdams.transfer_session
    IS 'Identifies allowance transfer session information.';
COMMENT ON COLUMN camdams.transfer_session.transfer_session_id
    IS 'Identity key for Transfer Session table.';
COMMENT ON COLUMN camdams.transfer_session.ppl_id
    IS 'PEOPLE identity key.';
COMMENT ON COLUMN camdams.transfer_session.xml_log_id
    IS 'XML_LOG identity key for XML containing the Allowance Tranfer Transaction data.';
COMMENT ON COLUMN camdams.transfer_session.trans_session_status_cd
    IS 'Code used to identify the status of Transaction Session';
COMMENT ON COLUMN camdams.transfer_session.test_mode_ind
    IS 'Test Mode Indicator for the Transfer Session table.';
COMMENT ON COLUMN camdams.transfer_session.job_name
    IS 'Name of the job run to Allowance transfer submission.';
COMMENT ON COLUMN camdams.transfer_session.priority
    IS 'Priority of the Allowance transfer jobs.';
COMMENT ON COLUMN camdams.transfer_session.interactive_ind
    IS 'Indicates if transfer session is interactive.';
COMMENT ON COLUMN camdams.transfer_session.userid
    IS 'User account or source of data that added or updated record. ';
COMMENT ON COLUMN camdams.transfer_session.add_date
    IS 'Date and time in which record was added. ';
COMMENT ON COLUMN camdams.transfer_session.update_date
    IS 'Date and time in which record was last updated. ';