CREATE TABLE IF NOT EXISTS camddmw.hour_unit_mats_data_log
(
    sql_function character varying(1) COLLATE pg_catalog."default" NOT NULL,
    unit_id numeric(38,0) NOT NULL,
    op_date date NOT NULL,
    op_hour numeric(2,0) NOT NULL,
    op_time numeric(3,2),
    gload numeric(8,2),
    sload numeric(8,2),
    tload numeric(8,2),
    heat_input numeric(15,3),
    heat_input_measure_flg character varying(60) COLLATE pg_catalog."default",
    hg_rate_eo numeric(22,10),
    hg_rate_hi numeric(22,10),
    hg_mass numeric(22,10),
    hg_measure_flg character varying(60) COLLATE pg_catalog."default",
    hcl_rate_eo numeric(22,10),
    hcl_rate_hi numeric(22,10),
    hcl_mass numeric(22,10),
    hcl_measure_flg character varying(60) COLLATE pg_catalog."default",
    hf_rate_eo numeric(22,10),
    hf_rate_hi numeric(22,10),
    hf_mass numeric(22,10),
    hf_measure_flg character varying(60) COLLATE pg_catalog."default",
    rpt_period_id numeric(38,0) NOT NULL,
    op_year numeric(4,0) NOT NULL,
    data_source character varying(35) COLLATE pg_catalog."default" NOT NULL,
    userid character varying(160) COLLATE pg_catalog."default" NOT NULL,
    add_date timestamp(0) without time zone NOT NULL,
    skey numeric NOT NULL,
    logged_time timestamp without time zone
);
