CREATE TABLE IF NOT EXISTS CAMDDMW.MONITOR_FACT
(
  OP_YEAR       NUMERIC(4)      NOT NULL,
  MON_LOC_ID    VARCHAR(45)     NOT NULL,
  FAC_ID        NUMERIC(12),
  LOCATION_ID   VARCHAR(120),
  ASSOC_UNITS   VARCHAR(1000),
  ADD_DATE      DATE
);


COMMENT ON TABLE CAMDDMW.MONITOR_FACT IS 'Monitor characteristics aggregated by year';


COMMENT ON COLUMN CAMDDMW.MONITOR_FACT.OP_YEAR IS 'Year in which data was collected';
COMMENT ON COLUMN CAMDDMW.MONITOR_FACT.MON_LOC_ID IS 'Identity key for MONITOR_LOCATION table';
COMMENT ON COLUMN CAMDDMW.MONITOR_FACT.FAC_ID IS 'Unique identifier of a facility';
COMMENT ON COLUMN CAMDDMW.MONITOR_FACT.LOCATION_ID IS 'Stack, unit, or pipe ID';
COMMENT ON COLUMN CAMDDMW.MONITOR_FACT.ASSOC_UNITS IS 'Units linked to a monitor';
COMMENT ON COLUMN CAMDDMW.MONITOR_FACT.ADD_DATE IS 'Date on which the record was added';
