DROP FUNCTION IF EXISTS GET_SUBMISSION_AUDIT_DATA(CHARACTER VARYING, CHARACTER VARYING, DATE, DATE, CHARACTER VARYING) CASCADE;

CREATE OR REPLACE FUNCTION GET_SUBMISSION_AUDIT_DATA(
    V_FAC_ID            CHARACTER VARYING,
    V_FACILITY_NAME     CHARACTER VARYING,
    V_BEGIN_DATE        DATE,
    V_END_DATE          DATE,
    V_FILE_TYPE_CD      CHARACTER VARYING
)
RETURNS TABLE (
    ORIS_CODE                       CHARACTER VARYING,
    FACILITY_NAME                   CHARACTER VARYING,
    STATE                           CHARACTER VARYING,
    LOCATIONS                       CHARACTER VARYING,
    PERIOD                          NUMERIC,
    FILE_TYPE_CD                    CHARACTER VARYING,
    SUBMISSION_ID                   BIGINT,
    SUBMISSION_DATE                 TIMESTAMP,
    SUBMISSION_SET                  CHARACTER VARYING,
    QUEUE_STATUS                    CHARACTER VARYING,
    QA_TYPE                         CHARACTER VARYING,
    QA_IDENTIFIER                   CHARACTER VARYING,
    SUBMITTER                       CHARACTER VARYING,
    LOADED_SUBMISSION_ID            BIGINT,
    LOADED_SUBMISSION_DATE          TIMESTAMP
) AS $BODY$
BEGIN
    RETURN QUERY
    WITH SUBMISSION_LOG AS (
        SELECT 
            SQ.SUBMISSION_SET_ID,
            SS.MON_PLAN_ID,
            SQ.RPT_PERIOD_ID,
            SQ.QUEUED_TIME,
            SQ.PROCESS_CD,
            SQ.SUBMISSION_ID,
            SQ.STATUS_CD,
            SQ.USERID,
            SQ.STARTED_TIME,
            SQ.COMPLETED_TIME
        FROM CAMDECMPSAUX.SUBMISSION_SET SS
        JOIN CAMDECMPSAUX.SUBMISSION_QUEUE SQ USING (SUBMISSION_SET_ID)
    ),
    UNION_QUERY AS (
      -- QUERY PART 1: MP/EM SUBMISSIONS
      SELECT DISTINCT
          VMP.ORIS_CODE,
          VMP.FACILITY_NAME,
          VMP.STATE,
          VMP.LOCATIONS,
          CASE 
              WHEN L.FILE_TYPE_CD = 'EM'
              THEN RP.CALENDAR_YEAR || ' Q' || RP.QUARTER
              ELSE NULL
          END AS PERIOD,
          L.FILE_TYPE_CD,
          L.SUBMISSION_ID,
          L.QUEUED_TIME AS SUBMISSION_DATE,
          (
            SELECT STRING_AGG(SQ.SUBMISSION_ID::TEXT, ',')
            FROM CAMDECMPSAUX.SUBMISSION_QUEUE SQ
            WHERE SQ.SUBMISSION_SET_ID = L.SUBMISSION_SET_ID
          ) AS SUBMISSION_SET,
          COALESCE(L.STATUS_CD, 'FAILED BEFORE SCHEDULING THE JOB') AS QUEUE_STATUS,
          NULL::TEXT AS QA_TYPE,
          NULL::TEXT AS QA_IDENTIFIER,
          COALESCE(L.USERID, '') AS SUBMITTER,
          CASE
              WHEN L.FILE_TYPE_CD IN ('EM', 'DM') THEN EES.SUBMISSION_ID
              WHEN L.FILE_TYPE_CD = 'MP' THEN MPS.SUBMISSION_ID
              ELSE NULL
          END AS LOADED_SUBMISSION_ID,
          CASE
              WHEN L.FILE_TYPE_CD IN ('EM', 'DM') THEN EES.QUEUED_TIME
              WHEN L.FILE_TYPE_CD = 'MP' THEN MPS.QUEUED_TIME
              ELSE NULL
          END AS LOADED_SUBMISSION_DATE,
          L.MON_PLAN_ID
      FROM SUBMISSION_LOG L
      INNER JOIN CAMDECMPS.VW_MONITOR_PLAN VMP 
        ON L.MON_PLAN_ID = VMP.MON_PLAN_ID
      LEFT JOIN CAMDECMPS.MONITOR_PLAN MP 
        ON L.MON_PLAN_ID = MP.MON_PLAN_ID
      LEFT JOIN SUBMISSION_LOG MPS 
        ON MP.SUBMISSION_ID = MPS.SUBMISSION_ID
      LEFT JOIN CAMDECMPS.EMISSION_EVALUATION EE 
        ON L.MON_PLAN_ID = EE.MON_PLAN_ID 
           AND COALESCE(L.RPT_PERIOD_ID, 0) = EE.RPT_PERIOD_ID
      LEFT JOIN SUBMISSION_LOG EES 
        ON EE.SUBMISSION_ID = EES.SUBMISSION_ID
      LEFT JOIN CAMDECMPSMD.REPORTING_PERIOD RP 
        ON L.RPT_PERIOD_ID = RP.RPT_PERIOD_ID
      WHERE
          VMP.FAC_ID = COALESCE(V_FAC_ID, VMP.FAC_ID)
          AND VMP.FACILITY_NAME = COALESCE(V_FACILITY_NAME, VMP.FACILITY_NAME)
          AND L.FILE_TYPE_CD = COALESCE(V_FILE_TYPE_CD, L.FILE_TYPE_CD)
          AND L.QUEUED_TIME IS NOT NULL
          AND L.QUEUED_TIME::DATE <= TO_DATE(COALESCE(V_END_DATE::TEXT, '12/31/9999'), 'MM/DD/YYYY')
          AND L.QUEUED_TIME::DATE >= TO_DATE(COALESCE(V_BEGIN_DATE::TEXT, '01/01/1900'), 'MM/DD/YYYY')
          AND (L.STARTED_TIME IS NULL OR L.COMPLETED_TIME IS NULL OR L.STATUS_CD = 'WIP')
      
      UNION ALL
      
      -- QUERY PART 2: QA SUBMISSIONS
      SELECT DISTINCT
          VMP.ORIS_CODE,
          VMP.FACILITY_NAME,
          VMP.STATE,
          VMP.LOCATIONS,
          NULL::NUMERIC AS PERIOD,
          L.FILE_TYPE_CD,
          L.SUBMISSION_ID,
          L.QUEUED_TIME AS SUBMISSION_DATE,
          (
            SELECT STRING_AGG(SQ2.SUBMISSION_ID::TEXT, ',')
            FROM SUBMISSION_QUEUE SQ2
            WHERE SQ2.SUBMISSION_SET_ID = L.SUBMISSION_SET_ID
          ) AS SUBMISSION_SET,
          COALESCE(L.STATUS_CD, 'FAILED BEFORE SCHEDULING THE JOB') AS QUEUE_STATUS,
          QA.QA_TYPE,
          QA.QA_IDENTIFIER,
          COALESCE(L.USERID, '') AS SUBMITTER,
          QA.LOADED_SUBMISSION_ID,
          QA.LOADED_SUBMISSION_DATE
      FROM SUBMISSION_LOG L
      JOIN (
          /* QA UNION SUBQUERY: TEST */
          SELECT WS.SUBMISSION_ID,
                 'TEST' AS QA_TYPE,
                 WS.MON_LOC_ID,
                 NULL::NUMERIC AS COMPONENT_ID,
                 NULL::NUMERIC AS MON_SYS_ID,
                 NULL::NUMERIC AS RPT_PERIOD_ID,
                 WS.TEST_TYPE_CD || ' ' || WS.TEST_NUM AS QA_IDENTIFIER,
                 WS.COMPLETED_TIME,
                 WS.STATUS_CD,
                 NULL::BIGINT AS LOADED_SUBMISSION_ID,
                 NULL::TIMESTAMP AS LOADED_SUBMISSION_DATE
          FROM CAMDECMPSWKS.QA_SUPP_DATA WS
          LEFT JOIN CAMDECMPS.QA_SUPP_DATA Q 
             ON WS.QA_SUPP_DATA_ID = Q.QA_SUPP_DATA_ID
          WHERE Q.QA_SUPP_DATA_ID IS NULL
            AND (
                 WS.COMPLETED_TIME IS NOT NULL
                 OR (WS.STATUS_CD = 'ERROR' AND NOT EXISTS (
                     SELECT 1 FROM CAMDECMPSWKS.QA_SUPP_DATA WS2
                     WHERE WS2.MON_LOC_ID = WS.MON_LOC_ID
                       AND WS2.TEST_TYPE_CD = WS.TEST_TYPE_CD
                       AND WS2.TEST_NUM > WS.TEST_NUM
                 ))
               )
          UNION ALL
          /* QA UNION SUBQUERY: EVENT */
          SELECT WS.SUBMISSION_ID,
                 'EVENT' AS QA_TYPE,
                 WS.MON_LOC_ID,
                 WS.COMPONENT_ID,
                 WS.MON_SYS_ID,
                 NULL::NUMERIC AS RPT_PERIOD_ID,
                 'CODE ' || WS.QA_CERT_EVENT_CD || ' DATE/HOUR ' ||
                 TO_CHAR(TO_DATE(WS.QA_CERT_EVENT_DATE, 'DD-MON-YY'), 'MM/DD/YYYY') || ' ' ||
                 TO_CHAR(WS.QA_CERT_EVENT_HOUR) AS QA_IDENTIFIER,
                 WS.COMPLETED_TIME,
                 WS.STATUS_CD,
                 NULL::BIGINT AS LOADED_SUBMISSION_ID,
                 NULL::TIMESTAMP AS LOADED_SUBMISSION_DATE
          FROM CAMDECMPSWKS.QA_CERT_EVENT WS
          LEFT JOIN CAMDECMPS.QA_CERT_EVENT Q 
             ON WS.QA_CERT_EVENT_ID = Q.QA_CERT_EVENT_ID
          WHERE Q.QA_CERT_EVENT_ID IS NULL
            AND (
                 WS.COMPLETED_TIME IS NOT NULL
                 OR (WS.STATUS_CD = 'ERROR' AND NOT EXISTS (
                     SELECT 1 FROM CAMDECMPSWKS.QA_CERT_EVENT WS2
                     WHERE WS2.MON_LOC_ID = WS.MON_LOC_ID
                       AND WS2.QA_CERT_EVENT_CD = WS.QA_CERT_EVENT_CD
                       AND WS2.QA_CERT_EVENT_DATE > WS.QA_CERT_EVENT_DATE
                 ))
               )
          UNION ALL
          /* QA UNION SUBQUERY: EXTENSION/EXEMPTION */
          SELECT WS.SUBMISSION_ID,
                 'EXTENSION/EXEMPTION' AS QA_TYPE,
                 WS.MON_LOC_ID,
                 WS.COMPONENT_ID,
                 WS.MON_SYS_ID,
                 WS.RPT_PERIOD_ID,
                 'CODE ' || WS.EXTENS_EXEMPT_CD AS QA_IDENTIFIER,
                 WS.COMPLETED_TIME,
                 WS.STATUS_CD,
                 NULL::BIGINT AS LOADED_SUBMISSION_ID,
                 NULL::TIMESTAMP AS LOADED_SUBMISSION_DATE
          FROM CAMDECMPSWKS.TEST_EXTENSION_EXEMPTION WS
          LEFT JOIN CAMDECMPS.TEST_EXTENSION_EXEMPTION Q 
             ON WS.TEST_EXTENSION_EXEMPTION_ID = Q.TEST_EXTENSION_EXEMPTION_ID
          WHERE Q.TEST_EXTENSION_EXEMPTION_ID IS NULL
            AND (
                 WS.COMPLETED_TIME IS NOT NULL
                 OR (WS.STATUS_CD = 'ERROR' AND NOT EXISTS (
                     SELECT 1 FROM CAMDECMPSWKS.TEST_EXTENSION_EXEMPTION WS2
                     WHERE WS2.MON_LOC_ID = WS.MON_LOC_ID
                       AND WS2.EXTENS_EXEMPT_CD = WS.EXTENS_EXEMPT_CD
                       AND WS2.RPT_PERIOD_ID > WS.RPT_PERIOD_ID
                 ))
               )
      ) QA ON QA.SUBMISSION_ID = L.SUBMISSION_ID
      LEFT JOIN CAMDECMPSMD.REPORTING_PERIOD RP 
          ON QA.RPT_PERIOD_ID = RP.RPT_PERIOD_ID
      LEFT JOIN (SELECT DISTINCT MON_LOC_ID, LOCATION_NAME FROM CAMDECMPS.VW_MONITOR_PLAN_LOCATION) MPL 
          ON QA.MON_LOC_ID = MPL.MON_LOC_ID
      LEFT JOIN CAMDECMPS.COMPONENT C 
          ON QA.COMPONENT_ID = C.COMPONENT_ID
      LEFT JOIN CAMDECMPS.MONITOR_SYSTEM MS 
          ON QA.MON_SYS_ID = MS.MON_SYS_ID
      /* END QUERY PART 2 */
    )
    SELECT *
    FROM UNION_QUERY
    ORDER BY ORIS_CODE, 
             LOCATIONS,
             SUBMISSION_DATE;
END;
$BODY$ LANGUAGE PLPGSQL;
