-- Ticket #7307: convert numeric(38,0) id columns to bigint (camdecmps)

ALTER TABLE IF EXISTS camdecmps.component_op_supp_data ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmps.daily_backstop ALTER COLUMN rpt_period_id TYPE bigint, ALTER COLUMN unit_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmps.daily_calibration ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmps.daily_emission ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmps.daily_fuel ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmps.daily_test_summary ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmps.daily_test_supp_data ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmps.daily_test_system_supp_data ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmps.derived_hrly_value ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmps.dm_emissions ALTER COLUMN fac_id TYPE bigint, ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmps.emission_evaluation ALTER COLUMN rpt_period_id TYPE bigint, ALTER COLUMN submission_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmps.emission_view_dailycal ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmps.hrly_fuel_flow ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmps.hrly_gas_flow_meter ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmps.hrly_op_data ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmps.hrly_param_fuel_flow ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmps.last_qa_value_supp_data ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmps.long_term_fuel_flow ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmps.mats_derived_hrly_value ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmps.mats_monitor_hrly_value ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmps.monitor_hrly_value ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmps.monitor_location ALTER COLUMN unit_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmps.monitor_plan ALTER COLUMN begin_rpt_period_id TYPE bigint, ALTER COLUMN end_rpt_period_id TYPE bigint, ALTER COLUMN fac_id TYPE bigint, ALTER COLUMN submission_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmps.monitor_plan_reporting_freq ALTER COLUMN begin_rpt_period_id TYPE bigint, ALTER COLUMN end_rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmps.nsps4t_annual ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmps.nsps4t_compliance_period ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmps.nsps4t_summary ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmps.operating_supp_data ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmps.qa_cert_event ALTER COLUMN submission_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmps.qa_cert_event_supp_data ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmps.qa_supp_data ALTER COLUMN rpt_period_id TYPE bigint, ALTER COLUMN submission_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmps.sampling_train ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmps.sampling_train_supp_data ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmps.sorbent_trap ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmps.sorbent_trap_supp_data ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmps.stack_pipe ALTER COLUMN fac_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmps.summary_value ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmps.system_op_supp_data ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmps.test_extension_exemption ALTER COLUMN rpt_period_id TYPE bigint, ALTER COLUMN submission_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmps.test_summary ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmps.unit_capacity ALTER COLUMN unit_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmps.unit_control ALTER COLUMN unit_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmps.unit_fuel ALTER COLUMN unit_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmps.unit_stack_configuration ALTER COLUMN unit_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmps.weekly_system_integrity ALTER COLUMN rpt_period_id TYPE bigint;
ALTER TABLE IF EXISTS camdecmps.weekly_test_summary ALTER COLUMN rpt_period_id TYPE bigint;
