---------------------
-- General Indexes --
---------------------

CREATE INDEX REP_DISPLAY_FACT_UNT_OYR_PRG_IX ON CAMDDMW.REP_DISPLAY_FACT ( UNIT_ID, OP_YEAR, PRG_CODE );
CREATE INDEX REP_DISPLAY_FACT_UNT_ACC_ADB_ADN_PDB_PDN_PRG_IX ON CAMDDMW.REP_DISPLAY_FACT ( UNIT_ID, ACCOUNT_NUMBER, ALT_DISPLAY_BLOCK, ALT_DISPLAY_NAME, PRM_DISPLAY_BLOCK, PRM_DISPLAY_NAME, PRG_CODE );


-----------------
-- Constraints --
-----------------

ALTER TABLE CAMDDMW.REP_DISPLAY_FACT ADD CONSTRAINT REP_DISPLAY_FACT_PK PRIMARY KEY ( OP_YEAR, REP_FACT_ID ); -- OP_YEAR needed because table has partitions
ALTER TABLE CAMDDMW.REP_DISPLAY_FACT ADD CONSTRAINT REP_DISPLAY_FACT_FK FOREIGN KEY ( UNIT_ID, OP_YEAR ) REFERENCES CAMDDMW.UNIT_FACT ( UNIT_ID, OP_YEAR ) ON DELETE CASCADE;
