SET DEFINE OFF;


--
-- ACCOUNT_COMPLIANCE_PENALTY_SS  (Materialized View) 
--
--  Dependencies: 
--   ACCOUNT_COMPLIANCE_PENALTY (Synonym)
--
CREATE MATERIALIZED VIEW ACCOUNT_COMPLIANCE_PENALTY_SS
BUILD IMMEDIATE
REFRESH FORCE ON DEMAND
WITH PRIMARY KEY
AS 
SELECT "ACCOUNT_COMPLIANCE_PENALTY"."ACCOUNT_COMP_ID" "ACCOUNT_COMP_ID",
       "ACCOUNT_COMPLIANCE_PENALTY"."PENALTY_AMOUNT" "PENALTY_AMOUNT"
  FROM "ACCOUNT_COMPLIANCE_PENALTY" "ACCOUNT_COMPLIANCE_PENALTY"
/

COMMENT ON MATERIALIZED VIEW ACCOUNT_COMPLIANCE_PENALTY_SS IS 'snapshot table for snapshot CAMDSNAP.ACCOUNT_COMPLIANCE_PENALTY_SS'
/

--
-- PK_ACCT_COMP_PENALTY  (Index) 
--
--  Dependencies: 
--   ACCOUNT_COMPLIANCE_PENALTY_SS (Table)
--   ACCOUNT_COMPLIANCE_PENALTY_SS (Materialized View)
--
CREATE UNIQUE INDEX PK_ACCT_COMP_PENALTY ON ACCOUNT_COMPLIANCE_PENALTY_SS
(ACCOUNT_COMP_ID)
/
