CREATE TABLE IF NOT EXISTS camdaux.audit_log
(
    audit_log_id bigint GENERATED BY DEFAULT AS IDENTITY,
    audit_action_cd varchar(3) NOT NULL,
    table_name varchar(30) NOT NULL,
    key_id varchar(45) NOT NULL,
    audit_comment varchar(4000),
    audit_source varchar(100) NOT NULL,
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (audit_log_id)
);
COMMENT ON TABLE camdaux.audit_log
    IS 'The AUDIT_LOG table stores information about a change to a table.';
COMMENT ON COLUMN camdaux.audit_log.audit_log_id
    IS 'AUDIT_LOG identity key.';
COMMENT ON COLUMN camdaux.audit_log.audit_action_cd
    IS 'The type of action being audited.  Actions can be Add (ADD), Update (UPD), Delete (DEL).';
COMMENT ON COLUMN camdaux.audit_log.table_name
    IS 'Name of table containing field for which changes will be tracked.';
COMMENT ON COLUMN camdaux.audit_log.key_id
    IS 'Identifies primary key for record changed and recorded in AUDIT LOG.';
COMMENT ON COLUMN camdaux.audit_log.audit_comment
    IS 'Description of transaction performed and/or identifiying information beyond unique ID.';
COMMENT ON COLUMN camdaux.audit_log.audit_source
    IS 'Identifies the source from which the data was modified (e.g., NUE or EGRID, name of machine).';
COMMENT ON COLUMN camdaux.audit_log.userid
    IS 'The user name of the person or process that created the record.';
COMMENT ON COLUMN camdaux.audit_log.add_date
    IS 'Date the change was made.';