CREATE TABLE IF NOT EXISTS camdaux.audit_log_detail
(
    audit_log_detail_id bigint GENERATED BY DEFAULT AS IDENTITY,
    audit_log_id numeric(38,0) NOT NULL,
    column_name varchar(30) NOT NULL,
    old_value varchar(4000),
    new_value varchar(4000),
    PRIMARY KEY (audit_log_detail_id)
);
COMMENT ON TABLE camdaux.audit_log_detail
    IS 'The AUDIT_LOG_DETAIL table stores information about a change to a table for selected fields.';
COMMENT ON COLUMN camdaux.audit_log_detail.audit_log_detail_id
    IS 'AUDIT_LOG_DETAIL identity key.';
COMMENT ON COLUMN camdaux.audit_log_detail.audit_log_id
    IS 'AUDIT_LOG foreign key.';
COMMENT ON COLUMN camdaux.audit_log_detail.column_name
    IS 'Field for which changes will be tracked.';
COMMENT ON COLUMN camdaux.audit_log_detail.old_value
    IS 'Original value of field which has been changed.';
COMMENT ON COLUMN camdaux.audit_log_detail.new_value
    IS 'Value to which field has been changed.';