CREATE TABLE IF NOT EXISTS camdaux.cbs_submission_log
(
    cbs_submission_log_id bigint GENERATED BY DEFAULT AS IDENTITY,
    compressed_xml blob NOT NULL,
    camd_hash varchar(512) NOT NULL,
    challenge_question_id numeric(38,0) NOT NULL,
    encrypted_answer varchar(4000) NOT NULL,
    encrypted_password varchar(100) NOT NULL,
    event_log_id numeric(38,0) NOT NULL,
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (cbs_submission_log_id)
);
COMMENT ON TABLE camdaux.cbs_submission_log
    IS 'Maintains information about submitted data from CBS';
COMMENT ON COLUMN camdaux.cbs_submission_log.cbs_submission_log_id
    IS 'Unique identifier of a CBS submission record. ';
COMMENT ON COLUMN camdaux.cbs_submission_log.compressed_xml
    IS 'Compressed XML content for the CBS submission record.';
COMMENT ON COLUMN camdaux.cbs_submission_log.camd_hash
    IS 'CROMERR eSignature for the CBS submission';
COMMENT ON COLUMN camdaux.cbs_submission_log.challenge_question_id
    IS 'Identity key for the challenge question table';
COMMENT ON COLUMN camdaux.cbs_submission_log.encrypted_answer
    IS 'Encrypted answer submitted by the CBS user for a particular challenge question';
COMMENT ON COLUMN camdaux.cbs_submission_log.encrypted_password
    IS 'Encrypted password submitted by the CBS user';
COMMENT ON COLUMN camdaux.cbs_submission_log.event_log_id
    IS 'Identity key for Event table.';
COMMENT ON COLUMN camdaux.cbs_submission_log.userid
    IS 'The user name of the person or process that made the last update.';
COMMENT ON COLUMN camdaux.cbs_submission_log.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camdaux.cbs_submission_log.update_date
    IS 'Date of the last record update.';