CREATE TABLE IF NOT EXISTS camdaux.cbs_news
(
    cbs_news_id bigint GENERATED BY DEFAULT AS IDENTITY,
    header varchar(400) NOT NULL,
    message varchar(4000) NOT NULL,
    security_group_cd varchar(7),
    alert_ind numeric NOT NULL DEFAULT 0,
    display_order numeric NOT NULL DEFAULT 0,
    active_ind numeric NOT NULL DEFAULT 0,
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (cbs_news_id)
);
COMMENT ON TABLE camdaux.cbs_news
    IS 'News and Alerts for the CBS Login page';
COMMENT ON COLUMN camdaux.cbs_news.cbs_news_id
    IS 'Primary Key - auto assigned identifier';
COMMENT ON COLUMN camdaux.cbs_news.header
    IS 'Header for the Message(s) which is displayed to the user';
COMMENT ON COLUMN camdaux.cbs_news.message
    IS 'Message to display to the user';
COMMENT ON COLUMN camdaux.cbs_news.security_group_cd
    IS '(optional) Messages for specific security group.';
COMMENT ON COLUMN camdaux.cbs_news.alert_ind
    IS 'If 1, then this is an alert. If 0, it is just a plain message';
COMMENT ON COLUMN camdaux.cbs_news.display_order
    IS 'Order of messages. If 0, is a disabled message.';
COMMENT ON COLUMN camdaux.cbs_news.active_ind
    IS '(replaced by DISPLAY_ORDER) Is this message/alert active or not';
COMMENT ON COLUMN camdaux.cbs_news.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camdaux.cbs_news.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camdaux.cbs_news.update_date
    IS 'Date of the last record update.';