CREATE TABLE IF NOT EXISTS camdaux.compliance_emission_log
(
    comp_emiss_log_id numeric(38,0) NOT NULL,
    comp_emiss_run_id numeric(38,0) NOT NULL,
    comp_period_id numeric(38,0),
    prg_cd varchar(7),
    year numeric(4,0),
    fac_id numeric(38,0),
    unit_id numeric(38,0),
    emission_parameter_cd varchar(7),
    compliance_parameter_cd varchar(7),
    log_message varchar(4000) NOT NULL,
    package_name varchar(30),
    method_name varchar(1000),
    method_line numeric(6,0),
    userid varchar(160),
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    error_ind numeric(1,0) NOT NULL,
    email_ind numeric(1,0) NOT NULL,
    rpt_period_id numeric(38,0),
    mon_plan_id varchar(45),
    event_id numeric,
    PRIMARY KEY (comp_emiss_log_id)
);
COMMENT ON TABLE camdaux.compliance_emission_log
    IS 'Logs information about the automated loading of compliance emission values.';
COMMENT ON COLUMN camdaux.compliance_emission_log.comp_emiss_log_id
    IS 'Identity key for compliance period log table.';
COMMENT ON COLUMN camdaux.compliance_emission_log.comp_emiss_run_id
    IS 'Indicates the emission load run that produced this record.';
COMMENT ON COLUMN camdaux.compliance_emission_log.comp_period_id
    IS 'Identity key for compliance period table.';
COMMENT ON COLUMN camdaux.compliance_emission_log.prg_cd
    IS 'Code used to identify regulatory program applicable to allowance vintage.  ';
COMMENT ON COLUMN camdaux.compliance_emission_log.year
    IS 'Compliance year.';
COMMENT ON COLUMN camdaux.compliance_emission_log.fac_id
    IS 'Identity key for facility table.';
COMMENT ON COLUMN camdaux.compliance_emission_log.unit_id
    IS 'Identity key for unit table.';
COMMENT ON COLUMN camdaux.compliance_emission_log.emission_parameter_cd
    IS 'Compliance parameter.';
COMMENT ON COLUMN camdaux.compliance_emission_log.compliance_parameter_cd
    IS 'Compliance parameter.';
COMMENT ON COLUMN camdaux.compliance_emission_log.log_message
    IS 'Message generated by compliance loading';
COMMENT ON COLUMN camdaux.compliance_emission_log.package_name
    IS 'The package that produced the message';
COMMENT ON COLUMN camdaux.compliance_emission_log.method_name
    IS 'The method that produced the message';
COMMENT ON COLUMN camdaux.compliance_emission_log.method_line
    IS 'The location of the call to the routine that logs the message';
COMMENT ON COLUMN camdaux.compliance_emission_log.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camdaux.compliance_emission_log.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camdaux.compliance_emission_log.error_ind
    IS '1 if the message is an error message, otherwise 0.';
COMMENT ON COLUMN camdaux.compliance_emission_log.email_ind
    IS '1 if the message should be e-mailed';
COMMENT ON COLUMN camdaux.compliance_emission_log.rpt_period_id
    IS 'Unique identifier of a reporting period record. ';
COMMENT ON COLUMN camdaux.compliance_emission_log.mon_plan_id
    IS 'Unique identifier of a monitoring plan record. ';
COMMENT ON COLUMN camdaux.compliance_emission_log.event_id
    IS 'A unique, assigned number, used to identify a single EVENT.';