CREATE TABLE IF NOT EXISTS camdaux.email_text
(
    email_text_id bigint GENERATED BY DEFAULT AS IDENTITY,
    email_text_name varchar(100) NOT NULL,
    email_text_content varchar(2000) NOT NULL,
    PRIMARY KEY (email_text_id)
);
COMMENT ON TABLE camdaux.email_text
    IS 'Lookup table containing codes that indicates the action for events.';
COMMENT ON COLUMN camdaux.email_text.email_text_id
    IS 'EMAIL_TEXT identity key.';
COMMENT ON COLUMN camdaux.email_text.email_text_name
    IS 'The name of the email text.';
COMMENT ON COLUMN camdaux.email_text.email_text_content
    IS 'The content of the email text.';