CREATE TABLE IF NOT EXISTS camdaux.email_action_text
(
    email_action_text_id bigint GENERATED BY DEFAULT AS IDENTITY,
    email_action_id numeric(38,0) NOT NULL,
    email_text_id numeric(38,0) NOT NULL,
    display_order numeric(2,0) NOT NULL,
    PRIMARY KEY (email_action_text_id)
);
COMMENT ON TABLE camdaux.email_action_text
    IS 'Lookup table containing email information for events.';
COMMENT ON COLUMN camdaux.email_action_text.email_action_text_id
    IS 'EMAIL_ACTION_TEXT identity key.';
COMMENT ON COLUMN camdaux.email_action_text.email_action_id
    IS 'EMAIL_ACTION identity key.';
COMMENT ON COLUMN camdaux.email_action_text.email_text_id
    IS 'EMAIL_TEXT identity key.';
COMMENT ON COLUMN camdaux.email_action_text.display_order
    IS 'Display order in the email.';