CREATE TABLE IF NOT EXISTS camdaux.email_action
(
    email_action_id bigint GENERATED BY DEFAULT AS IDENTITY,
    event_action_id numeric(38,0) NOT NULL,
    security_group_cd varchar(7),
    delivery_type_cd varchar(7) NOT NULL,
    enabled_ind numeric(1,0) NOT NULL DEFAULT 1,
    cbs_send_ind numeric(1,0) NOT NULL DEFAULT 0,
    PRIMARY KEY (email_action_id)
);
COMMENT ON TABLE camdaux.email_action
    IS 'Lookup table containing email information for events.';
COMMENT ON COLUMN camdaux.email_action.email_action_id
    IS 'EMAIL_ACTION identity key.';
COMMENT ON COLUMN camdaux.email_action.event_action_id
    IS 'EVENT_ACTION identity key.';
COMMENT ON COLUMN camdaux.email_action.security_group_cd
    IS 'Lookup code for people type group.';
COMMENT ON COLUMN camdaux.email_action.delivery_type_cd
    IS 'The code that indicates the delivery type for emails.';
COMMENT ON COLUMN camdaux.email_action.enabled_ind
    IS 'Indicates if an EMAIL_LOG record should be created for this action.';
COMMENT ON COLUMN camdaux.email_action.cbs_send_ind
    IS 'Indicates if an EMAIL_LOG record will be sent via CBS for this action.  Can only be 1 if the DELIVERY_TYPE_CD is USER and the SECURITY_GROUP_CD is ADMIN';