CREATE TABLE IF NOT EXISTS camdaux.email_action_group
(
    email_action_group_id bigint GENERATED BY DEFAULT AS IDENTITY,
    email_action_id numeric(38,0) NOT NULL,
    email_group_id numeric(38,0) NOT NULL,
    email_recipient_type_cd varchar(4) NOT NULL,
    PRIMARY KEY (email_action_group_id)
);
COMMENT ON TABLE camdaux.email_action_group
    IS 'Lookup table containing email group information for emails.';
COMMENT ON COLUMN camdaux.email_action_group.email_action_group_id
    IS 'EMAIL_ACTION_GROUP identity key.';
COMMENT ON COLUMN camdaux.email_action_group.email_action_id
    IS 'EMAIL_ACTION identity key.';
COMMENT ON COLUMN camdaux.email_action_group.email_group_id
    IS 'EMAIL_GROUP identity key.';
COMMENT ON COLUMN camdaux.email_action_group.email_recipient_type_cd
    IS 'Code for email recipient type (TO, CC or BCC).';