CREATE TABLE IF NOT EXISTS camdaux.email_attachment_log
(
    email_attachment_log_id bigint GENERATED BY DEFAULT AS IDENTITY,
    email_log_id numeric(38,0) NOT NULL,
    attachment_name varchar(4000) NOT NULL,
    content_type varchar(4000) NOT NULL,
    attachment_clob clob,
    attachment_blob blob,
    userid varchar(160) NOT NULL,
    PRIMARY KEY (email_attachment_log_id)
);
COMMENT ON TABLE camdaux.email_attachment_log
    IS 'The EMAIL_ATTACHMENT_LOG table stores email attachments.';
COMMENT ON COLUMN camdaux.email_attachment_log.email_attachment_log_id
    IS 'EMAIL_ATTACHMENT_LOG identity key.';
COMMENT ON COLUMN camdaux.email_attachment_log.email_log_id
    IS 'EMAIL_LOG identity key.';
COMMENT ON COLUMN camdaux.email_attachment_log.attachment_name
    IS 'The name of the attachment.';
COMMENT ON COLUMN camdaux.email_attachment_log.content_type
    IS 'The content type of the attachment, i.e. application/pdf or image/jpg, text/html, etc.';
COMMENT ON COLUMN camdaux.email_attachment_log.attachment_clob
    IS 'CLOB representation of the attachment.';
COMMENT ON COLUMN camdaux.email_attachment_log.attachment_blob
    IS 'BLOB representation of the attachment.';
COMMENT ON COLUMN camdaux.email_attachment_log.userid
    IS 'The user name of the person or process that created the record.';