CREATE TABLE IF NOT EXISTS camdaux.email_log
(
    email_log_id bigint GENERATED BY DEFAULT AS IDENTITY,
    event_log_id numeric(38,0) NOT NULL,
    email_action_id numeric(38,0) NOT NULL,
    sent_date timestamp without time zone,
    send_error clob,
    process_date timestamp without time zone,
    xml_log_id numeric(38,0),
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resend_ind numeric(1,0) NOT NULL DEFAULT 0,
    PRIMARY KEY (email_log_id)
);
COMMENT ON TABLE camdaux.email_log
    IS 'The EMAIL_LOG table stores information related to actions taken in the applications.';
COMMENT ON COLUMN camdaux.email_log.email_log_id
    IS 'EMAIL_LOG identity key.';
COMMENT ON COLUMN camdaux.email_log.event_log_id
    IS 'EVENT identity key.';
COMMENT ON COLUMN camdaux.email_log.email_action_id
    IS 'EMAIL_ACTION identity key.';
COMMENT ON COLUMN camdaux.email_log.sent_date
    IS 'Date the email was sent.';
COMMENT ON COLUMN camdaux.email_log.send_error
    IS 'Any error that occurred during sending.';
COMMENT ON COLUMN camdaux.email_log.process_date
    IS 'Date and time the email was send process was initiated.';
COMMENT ON COLUMN camdaux.email_log.xml_log_id
    IS 'XML_LOG identity key.';
COMMENT ON COLUMN camdaux.email_log.userid
    IS 'The user name of the person or process that created the record.';
COMMENT ON COLUMN camdaux.email_log.add_date
    IS 'Date the record was created.';