CREATE TABLE IF NOT EXISTS camdaux.event_log
(
    event_log_id bigint GENERATED BY DEFAULT AS IDENTITY,
    event_action_id numeric(38,0) NOT NULL,
    xml_log_id numeric(38,0) NOT NULL,
    form_received_date timestamp without time zone NOT NULL,
    ppl_id numeric(38,0),
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (event_log_id)
);
COMMENT ON TABLE camdaux.event_log
    IS 'The EVENT_LOG table stores information related to actions taken in the applications.';
COMMENT ON COLUMN camdaux.event_log.event_log_id
    IS 'EVENT_LOG identity key.';
COMMENT ON COLUMN camdaux.event_log.event_action_id
    IS 'EVENT_ACTION identity key.';
COMMENT ON COLUMN camdaux.event_log.xml_log_id
    IS 'XML_LOG identity key.';
COMMENT ON COLUMN camdaux.event_log.form_received_date
    IS 'Date the form was received or the event transpired.';
COMMENT ON COLUMN camdaux.event_log.ppl_id
    IS 'The ID of the person that created the record.';
COMMENT ON COLUMN camdaux.event_log.userid
    IS 'The user name of the person that created the record.';
COMMENT ON COLUMN camdaux.event_log.add_date
    IS 'Date the record was created.';