CREATE TABLE IF NOT EXISTS camdaux.job_error_log
(
    job_error_log_id bigint GENERATED BY DEFAULT AS IDENTITY DEFAULT CAMDAUX.S_JOB_ERROR_LOG.Nextval,
    error_number numeric(38,0) NOT NULL,
    error_message varchar(4000),
    error_backtrace clob,
    plsql_name varchar(30),
    plsql_line integer,
    job_name varchar(100),
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (job_error_log_id)
);
COMMENT ON TABLE camdaux.job_error_log
    IS 'Logs errors encountered during job processing.';
COMMENT ON COLUMN camdaux.job_error_log.job_error_log_id
    IS 'Primary key of JOB_ERROR_LOG.';
COMMENT ON COLUMN camdaux.job_error_log.error_number
    IS 'Error number generated';
COMMENT ON COLUMN camdaux.job_error_log.error_message
    IS 'Error message generated';
COMMENT ON COLUMN camdaux.job_error_log.error_backtrace
    IS 'Error call stack generated';
COMMENT ON COLUMN camdaux.job_error_log.plsql_name
    IS 'The name of the source code in which the error was raised.';
COMMENT ON COLUMN camdaux.job_error_log.plsql_line
    IS 'The line number of the source code in which the error was raised.';
COMMENT ON COLUMN camdaux.job_error_log.job_name
    IS 'Identity key of the PROCEDURE_CALL_LOG table';
COMMENT ON COLUMN camdaux.job_error_log.add_date
    IS 'Date the record was created.';