CREATE TABLE IF NOT EXISTS camdaux.transfer_session_log
(
    transfer_session_log_id bigint GENERATED BY DEFAULT AS IDENTITY,
    transfer_session_id numeric(38,0) NOT NULL,
    trans_session_status_cd varchar(7),
    transfer_session_trans_id numeric(38,0),
    trans_status_cd varchar(7),
    trans_error_cd varchar(7),
    trans_error_text varchar(1000),
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (transfer_session_log_id)
);
COMMENT ON TABLE camdaux.transfer_session_log
    IS 'Log of Allowance Transfer Transactions.';
COMMENT ON COLUMN camdaux.transfer_session_log.transfer_session_log_id
    IS 'Identifies Allowance Transfer Transactions log information.';
COMMENT ON COLUMN camdaux.transfer_session_log.transfer_session_id
    IS 'Identity key for Transfer Session table.';
COMMENT ON COLUMN camdaux.transfer_session_log.trans_session_status_cd
    IS 'Code used to identify the status of Transaction Session';
COMMENT ON COLUMN camdaux.transfer_session_log.transfer_session_trans_id
    IS 'Identity key for Transfer Session Transaction table.';
COMMENT ON COLUMN camdaux.transfer_session_log.trans_status_cd
    IS 'Transaction status code.';
COMMENT ON COLUMN camdaux.transfer_session_log.trans_error_cd
    IS 'Error code raised while processing allowance transaction.';
COMMENT ON COLUMN camdaux.transfer_session_log.trans_error_text
    IS 'Error message raised while processing allowance transaction.';
COMMENT ON COLUMN camdaux.transfer_session_log.add_date
    IS 'Date and time in which record was added.';