CREATE TABLE IF NOT EXISTS camdaux.xml_log
(
    xml_log_id bigint GENERATED BY DEFAULT AS IDENTITY,
    xsd_id numeric(38,0) NOT NULL,
    xml_data sys.xmltype,
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (xml_log_id)
);
COMMENT ON TABLE camdaux.xml_log
    IS 'The XML_LOG table stores XML formatted data.';
COMMENT ON COLUMN camdaux.xml_log.xml_log_id
    IS 'XML_LOG identity key.';
COMMENT ON COLUMN camdaux.xml_log.xsd_id
    IS 'XSD identity key.';
COMMENT ON COLUMN camdaux.xml_log.xml_data
    IS 'XMLTYPE of the data in the xml.';
COMMENT ON COLUMN camdaux.xml_log.userid
    IS 'The user name of the person or process that created the record.';
COMMENT ON COLUMN camdaux.xml_log.add_date
    IS 'Date the record was created.';