CREATE TABLE IF NOT EXISTS camd.cdx_session
(
    cdx_session_id bigint GENERATED BY DEFAULT AS IDENTITY,
    cdx_user_id varchar(160) NOT NULL,
    token varchar(4000) NOT NULL,
    token_expiration_date timestamp without time zone NOT NULL,
    sign_out_date timestamp without time zone,
    active_ind numeric(1,0) NOT NULL DEFAULT 0,
    PRIMARY KEY (cdx_session_id)
);
COMMENT ON TABLE camd.cdx_session
    IS 'The CDX_SESSION table stores information for a cdx session.';
COMMENT ON COLUMN camd.cdx_session.cdx_session_id
    IS 'CDX_SESSION identity key.';
COMMENT ON COLUMN camd.cdx_session.cdx_user_id
    IS 'The ID of cdx user for current session.';
COMMENT ON COLUMN camd.cdx_session.token
    IS 'The token of current session.';
COMMENT ON COLUMN camd.cdx_session.token_expiration_date
    IS 'The token expiration date of current session.';
COMMENT ON COLUMN camd.cdx_session.sign_out_date
    IS 'The date the user signed out of the current session.';
COMMENT ON COLUMN camd.cdx_session.active_ind
    IS 'Indicates if this is an active session.';