CREATE TABLE IF NOT EXISTS camd.cdx_user_role
(
    cdx_user_role_id bigint GENERATED BY DEFAULT AS IDENTITY,
    cdx_user_id varchar(160) NOT NULL,
    cdx_role_id numeric(38,0) NOT NULL,
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (cdx_user_role_id)
);
COMMENT ON TABLE camd.cdx_user_role
    IS 'The CDX_USER_ROLE table stores necessary information on all CDX organizations.';
COMMENT ON COLUMN camd.cdx_user_role.cdx_user_role_id
    IS 'CDX_USER_ROLE table identity key.';
COMMENT ON COLUMN camd.cdx_user_role.cdx_user_id
    IS 'The cdx user id of the corresponding CDX user record.';
COMMENT ON COLUMN camd.cdx_user_role.cdx_role_id
    IS 'The cdx role id of the corresponding CDX role record.';
COMMENT ON COLUMN camd.cdx_user_role.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty. Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camd.cdx_user_role.add_date
    IS 'The add date of the cdx user-role record.';
COMMENT ON COLUMN camd.cdx_user_role.update_date
    IS 'The update date of the cdx user-role record.';