CREATE TABLE IF NOT EXISTS camd.cdx_user_org_role
(
    cdx_user_org_role_id bigint GENERATED BY DEFAULT AS IDENTITY,
    cdx_user_org_id numeric(38,0) NOT NULL,
    cdx_role_id numeric(38,0) NOT NULL,
    active_ind numeric(1,0) NOT NULL DEFAULT 1,
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (cdx_user_org_role_id)
);
COMMENT ON TABLE camd.cdx_user_org_role
    IS 'The CDX_ORG table stores necessary information on all CDX organizations.';
COMMENT ON COLUMN camd.cdx_user_org_role.cdx_user_org_role_id
    IS 'CDX_USER_ORG_ROLE table identity key.';
COMMENT ON COLUMN camd.cdx_user_org_role.cdx_user_org_id
    IS 'The cdx user org id of the corresponding CDX user-org record.';
COMMENT ON COLUMN camd.cdx_user_org_role.cdx_role_id
    IS 'The cdx role id of the corresponding CDX role record.';
COMMENT ON COLUMN camd.cdx_user_org_role.active_ind
    IS 'the active status of the CDX user organization role record';
COMMENT ON COLUMN camd.cdx_user_org_role.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty. Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camd.cdx_user_org_role.add_date
    IS 'The add date of the cdx user-organization-role record.';
COMMENT ON COLUMN camd.cdx_user_org_role.update_date
    IS 'The update date of the cdx user-organization-role record.';