CREATE TABLE IF NOT EXISTS camd.cdx_user_org
(
    cdx_user_org_id bigint GENERATED BY DEFAULT AS IDENTITY,
    cdx_user_id varchar(160) NOT NULL,
    cdx_org_id numeric(38,0) NOT NULL,
    email_address varchar(70),
    active_ind numeric(1,0) NOT NULL DEFAULT 1,
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (cdx_user_org_id)
);
COMMENT ON TABLE camd.cdx_user_org
    IS 'The CDX_ORG table stores necessary information on all CDX organizations.';
COMMENT ON COLUMN camd.cdx_user_org.cdx_user_org_id
    IS 'CDX_USER_ORG table identity key.';
COMMENT ON COLUMN camd.cdx_user_org.cdx_user_id
    IS 'The cdx user id of the corresponding CDX user record.';
COMMENT ON COLUMN camd.cdx_user_org.cdx_org_id
    IS 'The cdx organization id of the corresponding CDX organization record.';
COMMENT ON COLUMN camd.cdx_user_org.email_address
    IS 'The email address of the cdx user in the organization.';
COMMENT ON COLUMN camd.cdx_user_org.active_ind
    IS 'the active status of the CDX user organization record';
COMMENT ON COLUMN camd.cdx_user_org.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty. Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camd.cdx_user_org.add_date
    IS 'The add date of the cdx user-organization record.';
COMMENT ON COLUMN camd.cdx_user_org.update_date
    IS 'The update date of the cdx user-organization record.';