CREATE TABLE IF NOT EXISTS camd.company
(
    company_id bigint GENERATED BY DEFAULT AS IDENTITY,
    company_name varchar(100) NOT NULL,
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (company_id)
);
COMMENT ON TABLE camd.company
    IS 'Identifies companies that own and/or operate units or are linked to a person.';
COMMENT ON COLUMN camd.company.company_id
    IS 'COMPANY identity key.';
COMMENT ON COLUMN camd.company.company_name
    IS 'Name of COMPANY.';
COMMENT ON COLUMN camd.company.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camd.company.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camd.company.update_date
    IS 'Date of the last record update.';