CREATE TABLE IF NOT EXISTS camd.contact_relation
(
    cnt_rel_id bigint GENERATED BY DEFAULT AS IDENTITY,
    cnt_id numeric(38,0) NOT NULL,
    ppl_id numeric(38,0) NOT NULL,
    relation_type_cd varchar(25) NOT NULL,
    begin_date timestamp without time zone NOT NULL,
    end_date timestamp without time zone,
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    agent_id numeric(38,0) DEFAULT TO_NUMBER(TO_CHAR("PPL_ID")),
    rep_id numeric(38,0) DEFAULT TO_NUMBER(TO_CHAR("CNT_ID")),
    PRIMARY KEY (cnt_rel_id)
);
COMMENT ON TABLE camd.contact_relation
    IS 'Table captures the relationship that one or more representatives have with each other.  The PPL_ID is the agent&#x0027;s id and the CNT_ID shows the representative&#x0027;s id.';
COMMENT ON COLUMN camd.contact_relation.cnt_rel_id
    IS 'Identity key for CONTACT_RELATION table.';
COMMENT ON COLUMN camd.contact_relation.cnt_id
    IS 'PEOPLE ID for representative.';
COMMENT ON COLUMN camd.contact_relation.ppl_id
    IS 'PEOPLE ID for agent.';
COMMENT ON COLUMN camd.contact_relation.relation_type_cd
    IS 'Lookup code which defines the scope of the relationship or agent responsibilities.';
COMMENT ON COLUMN camd.contact_relation.begin_date
    IS 'Date on which a relationship or an activity began.';
COMMENT ON COLUMN camd.contact_relation.end_date
    IS 'Date on which a relationship or an activity ended.';
COMMENT ON COLUMN camd.contact_relation.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camd.contact_relation.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camd.contact_relation.update_date
    IS 'Date of the last record update.';
COMMENT ON COLUMN camd.contact_relation.agent_id
    IS 'PPL_ID for the agent in the rep-agent relationship';
COMMENT ON COLUMN camd.contact_relation.rep_id
    IS 'PPL_ID for the representative in the rep-agent relationship';