CREATE TABLE IF NOT EXISTS camd.email_generator_group
(
    email_gen_group_id bigint GENERATED BY DEFAULT AS IDENTITY,
    email_gen_group_name varchar(100) NOT NULL,
    email_gen_group_description varchar(1000),
    email_gen_group_definition clob NOT NULL,
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (email_gen_group_id)
);
COMMENT ON TABLE camd.email_generator_group
    IS 'List of groups that receive emails.';
COMMENT ON COLUMN camd.email_generator_group.email_gen_group_id
    IS 'Identity key for EMAIL GENERATOR GROUP table.';
COMMENT ON COLUMN camd.email_generator_group.email_gen_group_name
    IS 'Name of EMAIL GENERATOR GROUP.';
COMMENT ON COLUMN camd.email_generator_group.email_gen_group_description
    IS 'Description of EMAIL GENERATOR GROUP.';
COMMENT ON COLUMN camd.email_generator_group.email_gen_group_definition
    IS 'Definition of EMAIL GENERATOR GROUP (criteria XML or custom list).';
COMMENT ON COLUMN camd.email_generator_group.userid
    IS 'The user name of the person or process associated with the record.';
COMMENT ON COLUMN camd.email_generator_group.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camd.email_generator_group.update_date
    IS 'Date the record was last updated.';