CREATE TABLE IF NOT EXISTS camd.email_generator_body
(
    email_gen_body_id bigint GENERATED BY DEFAULT AS IDENTITY,
    email_gen_body_name varchar(100) NOT NULL,
    email_gen_body_description varchar(1000),
    email_gen_body_rtf clob NOT NULL,
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    email_gen_body_html clob NOT NULL,
    PRIMARY KEY (email_gen_body_id)
);
COMMENT ON TABLE camd.email_generator_body
    IS 'The Body of Email messages from the EMAIL GENERATOR EMAIL table.';
COMMENT ON COLUMN camd.email_generator_body.email_gen_body_id
    IS 'Identity key for EMAIL GENERATOR BODY table.';
COMMENT ON COLUMN camd.email_generator_body.email_gen_body_name
    IS 'Name of EMAIL GENERATOR BODY.';
COMMENT ON COLUMN camd.email_generator_body.email_gen_body_description
    IS 'Description of EMAIL GENERATOR BODY.';
COMMENT ON COLUMN camd.email_generator_body.email_gen_body_rtf
    IS 'Content of EMAIL GENERATOR BODY (RTF format).';
COMMENT ON COLUMN camd.email_generator_body.userid
    IS 'The user name of the person or process associated with the record.';
COMMENT ON COLUMN camd.email_generator_body.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camd.email_generator_body.update_date
    IS 'Date the record was last updated.';
COMMENT ON COLUMN camd.email_generator_body.email_gen_body_html
    IS 'Content of EMAIL GENERATOR BODY (HTML format).';