CREATE TABLE IF NOT EXISTS camd.email_generator_email
(
    email_gen_email_id bigint GENERATED BY DEFAULT AS IDENTITY,
    author_ppl_id numeric,
    to_list clob,
    to_email_gen_group_id numeric,
    cc_list clob,
    cc_email_gen_group_id numeric,
    bcc_list clob,
    bcc_email_gen_group_id numeric,
    sent_date timestamp without time zone,
    from_address varchar(2000),
    subject_text varchar(2000),
    body_rtf clob,
    email_gen_body_id numeric,
    signature_ind numeric DEFAULT NULL,
    add_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    userid varchar(160),
    body_html clob,
    PRIMARY KEY (email_gen_email_id)
);
COMMENT ON TABLE camd.email_generator_email
    IS 'Stores pending and draft emails saved in the CSA Email Generator.';
COMMENT ON COLUMN camd.email_generator_email.email_gen_email_id
    IS 'Email Identifier.';
COMMENT ON COLUMN camd.email_generator_email.author_ppl_id
    IS 'Email sender''s people ID.';
COMMENT ON COLUMN camd.email_generator_email.to_list
    IS 'Email main recipients list.';
COMMENT ON COLUMN camd.email_generator_email.to_email_gen_group_id
    IS 'The Email_Gen_Group_ID in the EMAIL_GENERATOR_GROUP table, for the TO List.';
COMMENT ON COLUMN camd.email_generator_email.cc_list
    IS 'Email CC recipients list.';
COMMENT ON COLUMN camd.email_generator_email.cc_email_gen_group_id
    IS 'The Email_Gen_Group_ID in the EMAIL_GENERATOR_GROUP table, for the CC List.';
COMMENT ON COLUMN camd.email_generator_email.bcc_list
    IS 'Emails BCC recipients list.';
COMMENT ON COLUMN camd.email_generator_email.bcc_email_gen_group_id
    IS 'The Email_Gen_Group_ID in the EMAIL_GENERATOR_GROUP table, for the BCC List.';
COMMENT ON COLUMN camd.email_generator_email.sent_date
    IS 'Date the email was sent by GateKeeper.';
COMMENT ON COLUMN camd.email_generator_email.from_address
    IS 'Address to reply to.';
COMMENT ON COLUMN camd.email_generator_email.subject_text
    IS 'The subject of the email.';
COMMENT ON COLUMN camd.email_generator_email.body_rtf
    IS 'Body of the Message (RTF format).';
COMMENT ON COLUMN camd.email_generator_email.email_gen_body_id
    IS 'EMAIL_GEN_BODY_ID of the Body in the EMAIL_GENERATOR_BODY table.';
COMMENT ON COLUMN camd.email_generator_email.signature_ind
    IS 'The indicator of whether the author''s email signature is included.';
COMMENT ON COLUMN camd.email_generator_email.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camd.email_generator_email.update_date
    IS 'Date of the last record update.';
COMMENT ON COLUMN camd.email_generator_email.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camd.email_generator_email.body_html
    IS 'Body of the Message (HTML format).';