CREATE TABLE IF NOT EXISTS camd.person
(
    ppl_id bigint GENERATED BY DEFAULT AS IDENTITY,
    person_type_cd varchar(7),
    company_id numeric(38,0),
    agency_id numeric(38,0),
    email_address varchar(70),
    ppl_comment varchar(4000),
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    email_signature varchar(4000),
    PRIMARY KEY (ppl_id)
);
COMMENT ON TABLE camd.person
    IS 'The PERSON table stores information on all AGENTS, REPS, STAFF, and CONTACTS.';
COMMENT ON COLUMN camd.person.ppl_id
    IS 'PERSON identity key.';
COMMENT ON COLUMN camd.person.person_type_cd
    IS 'Identifies the type of user in system.';
COMMENT ON COLUMN camd.person.company_id
    IS 'COMPANY identity key.';
COMMENT ON COLUMN camd.person.agency_id
    IS 'AGENCY identity key.';
COMMENT ON COLUMN camd.person.email_address
    IS 'The email address for an individual. ';
COMMENT ON COLUMN camd.person.ppl_comment
    IS 'Text description of the PERSON record.';
COMMENT ON COLUMN camd.person.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camd.person.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camd.person.update_date
    IS 'Date of the last record update.';
COMMENT ON COLUMN camd.person.email_signature
    IS 'Used by the CSA email generator to store an email signature.';