CREATE TABLE IF NOT EXISTS camd.person_cert_statement
(
    person_cert_statement_id bigint GENERATED BY DEFAULT AS IDENTITY,
    ppl_id numeric(38,0) NOT NULL,
    cert_statement_id numeric(38,0) NOT NULL,
    sign_date timestamp without time zone,
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (person_cert_statement_id)
);
COMMENT ON TABLE camd.person_cert_statement
    IS 'Tracks the status of certification statements that must be signed by users.';
COMMENT ON COLUMN camd.person_cert_statement.person_cert_statement_id
    IS 'PERSON_CERT_STATEMENT identity key.';
COMMENT ON COLUMN camd.person_cert_statement.ppl_id
    IS 'PERSON identity key.';
COMMENT ON COLUMN camd.person_cert_statement.cert_statement_id
    IS 'CERT_STATEMENT identity key.';
COMMENT ON COLUMN camd.person_cert_statement.sign_date
    IS 'Date the cert statement was signed.';
COMMENT ON COLUMN camd.person_cert_statement.userid
    IS 'The user name of the person or process that created the record.';
COMMENT ON COLUMN camd.person_cert_statement.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camd.person_cert_statement.update_date
    IS 'Date of the last record update.';