CREATE TABLE IF NOT EXISTS camd.plant_alias
(
    plant_alias_id bigint GENERATED BY DEFAULT AS IDENTITY,
    fac_id numeric(38,0) NOT NULL,
    alias_type varchar(7) NOT NULL,
    alias_date timestamp without time zone,
    old_value varchar(40) NOT NULL,
    ampd_ind numeric(1,0) NOT NULL DEFAULT 0,
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (plant_alias_id)
);
COMMENT ON TABLE camd.plant_alias
    IS 'Records cross-reference of FACILITY plant name and oris code changes.';
COMMENT ON COLUMN camd.plant_alias.plant_alias_id
    IS 'PLANT_ALIAS identity key.';
COMMENT ON COLUMN camd.plant_alias.fac_id
    IS 'FACILITY identity key.';
COMMENT ON COLUMN camd.plant_alias.alias_type
    IS 'Type of alias, NAME (PLANT) or ORIS (ORIS_CODE).';
COMMENT ON COLUMN camd.plant_alias.alias_date
    IS 'Date on which FACILITY or UNIT alias was created.';
COMMENT ON COLUMN camd.plant_alias.old_value
    IS 'Old oris code or name of FACILITY, as reported by representative on Certification of Representation forms or equivalent.';
COMMENT ON COLUMN camd.plant_alias.ampd_ind
    IS 'Indicates if the plant alias should be shown in AMPD.';
COMMENT ON COLUMN camd.plant_alias.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camd.plant_alias.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camd.plant_alias.update_date
    IS 'Date of the last record update.';