CREATE TABLE IF NOT EXISTS camd.plant
(
    fac_id bigint GENERATED BY DEFAULT AS IDENTITY,
    oris_code numeric(6,0),
    facility_name varchar(40) NOT NULL,
    description varchar(4000),
    state varchar(2) NOT NULL,
    county_cd varchar(8),
    sic_code numeric(4,0),
    epa_region numeric(2,0),
    nerc_region varchar(5),
    airsid varchar(10),
    findsid varchar(12),
    stateid varchar(15),
    latitude numeric(7,4),
    longitude numeric(8,4),
    frs_id varchar(12),
    payee_id numeric(6,0),
    permit_exp_date timestamp without time zone,
    latlon_source varchar(200),
    tribal_land_cd varchar(7),
    first_ecmps_rpt_period_id numeric(38,0),
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (fac_id)
);
COMMENT ON TABLE camd.plant
    IS 'Identifies an electric generating or industrial facility consisting of UNITS known to or potentially subject to a trading program.';
COMMENT ON COLUMN camd.plant.fac_id
    IS 'FACILITY ID identity key.';
COMMENT ON COLUMN camd.plant.oris_code
    IS 'EIA-assigned identifier or FACILITY ID assigned by CAMD (if EIA number is not applicable).';
COMMENT ON COLUMN camd.plant.facility_name
    IS 'Name of FACILITY, as reported by representative on Certification of Representation forms or equivalent.';
COMMENT ON COLUMN camd.plant.description
    IS 'Text description of FACILITY or FACILITY configuration.';
COMMENT ON COLUMN camd.plant.state
    IS 'State abbreviation for state in which FACILITY, CONTACT, AGENCY, ACCOUNT REQUEST, PROGRAM, or STAFF is located. ';
COMMENT ON COLUMN camd.plant.county_cd
    IS 'Concatenation of State and county code.';
COMMENT ON COLUMN camd.plant.epa_region
    IS 'The EPA Region in which a FACILITY is located.';
COMMENT ON COLUMN camd.plant.nerc_region
    IS 'Code for one of thirteen regions as specified by the  North American Electric Reliability Council.';
COMMENT ON COLUMN camd.plant.airsid
    IS 'The identifier for the FACILITY in the AIRS Facility Subsystem (AFS).';
COMMENT ON COLUMN camd.plant.findsid
    IS 'Cross-reference field for FINDS database.';
COMMENT ON COLUMN camd.plant.stateid
    IS 'The State identification number for a FACILITY or UNIT.';
COMMENT ON COLUMN camd.plant.latitude
    IS 'The latitude at which a FACILITY is located.';
COMMENT ON COLUMN camd.plant.longitude
    IS 'The longitude at which a FACILITY is located.';
COMMENT ON COLUMN camd.plant.frs_id
    IS 'The cross-media Facility Registry System identifier for a FACILITY.';
COMMENT ON COLUMN camd.plant.payee_id
    IS 'ID of a payee entity.';
COMMENT ON COLUMN camd.plant.permit_exp_date
    IS 'Date permit expires.';
COMMENT ON COLUMN camd.plant.latlon_source
    IS 'Source of latitude/longitude data.';
COMMENT ON COLUMN camd.plant.tribal_land_cd
    IS 'Tribal Land abbreviation for tribal land in which FACILITY, CONTACT, AGENCY, ACCOUNT REQUEST, PROGRAM or STAFF is located.';
COMMENT ON COLUMN camd.plant.first_ecmps_rpt_period_id
    IS 'Identity key from REPORTING_PERIOD for the first quarter a facility reports via ECMPS.';
COMMENT ON COLUMN camd.plant.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camd.plant.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camd.plant.update_date
    IS 'Date of the last record update.';