CREATE TABLE IF NOT EXISTS camd.plant_person_program
(
    fac_ppl_prg_id bigint GENERATED BY DEFAULT AS IDENTITY,
    fac_ppl_id numeric(38,0) NOT NULL,
    prg_cd varchar(7) NOT NULL,
    begin_date timestamp without time zone NOT NULL,
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (fac_ppl_prg_id)
);
COMMENT ON TABLE camd.plant_person_program
    IS 'Links representatives to the beginning of their association between a plant rep and a program.';
COMMENT ON COLUMN camd.plant_person_program.fac_ppl_prg_id
    IS 'Plant Person Program relationship identity key.';
COMMENT ON COLUMN camd.plant_person_program.fac_ppl_id
    IS 'FACILITY and PEOPLE relationship identity key.';
COMMENT ON COLUMN camd.plant_person_program.prg_cd
    IS 'Code used to identify applicable regulatory PROGRAM.';
COMMENT ON COLUMN camd.plant_person_program.begin_date
    IS 'Date on which a relationship or an activity began. ';
COMMENT ON COLUMN camd.plant_person_program.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty. Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camd.plant_person_program.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camd.plant_person_program.update_date
    IS 'Date of the last record update.';