CREATE TABLE IF NOT EXISTS camd.region_analyst
(
    region_analyst_id bigint GENERATED BY DEFAULT AS IDENTITY,
    ppl_id numeric(38,0) NOT NULL,
    epa_region numeric(38,0) NOT NULL,
    begin_date timestamp without time zone NOT NULL,
    end_date timestamp without time zone,
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (region_analyst_id)
);
COMMENT ON TABLE camd.region_analyst
    IS 'Links ECMPS analysts to EPA Regions';
COMMENT ON COLUMN camd.region_analyst.region_analyst_id
    IS 'Unique identifier for the region analyst record.';
COMMENT ON COLUMN camd.region_analyst.ppl_id
    IS 'PERSON identity key.';
COMMENT ON COLUMN camd.region_analyst.epa_region
    IS 'The EPA Region in which a facility is located.';
COMMENT ON COLUMN camd.region_analyst.begin_date
    IS 'Date on which a relationship or an activity began.';
COMMENT ON COLUMN camd.region_analyst.end_date
    IS 'Date on which a relationship or an activity ended.';
COMMENT ON COLUMN camd.region_analyst.userid
    IS 'The user name of the person or process that made the last update.';
COMMENT ON COLUMN camd.region_analyst.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camd.region_analyst.update_date
    IS 'Date of the last record update.';