CREATE TABLE IF NOT EXISTS camd.rep_agent_account
(
    rep_agent_account_id bigint GENERATED BY DEFAULT AS IDENTITY,
    cnt_rel_id numeric NOT NULL,
    account_id numeric NOT NULL,
    begin_date timestamp without time zone NOT NULL,
    end_date timestamp without time zone,
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (rep_agent_account_id)
);
COMMENT ON TABLE camd.rep_agent_account
    IS 'Links application users with submission and retrieval permissions for specific accounts.';
COMMENT ON COLUMN camd.rep_agent_account.rep_agent_account_id
    IS 'Primary key for REP_AGENT_ACCOUNT table.';
COMMENT ON COLUMN camd.rep_agent_account.cnt_rel_id
    IS 'Contact relation ID for the agent.';
COMMENT ON COLUMN camd.rep_agent_account.account_id
    IS 'Account ID for the associated account.';
COMMENT ON COLUMN camd.rep_agent_account.begin_date
    IS 'Date the agent access for this account takes effect.';
COMMENT ON COLUMN camd.rep_agent_account.end_date
    IS 'Date the agent access for this account expired.';
COMMENT ON COLUMN camd.rep_agent_account.userid
    IS 'User ID of the person who added the record.';
COMMENT ON COLUMN camd.rep_agent_account.add_date
    IS 'Date the record was added to the table.';
COMMENT ON COLUMN camd.rep_agent_account.update_date
    IS 'Date record was updated.';