CREATE TABLE IF NOT EXISTS camd.rep_agent_plant
(
    rep_agent_plant_id bigint GENERATED BY DEFAULT AS IDENTITY,
    cnt_rel_id numeric NOT NULL,
    fac_id numeric NOT NULL,
    begin_date timestamp without time zone NOT NULL,
    end_date timestamp without time zone,
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (rep_agent_plant_id)
);
COMMENT ON TABLE camd.rep_agent_plant
    IS 'Links application users with submission and retrieval permissions for specific plants.';
COMMENT ON COLUMN camd.rep_agent_plant.rep_agent_plant_id
    IS 'Primary key for REP_AGENT_PLANT table.';
COMMENT ON COLUMN camd.rep_agent_plant.cnt_rel_id
    IS 'Contact relation ID for the agent.';
COMMENT ON COLUMN camd.rep_agent_plant.fac_id
    IS 'Facility ID for the associated plant.';
COMMENT ON COLUMN camd.rep_agent_plant.begin_date
    IS 'Date the agent access for this unit takes effect.';
COMMENT ON COLUMN camd.rep_agent_plant.end_date
    IS 'Date the agent access for this unit expired.';
COMMENT ON COLUMN camd.rep_agent_plant.userid
    IS 'User ID of the person who added the record.';
COMMENT ON COLUMN camd.rep_agent_plant.add_date
    IS 'Date the record was added to the table.';
COMMENT ON COLUMN camd.rep_agent_plant.update_date
    IS 'Date record was updated.';