CREATE TABLE IF NOT EXISTS camd.transfer_contact
(
    transfer_contact_id bigint GENERATED BY DEFAULT AS IDENTITY,
    ppl_id numeric(38,0) NOT NULL,
    contact_email_address varchar(100),
    contact_ppl_id numeric(38,0),
    begin_date timestamp without time zone,
    end_date timestamp without time zone,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    userid varchar(160) NOT NULL,
    PRIMARY KEY (transfer_contact_id)
);
COMMENT ON TABLE camd.transfer_contact
    IS 'Links email address for contacts to a ppl_id.';
COMMENT ON COLUMN camd.transfer_contact.transfer_contact_id
    IS 'Identify key for TRANSFER_CONTACT.';
COMMENT ON COLUMN camd.transfer_contact.ppl_id
    IS 'PERSON identity key.';
COMMENT ON COLUMN camd.transfer_contact.contact_email_address
    IS 'The email address for an individual.';
COMMENT ON COLUMN camd.transfer_contact.contact_ppl_id
    IS 'The PERSON identity key for an individual.';
COMMENT ON COLUMN camd.transfer_contact.begin_date
    IS 'Begin date for sending copies of allowance transfer emails to a contact email address.';
COMMENT ON COLUMN camd.transfer_contact.end_date
    IS 'End date for sending copies of allowance transfer emails to a contact email address.';
COMMENT ON COLUMN camd.transfer_contact.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camd.transfer_contact.update_date
    IS 'Date record was updated.';
COMMENT ON COLUMN camd.transfer_contact.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';