CREATE TABLE IF NOT EXISTS camd.unit_program_phase
(
    unit_prog_phase_id bigint GENERATED BY DEFAULT AS IDENTITY,
    up_id numeric NOT NULL,
    phase varchar(25),
    begin_year numeric NOT NULL,
    end_year numeric,
    PRIMARY KEY (unit_prog_phase_id)
);
COMMENT ON TABLE camd.unit_program_phase
    IS 'Stores non-standard ARP unit program phase data (substitution, compensating, etc...)';
COMMENT ON COLUMN camd.unit_program_phase.unit_prog_phase_id
    IS 'Unique key for unit program table.';
COMMENT ON COLUMN camd.unit_program_phase.up_id
    IS 'Identity key for unit program table.';
COMMENT ON COLUMN camd.unit_program_phase.phase
    IS 'Program phase and/or group information for the unit program phase record.';
COMMENT ON COLUMN camd.unit_program_phase.begin_year
    IS 'Year in which a relationship or an activity began. ';
COMMENT ON COLUMN camd.unit_program_phase.end_year
    IS 'Year in which a relationship or an activity ended. ';