CREATE TABLE IF NOT EXISTS camd.unit_boiler_type
(
    unit_boiler_type_id bigint GENERATED BY DEFAULT AS IDENTITY,
    unit_id numeric(38,0) NOT NULL,
    unit_type_cd varchar(7) NOT NULL,
    begin_date timestamp without time zone NOT NULL,
    end_date timestamp without time zone,
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (unit_boiler_type_id)
);
COMMENT ON TABLE camd.unit_boiler_type
    IS 'Identifies historical unit type for a unit id.';
COMMENT ON COLUMN camd.unit_boiler_type.unit_boiler_type_id
    IS 'Identity key for UNIT_BT_TYPE table.';
COMMENT ON COLUMN camd.unit_boiler_type.unit_id
    IS 'Identity key for UNIT table.';
COMMENT ON COLUMN camd.unit_boiler_type.unit_type_cd
    IS 'The type of UNIT or boiler.';
COMMENT ON COLUMN camd.unit_boiler_type.begin_date
    IS 'Date on which a relationship or an activity began. ';
COMMENT ON COLUMN camd.unit_boiler_type.end_date
    IS 'Date on which a relationship or an activity ended.';
COMMENT ON COLUMN camd.unit_boiler_type.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camd.unit_boiler_type.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camd.unit_boiler_type.update_date
    IS 'Date of the last record update.';