CREATE TABLE IF NOT EXISTS camd.unit_owner
(
    unit_owner_id bigint GENERATED BY DEFAULT AS IDENTITY,
    unit_id numeric(38,0) NOT NULL,
    comp_id numeric(38,0) NOT NULL,
    owner_type_cd varchar(7) NOT NULL,
    begin_date timestamp without time zone,
    end_date timestamp without time zone,
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (unit_owner_id)
);
COMMENT ON TABLE camd.unit_owner
    IS 'The person or organization who has the title (ownership) of the UNIT or ACCOUNT or is responsible for the operation of the FACILITY. (Also known as binding party.) Stores the relationship between UNIT and OWNER.';
COMMENT ON COLUMN camd.unit_owner.unit_owner_id
    IS 'Identity key for UNIT_OWNER table.';
COMMENT ON COLUMN camd.unit_owner.unit_id
    IS 'Identity key for UNIT table.';
COMMENT ON COLUMN camd.unit_owner.comp_id
    IS 'Identity key for COMPANY table.';
COMMENT ON COLUMN camd.unit_owner.owner_type_cd
    IS 'Indicates type of owner, operator or both.';
COMMENT ON COLUMN camd.unit_owner.begin_date
    IS 'Date on which a relationship or an activity began.';
COMMENT ON COLUMN camd.unit_owner.end_date
    IS 'Date on which a relationship or an activity ended.';
COMMENT ON COLUMN camd.unit_owner.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camd.unit_owner.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camd.unit_owner.update_date
    IS 'Date of the last record update.';