CREATE TABLE IF NOT EXISTS camd.unit
(
    unit_id bigint GENERATED BY DEFAULT AS IDENTITY,
    fac_id numeric(38,0) NOT NULL,
    unitid varchar(6) NOT NULL,
    unit_description varchar(4000),
    indian_country_ind numeric(1,0) NOT NULL DEFAULT 0,
    stateid varchar(6),
    boiler_sequence_number numeric(38,0),
    comm_op_date timestamp without time zone,
    comm_op_date_cd varchar(1),
    comr_op_date timestamp without time zone,
    comr_op_date_cd varchar(1),
    source_category_cd varchar(7),
    naics_cd numeric(6,0),
    no_active_gen_ind numeric(1,0) NOT NULL DEFAULT 0,
    non_load_based_ind numeric(1,0) NOT NULL DEFAULT 0,
    actual_90th_op_date timestamp without time zone,
    moved_ind numeric(1,0) NOT NULL DEFAULT 0,
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (unit_id)
);
COMMENT ON TABLE camd.unit
    IS 'Identifies industrial boilers or electric generating units.';
COMMENT ON COLUMN camd.unit.unit_id
    IS 'Identity key for UNIT table.';
COMMENT ON COLUMN camd.unit.fac_id
    IS 'FACILITY ID identity key.';
COMMENT ON COLUMN camd.unit.unitid
    IS 'Public identifier used for UNIT for PROGRAM identification purposes.';
COMMENT ON COLUMN camd.unit.unit_description
    IS 'Text description of UNIT or UNIT configuration.';
COMMENT ON COLUMN camd.unit.indian_country_ind
    IS 'Indicates whether of not a unit is located in Indian Country.';
COMMENT ON COLUMN camd.unit.stateid
    IS 'The state identification number for a FACILITY or UNIT.';
COMMENT ON COLUMN camd.unit.boiler_sequence_number
    IS 'A CAMD assigned unique identifier for each boiler or unit.';
COMMENT ON COLUMN camd.unit.comm_op_date
    IS 'First day of operation that a UNIT generated electricity for sale, including the sale of test generation.';
COMMENT ON COLUMN camd.unit.comm_op_date_cd
    IS 'Code indicating whether the UNIT initial operation date is projected or actual.';
COMMENT ON COLUMN camd.unit.comr_op_date
    IS 'First day of commercial operation for a UNIT.';
COMMENT ON COLUMN camd.unit.comr_op_date_cd
    IS 'Code indicating whether the commercial operation date for a UNIT is projected or actual.';
COMMENT ON COLUMN camd.unit.source_category_cd
    IS 'General description of FACILITY type.';
COMMENT ON COLUMN camd.unit.no_active_gen_ind
    IS 'Indicator to show that the unit does not currently have an active generator (1) or that the unit does currently have an active generator (0).';
COMMENT ON COLUMN camd.unit.non_load_based_ind
    IS 'Non load based unit indicator.';
COMMENT ON COLUMN camd.unit.actual_90th_op_date
    IS 'Stores the actual 90th operating date for a unit.  Supplied by sources via SMS/CBS.';
COMMENT ON COLUMN camd.unit.moved_ind
    IS 'Indicates whether or not a unit was moved from another facility.';
COMMENT ON COLUMN camd.unit.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camd.unit.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camd.unit.update_date
    IS 'Date of the last record update.';