CREATE TABLE IF NOT EXISTS camd.unit_op_status
(
    unit_op_status_id bigint GENERATED BY DEFAULT AS IDENTITY,
    unit_id numeric(38,0) NOT NULL,
    op_status_cd varchar(7) NOT NULL,
    begin_date timestamp without time zone NOT NULL,
    end_date timestamp without time zone,
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp without time zone,
    PRIMARY KEY (unit_op_status_id)
);
COMMENT ON TABLE camd.unit_op_status
    IS 'Used to track operating status for a unit.';
COMMENT ON COLUMN camd.unit_op_status.unit_op_status_id
    IS 'Identity key for UNIT_OP_STATUS table.';
COMMENT ON COLUMN camd.unit_op_status.unit_id
    IS 'Identity key for UNIT table.';
COMMENT ON COLUMN camd.unit_op_status.op_status_cd
    IS 'Operating status for a unit.';
COMMENT ON COLUMN camd.unit_op_status.begin_date
    IS 'Date on which a relationship or an activity began.';
COMMENT ON COLUMN camd.unit_op_status.end_date
    IS 'Date on which a relationship or an activity ended.';
COMMENT ON COLUMN camd.unit_op_status.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty. Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camd.unit_op_status.add_date
    IS 'Date the record was created.';
COMMENT ON COLUMN camd.unit_op_status.update_date
    IS 'Date of the last record update.';