CREATE TABLE IF NOT EXISTS camd.unit_alias
(
    unit_alias_id bigint GENERATED BY DEFAULT AS IDENTITY,
    unit_id numeric(38,0) NOT NULL,
    old_unitid varchar(6) NOT NULL,
    alias_date timestamp without time zone NOT NULL,
    userid varchar(160) NOT NULL,
    add_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (unit_alias_id)
);
COMMENT ON TABLE camd.unit_alias
    IS 'Records cross-reference of Unit ID changes.';
COMMENT ON COLUMN camd.unit_alias.unit_alias_id
    IS 'Identity key for UNIT_ALIAS table.';
COMMENT ON COLUMN camd.unit_alias.unit_id
    IS 'Identity key for UNIT table.';
COMMENT ON COLUMN camd.unit_alias.old_unitid
    IS 'The old UNITID for the UNIT.';
COMMENT ON COLUMN camd.unit_alias.alias_date
    IS 'Date on which UNIT alias was created.';
COMMENT ON COLUMN camd.unit_alias.userid
    IS 'The user name of the person or process that created the record if the Update Date is empty.  Otherwise this is the user name of the person or process that made the last update.';
COMMENT ON COLUMN camd.unit_alias.add_date
    IS 'Date the record was created.';