CREATE TABLE IF NOT EXISTS camdmd.cert_text
(
    cert_text_id bigint GENERATED BY DEFAULT AS IDENTITY,
    cert_text_name varchar(200) NOT NULL,
    cert_text_content varchar(4000) NOT NULL,
    PRIMARY KEY (cert_text_id)
);
COMMENT ON TABLE camdmd.cert_text
    IS 'Lookup table containing blocks of text used in certification statements.';
COMMENT ON COLUMN camdmd.cert_text.cert_text_id
    IS 'CERT_TEXT identity key.';
COMMENT ON COLUMN camdmd.cert_text.cert_text_name
    IS 'The name of the certification text.';
COMMENT ON COLUMN camdmd.cert_text.cert_text_content
    IS 'The content of the certification text.';