CREATE TABLE IF NOT EXISTS camdmd.cert_statement
(
    cert_statement_id bigint GENERATED BY DEFAULT AS IDENTITY,
    cert_statement_type_cd varchar(7) NOT NULL,
    cert_statement_title varchar(200) NOT NULL,
    cert_statement_description varchar(1000) NOT NULL,
    prg_cd varchar(7),
    cert_type_cd varchar(7),
    display_order numeric(3,0) NOT NULL,
    PRIMARY KEY (cert_statement_id)
);
COMMENT ON TABLE camdmd.cert_statement
    IS 'Lookup table containing the list of certfication statements.';
COMMENT ON COLUMN camdmd.cert_statement.cert_statement_id
    IS 'CERT_STATEMENT identity key.';
COMMENT ON COLUMN camdmd.cert_statement.cert_statement_type_cd
    IS 'Code used to identify the display type for the certification statement.';
COMMENT ON COLUMN camdmd.cert_statement.cert_statement_title
    IS 'The title of the certification statement.';
COMMENT ON COLUMN camdmd.cert_statement.cert_statement_description
    IS 'The description of the certification text.';
COMMENT ON COLUMN camdmd.cert_statement.prg_cd
    IS 'Code used to identify regulatory PROGRAM applicable to UNIT.';
COMMENT ON COLUMN camdmd.cert_statement.cert_type_cd
    IS 'Type of Certification Statement';
COMMENT ON COLUMN camdmd.cert_statement.display_order
    IS 'Order to display Certification Statements';