CREATE TABLE IF NOT EXISTS camdmd.cert_statement_text
(
    cert_statement_text_id bigint GENERATED BY DEFAULT AS IDENTITY,
    cert_statement_id numeric(38,0) NOT NULL,
    cert_text_id numeric(38,0) NOT NULL,
    display_order numeric(2,0) NOT NULL,
    PRIMARY KEY (cert_statement_text_id)
);
COMMENT ON TABLE camdmd.cert_statement_text
    IS 'Lookup table containing the list of certification statement text blocks to be used for each certification statement.';
COMMENT ON COLUMN camdmd.cert_statement_text.cert_statement_id
    IS 'CERT_STATEMENT identity key.';
COMMENT ON COLUMN camdmd.cert_statement_text.cert_text_id
    IS 'CERT_TEXT identity key.';
COMMENT ON COLUMN camdmd.cert_statement_text.display_order
    IS 'Display order in the certifcation statement.';