CREATE TABLE IF NOT EXISTS camdmd.email_group
(
    email_group_id bigint GENERATED BY DEFAULT AS IDENTITY,
    email_group_name varchar(100) NOT NULL,
    email_group_definition clob NOT NULL,
    PRIMARY KEY (email_group_id)
);
COMMENT ON TABLE camdmd.email_group
    IS 'Lookup table containing EMAIL_GROUP definitions used for emails.';
COMMENT ON COLUMN camdmd.email_group.email_group_id
    IS 'EMAIL_GROUP identity key.';
COMMENT ON COLUMN camdmd.email_group.email_group_name
    IS 'The name of the EMAIL_GROUP.';
COMMENT ON COLUMN camdmd.email_group.email_group_definition
    IS 'The definition the EMAIL_GROUP.';