CREATE TABLE IF NOT EXISTS camdmd.event_action
(
    event_action_id bigint GENERATED BY DEFAULT AS IDENTITY,
    event_action_description varchar(1000) NOT NULL,
    xsd_id numeric(38,0) NOT NULL,
    enabled_ind numeric(1,0) NOT NULL DEFAULT 1,
    PRIMARY KEY (event_action_id)
);
COMMENT ON TABLE camdmd.event_action
    IS 'Lookup table containing codes that indicates the action for events.';
COMMENT ON COLUMN camdmd.event_action.event_action_id
    IS 'EVENT_ACTION identity key.';
COMMENT ON COLUMN camdmd.event_action.event_action_description
    IS 'The description of the action.';
COMMENT ON COLUMN camdmd.event_action.xsd_id
    IS 'Id for the xml schema definition.';
COMMENT ON COLUMN camdmd.event_action.enabled_ind
    IS 'Indicator for whether the action is enabled.';