CREATE TABLE IF NOT EXISTS camdmd.xml_schema_definition
(
    xsd_id bigint GENERATED BY DEFAULT AS IDENTITY,
    xsd_name varchar(30) NOT NULL,
    xsd_description varchar(1000) NOT NULL,
    xsd_version varchar(10) NOT NULL,
    xsd_content clob NOT NULL,
    PRIMARY KEY (xsd_id)
);
COMMENT ON TABLE camdmd.xml_schema_definition
    IS 'Lookup table containing XML schema definitions used for XML data stored in XML_LOG.';
COMMENT ON COLUMN camdmd.xml_schema_definition.xsd_id
    IS 'XML_SCHEMA_DEFINITION identity key.';
COMMENT ON COLUMN camdmd.xml_schema_definition.xsd_name
    IS 'The name of the XSD.';
COMMENT ON COLUMN camdmd.xml_schema_definition.xsd_description
    IS 'The description of the XSD.';
COMMENT ON COLUMN camdmd.xml_schema_definition.xsd_version
    IS 'The version number of the XSD.';
COMMENT ON COLUMN camdmd.xml_schema_definition.xsd_content
    IS 'The XML Schema Definition.';