
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('EMAUDIT', 'Emissions Audit Checks');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('NSPS4T', 'NSPS4T Summary, Compliance Period and Annual Checks');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('AETB', 'Air Emission Testing');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('PGVP', 'Protocol Gas');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('INTSTAT', 'Daily Interference Status');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('LKSTAT', 'Leak Status');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('F2LSTAT', 'Flow-to-Load Status');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('EMGEN', 'Emissions Generation');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('ADESTAT', 'Appendix D and E Status');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('APPE', 'Appendix E Test');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('CAPAC', 'Capacity');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('CERTAPP', 'Certification Application');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('COMPON', 'Component and Associated Data');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('CONTROL', 'Control');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('CYCLE', 'Cycle Time Test');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('DAILY', 'Daily Emissions Data');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('DAYCAL', 'Daily Calibration Test');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('DCSTAT', 'Daily Calibration Status');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('DEFAULT', 'Default and WAF');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('EMTEST', 'Daily Test');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('EXTEXEM', 'Test Extension/Exemption');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('F2LCHK', 'Flow-to-Load Check');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('F2LREF', 'Flow-to-Load Reference Data');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('FF2LBAS', 'Fuelflow-to-Load Baseline Data');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('FF2LTST', 'Fuelflow-to-Load Test');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('FFACC', 'Fuel Flowmeter Accuracy Test');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('FFACCTT', 'Transmitter Transducer Test');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('FLOWCEM', 'Flow Rate CEM Hourly');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('FORMULA', 'Formula');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('FUEL', 'Fuel');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('FUELFLW', 'Fuel Flow');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('GENERIC', 'Generic');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('GFMCAL', 'Gas Flow Meter Calibration Test');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('HGLME', 'Hg LME Default Test');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('HOURAD', 'Hourly Appendix D');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('HOURAE', 'Hourly Appendix E');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('HOURAGG', 'Hourly Aggregation');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('HOURAPP', 'Hourly Apportionment');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('HOURCV', 'Hourly Calculated Data');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('HOURDHV', 'Hourly Derived Data');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('HOURGEN', 'Hourly General');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('HOURMHV', 'Hourly Monitor Data');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('HOUROP', 'Hourly Operating Data');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('IMPORT', 'Import');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('LINEAR', 'Linearity Check');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('LINSTAT', 'Linearity Status');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('LME', 'LME');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('LOAD', 'Load');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('METHOD', 'Method');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('MONLOC', 'Location');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('MONPLAN', 'Monitoring Plan');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('ONOFF', 'Online-Offline Calibration Test');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('PROGRAM', 'Program');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('QACERT', 'QA Certification Event');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('QUAL', 'Qualification');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('RATA', 'RATA');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('RATSTAT', 'RATA Status');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('SEVNDAY', '7-Day Calibration Test');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('SPAN', 'Span');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('SYSTEM', 'System');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('TEST', 'General Test');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('UNITDEF', 'Unit Default Test');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('DMEM', 'Data and Maps Emissions');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('EMWSI', 'EM Weekly System Integrity Test');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('EMWTS', 'EM Weekly Test Summary');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('MATSCHV', 'MATS Calculated Hourly Value Checks');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('MATSDHV', 'MATS Derived Hourly Value Checks');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('MATSGFM', 'MATS Hourly GFM Data');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('MATSHOD', 'MATS Operating Hour Checks');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('MATSMHV', 'MATS Monitor Hourly Value Checks');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('MATSTRN', 'MATS Sampling Train Checks');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('MATSTRP', 'MATS Sorbent Trap Data');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('WSISTAT', 'Weekly System Integrity Status');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('MATSMTH', 'MATS Supplemental Method');
INSERT INTO camdecmpsmd.check_type_code (check_type_cd, check_type_cd_description) VALUES ('QUALLEE', 'Qualification LEE');
