INSERT INTO camdecmpsmd.control_code (control_cd, control_description, control_equip_param_cd) VALUES ('APAC', 'Additives to Enhance PAC and Existing Equipment Performance', 'HG');
INSERT INTO camdecmpsmd.control_code (control_cd, control_description, control_equip_param_cd) VALUES ('C', 'Cyclone', 'PART');
INSERT INTO camdecmpsmd.control_code (control_cd, control_description, control_equip_param_cd) VALUES ('CAT', 'Catalyst (gold, palladium, or other) used to oxidize mercury', 'HG');
INSERT INTO camdecmpsmd.control_code (control_cd, control_description, control_equip_param_cd) VALUES ('CM', 'Combustion Modification/Fuel Reburning', 'NOX');
INSERT INTO camdecmpsmd.control_code (control_cd, control_description, control_equip_param_cd) VALUES ('DA', 'Dual Alkali', 'SO2');
INSERT INTO camdecmpsmd.control_code (control_cd, control_description, control_equip_param_cd) VALUES ('DL', 'Dry Lime FGD', 'SO2');
INSERT INTO camdecmpsmd.control_code (control_cd, control_description, control_equip_param_cd) VALUES ('DLNB', 'Dry Low NOx Burners', 'NOX');
INSERT INTO camdecmpsmd.control_code (control_cd, control_description, control_equip_param_cd) VALUES ('DSI', 'Dry Sorbent Injection', NULL);
INSERT INTO camdecmpsmd.control_code (control_cd, control_description, control_equip_param_cd) VALUES ('FBL', 'Fluidized Bed Limestone Injection', 'SO2');
INSERT INTO camdecmpsmd.control_code (control_cd, control_description, control_equip_param_cd) VALUES ('H2O', 'Water Injection', 'NOX');
INSERT INTO camdecmpsmd.control_code (control_cd, control_description, control_equip_param_cd) VALUES ('HPAC', 'Halogenated PAC Sorbent Injection', 'HG');
INSERT INTO camdecmpsmd.control_code (control_cd, control_description, control_equip_param_cd) VALUES ('LNB', 'Low NOx Burner Technology (Dry Bottom only)', 'NOX');
INSERT INTO camdecmpsmd.control_code (control_cd, control_description, control_equip_param_cd) VALUES ('LNBO', 'Low NOx Burner Technology w/ Overfire Air', 'NOX');
INSERT INTO camdecmpsmd.control_code (control_cd, control_description, control_equip_param_cd) VALUES ('LNC1', 'Low NOx Burner Technology w/ Closed-coupled OFA', 'NOX');
INSERT INTO camdecmpsmd.control_code (control_cd, control_description, control_equip_param_cd) VALUES ('LNC2', 'Low NOx Burner Technology w/ Separated OFA', 'NOX');
INSERT INTO camdecmpsmd.control_code (control_cd, control_description, control_equip_param_cd) VALUES ('LNC3', 'Low NOx Burner Technology w/ Closed-coupled/Separated OFA', 'NOX');
INSERT INTO camdecmpsmd.control_code (control_cd, control_description, control_equip_param_cd) VALUES ('LNCB', 'Low NOx Cell Burner', 'NOX');
INSERT INTO camdecmpsmd.control_code (control_cd, control_description, control_equip_param_cd) VALUES ('MO', 'Magnesium Oxide', 'SO2');
INSERT INTO camdecmpsmd.control_code (control_cd, control_description, control_equip_param_cd) VALUES ('NH3', 'Ammonia Injection', 'NOX');
INSERT INTO camdecmpsmd.control_code (control_cd, control_description, control_equip_param_cd) VALUES ('O', 'Other', NULL);
INSERT INTO camdecmpsmd.control_code (control_cd, control_description, control_equip_param_cd) VALUES ('OFA', 'Overfire Air', 'NOX');
INSERT INTO camdecmpsmd.control_code (control_cd, control_description, control_equip_param_cd) VALUES ('REAC', 'Regenerative Activated Coke Technology', 'HG');
INSERT INTO camdecmpsmd.control_code (control_cd, control_description, control_equip_param_cd) VALUES ('SB', 'Sodium Based', NULL);
INSERT INTO camdecmpsmd.control_code (control_cd, control_description, control_equip_param_cd) VALUES ('SCR', 'Selective Catalytic Reduction', 'NOX');
INSERT INTO camdecmpsmd.control_code (control_cd, control_description, control_equip_param_cd) VALUES ('SNCR', 'Selective Non-catalytic Reduction', 'NOX');
INSERT INTO camdecmpsmd.control_code (control_cd, control_description, control_equip_param_cd) VALUES ('SORB', 'Other (Non PAC) Sorbent Injection', 'HG');
INSERT INTO camdecmpsmd.control_code (control_cd, control_description, control_equip_param_cd) VALUES ('STM', 'Steam Injection', 'NOX');
INSERT INTO camdecmpsmd.control_code (control_cd, control_description, control_equip_param_cd) VALUES ('UPAC', 'Untreated PAC Sorbent Injection', 'HG');
INSERT INTO camdecmpsmd.control_code (control_cd, control_description, control_equip_param_cd) VALUES ('WL', 'Wet Lime FGD', 'SO2');
INSERT INTO camdecmpsmd.control_code (control_cd, control_description, control_equip_param_cd) VALUES ('WLS', 'Wet Limestone', 'SO2');
INSERT INTO camdecmpsmd.control_code (control_cd, control_description, control_equip_param_cd) VALUES ('WS', 'Wet Scrubber', 'PART');
INSERT INTO camdecmpsmd.control_code (control_cd, control_description, control_equip_param_cd) VALUES ('B', 'Baghouse', NULL);
INSERT INTO camdecmpsmd.control_code (control_cd, control_description, control_equip_param_cd) VALUES ('ESP', 'Electrostatic Precipitator', NULL);
INSERT INTO camdecmpsmd.control_code (control_cd, control_description, control_equip_param_cd) VALUES ('HESP', 'Hybrid ESP', NULL);
INSERT INTO camdecmpsmd.control_code (control_cd, control_description, control_equip_param_cd) VALUES ('WESP', 'Wet ESP', NULL);

