
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('MS-2', 'Flow-weighted apportionment to multiple stacks', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('19-1', 'NOXR/SO2R (same as F-5)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('19-14', 'FW (from fuel composition)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('19-2', 'NOXR/SO2R (from wet NOX or SO2, wet O2, Bwa, Fw)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('19-3', 'NOXR/SO2R (from wet NOX or SO2, wet O2, H2O, Fd)', 1);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('19-3D', 'NOXR/SO2R (replacement for 19-3 during diluent cap hours)', 1);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('19-4', 'NOXR/SO2R (from wet NOX or SO2, dry O2, H2O, Fd)', 1);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('19-5', 'NOXR/SO2R (from dry NOX or SO2, wet O2, H2O, Fd)', 1);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('19-5D', 'NOXR/SO2R (replacement for 19-5 during diluent cap hours)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('19-6', 'NOXR/SO2R (from dry NOX or SO2, dry CO2, Fc)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('19-7', 'NOXR/SO2R (same as F-6)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('19-8', 'NOXR/SO2R (from wet NOX or SO2, dry CO2, H2O, Fc)', 1);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('19-9', 'NOXR/SO2R (from dry NOX or SO2, wet CO2, H2O, Fc)', 1);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('D-12', 'SO2 (from SO2 rate for multiple fuels)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('D-15', 'HIT (from HI from oil or gas)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('D-15A', 'HI (from HI rate for multiple fuels)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('D-1H', 'SO2R (from gas sulfur content, GCV)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('D-2', 'SO2 (from OILM, oil sulfur content)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('D-3', 'OILM (from volumetric oil flow rate, density)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('D-4', 'SO2 (from gas sulfur content)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('D-5', 'SO2 (from gas SO2 emission rate, HI)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('D-6', 'HI (from gas flow rate, GCV)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('D-8', 'HI (from oil flow rate, GCV)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('E-2', 'NOXR (from multiple NOXE systems)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('F-1', 'SO2 (from SO2 wet, flow)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('F-11', 'CO2 (from CO2 wet, flow)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('F-14A', 'CO2C (from dry O2, Fd, Fc)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('F-14B', 'CO2C (from wet O2, H2O, Fd, Fc)', 1);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('F-15', 'HI (from wet CO2, flow, Fc)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('F-16', 'HI (from dry CO2, flow, H2O, Fc)', 1);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('F-17', 'HI (from wet O2, flow, H2O, Fd)', 1);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('F-18', 'HI (from dry O2, flow, H2O, Fd)', 1);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('F-19', 'HI (same as D-8)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('F-19V', 'HI (from volumetric oil flow rate, GCV)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('F-2', 'SO2/CO2 (from SO2 or CO2 dry, flow, H2O)', 1);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('F-20', 'HI (same as D-6)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('F-21A', 'HI (apportioned from HI for common stack/pipe by MWe)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('F-21B', 'HI (apportioned from HI for common stack/pipe by steam load)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('F-21C', 'HI (summed from HI for multiple stacks/pipes)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('F-21D', 'HI (apportioned from HI for common pipe by uncertified fuel flowmeter)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('F-23', 'SO2R (from gas SO2 emission rate, HI- same as D-5)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('F-24A', 'NOX (from NOX rate, HI)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('F-25', 'HI (for common stack summed from HI for units)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('F-26A', 'NOX (hourly from wet NOXC, flow)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('F-26B', 'NOX (hourly from dry NOXC, flow, H2O)', 1);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('F-31', 'H2O (from wet and dry O2)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('F-5', 'NOXR/SO2R (from NOX or SO2 dry, O2 dry, Fd)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('F-6', 'NOXR/SO2R (from NOX or SO2 wet, CO2 wet, Fc)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('F-7A', 'FD (from fuel composition)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('F-7B', 'FC (from carbon content, GCV)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('F-8', 'FD/FC/FW (from multiple fuels)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('G-1', 'CO2M (from fuel composition)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('G-2', 'CO2M (from fuel composition adjusted by carbon retained in ash)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('G-3', 'CO2M (from fuel composition adjusted by carbon retained in ash)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('G-4', 'CO2 (from HI, Fc)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('G-4A', 'CO2 (from CO2 rate for multiple fuels)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('G-5', 'CO2M (for sorbent)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('G-6', 'CO2M (for sorbent with SO2 controls)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('G-8', 'CO2M (from CO2M for both fuel and sorbent)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('M-1K', 'H2O (from wet and dry O2 with K-factor adjustment)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('N-GAS', 'FGAS (net gas flow rate)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('N-OIL', 'FOIL (net volumetric oil flow rate)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('NS-1', 'NOXR (for affected units in a subtractive configuration)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('NS-2', 'NOXR (apportioned)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('SS-1A', 'SO2 (hourly for affected units in a subtractive configuration)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('SS-1B', 'SO2 (hourly for affected units in a subtractive configuration)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('SS-2A', 'NOX (hourly for affected units in a subtractive configuration)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('SS-2B', 'NOX (hourly for affected units in a subtractive configuration)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('SS-2C', 'NOX (hourly for affected units in a subtractive configuration)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('SS-3A', 'HI (hourly for affected units in a subtractive configuration)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('SS-3B', 'HI (hourly for affected units in a subtractive configuration)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('T-FL', 'FLOW (total stack flow rate)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('X-FL', 'FLOW (average stack flow rate)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('A-3', 'HGRE (lb/hr dry)', 1);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('A-4', 'HGRE (Conversion lb/hr to lb/GWh)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('HC-2', 'HCLRE (lb/MWh wet)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('HC-3', 'HCLRE (lb/MWh dry)', 1);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('HC-4', 'HCLRE(Conversion lb/hr to lb/MWh)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('HF-2', 'HFRE (lb/MWh wet)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('HF-3', 'HFRE (lb/MWh dry)', 1);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('HF-4', 'HFRE (Conversion lb/hr to lb/MWh)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('HG-1', 'HG(converts lb/mmBtu to lb/TBtu)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('S-2', 'SO2RE (lb/MWh wet)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('S-3', 'SO2RE (lb/MWh dry)', 1);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('S-4', 'SO2RE (Conversion lb/hr to lb/MWh)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('A-2', 'HGRE (lb/hr wet)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('MS-1', 'Flow-weighted average from multiple stacks', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('11-3', 'PS-11 Linear Equation', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('11-16', 'PS-11 Polynomial Equation', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('11-34', 'PS-11 Logarithmic Equation', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('11-37', 'PS-11 Exponential Equation', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('11-46', 'PS-11 Power Function Equation', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('F-18C', 'Total Daily Heat Input', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('F-27B', 'Daily NOx Mass', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('C-3', 'PMRE (lb/MWh wet)', NULL);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('C-4', 'PMRE (lb/MWh dry)', 1);
INSERT INTO camdecmpsmd.equation_code (equation_cd, equation_cd_description, moisture_ind) VALUES ('F-28', 'Apportioned NOx Mass', NULL);

