INSERT INTO camdecmpsmd.es_match_data_type_code (es_match_data_type_cd, es_match_data_type_description, es_match_data_type_label, es_match_data_type_url) VALUES ('CEPARAM', 'CE Parameter Code', 'CE Parameter', '/master-data-mgmt/control-equip-param-codes');
INSERT INTO camdecmpsmd.es_match_data_type_code (es_match_data_type_cd, es_match_data_type_description, es_match_data_type_label, es_match_data_type_url) VALUES ('COMPTYP', 'Component Type Code', 'Comp Type', '/master-data-mgmt/component-type-codes');
INSERT INTO camdecmpsmd.es_match_data_type_code (es_match_data_type_cd, es_match_data_type_description, es_match_data_type_label, es_match_data_type_url) VALUES ('FUELTYP', 'Fuel Type Code', 'Fuel Type', '/master-data-mgmt/fuel-type-codes');
INSERT INTO camdecmpsmd.es_match_data_type_code (es_match_data_type_cd, es_match_data_type_description, es_match_data_type_label, es_match_data_type_url) VALUES ('MONPLAN', 'Monitor Plan Id', 'Monitor Plan', '/monitor-plan-mgmt/workspace/configurations');
INSERT INTO camdecmpsmd.es_match_data_type_code (es_match_data_type_cd, es_match_data_type_description, es_match_data_type_label, es_match_data_type_url) VALUES ('PARAM', 'Parameter Code', 'Parameter', '/master-data-mgmt/es-parameter-codes');
INSERT INTO camdecmpsmd.es_match_data_type_code (es_match_data_type_cd, es_match_data_type_description, es_match_data_type_label, es_match_data_type_url) VALUES ('PROGRAM', 'Program Code', 'Program', '/master-data-mgmt/program-codes');
INSERT INTO camdecmpsmd.es_match_data_type_code (es_match_data_type_cd, es_match_data_type_description, es_match_data_type_label, es_match_data_type_url) VALUES ('QUALTYP', 'Qualification Type Code', 'Qual Type', '/master-data-mgmt/qualification-type-codes');
INSERT INTO camdecmpsmd.es_match_data_type_code (es_match_data_type_cd, es_match_data_type_description, es_match_data_type_label, es_match_data_type_url) VALUES ('SYSTYP', 'System Type Code', 'System Type', '/master-data-mgmt/system-type-codes');
INSERT INTO camdecmpsmd.es_match_data_type_code (es_match_data_type_cd, es_match_data_type_description, es_match_data_type_label, es_match_data_type_url) VALUES ('TESTNUM', 'Test Number', 'Test Number', '/qa-certification-mgmt/workspace/locations/{id}/test-summary');
INSERT INTO camdecmpsmd.es_match_data_type_code (es_match_data_type_cd, es_match_data_type_description, es_match_data_type_label, es_match_data_type_url) VALUES ('TESTTYP', 'Test Type Code', 'Test Type', '/master-data-mgmt/test-type-codes');
INSERT INTO camdecmpsmd.es_match_data_type_code (es_match_data_type_cd, es_match_data_type_description, es_match_data_type_label, es_match_data_type_url) VALUES ('MATSPAR', 'MATS Method Parameter Code', 'MATS Param', '/master-data-mgmt/mats-method-parameter-codes');

