INSERT INTO camdecmpsmd.fuel_code (fuel_cd, fuel_group_cd, unit_fuel_cd, fuel_cd_description) VALUES ('ANT', 'COAL', 'C', 'Anthracite Coal');
INSERT INTO camdecmpsmd.fuel_code (fuel_cd, fuel_group_cd, unit_fuel_cd, fuel_cd_description) VALUES ('BFG', 'GAS', 'OGS', 'Blast Furnace Gas');
INSERT INTO camdecmpsmd.fuel_code (fuel_cd, fuel_group_cd, unit_fuel_cd, fuel_cd_description) VALUES ('BT', 'COAL', 'C', 'Bituminous Coal');
INSERT INTO camdecmpsmd.fuel_code (fuel_cd, fuel_group_cd, unit_fuel_cd, fuel_cd_description) VALUES ('BUT', 'GAS', 'OGS', 'Butane Gas');
INSERT INTO camdecmpsmd.fuel_code (fuel_cd, fuel_group_cd, unit_fuel_cd, fuel_cd_description) VALUES ('C', 'COAL', 'C', 'Coal');
INSERT INTO camdecmpsmd.fuel_code (fuel_cd, fuel_group_cd, unit_fuel_cd, fuel_cd_description) VALUES ('CDG', 'GAS', 'OGS', 'Coal Derived Gas');
INSERT INTO camdecmpsmd.fuel_code (fuel_cd, fuel_group_cd, unit_fuel_cd, fuel_cd_description) VALUES ('COG', 'GAS', 'PRG', 'Coke Oven Gas');
INSERT INTO camdecmpsmd.fuel_code (fuel_cd, fuel_group_cd, unit_fuel_cd, fuel_cd_description) VALUES ('CRF', 'OTHER', 'CRF', 'Coal Refuse');
INSERT INTO camdecmpsmd.fuel_code (fuel_cd, fuel_group_cd, unit_fuel_cd, fuel_cd_description) VALUES ('DGG', 'GAS', 'PRG', 'Digester Gas');
INSERT INTO camdecmpsmd.fuel_code (fuel_cd, fuel_group_cd, unit_fuel_cd, fuel_cd_description) VALUES ('DSL', 'OIL', 'DSL', 'Diesel Oil');
INSERT INTO camdecmpsmd.fuel_code (fuel_cd, fuel_group_cd, unit_fuel_cd, fuel_cd_description) VALUES ('LFG', 'GAS', 'OGS', 'Landfill Gas');
INSERT INTO camdecmpsmd.fuel_code (fuel_cd, fuel_group_cd, unit_fuel_cd, fuel_cd_description) VALUES ('LIG', 'COAL', 'C', 'Lignite Coal');
INSERT INTO camdecmpsmd.fuel_code (fuel_cd, fuel_group_cd, unit_fuel_cd, fuel_cd_description) VALUES ('LPG', 'GAS', 'LPG', 'Liquefied Petroleum Gas');
INSERT INTO camdecmpsmd.fuel_code (fuel_cd, fuel_group_cd, unit_fuel_cd, fuel_cd_description) VALUES ('MIX', 'MIX', NULL, 'Mixture (Co-Fired Fuels)');
INSERT INTO camdecmpsmd.fuel_code (fuel_cd, fuel_group_cd, unit_fuel_cd, fuel_cd_description) VALUES ('NFS', 'NFS', NULL, 'Non-Fuel Specific');
INSERT INTO camdecmpsmd.fuel_code (fuel_cd, fuel_group_cd, unit_fuel_cd, fuel_cd_description) VALUES ('NNG', 'GAS', 'NNG', 'Natural Gas');
INSERT INTO camdecmpsmd.fuel_code (fuel_cd, fuel_group_cd, unit_fuel_cd, fuel_cd_description) VALUES ('OGS', 'GAS', 'OGS', 'Other Gas');
INSERT INTO camdecmpsmd.fuel_code (fuel_cd, fuel_group_cd, unit_fuel_cd, fuel_cd_description) VALUES ('OIL', 'OIL', 'OIL', 'Residual Oil');
INSERT INTO camdecmpsmd.fuel_code (fuel_cd, fuel_group_cd, unit_fuel_cd, fuel_cd_description) VALUES ('OOL', 'OIL', 'OOL', 'Other Oil');
INSERT INTO camdecmpsmd.fuel_code (fuel_cd, fuel_group_cd, unit_fuel_cd, fuel_cd_description) VALUES ('OSF', 'OTHER', 'OSF', 'Other Solid Fuel');
INSERT INTO camdecmpsmd.fuel_code (fuel_cd, fuel_group_cd, unit_fuel_cd, fuel_cd_description) VALUES ('PDG', 'GAS', 'PRG', 'Producer Gas');
INSERT INTO camdecmpsmd.fuel_code (fuel_cd, fuel_group_cd, unit_fuel_cd, fuel_cd_description) VALUES ('PNG', 'GAS', 'PNG', 'Pipeline Natural Gas');
INSERT INTO camdecmpsmd.fuel_code (fuel_cd, fuel_group_cd, unit_fuel_cd, fuel_cd_description) VALUES ('PRG', 'GAS', 'PRG', 'Process Gas');
INSERT INTO camdecmpsmd.fuel_code (fuel_cd, fuel_group_cd, unit_fuel_cd, fuel_cd_description) VALUES ('PRP', 'GAS', 'OGS', 'Propane Gas');
INSERT INTO camdecmpsmd.fuel_code (fuel_cd, fuel_group_cd, unit_fuel_cd, fuel_cd_description) VALUES ('PRS', 'OTHER', 'PRS', 'Process Sludge');
INSERT INTO camdecmpsmd.fuel_code (fuel_cd, fuel_group_cd, unit_fuel_cd, fuel_cd_description) VALUES ('PTC', 'OTHER', 'PTC', 'Petroleum Coke');
INSERT INTO camdecmpsmd.fuel_code (fuel_cd, fuel_group_cd, unit_fuel_cd, fuel_cd_description) VALUES ('R', 'OTHER', 'R', 'Refuse');
INSERT INTO camdecmpsmd.fuel_code (fuel_cd, fuel_group_cd, unit_fuel_cd, fuel_cd_description) VALUES ('RFG', 'GAS', 'PRG', 'Refinery Gas');
INSERT INTO camdecmpsmd.fuel_code (fuel_cd, fuel_group_cd, unit_fuel_cd, fuel_cd_description) VALUES ('SRG', 'GAS', 'OGS', 'Unrefined Sour Gas');
INSERT INTO camdecmpsmd.fuel_code (fuel_cd, fuel_group_cd, unit_fuel_cd, fuel_cd_description) VALUES ('SUB', 'COAL', 'C', 'Sub-Bituminous Coal');
INSERT INTO camdecmpsmd.fuel_code (fuel_cd, fuel_group_cd, unit_fuel_cd, fuel_cd_description) VALUES ('TDF', 'OTHER', 'TDF', 'Tire-Derived Fuel');
INSERT INTO camdecmpsmd.fuel_code (fuel_cd, fuel_group_cd, unit_fuel_cd, fuel_cd_description) VALUES ('W', 'OTHER', 'W', 'Wood');
INSERT INTO camdecmpsmd.fuel_code (fuel_cd, fuel_group_cd, unit_fuel_cd, fuel_cd_description) VALUES ('WL', 'OTHER', 'WL', 'Waste Liquid');
