INSERT INTO camdecmpsmd.gas_component_code (gas_component_cd, gas_component_description, can_combine_ind, balance_component_ind) VALUES ('AIR', 'Purified air material', 0, 0);
INSERT INTO camdecmpsmd.gas_component_code (gas_component_cd, gas_component_description, can_combine_ind, balance_component_ind) VALUES ('APPVD', 'Other EPA-approved EPA Protocol gas blend  ', 0, 0);
INSERT INTO camdecmpsmd.gas_component_code (gas_component_cd, gas_component_description, can_combine_ind, balance_component_ind) VALUES ('BALA', 'Air Balance Gas', 1, 1);
INSERT INTO camdecmpsmd.gas_component_code (gas_component_cd, gas_component_description, can_combine_ind, balance_component_ind) VALUES ('BALN', 'Nitrogen Balance Gas', 1, 1);
INSERT INTO camdecmpsmd.gas_component_code (gas_component_cd, gas_component_description, can_combine_ind, balance_component_ind) VALUES ('CH4', 'Methane', 1, 0);
INSERT INTO camdecmpsmd.gas_component_code (gas_component_cd, gas_component_description, can_combine_ind, balance_component_ind) VALUES ('CO', 'Carbon Monoxide ', 1, 0);
INSERT INTO camdecmpsmd.gas_component_code (gas_component_cd, gas_component_description, can_combine_ind, balance_component_ind) VALUES ('CO2', 'Carbon Dioxide', 1, 0);
INSERT INTO camdecmpsmd.gas_component_code (gas_component_cd, gas_component_description, can_combine_ind, balance_component_ind) VALUES ('GMIS', 'Gas manufacturer’s intermediate standard', 0, 0);
INSERT INTO camdecmpsmd.gas_component_code (gas_component_cd, gas_component_description, can_combine_ind, balance_component_ind) VALUES ('H2S', 'Hydrogen Sulfide', 1, 0);
INSERT INTO camdecmpsmd.gas_component_code (gas_component_cd, gas_component_description, can_combine_ind, balance_component_ind) VALUES ('HE', 'Helium', 1, 0);
INSERT INTO camdecmpsmd.gas_component_code (gas_component_cd, gas_component_description, can_combine_ind, balance_component_ind) VALUES ('N2O', 'Nitrous Oxide', 1, 0);
INSERT INTO camdecmpsmd.gas_component_code (gas_component_cd, gas_component_description, can_combine_ind, balance_component_ind) VALUES ('NO', 'Nitric Oxide', 1, 0);
INSERT INTO camdecmpsmd.gas_component_code (gas_component_cd, gas_component_description, can_combine_ind, balance_component_ind) VALUES ('NO2', 'Nitrogen Dioxide', 1, 0);
INSERT INTO camdecmpsmd.gas_component_code (gas_component_cd, gas_component_description, can_combine_ind, balance_component_ind) VALUES ('NOX', 'Total Oxides of Nitrogen', 1, 0);
INSERT INTO camdecmpsmd.gas_component_code (gas_component_cd, gas_component_description, can_combine_ind, balance_component_ind) VALUES ('NTRM', 'NIST-traceable reference material', 0, 0);
INSERT INTO camdecmpsmd.gas_component_code (gas_component_cd, gas_component_description, can_combine_ind, balance_component_ind) VALUES ('O2', 'Oxygen', 1, 0);
INSERT INTO camdecmpsmd.gas_component_code (gas_component_cd, gas_component_description, can_combine_ind, balance_component_ind) VALUES ('PPN', 'Propane', 1, 0);
INSERT INTO camdecmpsmd.gas_component_code (gas_component_cd, gas_component_description, can_combine_ind, balance_component_ind) VALUES ('PRM', 'SRM-equivalent compressed gas primary reference material', 0, 0);
INSERT INTO camdecmpsmd.gas_component_code (gas_component_cd, gas_component_description, can_combine_ind, balance_component_ind) VALUES ('RGM', 'Research gas mixture', 0, 0);
INSERT INTO camdecmpsmd.gas_component_code (gas_component_cd, gas_component_description, can_combine_ind, balance_component_ind) VALUES ('SO2', 'Sulfur Dioxide', 1, 0);
INSERT INTO camdecmpsmd.gas_component_code (gas_component_cd, gas_component_description, can_combine_ind, balance_component_ind) VALUES ('SRM', 'Standard reference material', 0, 0);
INSERT INTO camdecmpsmd.gas_component_code (gas_component_cd, gas_component_description, can_combine_ind, balance_component_ind) VALUES ('ZERO', 'Zero calibration gas', 0, 0);