INSERT INTO camdecmpsmd.gas_type_code (gas_type_cd, gas_type_description) VALUES ('ZERO', 'Zero level gas used for the low level calibration of a reference analyzer used in RATA testing');
INSERT INTO camdecmpsmd.gas_type_code (gas_type_cd, gas_type_description) VALUES ('ZAM', 'Zero Air Material');
INSERT INTO camdecmpsmd.gas_type_code (gas_type_cd, gas_type_description) VALUES ('AIR', 'Purified air material');
INSERT INTO camdecmpsmd.gas_type_code (gas_type_cd, gas_type_description) VALUES ('APPVD', 'Other EPA-approved EPA Protocol gas blend');
INSERT INTO camdecmpsmd.gas_type_code (gas_type_cd, gas_type_description) VALUES ('CO2', 'EPA Protocol gas consisting of CO2, and a balance gas');
INSERT INTO camdecmpsmd.gas_type_code (gas_type_cd, gas_type_description) VALUES ('GMIS', 'Gas manufacturer''s intermediate standard');
INSERT INTO camdecmpsmd.gas_type_code (gas_type_cd, gas_type_description) VALUES ('N2C', 'EPA Protocol gas bi-blend consisting of NO2 and CO, and a balance gas');
INSERT INTO camdecmpsmd.gas_type_code (gas_type_cd, gas_type_description) VALUES ('N2C2', 'EPA Protocol gas bi-blend consisting of NO2 and CO2, and a balance gas');
INSERT INTO camdecmpsmd.gas_type_code (gas_type_cd, gas_type_description) VALUES ('N2CC', 'EPA Protocol gas tri-blend consisting of NO2, CO, and CO2, and a balance gas');
INSERT INTO camdecmpsmd.gas_type_code (gas_type_cd, gas_type_description) VALUES ('NC', 'EPA Protocol gas bi-blend consisting of NO and CO, and a balance gas');
INSERT INTO camdecmpsmd.gas_type_code (gas_type_cd, gas_type_description) VALUES ('NC2', 'EPA Protocol gas bi-blend consisting of NO and CO2, and a balance gas');
INSERT INTO camdecmpsmd.gas_type_code (gas_type_cd, gas_type_description) VALUES ('NCC', 'EPA Protocol gas tri-blend consisting of NO, CO, and CO2, and a balance gas');
INSERT INTO camdecmpsmd.gas_type_code (gas_type_cd, gas_type_description) VALUES ('NO', 'EPA Protocol gas consisting of NO, and a balance gas');
INSERT INTO camdecmpsmd.gas_type_code (gas_type_cd, gas_type_description) VALUES ('NO2', 'EPA Protocol gas consisting of NO2, and a balance gas');
INSERT INTO camdecmpsmd.gas_type_code (gas_type_cd, gas_type_description) VALUES ('NTRM', 'NIST-traceable reference material');
INSERT INTO camdecmpsmd.gas_type_code (gas_type_cd, gas_type_description) VALUES ('NX', 'EPA Protocol gas bi-blend consisting of NO and NO2, and a balance gas');
INSERT INTO camdecmpsmd.gas_type_code (gas_type_cd, gas_type_description) VALUES ('NXC', 'EPA Protocol gas tri-blend consisting of NO, NO2, and CO, and a balance gas');
INSERT INTO camdecmpsmd.gas_type_code (gas_type_cd, gas_type_description) VALUES ('NXC2', 'EPA Protocol gas tri-blend consisting of NO, NO2, and CO2, and a balance gas');
INSERT INTO camdecmpsmd.gas_type_code (gas_type_cd, gas_type_description) VALUES ('NXCC', 'EPA Protocol gas quad-blend consisting of NO, NO2, CO, and CO2, and a balance gas');
INSERT INTO camdecmpsmd.gas_type_code (gas_type_cd, gas_type_description) VALUES ('O2', 'EPA Protocol gas consisting of O2, and a balance gas');
INSERT INTO camdecmpsmd.gas_type_code (gas_type_cd, gas_type_description) VALUES ('OC', 'EPA Protocol gas bi-blend consisting of O2 and CO, and a balance gas');
INSERT INTO camdecmpsmd.gas_type_code (gas_type_cd, gas_type_description) VALUES ('OC2', 'EPA Protocol gas bi-blend consisting of O2 and CO2, and a balance gas');
INSERT INTO camdecmpsmd.gas_type_code (gas_type_cd, gas_type_description) VALUES ('OCC', 'EPA Protocol gas tri-blend consisting of O2, CO, and CO2, and a balance gas');
INSERT INTO camdecmpsmd.gas_type_code (gas_type_cd, gas_type_description) VALUES ('PRM', 'SRM-equivalent compressed gas primary reference material');
INSERT INTO camdecmpsmd.gas_type_code (gas_type_cd, gas_type_description) VALUES ('RGM', 'Research gas mixture');
INSERT INTO camdecmpsmd.gas_type_code (gas_type_cd, gas_type_description) VALUES ('SC', 'EPA Protocol gas bi-blend consisting of SO2 and CO, and a balance gas');
INSERT INTO camdecmpsmd.gas_type_code (gas_type_cd, gas_type_description) VALUES ('SC2', 'EPA Protocol gas bi-blend consisting of SO2 and CO2, and a balance gas');
INSERT INTO camdecmpsmd.gas_type_code (gas_type_cd, gas_type_description) VALUES ('SN', 'EPA Protocol gas bi-blend consisting of SO2 and NO, and a balance gas');
INSERT INTO camdecmpsmd.gas_type_code (gas_type_cd, gas_type_description) VALUES ('SN2', 'EPA Protocol gas bi-blend consisting of SO2 and NO2, and a balance gas');
INSERT INTO camdecmpsmd.gas_type_code (gas_type_cd, gas_type_description) VALUES ('SN2C', 'EPA Protocol gas tri-blend consisting of SO2, NO2, and CO, and a balance gas');
INSERT INTO camdecmpsmd.gas_type_code (gas_type_cd, gas_type_description) VALUES ('SN2C2', 'EPA Protocol gas tri-blend consisting of SO2, NO2, and CO2, and a balance gas');
INSERT INTO camdecmpsmd.gas_type_code (gas_type_cd, gas_type_description) VALUES ('SN2CC', 'EPA Protocol gas quad-blend consisting of SO2, NO2, CO, and CO2, and a balance gas');
INSERT INTO camdecmpsmd.gas_type_code (gas_type_cd, gas_type_description) VALUES ('SNC', 'EPA Protocol gas tri-blend consisting of SO2, NO, and CO, and a balance gas');
INSERT INTO camdecmpsmd.gas_type_code (gas_type_cd, gas_type_description) VALUES ('SNC2', 'EPA Protocol gas tri-blend consisting of SO2, NO, and CO2, and a balance gas');
INSERT INTO camdecmpsmd.gas_type_code (gas_type_cd, gas_type_description) VALUES ('SNCC', 'EPA Protocol gas quad-blend consisting of SO2, NO, CO, and CO2, and a balance gas');
INSERT INTO camdecmpsmd.gas_type_code (gas_type_cd, gas_type_description) VALUES ('SNX', 'EPA Protocol gas tri-blend consisting of SO2, NO, and NO2, and a balance gas');
INSERT INTO camdecmpsmd.gas_type_code (gas_type_cd, gas_type_description) VALUES ('SNXC', 'EPA Protocol gas quad-blend consisting of SO2, NO, NO2, and CO, and a balance gas');
INSERT INTO camdecmpsmd.gas_type_code (gas_type_cd, gas_type_description) VALUES ('SNXC2', 'EPA Protocol gas quad-blend consisting of SO2, NO, NO2, and CO2, and a balance gas');
INSERT INTO camdecmpsmd.gas_type_code (gas_type_cd, gas_type_description) VALUES ('SNXCC', 'EPA Protocol gas quint-blend consisting of SO2, NO, NO2, CO, and CO2, and a balance gas');
INSERT INTO camdecmpsmd.gas_type_code (gas_type_cd, gas_type_description) VALUES ('SO', 'EPA Protocol gas bi-blend consisting of SO2 and O2, and a balance gas');
INSERT INTO camdecmpsmd.gas_type_code (gas_type_cd, gas_type_description) VALUES ('SO2', 'EPA Protocol gas consisting of SO2, and a balance gas');
INSERT INTO camdecmpsmd.gas_type_code (gas_type_cd, gas_type_description) VALUES ('SOC', 'EPA Protocol gas tri-blend consisting of SO2, O2, and CO, and a balance gas');
INSERT INTO camdecmpsmd.gas_type_code (gas_type_cd, gas_type_description) VALUES ('SRM', 'Standard reference material');
