INSERT INTO camdecmpsmd.modc_code (modc_cd, modc_description) VALUES ('46', 'NOX Concentration or CO2/O2 Concentration reported during missing data hour when only used for NOXR, H2O or CO2C derived values.');
INSERT INTO camdecmpsmd.modc_code (modc_cd, modc_description) VALUES ('47', 'NOX Concentration or CO2/O2 Concentration available but not used to determine NOx emission rate.');
INSERT INTO camdecmpsmd.modc_code (modc_cd, modc_description) VALUES ('48', 'Missing data NOX Concentration or CO2/O2 Concentration that is not used to determine NOx emission rate status.');
INSERT INTO camdecmpsmd.modc_code (modc_cd, modc_description) VALUES ('18', 'MPC Used for Portion of Hour When High Range of Dual Range Analyzer Unavailable due to Expired Test');
INSERT INTO camdecmpsmd.modc_code (modc_cd, modc_description) VALUES ('01', 'Primary (or Primary Bypass) Monitoring System');
INSERT INTO camdecmpsmd.modc_code (modc_cd, modc_description) VALUES ('02', 'Redundant or Non-Redundant Backup Monitoring System');
INSERT INTO camdecmpsmd.modc_code (modc_cd, modc_description) VALUES ('03', 'Approved Subpart E Alternative Monitoring System');
INSERT INTO camdecmpsmd.modc_code (modc_cd, modc_description) VALUES ('04', 'Reference Method Backup System');
INSERT INTO camdecmpsmd.modc_code (modc_cd, modc_description) VALUES ('05', 'Preapproved Parametric Monitoring Method for Controlled Units');
INSERT INTO camdecmpsmd.modc_code (modc_cd, modc_description) VALUES ('06', 'Average Hour Before/Hour After');
INSERT INTO camdecmpsmd.modc_code (modc_cd, modc_description) VALUES ('07', 'Average Hourly Concentration, Initial Missing Data');
INSERT INTO camdecmpsmd.modc_code (modc_cd, modc_description) VALUES ('08', '90th Percentile Value in Lookback Period');
INSERT INTO camdecmpsmd.modc_code (modc_cd, modc_description) VALUES ('09', '95th Percentile Value in Lookback Period');
INSERT INTO camdecmpsmd.modc_code (modc_cd, modc_description) VALUES ('10', 'Maximum Value in Lookback Period');
INSERT INTO camdecmpsmd.modc_code (modc_cd, modc_description) VALUES ('11', 'Average Value in Lookback Period');
INSERT INTO camdecmpsmd.modc_code (modc_cd, modc_description) VALUES ('12', 'Maximum or Minimum Value from Default or Span Record');
INSERT INTO camdecmpsmd.modc_code (modc_cd, modc_description) VALUES ('13', 'Maximum Controlled Value from Default Record');
INSERT INTO camdecmpsmd.modc_code (modc_cd, modc_description) VALUES ('14', 'Diluent Cap Value');
INSERT INTO camdecmpsmd.modc_code (modc_cd, modc_description) VALUES ('15', '1.25 Times Maximum Value in Lookback Period');
INSERT INTO camdecmpsmd.modc_code (modc_cd, modc_description) VALUES ('16', 'SO2 Concentration When Very Low Sulfur Fuel Combusted');
INSERT INTO camdecmpsmd.modc_code (modc_cd, modc_description) VALUES ('17', 'Like-Kind Replacement Analyzer');
INSERT INTO camdecmpsmd.modc_code (modc_cd, modc_description) VALUES ('19', 'Default High Range Value Used');
INSERT INTO camdecmpsmd.modc_code (modc_cd, modc_description) VALUES ('20', '200% of Full Scale Range Used');
INSERT INTO camdecmpsmd.modc_code (modc_cd, modc_description) VALUES ('21', 'Negative Value Replaced with Zero');
INSERT INTO camdecmpsmd.modc_code (modc_cd, modc_description) VALUES ('22', 'Control Inlet Monitoring System');
INSERT INTO camdecmpsmd.modc_code (modc_cd, modc_description) VALUES ('23', 'Maximum Value when Emitting through Unmonitored Bypass Stack');
INSERT INTO camdecmpsmd.modc_code (modc_cd, modc_description) VALUES ('24', 'Maximum Controlled Value when Emitting through Unmonitored Bypass Stack');
INSERT INTO camdecmpsmd.modc_code (modc_cd, modc_description) VALUES ('25', 'NOx MER When Full-Scale Exceedance of NOx Concentration and Diluent Monitor Unavailable');
INSERT INTO camdecmpsmd.modc_code (modc_cd, modc_description) VALUES ('26', 'Zero or Negative Heat Input Rate Replaced with 1 mmBtu');
INSERT INTO camdecmpsmd.modc_code (modc_cd, modc_description) VALUES ('40', 'Fuel-Specific or Pro-Rated Default Value');
INSERT INTO camdecmpsmd.modc_code (modc_cd, modc_description) VALUES ('45', 'Maximum Rated Hourly Heat Input Rate (LME)');
INSERT INTO camdecmpsmd.modc_code (modc_cd, modc_description) VALUES ('53', 'Method Approved by Petition (Available Hours Included in Missing Data Lookback)');
INSERT INTO camdecmpsmd.modc_code (modc_cd, modc_description) VALUES ('54', 'Method Approved by Petition (Included in Missing Data Lookback)');
INSERT INTO camdecmpsmd.modc_code (modc_cd, modc_description) VALUES ('55', 'Method Approved by Petition (Not included in Missing Data Lookback)');
INSERT INTO camdecmpsmd.modc_code (modc_cd, modc_description) VALUES ('32', 'Hourly Hg concentration determined from analysis of a single sorbent trap multiplied by a factor of 1.111');
INSERT INTO camdecmpsmd.modc_code (modc_cd, modc_description) VALUES ('33', 'Hourly Hg concentration determined from the  sorbent trap with the higher Hg concentration  (relative deviation criterion for the paired traps is not met)');
INSERT INTO camdecmpsmd.modc_code (modc_cd, modc_description) VALUES ('34', 'Hourly Hg, HCl, or HF concentration missing or invalid.');
INSERT INTO camdecmpsmd.modc_code (modc_cd, modc_description) VALUES ('35', 'Hourly Hg, HCl, or HF concentration not monitored (flue gases routed through an unmonitored bypass stack).');
INSERT INTO camdecmpsmd.modc_code (modc_cd, modc_description) VALUES ('36', 'Hourly Hg, HCl, SO2, or HF emission rate calculated-- valid data obtained for pollutant concentration and for all essential auxiliary parameters.');
INSERT INTO camdecmpsmd.modc_code (modc_cd, modc_description) VALUES ('37', 'Hourly heat input-based Hg, HCl, SO2, or HF emission rate calculated for a startup or shutdown hour, using the diluent cap value.');
INSERT INTO camdecmpsmd.modc_code (modc_cd, modc_description) VALUES ('38', 'Hourly Hg, HCl, or HF emission rate not calculated-- valid concentration not available or substitute data reported for one or more essential auxiliary parameters.');
INSERT INTO camdecmpsmd.modc_code (modc_cd, modc_description) VALUES ('39', 'Hourly electric output-based Hg, HCl, SO2, or HF emission rate calculated for a startup or shutdown hour, using the default electrical load value.');
INSERT INTO camdecmpsmd.modc_code (modc_cd, modc_description) VALUES ('41', 'Hourly Hg concentration determined from two different pairs of sorbent traps during the hour. This code applies only to routine sorbent trap change outs during normal, day-to-day operation of the sorbent trap monitoring system.');
INSERT INTO camdecmpsmd.modc_code (modc_cd, modc_description) VALUES ('42', 'Hourly Hg concentration determined from two different pairs of sorbent traps during the hour.  This code applies only to sorbent trap change outs that occur during  RATA testing periods.');
INSERT INTO camdecmpsmd.modc_code (modc_cd, modc_description) VALUES ('43', 'Hourly Hg concentration determined by the Method Detection Level.');
INSERT INTO camdecmpsmd.modc_code (modc_cd, modc_description) VALUES ('44', 'Hourly Hg concentration determined from Method Detection Level of a single sorbent trap multiplied by a factor of 1.111');
