INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('AKSF', 'Appendix K Sample to Stack Flow Scaling Factor');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('BCO2', 'Biogenic CO2 Mass (ton)');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('CO2C', 'CO2 Concentration (pct)');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('CO2R', 'CO2 Emission Rate (ton/mmBtu)');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('CO2', 'CO2 Hourly Mass Rate (ton/hr)');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('CO2M', 'CO2 Mass (ton)');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('CO2X', 'CO2 Maximum Concentration (pct)');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('CO2N', 'CO2 Minimum Concentration (pct)');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('DENSOIL', 'Density of Oil');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('FC', 'F-Factor Carbon-based');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('FD', 'F-Factor Dry-basis');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('FW', 'F-Factor Wet-basis');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('FF2L', 'Fuel Flow to Load Rate');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('FGAS', 'Gas Hourly Flow Rate (hscf)');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('GCV', 'Gross Calorific Value for Oil or Gas');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('GHR', 'Gross Heat Rate');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('HCLRE', 'HCl Electrical Output Based Emissions Rate (lb/MWh)');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('HCLRH', 'HCl Heat Input Based Emissions Rate (lb/mmBtu)');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('HCLC', 'HCl concentration (ppm)');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('HFRE', 'HF Electrical Output Based Emissions Rate (lb/MWh)');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('HFRH', 'HF Heat Input Based Emissions Rate (lb/mmBtu)');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('HFC', 'HF concentration (ppm)');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('HI', 'Heat Input Rate (mmBtu/hr)');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('HIT', 'Heat Input Total (mmBtu)');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('HGC', 'Hg Concentration (ugscm)');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('HGRE', 'Hg Electrical Output Based Emission Rate');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('HGRH', 'Hg Heat Input Based Emission Rate');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('HCL', 'Hydrogen chloride');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('HF', 'Hydrogen fluoride');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('H2OX', 'Maximum Moisture (pct)');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('NOCX', 'Maximum NOx Concentration (ppm)');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('NORX', 'Maximum NOx Emission Rate (lb/mmBtu)');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('O2X', 'Maximum O2 Concentration (pct)');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('MHHI', 'Maximum Rated Hourly Heat Input Rate (mmBtu/hr)');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('SO2X', 'Maximum SO2 Concentration (ppm)');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('SORX', 'Maximum SO2 Emission Rate (lb/mmBtu)');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('FLOX', 'Maximum Stack Flow (scfh)');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('HG', 'Mercury');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('MNGF', 'Minimum Gas Flow Rate (hscf)');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('MNHI', 'Minimum Heat Input Rate (mmBtu/hr)');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('H2ON', 'Minimum Moisture (pct)');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('MNNX', 'Minimum NOx Emission Rate (lb/mmBtu)');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('O2N', 'Minimum O2 Concentration (pct)');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('MNOF', 'Minimum Oil Flow Rate');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('BWA', 'Moisture Fraction in Ambient Air');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('H2O', 'Moisture Percentage (pct)');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('NOXC', 'NOx Concentration (ppm)');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('NOXR', 'NOx Emission Rate (lb/mmBtu)');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('NOX', 'NOx Hourly Mass Rate (lb/hr)');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('NOXM', 'NOx Mass (lb)');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('OPHOURS', 'Number of Operating Hours');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('O2C', 'O2 Concentration (pct)');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('FOIL', 'Oil Flow Rate');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('OILM', 'Oil Mass Flow Rate (lb/hr)');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('VOIL', 'Oil Volume');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('OILV', 'Oil Volumetric Flow Rate');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('OP', 'Opacity');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('LOAD', 'Operating Load');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('OPTIME', 'Operating Time (hr)');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('PM', 'Particulate Matter');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('SO2C', 'SO2 Concentration (ppm)');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('SO2RE', 'SO2 Electrical Output Based Hourly Emission Rate (lb/MW-hr)');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('SO2RH', 'SO2 Heat Input Based Hourly Emission Rate (lb/mmBtu)');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('SO2R', 'SO2 Hourly  Emission Rate (lb/mmBtu)');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('SO2', 'SO2 Hourly Mass Rate (lb/hr)');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('SO2M', 'SO2 Mass (lb)');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('SGF', 'Sample Gas Flow');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('FLOW', 'Stack Flow (scfh)');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('SULFUR', 'Sulfur Content');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('PMC', 'PM Concentration (mg/acm)');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('PMCO', 'PM Concentration Parameter Output (mA, or other unit of measure)');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('PMRE', 'Gross Output-Based PM Emission Rate (lb/MWh)');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('PMRH', 'Heat Input-Based PM Emission Rate (lb/mmBtu)');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('PMPMA', 'PM Parametric Emissions (mA)');
INSERT INTO camdecmpsmd.parameter_code (parameter_cd, parameter_cd_description) VALUES ('PMPMC', 'PM Parametric Emissions (mg/acm)');
