INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('2', 'FLOW RM 2 (no WAF)', 'FLOW');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('20', 'NOX RM 20', 'NOXC');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('20,3', 'NOX RM 20 and CO2/O2 RM 3', 'NOX,NOXP');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('20,3A', 'NOX RM 20 and CO2/O2 RM 3A', 'NOX,NOXP');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('20,3B', 'NOX RM 20 and CO2/O2 RM 3B', 'NOX,NOXP');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('2F', 'FLOW RM 2F (no WAF)', 'FLOW');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('2FH', 'FLOW RM 2F with WAF from 2H', 'FLOW');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('2FJ', 'FLOW RM 2F with WAF from CTM-041', 'FLOW');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('2G', 'FLOW RM 2G (no WAF)', 'FLOW');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('2GH', 'FLOW RM 2G with WAF from 2H', 'FLOW');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('2GJ', 'FLOW RM 2G with WAF from CTM-041', 'FLOW');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('2J', 'FLOW RM 2 with WAF from CTM-041', 'FLOW');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('3', 'CO2 or O2 RM 3', 'CO2,O2');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('3A', 'CO2 or O2 RM 3A', 'CO2,O2');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('3B', 'CO2 or O2 RM 3B', 'CO2,O2');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('4', 'H2O RM 4', 'H2O,H2OM');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('6', 'SO2 RM 6', 'SO2');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('6,3', 'SO2 RM 6 and CO2/O2 RM 3', 'SO2R');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('6,3A', 'SO2 RM 6 and CO2/O2 RM 3A', 'SO2R');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('6,3B', 'SO2 RM 6 and CO2/O2 RM 3B', 'SO2R');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('6A', 'SO2 RM 6A', 'SO2');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('6A,3', 'SO2 RM 6A and CO2/O2 RM 3', 'SO2R');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('6A,3A', 'SO2 RM 6A and CO2/O2 RM 3A', 'SO2R');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('6A,3B', 'SO2 RM 6A and CO2/O2 RM 3B', 'SO2R');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('6C', 'SO2 RM 6C', 'SO2');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('6C,3', 'SO2 RM 6C and CO2/O2 RM 3', 'SO2R');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('6C,3A', 'SO2 RM 6C and CO2/O2 RM 3A', 'SO2R');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('6C,3B', 'SO2 RM 6C and CO2/O2 RM 3B', 'SO2R');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('7', 'NOX RM 7', 'NOXC');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('7,3', 'NOX RM 7 and CO2/O2 RM 3', 'NOX,NOXP');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('7,3A', 'NOX RM 7 and CO2/O2 RM 3A', 'NOX,NOXP');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('7,3B', 'NOX RM 7 and CO2/O2 RM 3B', 'NOX,NOXP');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('7A', 'NOX RM 7A', 'NOXC');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('7A,3', 'NOX RM 7A and CO2/O2 RM 3', 'NOX,NOXP');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('7A,3A', 'NOX RM 7A and CO2/O2 RM 3A', 'NOX,NOXP');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('7A,3B', 'NOX RM 7A and CO2/O2 RM 3B', 'NOX,NOXP');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('7C', 'NOX RM 7C', 'NOXC');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('7C,3', 'NOX RM 7C and CO2/O2 RM 3', 'NOX,NOXP');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('7C,3A', 'NOX RM 7C and CO2/O2 RM 3A', 'NOX,NOXP');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('7C,3B', 'NOX RM 7C and CO2/O2 RM 3B', 'NOX,NOXP');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('7D', 'NOX RM 7D', 'NOXC');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('7D,3', 'NOX RM 7D and CO2/O2 RM 3', 'NOX,NOXP');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('7D,3A', 'NOX RM 7D and CO2/O2 RM 3A', 'NOX,NOXP');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('7D,3B', 'NOX RM 7D and CO2/O2 RM 3B', 'NOX,NOXP');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('7E', 'NOX RM 7E', 'NOXC');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('7E,3', 'NOX RM 7E and CO2/O2 RM 3', 'NOX,NOXP');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('7E,3A', 'NOX RM 7E and CO2/O2 RM 3A', 'NOX,NOXP');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('7E,3B', 'NOX RM 7E and CO2/O2 RM 3B', 'NOX,NOXP');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('D2H', 'FLOW RM 2 with Default WAF from 2H', 'FLOW');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('M2H', 'FLOW RM 2 with Measured WAF from 2H', 'FLOW');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('29', 'Hg RM 29 (Appendix A-8 to Part 60)', 'HG,ST');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('30A', 'Hg RM 30A Instrumental (Appendix A-8 to Part 60)', 'HG,ST');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('30B', 'Hg RM 30B Sorbent Trap (Appendix A-8 to Part 60)', 'HG,ST');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('OH', 'Hg Ontario Hydro Method (ASTM D6784-02)', 'HG,ST');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('26', 'EPA Method 26 in Appendix A-8 to 40 CFR Part 60', 'HCL,HF');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('26A', 'EPA Method 26A in Appendix A-8 to 40 CFR Part 60', 'HCL,HF');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('320', 'EPA Method 320 in Appendix A to 40 CFR Part 63', 'HCL,HF');
INSERT INTO camdecmpsmd.ref_method_code (ref_method_cd, ref_method_cd_description, parameter_cd) VALUES ('D6348', 'ASTM D6348-03 (Reapproved 2010) "Standard Test Method for Determination of Gaseous Compounds by Extractive Direct Interface Fourier Transform Infrared (FTIR) Spectroscopy"', 'HCL,HF');
