INSERT INTO camdecmpsmd.required_test_code (required_test_cd, required_test_cd_description) VALUES ('3', '3-load RATA, 7-day Calibration Error Test, DAHS Verification');
INSERT INTO camdecmpsmd.required_test_code (required_test_cd, required_test_cd_description) VALUES ('53', 'Fuel Flowmeter Transmitter Test');
INSERT INTO camdecmpsmd.required_test_code (required_test_cd, required_test_cd_description) VALUES ('17', 'Linearity Check, Cycle Time Test');
INSERT INTO camdecmpsmd.required_test_code (required_test_cd, required_test_cd_description) VALUES ('16', 'Normal Load RATA, Cycle Time Test');
INSERT INTO camdecmpsmd.required_test_code (required_test_cd, required_test_cd_description) VALUES ('42', 'Stack Exit Correction Factor');
INSERT INTO camdecmpsmd.required_test_code (required_test_cd, required_test_cd_description) VALUES ('10', 'Linearity Check, 7-day Calibration Error Test');
INSERT INTO camdecmpsmd.required_test_code (required_test_cd, required_test_cd_description) VALUES ('51', 'Fuel Flowmeter Accuracy Test');
INSERT INTO camdecmpsmd.required_test_code (required_test_cd, required_test_cd_description) VALUES ('30', 'Normal Load RATA, 7-Day Calibration Error Test, Linearity Check, Cycle Time Test, 3-point System Integrity Check');
INSERT INTO camdecmpsmd.required_test_code (required_test_cd, required_test_cd_description) VALUES ('99', 'Other');
INSERT INTO camdecmpsmd.required_test_code (required_test_cd, required_test_cd_description) VALUES ('21', 'DAHS Verification (Missing Data Routines)');
INSERT INTO camdecmpsmd.required_test_code (required_test_cd, required_test_cd_description) VALUES ('32', 'Normal Load RATA, 7-Day Calibration Error Test, Linearity Check, 3-point System Integrity Check');
INSERT INTO camdecmpsmd.required_test_code (required_test_cd, required_test_cd_description) VALUES ('28', 'Abbreviated Stack Flow-to-load Ratio Test, Leak Check');
INSERT INTO camdecmpsmd.required_test_code (required_test_cd, required_test_cd_description) VALUES ('52', 'Fuel Flowmeter Transmitter Test, Primary Element Inspection');
INSERT INTO camdecmpsmd.required_test_code (required_test_cd, required_test_cd_description) VALUES ('23', 'DAHS Verification (Formulas and Missing Data), Daily Calibration Error Test');
INSERT INTO camdecmpsmd.required_test_code (required_test_cd, required_test_cd_description) VALUES ('76', 'Unit Default Test (NOx)');
INSERT INTO camdecmpsmd.required_test_code (required_test_cd, required_test_cd_description) VALUES ('9', 'Linearity Check');
INSERT INTO camdecmpsmd.required_test_code (required_test_cd, required_test_cd_description) VALUES ('81', 'PEMS Daily QA/QC, 3-Run RATA with RM or Portable Analyzer');
INSERT INTO camdecmpsmd.required_test_code (required_test_cd, required_test_cd_description) VALUES ('13', 'Normal Load RATA, 7-day Calibration Error Test, Cycle Time Test');
INSERT INTO camdecmpsmd.required_test_code (required_test_cd, required_test_cd_description) VALUES ('18', '7-day Calibration Error Test');
INSERT INTO camdecmpsmd.required_test_code (required_test_cd, required_test_cd_description) VALUES ('31', '          Normal Load RATA, Linearity Check, Cycle Time Test, 3-point System Integrity Check');
INSERT INTO camdecmpsmd.required_test_code (required_test_cd, required_test_cd_description) VALUES ('80', 'PEMS Sensor Validations, Daily QA/QC, Statistical Tests, 3-Load RATA');
INSERT INTO camdecmpsmd.required_test_code (required_test_cd, required_test_cd_description) VALUES ('34', 'Linearity Check, Single-point System Integrity Check');
INSERT INTO camdecmpsmd.required_test_code (required_test_cd, required_test_cd_description) VALUES ('5', 'Normal Load RATA');
INSERT INTO camdecmpsmd.required_test_code (required_test_cd, required_test_cd_description) VALUES ('27', '3-load RATA, 7-day Calibration Error Test, Leak Check');
INSERT INTO camdecmpsmd.required_test_code (required_test_cd, required_test_cd_description) VALUES ('55', 'Abbreviated Fuel Flow-to-load Test');
INSERT INTO camdecmpsmd.required_test_code (required_test_cd, required_test_cd_description) VALUES ('1', '3-load RATA, 7-day Calibration Error Test');
INSERT INTO camdecmpsmd.required_test_code (required_test_cd, required_test_cd_description) VALUES ('19', 'Cycle Time Test');
INSERT INTO camdecmpsmd.required_test_code (required_test_cd, required_test_cd_description) VALUES ('40', 'Angle of View, Angle of Projection, Mean Spectral Response, Response Time, Calibration Drift Test, Stack Exit Correction Factor');
INSERT INTO camdecmpsmd.required_test_code (required_test_cd, required_test_cd_description) VALUES ('75', 'Appendix E Test');
INSERT INTO camdecmpsmd.required_test_code (required_test_cd, required_test_cd_description) VALUES ('15', 'Normal Load RATA, 7-day Calibration Error Test, Leak Check');
INSERT INTO camdecmpsmd.required_test_code (required_test_cd, required_test_cd_description) VALUES ('24', 'Off-line Calibration Demonstration');
INSERT INTO camdecmpsmd.required_test_code (required_test_cd, required_test_cd_description) VALUES ('25', 'Off-line Calibration Demonstration, 7-day Calibration Error Test');
INSERT INTO camdecmpsmd.required_test_code (required_test_cd, required_test_cd_description) VALUES ('26', 'Abbreviated Stack Flow-to-load Ratio Test');
INSERT INTO camdecmpsmd.required_test_code (required_test_cd, required_test_cd_description) VALUES ('7', '2-load Flow RATA');
INSERT INTO camdecmpsmd.required_test_code (required_test_cd, required_test_cd_description) VALUES ('33', 'Normal Load RATA, Linearity Check, 3-point System Integrity Check');
INSERT INTO camdecmpsmd.required_test_code (required_test_cd, required_test_cd_description) VALUES ('57', 'Primary Element Inspection, Re-determine Flow Coefficients');
INSERT INTO camdecmpsmd.required_test_code (required_test_cd, required_test_cd_description) VALUES ('20', 'DAHS Verification (Formulas)');
INSERT INTO camdecmpsmd.required_test_code (required_test_cd, required_test_cd_description) VALUES ('82', 'PEMS Daily QA/QC');
INSERT INTO camdecmpsmd.required_test_code (required_test_cd, required_test_cd_description) VALUES ('29', 'Leak Check (Differential Pressure Monitors Only)');
INSERT INTO camdecmpsmd.required_test_code (required_test_cd, required_test_cd_description) VALUES ('4', 'Normal Load RATA, 7-day Calibration Error Test, Linearity Check, Cycle Time Test, DAHS Verification');
INSERT INTO camdecmpsmd.required_test_code (required_test_cd, required_test_cd_description) VALUES ('11', 'Normal Load RATA, 7-day Calibration Error Test, Linearity Check');
INSERT INTO camdecmpsmd.required_test_code (required_test_cd, required_test_cd_description) VALUES ('6', '3-load Flow RATA');
INSERT INTO camdecmpsmd.required_test_code (required_test_cd, required_test_cd_description) VALUES ('14', '7-day Calibration Error Test, Cycle Time Test');
INSERT INTO camdecmpsmd.required_test_code (required_test_cd, required_test_cd_description) VALUES ('12', 'Normal Load RATA, Linearity Check, Cycle Time Test');
INSERT INTO camdecmpsmd.required_test_code (required_test_cd, required_test_cd_description) VALUES ('54', 'Primary Fuel Flowmeter Element Inspection');
INSERT INTO camdecmpsmd.required_test_code (required_test_cd, required_test_cd_description) VALUES ('77', 'Hg LME Default Test');
INSERT INTO camdecmpsmd.required_test_code (required_test_cd, required_test_cd_description) VALUES ('56', 'Fuel Flowmeter Transmitter Test, Primary Element Inspection, Re-determine Flow Coefficients');
INSERT INTO camdecmpsmd.required_test_code (required_test_cd, required_test_cd_description) VALUES ('2', 'Normal Load RATA, 7-day Calibration Error Test, Linearity Check, Cycle Time Test');
INSERT INTO camdecmpsmd.required_test_code (required_test_cd, required_test_cd_description) VALUES ('22', 'DAHS Verification (Formulas and Missing Data)');
INSERT INTO camdecmpsmd.required_test_code (required_test_cd, required_test_cd_description) VALUES ('8', 'Normal Load RATA, Linearity Check');
