INSERT INTO camdecmpsmd.system_parameter (sys_param_id, sys_param_name, param_name1, param_value1, param_name2, param_value2, param_name3, param_value3, param_name4, param_value4, param_name5, param_value5, notes) OVERRIDING SYSTEM VALUE VALUES (1, 'CLIENT_SETTINGS', 'RequirePasswordFlg', '0', 'HostAutoLoginFlg', '1', NULL, NULL, NULL, NULL, NULL, NULL, 'The system settings for the ECMPS Client Tool');
INSERT INTO camdecmpsmd.system_parameter (sys_param_id, sys_param_name, param_name1, param_value1, param_name2, param_value2, param_name3, param_value3, param_name4, param_value4, param_name5, param_value5, notes) OVERRIDING SYSTEM VALUE VALUES (2, 'DB_SETTINGS', 'DatabasePrefix', 'CHV-DWHITTEN2', 'IsSharedDB', '0', 'UTC_Conversion', '1', NULL, NULL, NULL, NULL, 'The database settings for the Client Tool');
INSERT INTO camdecmpsmd.system_parameter (sys_param_id, sys_param_name, param_name1, param_value1, param_name2, param_value2, param_name3, param_value3, param_name4, param_value4, param_name5, param_value5, notes) OVERRIDING SYSTEM VALUE VALUES (3, 'ADD_EDIT_MESSAGES', 'AddNewStackPipe', 'Successfully inserted new Stack/Pipe record. You should now assign any associated Units.', 'DeleteSubmittedTest', 'Warning: Removing this test from your Client Tool will not remove the test record from the EPA Host System.', 'DeleteSubmittedTEE', 'This record cannot be deleted because it already has been submitted. Contact EPA for permission to delete this record.', 'DeleteSubmittedEvent', 'This record cannot be deleted because it already has been submitted. Contact EPA for permission to delete this record.', 'CantDeleteThing', 'You cannot remove this <thing> record.', 'Messages used by the Add/Edit procedures');
INSERT INTO camdecmpsmd.system_parameter (sys_param_id, sys_param_name, param_name1, param_value1, param_name2, param_value2, param_name3, param_value3, param_name4, param_value4, param_name5, param_value5, notes) OVERRIDING SYSTEM VALUE VALUES (4, 'CAMD_CONTACT_INFO', 'InitialUserProfile', 'If you do not have a CBS User Name and password, please contact {0} for assistance.', 'GeneralErrors', 'ECMPS Technical Support: (866) 470-0636', 'CAMD_Contacts', 'CAMD at CAMDForms@epa.gov', NULL, NULL, NULL, NULL, 'Messages with CAMD contact info');
INSERT INTO camdecmpsmd.system_parameter (sys_param_id, sys_param_name, param_name1, param_value1, param_name2, param_value2, param_name3, param_value3, param_name4, param_value4, param_name5, param_value5, notes) OVERRIDING SYSTEM VALUE VALUES (5, 'HOST_SETTINGS', 'ThisHost', 'ecmps.epa.gov/', 'EPA_Prod', 'ecmps.epa.gov/', 'EPA_Test', 'ecmps.epa.gov/ECMPST', NULL, NULL, NULL, NULL, NULL);
INSERT INTO camdecmpsmd.system_parameter (sys_param_id, sys_param_name, param_name1, param_value1, param_name2, param_value2, param_name3, param_value3, param_name4, param_value4, param_name5, param_value5, notes) OVERRIDING SYSTEM VALUE VALUES (6, 'REPORT_SETTINGS', 'Hyperlink', 'http://ecmps.camdsupport.com/learn_docs.shtml?CHECK_CATALOG_ID=', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO camdecmpsmd.system_parameter (sys_param_id, sys_param_name, param_name1, param_value1, param_name2, param_value2, param_name3, param_value3, param_name4, param_value4, param_name5, param_value5, notes) OVERRIDING SYSTEM VALUE VALUES (10, 'PGVP_AETB_RULE_DATE', 'RuleDate', '03/28/2011', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO camdecmpsmd.system_parameter (sys_param_id, sys_param_name, param_name1, param_value1, param_name2, param_value2, param_name3, param_value3, param_name4, param_value4, param_name5, param_value5, notes) OVERRIDING SYSTEM VALUE VALUES (11, 'EXPORT_SETTINGS', 'XSLT_Location_MP', 'http://ecmps.camdsupport.com/documents/ECMPS_MonitoringPlan.xslt', 'XSLT_Location_QA', NULL, 'XSLT_Location_EM', 'http://ecmps.camdsupport.com/documents/ECMPS_Emissions.xslt', NULL, NULL, NULL, NULL, 'Location of the XSLT files for the XML Transformations');
INSERT INTO camdecmpsmd.system_parameter (sys_param_id, sys_param_name, param_name1, param_value1, param_name2, param_value2, param_name3, param_value3, param_name4, param_value4, param_name5, param_value5, notes) OVERRIDING SYSTEM VALUE VALUES (12, 'MATS_RULE', 'ComplianceDeadline', '09/13/2015', 'DailyCalibrationRequiredDatehour', '09/13/2015 00:00:00', 'Mats2.0Date', '01/01/2024', NULL, NULL, NULL, NULL, NULL);
