INSERT INTO camdecmpsmd.system_type_code (sys_type_cd, sys_type_description, parameter_cd) VALUES ('CO2', 'CO2 Concentration', 'CO2C');
INSERT INTO camdecmpsmd.system_type_code (sys_type_cd, sys_type_description, parameter_cd) VALUES ('FLOW', 'Stack Flow', 'FLOW');
INSERT INTO camdecmpsmd.system_type_code (sys_type_cd, sys_type_description, parameter_cd) VALUES ('GAS', 'Gas Fuel Flow', 'FGAS');
INSERT INTO camdecmpsmd.system_type_code (sys_type_cd, sys_type_description, parameter_cd) VALUES ('H2O', 'Moisture (O2 Wet and Dry)', 'H2O');
INSERT INTO camdecmpsmd.system_type_code (sys_type_cd, sys_type_description, parameter_cd) VALUES ('H2OM', 'Moisture Sensor', 'H2O');
INSERT INTO camdecmpsmd.system_type_code (sys_type_cd, sys_type_description, parameter_cd) VALUES ('H2OT', 'Moisture Table', 'H2O');
INSERT INTO camdecmpsmd.system_type_code (sys_type_cd, sys_type_description, parameter_cd) VALUES ('HG', 'Hg Concentration CEMS', 'HGC');
INSERT INTO camdecmpsmd.system_type_code (sys_type_cd, sys_type_description, parameter_cd) VALUES ('LTGS', 'Long-term Gas Fuel Flow', 'FGAS');
INSERT INTO camdecmpsmd.system_type_code (sys_type_cd, sys_type_description, parameter_cd) VALUES ('LTOL', 'Long-term Oil Fuel Flow', 'FOIL');
INSERT INTO camdecmpsmd.system_type_code (sys_type_cd, sys_type_description, parameter_cd) VALUES ('NOX', 'NOx Emission Rate', 'NOXR');
INSERT INTO camdecmpsmd.system_type_code (sys_type_cd, sys_type_description, parameter_cd) VALUES ('NOXC', 'NOx Concentration', 'NOXC');
INSERT INTO camdecmpsmd.system_type_code (sys_type_cd, sys_type_description, parameter_cd) VALUES ('NOXE', 'NOx Appendix E', 'NOXR');
INSERT INTO camdecmpsmd.system_type_code (sys_type_cd, sys_type_description, parameter_cd) VALUES ('NOXP', 'NOx PEMS', 'NOXR');
INSERT INTO camdecmpsmd.system_type_code (sys_type_cd, sys_type_description, parameter_cd) VALUES ('O2', 'O2 Concentration', 'O2C');
INSERT INTO camdecmpsmd.system_type_code (sys_type_cd, sys_type_description, parameter_cd) VALUES ('OILM', 'Mass of Oil Fuel Flow', 'OILM');
INSERT INTO camdecmpsmd.system_type_code (sys_type_cd, sys_type_description, parameter_cd) VALUES ('OILV', 'Volumetric Oil Fuel Flow', 'OILV');
INSERT INTO camdecmpsmd.system_type_code (sys_type_cd, sys_type_description, parameter_cd) VALUES ('OP', 'Opacity', 'OP');
INSERT INTO camdecmpsmd.system_type_code (sys_type_cd, sys_type_description, parameter_cd) VALUES ('PM', 'Particulate Matter', 'PM');
INSERT INTO camdecmpsmd.system_type_code (sys_type_cd, sys_type_description, parameter_cd) VALUES ('SO2', 'SO2 Concentration', 'SO2C');
INSERT INTO camdecmpsmd.system_type_code (sys_type_cd, sys_type_description, parameter_cd) VALUES ('HCL', 'HCl Concentration CEMS', 'HCL');
INSERT INTO camdecmpsmd.system_type_code (sys_type_cd, sys_type_description, parameter_cd) VALUES ('HF', 'HF Concentration CEMS', 'HF');
INSERT INTO camdecmpsmd.system_type_code (sys_type_cd, sys_type_description, parameter_cd) VALUES ('ST', 'Sorbent Trap Monitoring System', 'HG');
INSERT INTO camdecmpsmd.system_type_code (sys_type_cd, sys_type_description, parameter_cd) VALUES ('CPMS', 'Particulate Matter Parametric Monitoring System', 'PMCO');
