INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('7DAY', '7-Day Calibration', 'CALINJ');
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('CYCLE', 'Cycle Time Test', 'CYCSUM');
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('LINE', 'Linearity Check', 'LINSUM');
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('RATA', 'Relative Accuracy Test', 'RELACC');
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('F2LREF', 'Flow-to-Load or GHR Reference Data', 'FLR');
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('F2LCHK', 'Flow-to-Load Ratio or GHR Test', 'FLC');
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('ONOFF', 'On-Line/Off-Line Calibration', 'OLOLCAL');
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('APPE', 'Appendix E NOx Rate Test', 'APPESUM');
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('FFACC', 'Fuel Flowmeter Accuracy Test', 'FFACC');
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('FFACCTT', 'Transmitter Transducer Test', 'TTACC');
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('FF2LBAS', 'Fuel Flow-to-Load Baseline Data', 'FFLB');
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('FF2LTST', 'Fuel Flow-to-Load Test', 'FFL');
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('UNITDEF', 'Unit-Specific Default NOx Rate Test', 'LME');
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('PEI', 'Primary Element Inspection', 'PEI');
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('HGLINE', 'Mercury Linearity', 'HGL3LS');
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('HGSI3', 'Three-Point Hg System Integrity Check', 'HGL3LS');
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('DAHS', 'DAHS Verification', 'MISC');
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('LEAK', 'Leak Check', 'MISC');
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('OTHER', 'Other Test', 'MISC');
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('PEMSACC', 'PEMS Accuracy Check', 'MISC');
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('DGFMCAL', 'Dry Gas Meter Calibration (Sorbent Trap Monitoring System)', 'MISC');
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('MFMCAL', 'Mass Flow Meter Calibration (Sorbent Trap Monitoring System)', 'MISC');
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('BCAL', 'Barometer calibration (sorbent trap monitoring systems)', 'MISC');
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('QGA', 'Quarterly Gas Audit (HCl and HF monitoring systems)', 'MISC');
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('TSCAL', 'Temperature sensor calibration (sorbent trap monitoring systems)', 'MISC');
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('DAYCAL', 'Daily Calibration', NULL);
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('INTCHK', 'Flow Interference Check', NULL);
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('PEMSCAL', 'Daily PEMS Calibration', NULL);
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('AF2LCHK', 'Abbreviated Flow-to-Load Check', NULL);
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('HGSI1', 'One-Point Hg System Integrity Check', NULL);

