INSERT INTO camdecmpsmd.test_type_group_code (test_type_group_cd, test_type_group_cd_description, child_depth) VALUES ('APPE', 'Appendix E Correlation Test', 4);
INSERT INTO camdecmpsmd.test_type_group_code (test_type_group_cd, test_type_group_cd_description, child_depth) VALUES ('7DAY', '7-Day Calibration Error Test', 2);
INSERT INTO camdecmpsmd.test_type_group_code (test_type_group_cd, test_type_group_cd_description, child_depth) VALUES ('CYCLE', 'Cycle Time Test', 3);
INSERT INTO camdecmpsmd.test_type_group_code (test_type_group_cd, test_type_group_cd_description, child_depth) VALUES ('F2LCHK', 'Flow-to-Load Check', 2);
INSERT INTO camdecmpsmd.test_type_group_code (test_type_group_cd, test_type_group_cd_description, child_depth) VALUES ('F2LREF', 'Flow-to-Load Reference', 2);
INSERT INTO camdecmpsmd.test_type_group_code (test_type_group_cd, test_type_group_cd_description, child_depth) VALUES ('FF2LBAS', 'Fuel Flow-to-Load Baseline', 2);
INSERT INTO camdecmpsmd.test_type_group_code (test_type_group_cd, test_type_group_cd_description, child_depth) VALUES ('FF2LTST', 'Fuel Flow-to-Load Test', 2);
INSERT INTO camdecmpsmd.test_type_group_code (test_type_group_cd, test_type_group_cd_description, child_depth) VALUES ('FFACC', 'Fuel Flowmeter Accuracy Test', 2);
INSERT INTO camdecmpsmd.test_type_group_code (test_type_group_cd, test_type_group_cd_description, child_depth) VALUES ('HGTEST', 'Hg Linearity and 3-Level System Integrity Check Data', 3);
INSERT INTO camdecmpsmd.test_type_group_code (test_type_group_cd, test_type_group_cd_description, child_depth) VALUES ('LINE', 'Linearity Check Data', 3);
INSERT INTO camdecmpsmd.test_type_group_code (test_type_group_cd, test_type_group_cd_description, child_depth) VALUES ('ONOFF', 'Online Offline Calibration Error Demonstration', 2);
INSERT INTO camdecmpsmd.test_type_group_code (test_type_group_cd, test_type_group_cd_description, child_depth) VALUES ('RATA', 'Relative Accuracy Test (RATA)', 6);
INSERT INTO camdecmpsmd.test_type_group_code (test_type_group_cd, test_type_group_cd_description, child_depth) VALUES ('FFACCTT', 'Transmitter Transducer Test', 2);
INSERT INTO camdecmpsmd.test_type_group_code (test_type_group_cd, test_type_group_cd_description, child_depth) VALUES ('PEI', 'Primary Element Inspection', 1);
INSERT INTO camdecmpsmd.test_type_group_code (test_type_group_cd, test_type_group_cd_description, child_depth) VALUES ('UNITDEF', 'Unit Default Test', 3);
INSERT INTO camdecmpsmd.test_type_group_code (test_type_group_cd, test_type_group_cd_description, child_depth) VALUES ('MISC', 'Miscellaneous', 1);
