INSERT INTO camdecmpsmd.test_type_group_code (test_type_group_cd, test_type_group_cd_description, child_depth) VALUES ('APPESUM', 'Appendix E Correlation Test', 4);
INSERT INTO camdecmpsmd.test_type_group_code (test_type_group_cd, test_type_group_cd_description, child_depth) VALUES ('CALINJ', '7-Day Calibration Error Test', 2);
INSERT INTO camdecmpsmd.test_type_group_code (test_type_group_cd, test_type_group_cd_description, child_depth) VALUES ('CYCSUM', 'Cycle Time Test', 3);
INSERT INTO camdecmpsmd.test_type_group_code (test_type_group_cd, test_type_group_cd_description, child_depth) VALUES ('FLC', 'Flow-to-Load Check', 2);
INSERT INTO camdecmpsmd.test_type_group_code (test_type_group_cd, test_type_group_cd_description, child_depth) VALUES ('FLR', 'Flow-to-Load Reference', 2);
INSERT INTO camdecmpsmd.test_type_group_code (test_type_group_cd, test_type_group_cd_description, child_depth) VALUES ('FFLB', 'Fuel Flow-to-Load Baseline', 2);
INSERT INTO camdecmpsmd.test_type_group_code (test_type_group_cd, test_type_group_cd_description, child_depth) VALUES ('FFL', 'Fuel Flow-to-Load Test', 2);
INSERT INTO camdecmpsmd.test_type_group_code (test_type_group_cd, test_type_group_cd_description, child_depth) VALUES ('FFACC', 'Fuel Flowmeter Accuracy Test', 2);
INSERT INTO camdecmpsmd.test_type_group_code (test_type_group_cd, test_type_group_cd_description, child_depth) VALUES ('HGL3LS', 'Hg Linearity and 3-Level System Integrity Check Data', 3);
INSERT INTO camdecmpsmd.test_type_group_code (test_type_group_cd, test_type_group_cd_description, child_depth) VALUES ('LINSUM', 'Linearity Check Data', 3);
INSERT INTO camdecmpsmd.test_type_group_code (test_type_group_cd, test_type_group_cd_description, child_depth) VALUES ('OLOLCAL', 'Online Offline Calibration Error Demonstration', 2);
INSERT INTO camdecmpsmd.test_type_group_code (test_type_group_cd, test_type_group_cd_description, child_depth) VALUES ('RELACC', 'Relative Accuracy Test (RATA)', 6);
INSERT INTO camdecmpsmd.test_type_group_code (test_type_group_cd, test_type_group_cd_description, child_depth) VALUES ('TTACC', 'Transmitter Transducer Test', 2);
INSERT INTO camdecmpsmd.test_type_group_code (test_type_group_cd, test_type_group_cd_description, child_depth) VALUES ('PEI', 'Primary Element Inspection', 1);
INSERT INTO camdecmpsmd.test_type_group_code (test_type_group_cd, test_type_group_cd_description, child_depth) VALUES ('LME', 'Unit Default Test (LME)', 3);
INSERT INTO camdecmpsmd.test_type_group_code (test_type_group_cd, test_type_group_cd_description, child_depth) VALUES ('MISC', 'Miscellaneous', 1);
