INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('7DAY', '7-Day Calibration', '7DAY');
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('CYCLE', 'Cycle Time Test', 'CYCLE');
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('LINE', 'Linearity Check', 'LINE');
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('RATA', 'Relative Accuracy Test', 'RATA');
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('F2LREF', 'Flow-to-Load or GHR Reference Data', 'F2LREF');
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('F2LCHK', 'Flow-to-Load Ratio or GHR Test', 'F2LCHK');
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('ONOFF', 'On-Line/Off-Line Calibration', 'ONOFF');
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('APPE', 'Appendix E NOx Rate Test', 'APPE');
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('FFACC', 'Fuel Flowmeter Accuracy Test', 'FFACC');
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('FFACCTT', 'Transmitter Transducer Test', 'FFACCTT');
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('FF2LBAS', 'Fuel Flow-to-Load Baseline Data', 'FF2LBAS');
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('FF2LTST', 'Fuel Flow-to-Load Test', 'FF2LTST');
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('UNITDEF', 'Unit-Specific Default NOx Rate Test', 'UNITDEF');
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('PEI', 'Primary Element Inspection', 'PEI');
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('HGLINE', 'Mercury Linearity', 'HGTEST');
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('HGSI3', 'Three-Point Hg System Integrity Check', 'HGTEST');
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('DAHS', 'DAHS Verification', 'MISC');
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('LEAK', 'Leak Check', 'MISC');
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('OTHER', 'Other Test', 'MISC');
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('PEMSACC', 'PEMS Accuracy Check', 'MISC');
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('DGFMCAL', 'Dry Gas Meter Calibration (Sorbent Trap Monitoring System)', 'MISC');
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('MFMCAL', 'Mass Flow Meter Calibration (Sorbent Trap Monitoring System)', 'MISC');
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('BCAL', 'Barometer calibration (sorbent trap monitoring systems)', 'MISC');
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('QGA', 'Quarterly Gas Audit (HCl and HF monitoring systems)', 'MISC');
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('TSCAL', 'Temperature sensor calibration (sorbent trap monitoring systems)', 'MISC');
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('DAYCAL', 'Daily Calibration', NULL);
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('INTCHK', 'Flow Interference Check', NULL);
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('PEMSCAL', 'Daily PEMS Calibration', NULL);
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('AF2LCHK', 'Abbreviated Flow-to-Load Check', NULL);
INSERT INTO camdecmpsmd.test_type_code (test_type_cd, test_type_cd_description, group_cd) VALUES ('HGSI1', 'One-Point Hg System Integrity Check', NULL);

