INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('1', '100 Standard Cubic Feet / Hour per Megawatt');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('2', '100 Standard Cubic Feet / Hour per 1000 Pounds / Hour of Steam Load');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('3', 'Pounds / Hour per Megawatt');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('4', 'Pounds / Hour per 1000 Pounds / Hour of Steam Load');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('5', 'Gallons / Hour per Megawatt');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('6', 'Gallons / Hour per 1000 Pounds / Hour of Steam Load');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('7', '100 Standard Cubic Feet / Hour per mmBtu / Hour of Steam Load');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('8', 'Pounds / Hour per mmBtu / Hour of Steam Load');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('9', 'Gallons / Hour per mmBtu / Hour of Steam Load');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('ACFH', 'Actual Cubic Feet of Stack Flow / Hour');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('ACFM', 'Actual Cubic Feet of Stack Flow / Minute');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('AFPM', 'Actual Feet of Stack Flow / Minute');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('AMSEC', 'Actual Meters of Stack Flow / Second');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('BBL', 'Barrel');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('BBLHR', 'Barrels / Hour');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('BTUBBL', 'BTU per Barrel');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('BTUGAL', 'BTU per Gallon');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('BTUHSCF', 'BTU per 100 Standard Cubic Feet');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('BTUKBTU', 'mmBTU per mmBTU of Steam Load times 1000');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('BTUKWH', 'BTU per Kilowatt Hour');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('BTULB', 'BTU per Pound');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('BTUM3', 'BTU per Cubic Meter');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('BTUSCF', 'BTU per Standard Cubic Feet');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('GAL', 'Gallon');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('GALHR', 'Gallons / Hour');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('GRHSCF', 'Grains / 100 Standard Cubic Feet');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('HR', 'Hours');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('HSCF', 'Hundred Standard Cubic Feet / Hour');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('INH2O', 'Inches of Water');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('KACFH', 'Thousand Actual Cubic Feet of Stack Flow / Hour');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('KACFM', 'Thousand Actual Cubic Feet of Stack Flow / Minute');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('KAFPM', 'Thousand Actual Feet of Stack Flow / Minute');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('KLBHR', '1000 Pounds Steam Load / Hour');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('KSCFH', 'Thousand Standard Cubic Feet of Stack Flow / Hour');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('KSCFM', 'Thousand Standard Cubic Feet of Stack Flow / Minute');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('KSFPM', 'Thousand Standard Feet of Stack Flow / Minute');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('LB', 'Pounds');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('LBBBL', 'Pounds per Barrel');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('LBGAL', 'Pounds per Gallon');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('LBHR', 'Pounds / Hour');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('LBM3', 'Pounds per Cubic Meter');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('LBMMBTU', 'Pounds / mmBtu');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('LBSCF', 'Pounds per Standard Cubic Feet');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('M3', 'Cubic Meter');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('M3HR', 'Cubic Meters / Hour');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('MACFH', 'Million Actual Cubic Feet of Stack Flow / Hour');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('MMBTU', 'mmBtu');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('MMBTUHR', 'mmBtu/ Hour');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('MSCFH', 'Million Standard Cubic Feet of Stack Flow / Hour');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('MW', 'Megawatt');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('PCT', 'Percentage');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('PPM', 'Parts per Million');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('SCF', 'Standard Cubic Feet');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('SCFCBTU', 'CO2 Standard Cubic Feet / mmBtu');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('SCFDBTU', 'Dry Standard Cubic Feet / mmBtu');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('SCFH', 'Standard Cubic Feet / Hour');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('SCFM', 'Standard Cubic Feet of Stack Flow / Minute');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('SCFWBTU', 'Wet Standard Cubic Feet / mmBtu');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('SFPM', 'Standard Feet of Stack Flow / Minute');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('SMSEC', 'Standard Meters of Stack Flow / Second');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('TNHR', 'Tons / Hour');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('TNMMBTU', 'Tons / mmBtu');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('TON', 'Tons');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('UGSCM', 'Micrograms / Standard Cubic Meter');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('AFSEC', 'Actual Feet of Stack Flow / Second');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('CCHR', 'Cubic Centimeters / Hour');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('CCMIN', 'Cubic Centimeters / Minute');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('DSCMHR', 'Dry Standard Cubic Meters / Hour');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('DSCMMIN', 'Dry Standard Cubic Meters / Minute');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('LBGWH', 'Pounds / Giga-watt Hour');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('LBMWH', 'Pounds / Megawatt Hour');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('LBTBTU', 'Pounds / TBtu');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('LHR', 'Liters / Hour');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('LMIN', 'Liters / Minute');
INSERT INTO camdecmpsmd.units_of_measure_code (uom_cd, uom_cd_description) VALUES ('KGMWH', 'kg / Megawatt Hour');
